@echo off
REM This is a hacked script to produce rtiforms.fnx. I just found all .frm
REM files in %ING_SRC%\front and concatenate them together with formindx.exe
REM to approximate what is done in Unix. If anything changes in front you
REM must make sure to pick up any new .frm files.
REM
REM This needs to be revisited when time permits.
REM
REM Histoty:
REM 19-may-95 (emmag)
REM     File created.
REM 15-Jul-95 (fanra01)
REM     Replaced formindx with formindex.  Removed abfdemo\qbf_forms.frm entry.
REM 15-jan-96 (tutto01)
REM     Copy the results into the current installation.
REM 02-sep-96 (mcgem01)
REM	Add forms which are new to OI 2.0
REM 02-sep-96 (mcgem01)
REM	Managed to include 2 .hlp files in last submission.  Removed them.
REM 15-jan-97 (mcgem01)
REM	Added the replicator forms.
REM 30-Mar-98 (rajus01)
REM	Added attribform.frm, attribedit.frm, loginform.frm, logpassedit.frm.
REM 18-may-1998 (canor01)
REM	Quote pathname to allow for embedded spaces.  Remove getpass.frm,
REM	logpass.frm, nucomsvr.frm, numain.frm, rmbldsvr.frm
REM 31-Jul-98 (fanra01)
REM     Add secmechs.frm.
REM 02-Apr-2003 (wansh01)
REM	Added addvnode.frm. 

formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abaddtop.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abcompcr.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abcompsx.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abdeflts.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abedlock.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abfcnsed.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abfconf.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abfconst.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abfcpcat.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abfcpdet.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abfcreat.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abfgcnsf.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abfglobs.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abfgrafd.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abfimage.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abfprocd.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abfqbfd.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abfrec.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abfrecd.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abfrepwd.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abfuserd.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abglobsx.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\ablnkdsp.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\ablokadm.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\ablokdet.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abloktr.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abpartcr.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abpaswrd.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abreccr.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abf\abtyppik.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abfrt\afrblank.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abfrt\afrnproc.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abfrt\afrtsdmp.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\abfrt\afrunfrm.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\interp\itieffo.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\interp\ititffo.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\vq\newfr.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\vq\newlup.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\vq\newmi.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\vq\newvq.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\vq\vqapprep.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\vq\vqcmper2.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\vq\vqcmperr.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\vq\vqedectf.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\vq\vqhlparm.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\vq\vqlcreat.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\vq\vqlisfil.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\vq\vqlocals.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\vq\vqlocks.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\vq\vqmarkfm.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\vq\vqparms.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\vq\vqpcreat.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\vq\vqprocs.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\vq\vqqparts.frm
formindex rtiforms.fnx %ING_SRC%\front\abf\vq\vqrecapp.frm
formindex rtiforms.fnx %ING_SRC%\front\misc\ingcntrl\catamenu.frm
formindex rtiforms.fnx %ING_SRC%\front\misc\ingcntrl\ctrlmenu.frm
formindex rtiforms.fnx %ING_SRC%\front\misc\ingcntrl\dbacc.frm
formindex rtiforms.fnx %ING_SRC%\front\misc\ingcntrl\dbfrm.frm
formindex rtiforms.fnx %ING_SRC%\front\misc\ingcntrl\dbtblfrm.frm
formindex rtiforms.fnx %ING_SRC%\front\misc\ingcntrl\extdb.frm
formindex rtiforms.fnx %ING_SRC%\front\misc\ingcntrl\extenddb.frm
formindex rtiforms.fnx %ING_SRC%\front\misc\ingcntrl\extens.frm
formindex rtiforms.fnx %ING_SRC%\front\misc\ingcntrl\icdbpacc.frm
formindex rtiforms.fnx %ING_SRC%\front\misc\ingcntrl\icinsacc.frm
formindex rtiforms.fnx %ING_SRC%\front\misc\ingcntrl\location.frm
formindex rtiforms.fnx %ING_SRC%\front\misc\ingcntrl\loclist.frm
formindex rtiforms.fnx %ING_SRC%\front\misc\ingcntrl\locnew.frm
formindex rtiforms.fnx %ING_SRC%\front\misc\ingcntrl\lpick.frm
formindex rtiforms.fnx %ING_SRC%\front\misc\ingcntrl\nlocatio.frm
formindex rtiforms.fnx %ING_SRC%\front\misc\ingcntrl\prvfrm.frm
formindex rtiforms.fnx %ING_SRC%\front\misc\ingcntrl\pwdfrm.frm
formindex rtiforms.fnx %ING_SRC%\front\misc\ingcntrl\usrfrm.frm
formindex rtiforms.fnx %ING_SRC%\front\misc\ingcntrl\usrtbfrm.frm
formindex rtiforms.fnx %ING_SRC%\front\misc\ingmenu\imtopfr.frm
formindex rtiforms.fnx %ING_SRC%\front\qbf\qbf\mqbfjoin.frm
formindex rtiforms.fnx %ING_SRC%\front\qbf\qbf\mqbfops.frm
formindex rtiforms.fnx %ING_SRC%\front\qbf\qbf\mqbftbls.frm
formindex rtiforms.fnx %ING_SRC%\front\qbf\qbf\mqchange.frm
formindex rtiforms.fnx %ING_SRC%\front\qbf\qbf\mqcrjoin.frm
formindex rtiforms.fnx %ING_SRC%\front\qbf\qbf\mqexec.frm
formindex rtiforms.fnx %ING_SRC%\front\qbf\qbf\mqjdup.frm
formindex rtiforms.fnx %ING_SRC%\front\qbf\qbf\mqnewjoi.frm
formindex rtiforms.fnx %ING_SRC%\front\qbf\qbf\mqqfnms.frm
formindex rtiforms.fnx %ING_SRC%\front\qbf\qbf\mqstart.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rbf\break.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rbf\coptions.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rbf\rbfabf.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rbf\rfadcols.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rbf\rfagg.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rbf\rfarchv.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rbf\rfbrkopt.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rbf\rfchcols.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rbf\rfcols.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rbf\rffile.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rbf\rfgetnm.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rbf\rfiidet.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rbf\rfiisave.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rbf\rfindop.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rbf\rfnwpag.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rbf\rfprint.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rbf\rfprompt.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rbf\rfvar.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rbf\rlayout.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rbf\roptions.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rfvifred\dupfld.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rfvifred\tfcreate.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rfvifred\valerr.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rfvifred\vfabcfrm.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rfvifred\vfboxatr.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rfvifred\vfcat.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rfvifred\vfcfdup.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rfvifred\vfcfjdef.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rfvifred\vfcfrm.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rfvifred\vfcftbl.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rfvifred\vfdetail.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rfvifred\vffrmatr.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rfvifred\vfqbfcat.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rfvifred\vfrulfrm.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rfvifred\vfsave.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rfvifred\vftblprm.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rfvifred\vftrmatr.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rfvifred\vfvalder.frm
formindex rtiforms.fnx %ING_SRC%\front\report\rfvifred\vifattr.frm
formindex rtiforms.fnx %ING_SRC%\front\st\config\bridgeprots.frm
formindex rtiforms.fnx %ING_SRC%\front\st\config\addvnode.frm
formindex rtiforms.fnx %ING_SRC%\front\st\config\browser.frm
formindex rtiforms.fnx %ING_SRC%\front\st\config\c2audit.frm
formindex rtiforms.fnx %ING_SRC%\front\st\config\cfgcache.frm
formindex rtiforms.fnx %ING_SRC%\front\st\config\dblist.frm
formindex rtiforms.fnx %ING_SRC%\front\st\config\dmfdep.frm
formindex rtiforms.fnx %ING_SRC%\front\st\config\dmfind.frm
formindex rtiforms.fnx %ING_SRC%\front\st\config\gendep.frm
formindex rtiforms.fnx %ING_SRC%\front\st\config\genind.frm
formindex rtiforms.fnx %ING_SRC%\front\st\config\lgraph.frm
formindex rtiforms.fnx %ING_SRC%\front\st\config\netprots.frm
formindex rtiforms.fnx %ING_SRC%\front\st\config\startup.frm
formindex rtiforms.fnx %ING_SRC%\front\st\config\txlogs.frm
formindex rtiforms.fnx %ING_SRC%\front\st\config\txlog2.frm
formindex rtiforms.fnx %ING_SRC%\front\st\config\secmechs.frm
formindex rtiforms.fnx %ING_SRC%\front\st\netutil\connedit.frm
formindex rtiforms.fnx %ING_SRC%\front\st\netutil\nusvrcntrl.frm
formindex rtiforms.fnx %ING_SRC%\front\st\netutil\attribform.frm
formindex rtiforms.fnx %ING_SRC%\front\st\netutil\attribedit.frm
formindex rtiforms.fnx %ING_SRC%\front\st\netutil\loginform.frm
formindex rtiforms.fnx %ING_SRC%\front\st\netutil\logpassedit.frm
formindex rtiforms.fnx %ING_SRC%\front\st\starview\dut_f1.frm
formindex rtiforms.fnx %ING_SRC%\front\st\starview\dut_f2.frm
formindex rtiforms.fnx %ING_SRC%\front\st\starview\dut_f3.frm
formindex rtiforms.fnx %ING_SRC%\front\st\starview\dut_p11.frm
formindex rtiforms.fnx %ING_SRC%\front\st\starview\dut_p12.frm
formindex rtiforms.fnx %ING_SRC%\front\st\starview\dut_p13.frm
formindex rtiforms.fnx %ING_SRC%\front\st\starview\dut_p14.frm
formindex rtiforms.fnx %ING_SRC%\front\st\starview\dut_p15.frm
formindex rtiforms.fnx %ING_SRC%\front\st\starview\dut_p16.frm
formindex rtiforms.fnx %ING_SRC%\front\st\starview\dut_p2.frm
formindex rtiforms.fnx %ING_SRC%\front\st\starview\dut_p3.frm
formindex rtiforms.fnx %ING_SRC%\front\st\starview\dut_p6.frm
formindex rtiforms.fnx %ING_SRC%\front\st\starview\dut_p7.frm
formindex rtiforms.fnx %ING_SRC%\front\st\starview\dut_p7_1.frm
formindex rtiforms.fnx %ING_SRC%\front\st\starview\dut_p8.frm
formindex rtiforms.fnx %ING_SRC%\front\st\starview\dut_p9.frm
formindex rtiforms.fnx %ING_SRC%\front\tm\fstm\fserrfrm.frm
formindex rtiforms.fnx %ING_SRC%\front\tm\fstm\quelcmds.frm
formindex rtiforms.fnx %ING_SRC%\front\tools\erconvert\mcconv.frm
formindex rtiforms.fnx %ING_SRC%\front\tools\erconvert\mcmsg.frm
formindex rtiforms.fnx %ING_SRC%\front\tools\erconvert\mctbl.frm
formindex rtiforms.fnx %ING_SRC%\front\tools\erconvert\mctop.frm
formindex rtiforms.fnx %ING_SRC%\front\utils\oo\iicat.frm
formindex rtiforms.fnx %ING_SRC%\front\utils\oo\iidetail.frm
formindex rtiforms.fnx %ING_SRC%\front\utils\oo\iisave.frm
formindex rtiforms.fnx %ING_SRC%\front\utils\oo\oolngrem.frm
formindex rtiforms.fnx %ING_SRC%\front\utils\tblutil\tucreate.frm
formindex rtiforms.fnx %ING_SRC%\front\utils\tblutil\tudefprm.frm
formindex rtiforms.fnx %ING_SRC%\front\utils\tblutil\tuexam.frm
formindex rtiforms.fnx %ING_SRC%\front\utils\tblutil\tutblprm.frm
formindex rtiforms.fnx %ING_SRC%\front\utils\tblutil\tutopfr.frm
formindex rtiforms.fnx %ING_SRC%\front\utils\uf\help2frm.frm
formindex rtiforms.fnx %ING_SRC%\front\utils\uf\helpform.frm
formindex rtiforms.fnx %ING_SRC%\front\utils\uf\helptype.frm
formindex rtiforms.fnx %ING_SRC%\front\utils\uf\helpvmax.frm
formindex rtiforms.fnx %ING_SRC%\front\utils\uf\keysform.frm
formindex rtiforms.fnx %ING_SRC%\front\utils\uf\uffile.frm
formindex rtiforms.fnx %ING_SRC%\front\utils\uf\uflstfrm.frm
formindex rtiforms.fnx %ING_SRC%\front\utils\uf\ufprint.frm
formindex rtiforms.fnx %ING_SRC%\front\vifred\vifred\dupfld.frm
formindex rtiforms.fnx %ING_SRC%\front\vifred\vifred\tfcreate.frm
formindex rtiforms.fnx %ING_SRC%\front\vifred\vifred\valerr.frm
formindex rtiforms.fnx %ING_SRC%\front\vifred\vifred\vfabcfrm.frm
formindex rtiforms.fnx %ING_SRC%\front\vifred\vifred\vfboxatr.frm
formindex rtiforms.fnx %ING_SRC%\front\vifred\vifred\vfcat.frm
formindex rtiforms.fnx %ING_SRC%\front\vifred\vifred\vfcfdup.frm
formindex rtiforms.fnx %ING_SRC%\front\vifred\vifred\vfcfjdef.frm
formindex rtiforms.fnx %ING_SRC%\front\vifred\vifred\vfcfrm.frm
formindex rtiforms.fnx %ING_SRC%\front\vifred\vifred\vfcftbl.frm
formindex rtiforms.fnx %ING_SRC%\front\vifred\vifred\vfdetail.frm
formindex rtiforms.fnx %ING_SRC%\front\vifred\vifred\vffrmatr.frm
formindex rtiforms.fnx %ING_SRC%\front\vifred\vifred\vfrulfrm.frm
formindex rtiforms.fnx %ING_SRC%\front\vifred\vifred\vfsave.frm
formindex rtiforms.fnx %ING_SRC%\front\vifred\vifred\vftblprm.frm
formindex rtiforms.fnx %ING_SRC%\front\vifred\vifred\vftrmatr.frm
formindex rtiforms.fnx %ING_SRC%\front\vifred\vifred\vfvalder.frm
formindex rtiforms.fnx %ING_SRC%\front\vifred\vifred\vifattr.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmcddact.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmcdddbs.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmcdddet.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmcddpth.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmcddsum.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmcddtbl.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmcfgmnu.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmdbdetl.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmdbsumm.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmdisply.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmedtcfg.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmevents.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmlocldb.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmmailct.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmmainmn.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmmonitr.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmmovcfg.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmreport.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmshwasg.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmsndevt.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmtbldet.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmtblint.frm
formindex rtiforms.fnx %ING_SRC%\front\rep\repmgr\rmtblsum.frm

copy rtiforms.fnx "%II_SYSTEM%\ingres\files\english"
