DROP USER devtest;
CREATE USER devtest WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB,TRACE,SECURITY,MAINTAIN_LOCATIONS,OPERATOR,AUDITOR,MAINTAIN_AUDIT,MAINTAIN_USERS),
  DEFAULT_PRIVILEGES=(CREATEDB,TRACE,SECURITY,MAINTAIN_LOCATIONS,OPERATOR,AUDITOR,MAINTAIN_AUDIT,MAINTAIN_USERS),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER notauth;
CREATE USER notauth WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB),
  DEFAULT_PRIVILEGES=(CREATEDB),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER pvusr1;
CREATE USER pvusr1 WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB),
  DEFAULT_PRIVILEGES=(CREATEDB),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER pvusr2;
CREATE USER pvusr2 WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB),
  DEFAULT_PRIVILEGES=(CREATEDB),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER pvusr3;
CREATE USER pvusr3 WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB),
  DEFAULT_PRIVILEGES=(CREATEDB),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER pvusr4;
CREATE USER pvusr4 WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB),
  DEFAULT_PRIVILEGES=(CREATEDB),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER pvusr5;
CREATE USER pvusr5 WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB),
  DEFAULT_PRIVILEGES=(CREATEDB),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER sdstest;
CREATE USER sdstest WITH
  NOGROUP,
  NOPRIVILEGES,
  NODEFAULT_PRIVILEGES,
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER ssd;
CREATE USER ssd WITH
  NOGROUP,
  NOPRIVILEGES,
  NODEFAULT_PRIVILEGES,
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER super;
CREATE USER super WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB,TRACE,SECURITY,MAINTAIN_LOCATIONS,AUDITOR,MAINTAIN_AUDIT,MAINTAIN_USERS),
  DEFAULT_PRIVILEGES=(CREATEDB,TRACE,SECURITY,MAINTAIN_LOCATIONS,AUDITOR,MAINTAIN_AUDIT,MAINTAIN_USERS),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER syscat;
CREATE USER syscat WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS),
  DEFAULT_PRIVILEGES=(CREATEDB,TRACE,MAINTAIN_LOCATIONS),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
DROP USER testenv;
CREATE USER testenv WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB,TRACE,SECURITY,MAINTAIN_LOCATIONS,OPERATOR,AUDITOR,MAINTAIN_AUDIT,MAINTAIN_USERS),
  DEFAULT_PRIVILEGES=(CREATEDB,TRACE,SECURITY,MAINTAIN_LOCATIONS,OPERATOR,AUDITOR,MAINTAIN_AUDIT,MAINTAIN_USERS),
  NOEXPIRE_DATE,
  NOPROFILE,
  NOSECURITY_AUDIT;
\go
CREATE ROLE copyrole;
\go
