/*
** Copyright (c) 2004 Ingres Corporation
*/
CREATE USER mdbadmin WITH
  NOGROUP,
  PRIVILEGES=(CREATEDB,TRACE,SECURITY,MAINTAIN_LOCATIONS,OPERATOR,AUDITOR,MAINTAIN_AUDIT,MAINTAIN_USERS),
  DEFAULT_PRIVILEGES=(CREATEDB,TRACE,SECURITY,MAINTAIN_LOCATIONS,OPERATOR,AUDITOR,MAINTAIN_AUDIT,MAINTAIN_USERS),
  NOEXPIRE_DATE,
  NOPROFILE;
\p\g


/*
 * from tngusers.sql
 */

CREATE USER tngsa WITH 
			   NOGROUP,
			   PRIVILEGES=(CREATEDB,TRACE,SECURITY,MAINTAIN_LOCATIONS,OPERATOR,AUDITOR,MAINTAIN_AUDIT,MAINTAIN_USERS),
               DEFAULT_PRIVILEGES=(CREATEDB,TRACE,SECURITY,MAINTAIN_LOCATIONS,OPERATOR,AUDITOR,MAINTAIN_AUDIT,MAINTAIN_USERS),
               NOEXPIRE_DATE, 
			   NOPROFILE,
			   PASSWORD='tngadmin'


\p\g


CREATE GROUP tngadmin with users = (tngsa)
\p\g

ALTER USER tngsa WITH DEFAULT_GROUP = tngadmin
\p\g

CREATE USER tng WITH NOGROUP, NOPRIVILEGES, nodefault_privileges, NOEXPIRE_DATE, NOPROFILE, PASSWORD='tnguser'

\p\g

CREATE GROUP tnguser with users = (tng) 
\p\g


ALTER USER tng WITH DEFAULT_GROUP = tnguser
\p\g


CREATE USER SeverityPropagation WITH
			   group = tngadmin,
		   PRIVILEGES=(CREATEDB,TRACE,SECURITY,MAINTAIN_LOCATIONS,OPERATOR,AUDITOR,MAINTAIN_AUDIT,MAINTAIN_USERS),
               DEFAULT_PRIVILEGES=(CREATEDB,TRACE,SECURITY,MAINTAIN_LOCATIONS,OPERATOR,AUDITOR,MAINTAIN_AUDIT,MAINTAIN_USERS),
               NOEXPIRE_DATE, 
			   NOPROFILE
\p\g



/*
 * for Data Transformer
 */

CREATE GROUP infopump_admin 
\p\g

CREATE GROUP infopump_user
\p\g

CREATE USER infopump WITH
			   group = infopump_admin,
		   PRIVILEGES=(CREATEDB,TRACE,SECURITY,MAINTAIN_LOCATIONS,OPERATOR,AUDITOR,MAINTAIN_AUDIT,MAINTAIN_USERS),
               DEFAULT_PRIVILEGES=(CREATEDB,TRACE,SECURITY,MAINTAIN_LOCATIONS,OPERATOR,AUDITOR,MAINTAIN_AUDIT,MAINTAIN_USERS),
               NOEXPIRE_DATE, 
			   NOPROFILE
\p\g
