//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by vsda.rc
//
#define IDS_VSDA                        1
#define IDB_VSDA                        1
#define IDS_VSDA_PPG                    2
#define IDS_VSDA_PPG_CAPTION            200
#define IDD_PROPPAGE_VSDA               200
#define IDD_DIFFERENT_LIST              201
#define IDC_LIST1                       201
#define IDB_VSD_TABLE                   202
#define IDC_CHECK1                      202
#define IDB_VSD_FOLDER                  203
#define IDC_EDIT1                       203
#define IDB_VSD_VIEW                    204
#define IDC_SPIN1                       204
#define IDB_VSD_DATABASE                205
#define IDC_STATIC_DIFF_COUNT           205
#define IDB_VSD_EMPTY                   206
#define IDC_STATIC_SELECTED_ITEM        206
#define IDB_VSD_PROCEDURE               207
#define IDC_STATIC_NODIFFERENCE         207
#define IDB_VSD_DBEVENT                 208
#define IDC_STATIC_DEPT1                208
#define IDB_VSD_SYNONYM                 209
#define IDC_STATIC_DEPT2                209
#define IDB_VSD_INDEX                   210
#define IDC_STATIC1                     210
#define IDB_VSD_RULE                    211
#define IDB_VSD_INTEGRITY               212
#define IDB_VSD_INSTALLATION            213
#define IDB_VSD_GROUP                   214
#define IDB_VSD_USER                    215
#define IDB_VSD_ROLE                    216
#define IDB_VSD_PROFILE                 217
#define IDB_VSD_LOCATION                218
#define IDR_POPUP_DISCARD               220
#define IDB_VSD_DISCARD                 221
#define IDB_VSD_GRANTEE_INSTALLATION    223
#define IDB_VSD_GRANTEE_DATABASE        224
#define IDB_VSD_GRANTEE_TABLE           225
#define IDB_VSD_GRANTEE_VIEW            226
#define IDD_DIFFERENT_DETAIL            226
#define IDB_VSD_GRANTEE_PROCEDURE       227
#define IDB_VSD_GRANTEE_DBEVENT         228
#define IDB_VSD_ALARM_DATABASE          229
#define IDB_VSD_ALARM_INSTALLATION      230
#define IDB_VSD_ALARM_TABLE             231
#define IDB_VSD_TABLE_STAR_NATIVE       232
#define IDB_VSD_TABLE_STAR_LINK         233
#define IDB_VSD_VIEW_STAR_LINK          234
#define IDB_VSD_VIEW_STAR_NATIVE        235
#define IDB_VSD_PROCEDURE_STAR          236
#define IDB_VSD_DATABASE_DISTRIBUTED    237
#define IDB_VSD_DATABASE_COORDINATOR    238
#define IDB_VSD_INDEX_STAR_LINK         239
#define IDB_VSD_SEQUENCE                240
#define IDB_VSD_GRANTEE_SEQUENCE        241
#define IDD_DIFFERENCE_DETAIL_PAGE      242
#define IDS_OWNERxITEM                  1000
#define IDS_INVITATION                  1001
#define IDS_TITLE_ANIMATE_INSTALLATION  1002
#define IDS_TITLE_ANIMATE_DATABASE_SCHEMA 1003
#define IDS_TITLE_STORE_INSTALLATION    1004
#define IDS_TITLE_STORE_DATABASE_SCHEMA 1005
#define IDS_TAB_OBJECT                  1006
#define IDS_TAB_TYPE                    1007
#define IDS_TAB_DIFF                    1008
#define IDS_TAB_SCHEMA1                 1009
#define IDS_TAB_SCHEMA2                 1010
#define IDS_TAB_GROUP_DIFF1             1011
#define IDS_TAB_GROUP_DIFF2             1012
#define IDS_DIFFPROPERTY_CAPTION        1013
#define IDS_NODETAIL_DIFFERENCExTHISITEM 1014
#define IDS_DIFFERENCES_IN_SUBBRANCHES  1015
#define IDS_NO_SELECTED_ITEM4DETAIL     1016
#define IDS_COMPARISON_ABORTED          1017
#define IDS_MSG_NODIFF_4WRITE           1018
#define IDS_MSG_COMPARE_WRONGTYPE       2000
#define IDS_MSG_COMPARE_WRONGTYPE_INSTALLATIONxFILE 2001
#define IDS_MSG_COMPARE_WRONGTYPE_SCHEMAxFILE 2002
#define IDS_MSG_COMPARE_WRONGTYPE_FILExFILE 2003
#define IDS_MSG_COMPARE_WRONGTYPE_SCHEMA 2004
#define IDS_MSG_II_SYSTEM_NOT_DEFINED   2005
#define IDS_MSG_FAIL_2_STOREDATA        2006
#define IDS_MSG_FAIL_2_COMPAREDATA      2007
#define IDS_MSG_COMPARE_WRONGTYPE_DATABASE 2008
#define IDS_MSG_OBJ_DIFF                2009
#define IDS_MSG_WAIT_DB                 2010
#define IDS_MSG_WAIT_GENERAL            2011
#define IDS_MSG_WAIT_USERS              2012
#define IDS_MSG_WAIT_GROUPS             2013
#define IDS_MSG_WAIT_ROLES              2014
#define IDS_MSG_WAIT_PROFILES           2015
#define IDS_MSG_WAIT_LOCATIONS          2016
#define IDS_MSG_WAIT_GRANTEES           2017
#define IDS_MSG_WAIT_SEC_ALARMS         2018
#define IDS_MSG_WAIT_INDICES            2019
#define IDS_MSG_WAIT_RULES              2020
#define IDS_MSG_WAIT_INTEGRITIES        2021
#define IDS_MSG_WAIT_SECURITY_ALARMS    2022
#define IDS_MSG_WAIT_TABLES             2023
#define IDS_MSG_WAIT_VIEWS              2024
#define IDS_MSG_WAIT_PROCEDURES         2025
#define IDS_MSG_WAIT_SEQUENCES          2026
#define IDS_MSG_WAIT_DB_EVENTS          2027
#define IDS_MSG_WAIT_SYNONYMS           2028
#define IDS_NOT_FETCHED                 2029
#define IDS_FILE_ERROR                  2030
#define IDS_MISSING_OBJ                 2031
#define IDS_AVAILABLE                   2032
#define IDS_NOT_AVAILABLE               2033
#define IDS_MISSING_MEMBERS             2034
#define IDS_MISSING_COLUMN              2035
#define IDS_PRIM_KEY                    2036
#define IDS_MISSING_PRIM_KEY            2036
#define IDS_MISSING_UNIQUE_KEY          2037
#define IDS_MISSING_FOREIGN_KEY         2038
#define IDS_MISSING_CHECK               2039
#define IDS_MISSING_PRIV                2040
#define IDS_MISSING_ALARM               2041
#define IDS_TYPE_QUERY_TXT              2042
#define IDS_TYPE_ALL_EVENT              2043
#define IDS_TYPE_LIMIT_SEC              2044
#define IDS_TYPE_DEF_GROUP              2045
#define IDS_TYPE_DEF_PROF               2046
#define IDS_TYPE_EXT_PASSWORD           2047
#define IDS_TYPE_EXP_DATE               2048
#define IDS_TYPE_DATA_USAGE             2049
#define IDS_TYPE_JNL_USAGE              2050
#define IDS_TYPE_CHECKPOINT_USAGE       2051
#define IDS_TYPE_WORK_USAGE             2052
#define DS_TYPE_DUMP                    2053
#define IDS_TYPE_LOC_AREA               2054
#define IDS_TYPE_OWNER                  2055
#define IDS_TYPE_READ_ONLY              2056
#define IDS_TYPE_PRIVATE                2057
#define IDS_TYPE_DB_TYPE                2058
#define IDS_TYPE_UNICODE                2059
#define IDS_TYPE_CHECKPOINT_LOC         2060
#define IDS_TYPE_DTA_LOC                2061
#define IDS_TYPE_JNL_LOC                2062
#define IDS_TYPE_DUMP_LOC               2063
#define IDS_TYPE_WORK_LOC               2064
#define IDS_TYPE_SEC_LABEL              2065
#define IDS_TYPE_STOR_STRUCT            2066
#define IDS_TYPE_PAGE_SIZE              2067
#define IDS_TYPE_EXTEND                 2068
#define IDS_TYPE_ALLOC                  2069
#define IDS_TYPE_ALLOCATED_PAGES        2070
#define IDS_TYPE_UNIQUE_SCOPE           2071
#define IDS_TYPE_UNIQUE_RULE            2072
#define IDS_TYPE_COMPRESS               2073
#define IDS_TYPE_KEY_COMPRESS           2074
#define IDS_TYPE_FILL_FACTOR            2075
#define IDS_TYPE_LEAFFILL               2076
#define IDS_TYPE_NON_LEAFFILL           2077
#define IDS_TYPE_MIN_PAGE               2078
#define IDS_TYPE_MAX_PAGE               2079
#define IDS_TYPE_NUM_COLS               2080
#define IDS_TYPE_ORDER_COLS             2081
#define IDS_TYPE_COL_ATTRIB             2082
#define IDS_TYPE_PRIMARY_KEY            2083
#define IDS_TYPE_TBL_PHYSICALLY         2084
#define IDS_TYPE_TBL_LOGICALLY          2085
#define IDS_TYPE_TBL_RECOVERY           2086
#define IDS_TYPE_JOURNALING             2087
#define IDS_TYPE_DUP_ROW                2088
#define IDS_TYPE_ESTIMATE_ROW           2089
#define IDS_TYPE_COMMENT                2090
#define IDS_TYPE_STATEMENT              2091
#define IDS_TYPE_CHECK_OPT              2092
#define IDS_TYPE_LANGUAGE               2093
#define IDS_TYPE_TYPE                   2094
#define IDS_TYPE_DEC_PREC               2095
#define IDS_TYPE_CYCLE                  2096
#define IDS_TYPE_ORDER                  2097
#define IDS_TYPE_MAX_VAL                2098
#define IDS_TYPE_MIN_VAL                2099
#define IDS_TYPE_LOCATION               2100
#define IDS_TYPE_CACHE_PRIORITY         2101
#define IDS_TYPE_PERSISTENT             2102
#define IDS_TYPE_START_WITH             2103
#define IDS_TYPE_INCREMENT_BY           2104
#define IDS_TYPE_NEXT_VALUE             2105
#define IDS_TYPE_SYNONYM_ON             2106
#define IDS_TYPE_SUBJECT_TYPE           2107
#define IDS_TYPE_SECURITY_USER          2108
#define IDS_TYPE_ALARM_CONDITION        2109
#define IDS_TYPE_CACHE                  2110
#define IDS_TYPE_ALARM_RAISES           2111
#define IDS_USER                        2112
#define IDS_USER_DEFAULT                2113
#define IDS_COMPARE_SECURITY            2114
#define IDS_COMPARE_GRANTEE             2115
#define IDS_COMPARE_TBL                 2116
#define IDS_COMPARE_VIEW                2117
#define IDS_COMPARE_PROC                2118
#define IDS_COMPARE_SEQ                 2119
#define IDS_COMPARE_DBEVEVNT            2120
#define IDS_COMPARE_SYNONYM             2121
#define IDS_COMPARE_INDEX               2122
#define IDS_COMPARE_RULE                2123
#define IDS_COMPARE_INTEGRITY           2124
#define IDS_COMPARE_DB                  2125
#define IDS_COMPARE_USER                2126
#define IDS_COMPARE_GROUP               2127
#define IDS_COMPARE_ROLE                2128
#define IDS_COMPARE_PROFILE             2129
#define IDS_COMPARE_LOC                 2130
#define ID_POPUP_DISCARD                32768
#define ID_POPUP_UNDISCARD              32769
#define ID_POPUP_ACCESSVDBA             32770

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        243
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         211
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
