/****************************************************************************************
//                                                                                     //
//  Copyright (C) 2005-2006 Ingres Corporation. All Rights Reserved.                   //
//                                                                                     //
//    Source   : DbeView.h, Header File   (MDI Child Frame)                            //
//                                                                                     //
//                                                                                     //
//    Project  : CA-OpenIngres/Monitoring.                                             //
//    Author   : EMB, Standard Skeleton Generated by MFC Widzard.                      //
//               UK Sotheavut, Detail implementation.                                  //
//                                                                                     //
//    Purpose  : The left pane for the DBEvent Trace.                                  //
//               It contains the Modeless Dialog (Header and Check list Box)           //
****************************************************************************************/
#ifndef DBEVIEW_HEADER
#define DBEVIEW_HEADER

#include "dgdbep01.h"
class CDbeventView : public CView
{
protected:
    CDbeventView();           // protected constructor used by dynamic creation
    DECLARE_DYNCREATE(CDbeventView)



public:
    CuDlgDBEventPane01* m_pDlgRegisteredDBEvent;
    // Overrides
    // ClassWizard generated virtual function overrides
    //{{AFX_VIRTUAL(CDbeventView)
	public:
    virtual void OnInitialUpdate();
	protected:
    virtual void OnDraw(CDC* pDC);      // overridden to draw this view
    virtual BOOL PreCreateWindow(CREATESTRUCT& cs);
	virtual void OnUpdate(CView* pSender, LPARAM lHint, CObject* pHint);
	//}}AFX_VIRTUAL

    // Implementation
protected:
    virtual ~CDbeventView();
#ifdef _DEBUG
    virtual void AssertValid() const;
    virtual void Dump(CDumpContext& dc) const;
#endif

    // Generated message map functions
protected:
    //{{AFX_MSG(CDbeventView)
    afx_msg int OnCreate(LPCREATESTRUCT lpCreateStruct);
    afx_msg void OnSize(UINT nType, int cx, int cy);
    //}}AFX_MSG
    DECLARE_MESSAGE_MAP()
};

#endif
