//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MAINMFC.RC
//
#define IDR_MAINFRAME                   99
#define IDD_STAR_TABLEREGISTER          102
#define IDR_POPUP_VIRTUALNODEBAR        106
#define IDD_DOM_CREATE_DB               109
#define IDR_DOM                         127
#define IDR_MAINMFTYPE_NOTOI            128
#define IDR_MAINMFTYPE                  129
#define IDD_DOMPROP_ICE_HTML_SOURCE     129
#define IDR_SQLACTTYPE                  130
#define IDR_SQLACT                      131
#define IDB_DATABASEOBJECT              133
#define IDR_IPMTYPE                     135
#define IDD_STATBAR_SETTING             135
#define IDR_VNODEMDI                    136
#define IDR_DBEVENTTYPE                 137
#define IDR_DOM_NOTOI                   137
#define IDI_ICON_COUNTER09              138
#define IDI_ICON_COUNTER10              139
#define IDI_ICON_COUNTER11              140
#define IDB_BITMAP_DEFAULT              141
#define IDI_ICON_COUNTER12              141
#define IDB_NODE                        142
#define IDI_ICON_COUNTER13              142
#define IDB_NODE_OPENWIN                143
#define IDI_ICON_COUNTER14              143
#define IDB_NODE_LOGINPSW               144
#define IDI_ICON_COUNTER15              144
#define IDB_NODE_CONNECTIONDATA         145
#define IDI_ICON_COUNTER16              145
#define IDB_NODE_ADVANCED               146
#define IDD_IPMBAR                      159
#define IDC_TREE1                       160
#define IDB_TM_DB                       160
#define IDM_VNODEBAR01                  161
#define IDM_VNODEBAR02                  162
#define IDM_VNODEBAR03                  163
#define IDM_VNODEBAR04                  164
#define IDM_VNODEBAR05                  165
#define IDM_VNODEBAR06                  166
#define IDM_VNODEBAR07                  167
#define IDB_NODE_CONNECTED              167
#define IDM_VNODEBAR08                  168
#define IDB_NODE_NOTCONNECTED           168
#define IDM_VNODEBAR09                  169
#define IDD_XVIRTUALNODE                169
#define IDM_VNODEBAR10                  170
#define IDM_VNODEBAR11                  171
#define IDM_VNODEBAR12                  172
#define IDC_DIVIDER1                    173
#define IDC_DIVIDER2                    174
#define IDC_DIVIDER3                    175
#define IDC_DIVIDER4                    176
#define IDB_TM_CONNECT_DATA_GROUP       189
#define IDB_TM_CONNECT_DATA_USER        190
#define ID_SERVERS_TESTNODE             192
#define ID_SERVERS_INSTALLPSW           193
#define ID_BUTTON_FASTLOAD              194
#define ID_BUTTON_INFODB                195
#define ID_BUTTON_DUPLICATEDB           196
#define ID_BUTTON_REPLIC_CREATEKEYS     197
#define ID_BUTTON_REPLIC_ACTIVATE       198
#define ID_BUTTON_SECURITYAUDIT         199
#define IDD_VIRTUALNODEBAR              500
#define IDD_DBEVENTPANE1                501
#define IDD_DBEVENTPANE2                502
#define IDB_NODE_CONNECTED_LOCAL        505
#define IDB_NODE_CONNECTED_PRIVATE      506
#define IDB_NODE_CONNECTED_GLOBAL       507
#define IDB_NODE_CONNECTED_COMPLEX      508
#define IDB_NODE_NOTCONNECTED_LOCAL     509
#define IDB_NODE_NOTCONNECTED_PRIVATE   510
#define IDD_TOOLBARS                    510
#define IDD_IPMBARV                     511
#define IDB_NODE_NOTCONNECTED_GLOBAL    511
#define IDD_DBEVENTBAR                  512
#define IDB_NODE_NOTCONNECTED_COMPLEX   512
#define IDD_DBEVENTBARV                 513
#define IDD_IPMDETAIL_LOCATION          519
#define IDD_IPMDETAIL_LOCATIONS         520
#define IDD_XVNODEDATA                  535
#define IDD_XVNODELOGIN                 536
#define IDD_NODE_DISCONNECT             537
#define IDD_SHUTDOWN_SERVER             540
#define IDD_IPMPAGE_LOCATION            541
#define IDB_TM_CONNECTION_DATA_GROUP    544
#define IDD_STAR_PROCREGISTER           544
#define IDB_TM_CONNECTION_DATA_USER     545
#define IDB_STAR_DATABASE_CDB           547
#define IDB_STAR_TABLE_NOTSTAR          548
#define IDB_STAR_VIEW_NOTSTAR           549
#define IDD_STAR_TABLECREATE            549
#define IDB_STAR_DATABASE_DDB           550
#define IDD_DOMDETAIL                   550
#define IDB_STAR_DATABASE_NOTSTAR       551
#define IDD_DOMPROP_TABLE_TEST          551
#define IDB_STAR_PROCEDURE_NOTSTAR      552
#define IDB_CHECK                       555
#define IDD_DOMPROP_LOCATION            561
#define IDD_DOMPROP_USER                564
#define IDD_DOMPROP_ROLE                565
#define IDB_CHECK_NOFRAME               565
#define IDD_DOMPROP_PROF                566
#define IDD_DOMPROP_INDEX               567
#define IDD_DOMPROP_INTEG               568
#define IDD_DOMPROP_RULE                569
#define IDD_DOMPROP_PROC                570
#define IDD_FORCEREFRESH                571
#define IDD_DOMPROP_GROUP               572
#define IDD_DOMPROP_DB_ALARMS           573
#define IDB_SPLASH                      573
#define IDD_DOMPROP_TABLE_ALARMS        574
#define IDD_DOMPROP_TABLE_GRANTEES      575
#define IDB_IMGLIST_STARTBL             575
#define IDD_DOMPROP_DB_GRANTEES         576
#define IDB_IMGLIST_STARVIEW            576
#define IDD_DOMPROP_DB                  577
#define IDB_IMGLIST_STARPROC            577
#define IDD_DOMPROP_TABLE               578
#define IDD_DOMPROP_VIEW_GRANTEES       579
#define IDD_DOMPROP_VIEW                580
#define IDD_DOMPROP_CDDS                581
#define IDD_DOMPROP_CDDS_TBL            582
#define IDD_DOMPROP_DBEV_GRANTEES       583
#define IDD_DOMPROP_PROC_GRANTEES       584
#define IDD_DOMPROP_TABLE_COLUMNS       585
#define IDD_DOMPROP_REPL_CONN           586
#define IDD_DOMPROP_REPL_CDDS           587
#define IDD_DOMPROP_REPL_MAILU          588
#define IDD_DOMPROP_REPL_REGTBL         589
#define IDD_DOMPROP_DB_TBLS             591
#define IDD_DOMPROP_DB_VIEWS            592
#define IDD_DOMPROP_DB_PROCS            593
#define IDD_DOMPROP_DB_SCHEMAS          594
#define IDD_DOMPROP_DB_SYNS             595
#define IDD_DOMPROP_DB_EVTS             596
#define IDD_DOMPROP_TABLE_INTEG         597
#define IDD_DOMPROP_TABLE_RULE          598
#define IDD_DOMPROP_TABLE_IDX           599
#define IDD_DOMPROP_TABLE_LOC           600
#define IDD_DOMPROP_USER_XALARMS        601
#define IDD_DOMPROP_USER_XGRANTED_DB    602
#define IDD_DOMPROP_USER_XGRANTED_TBL   603
#define IDD_DOMPROP_USER_XGRANTED_VIEW  604
#define IDD_DOMPROP_USER_XGRANTED_DBEV  605
#define IDD_DOMPROP_USER_XGRANTED_PROC  606
#define IDD_DOMPROP_USER_XGRANTED_ROLE  607
#define IDD_DOMPROP_GROUP_XGRANTED_DB   608
#define IDD_DOMPROP_GROUP_XGRANTED_DBEV 609
#define IDD_DOMPROP_GROUP_XGRANTED_PROC 610
#define IDD_DOMPROP_GROUP_XGRANTED_TBL  611
#define IDD_DOMPROP_GROUP_XGRANTED_VIEW 612
#define IDD_DOMPROP_ROLE_XGRANTED_DB    613
#define IDD_DOMPROP_ROLE_XGRANTED_DBEV  614
#define IDD_DOMPROP_ROLE_XGRANTED_PROC  615
#define IDD_DOMPROP_ROLE_XGRANTED_TBL   616
#define IDD_DOMPROP_ROLE_XGRANTED_VIEW  617
#define IDD_DOMPROP_CONNECTION          618
#define IDD_DOMPROP_DDB                 620
#define IDD_DOMPROP_DDB_TBLS            621
#define IDD_DOMPROP_DDB_VIEWS           622
#define IDD_DOMPROP_DDB_PROCS           623
#define IDD_DOMPROP_STARPROC_L          624
#define IDD_DOMPROP_STARTBL_L_IDX       625
#define IDD_DOMPROP_STARVIEW_N          626
#define IDD_DOMPROP_STARVIEW_L          627
#define IDD_DOMPROP_SCHEMA_TBLS         631
#define IDD_DOMPROP_SCHEMA_VIEWS        632
#define IDD_DOMPROP_SCHEMA_PROCS        633
#define IDB_PAGETYPE                    638
#define IDD_ERROR_WITH_HISTORY          639
#define IDD_DOMPROP_TABLE_PAGES         640
#define IDB_SVRCLASS                    640
#define IDD_DOMPROP_INDEX_PAGES         641
#define IDB_SVRCLASS_CONNECTED          641
#define IDD_DOMPROP_TABLE_ROWS          642
#define IDB_SVRCLASS_NOTCONNECTED       642
#define IDD_DOMPROP_TABLE_STATISTIC     643
#define IDB_USER_OPENWIN                643
#define IDD_REPLIC_QUESTION             644
#define IDB_NODEUSER                    644
#define IDB_NODEUSER_CONNECTED          645
#define IDD_DOMPROP_STARTBL_L           647
#define IDB_STAR_DATABASE_COMPONENT     647
#define IDD_DOMPROP_STARTBL_L_TOBEDELETED 648
#define IDD_REPLICATION_BUILD_SERVER    649
#define IDD_DOMPROP_STARDB_COMPONENT    650
#define IDD_XSERVICE_ACCOUNT            651
#define IDD_DOMPROP_INDEX_L_SOURCE      652
#define IDD_DOMPROP_PROC_L_SOURCE       653
#define IDD_DOMPROP_VIEW_L_SOURCE       654
#define IDD_DOMPROP_VIEW_N_SOURCE       655
#define IDD_DOMPROP_TABLE_ROWSNA        656
#define IDB_NODE_ATTRIBUTE              665
#define IDB_TM_ATTRIBUTE_GROUP          666
#define IDB_TM_ATTRIBUTE_USER           667
#define IDB_NODE_INSTALLPASSWORD        668
#define IDD_XTASK_WAIT                  669
#define IDI_BIGTABLE                    670
#define IDD_REPLICATION_ARCCLEAN        675
#define IDD_DOMPROP_ST_DB               677
#define IDD_DOMPROP_ST_PROFILE          678
#define IDD_DOMPROP_ST_USER             679
#define IDD_DOMPROP_ST_GROUP            680
#define IDD_DOMPROP_ST_ROLE             681
#define IDD_DOMPROP_ST_LOCATION         682
#define IDD_DOMPROP_ST_GWDB             683
#define IDD_CREATEDB_LOCATION           689
#define IDD_CREATEDB_LOC_ALTERNATE      690
#define IDI_ICON_COUNTER01              691
#define IDI_ICON_COUNTER02              692
#define IDI_ICON_COUNTER03              693
#define IDI_ICON_COUNTER04              694
#define IDI_ICON_COUNTER05              695
#define IDI_ICON_COUNTER06              696
#define IDD_XCREATE_INDEX               696
#define IDI_ICON_COUNTER07              697
#define IDD_XVNODE_INSTALLATION_PASSWORD 697
#define IDI_ICON_COUNTER08              698
#define IDD_XVNODE_ATTRIBUTE            698
#define IDD_FASTLOAD                    699
#define IDR_ANFETCHR                    700
#define IDD_XINDEX_OPTION               700
#define IDR_ANFETCHF                    701
#define IDR_ANREFRESH                   702
#define IDD_ICE_ROLE                    702
#define IDR_ANCLOCK                     703
#define IDD_ICE_DATABASE_USER           703
#define IDR_ANCONNECT                   704
#define IDD_ICE_DATABASE_CONNECT        704
#define IDR_ANDISCONNECT                705
#define IDD_ICE_WEB_USER                705
#define IDR_ANDRAGDC                    706
#define IDD_ICE_PROFILE                 706
#define IDR_ANDELETE                    707
#define IDD_ICE_BUSINESS_FACET_PAGE     707
#define IDR_ANEXAMINE                   708
#define IDD_DOMPROP_ICE_DBCONNECTION    708
#define IDD_DOMPROP_ICE_DBUSER          709
#define IDD_DOMPROP_ICE_PROFILE         710
#define IDD_DOMPROP_ICE_ROLE            711
#define IDD_DOMPROP_ICE_WEBUSER         712
#define IDD_XTASK_WAIT_WITH_TITLE       713
#define IDD_XTABLE_PRIMARY_KEY          714
#define IDD_DOMPROP_ICE_SERVER_LOCATION 715
#define IDD_DOMPROP_ICE_SERVER_VARIABLE 716
#define IDD_DOMPROP_ICE_BUNIT           717
#define IDD_DOMPROP_ICE_SEC_ROLES       718
#define IDD_DOMPROP_ICE_SEC_DBUSERS     719
#define IDD_DOMPROP_ICE_SEC_DBCONNS     720
#define IDD_DOMPROP_ICE_SEC_WEBUSERS    721
#define IDD_DOMPROP_ICE_SEC_PROFILES    722
#define IDD_DOMPROP_ICE_WEBUSER_ROLES   723
#define IDD_DOMPROP_ICE_WEBUSER_CONNECTIONS 724
#define IDD_DOMPROP_ICE_PROFILE_ROLES   725
#define IDD_DOMPROP_ICE_PROFILE_CONNECTIONS 726
#define IDD_DOMPROP_ICE_SERVER_APPLICATIONS 727
#define IDD_DOMPROP_ICE_SERVER_LOCATIONS 728
#define IDD_DOMPROP_ICE_SERVER_VARIABLES 729
#define IDD_ICE_BUSINESS_ROLE           730
#define IDD_ICE_BUSINESS_USER           731
#define IDD_DOMPROP_INSTLEVEL_AUDITUSERS 746
#define IDD_DOMPROP_INSTLEVEL_ENABLEDLEVEL 747
#define IDD_DOMPROP_INSTLEVEL_AUDITLOG  748
#define IDD_DUPLICATE_DATABASE          749
#define IDD_ICE_COMMON_COMBOBOX         750
#define IDD_ICE_COMMON_EDIT             751
#define IDD_ICE_PASSWORD                752
#define IDD_ICE_SVR_VARIABLE            753
#define IDD_ICE_LOCATION                754
#define IDD_XENABLE_SECURITY_LEVEL      755
#define IDD_XRULE                       756
#define IDD_XGRANTDB                    757
#define IDI_EXPIRE                      758
#define IDD_EXPIREDATE                  759
#define IDR_GENERAL_DISPLAY             759
#define IDD_XDROP_OBJECT                760
#define IDB_SECALARM                    761
#define IDD_DOMPROP_ICE_FACETNPAGE      761
#define IDD_DOMPROP_ICE_FACETNPAGE_NOOVERLAP 762
#define IDB_PREFERENCE_SMALL            762
#define IDD_XRMCMD                      763
#define IDD_XRMCMD_SEND_ANSWER          764
#define IDD_BACKGROUND_REFRESH          765
#define IDD_ICE_BU_FACETPAGE_ROLEUSER   766
#define IDD_DOMPROP_ICE_BUNIT_ACCESSDEF 767
#define IDD_DOMPROP_ICE_BUNITS          768
#define IDD_DOMPROP_ICE_SEC_DBUSER      769
#define IDD_DOMPROP_ICE_SEC_ROLE        770
#define IDD_DOMPROP_ICE_FACETS          771
#define IDD_DOMPROP_ICE_PAGES           772
#define IDD_DOMPROP_ICE_LOCATIONS       773
#define IDD_DOMPROP_ICE_BUNIT_ROLES     774
#define IDD_DOMPROP_ICE_BUNIT_USERS     775
#define IDD_DOMPROP_ICE_FACETNPAGE_ROLES 776
#define IDD_DOMPROP_ICE_FACETNPAGE_USERS 777
#define IDD_XGENERAL_DISPLAY_SETTING    778
#define IDR_MENU_DLGPREFERENCE          779
#define IDD_XPREFERENCES                780
#define IDD_XPREFERENCES_BACKGROUND_REFRESH 781
#define IDD_REPLICATION_KEY_OPTION      782
#define IDD_TBLJOURNALING               784
#define IDD_DOMPROP_ICE_HTML_IMAGE      785
#define BTN_DOWN_DOWN                   797
#define BTN_DOWN_FOCUS                  798
#define BTN_DOWN_GREY                   799
#define BTN_DOWN_UP                     800
#define BTN_UP_DOWN                     801
#define BTN_UP_FOCUS                    802
#define BTN_UP_GREY                     803
#define BTN_UP_UP                       804
#define IDD_XUSER                       853
#define IDD_XMESSAGEBOX                 854
#define IDD_XOBJECT_COMMENT             859
#define IDD_USERMOD                     860
#define IDD_XCOPYDB                     861
#define IDD_XCHOOSEOBJECTS              862
#define IDD_MODIFY_PAGE_SIZE            864
#define IDD_CHECKPOINT_LIST             865
#define IDD_INFODB                      866
#define IDI_KILLSESSION                 866
#define IDI_EXPANDBRANCH                867
#define IDI_EXPANDALL                   868
#define IDI_COLLAPSEBRANCH              869
#define IDI_COLLAPSEALL                 870
#define IDI_RESET                       871
#define IDI_DOM                         872
#define IDI_SQL                         873
#define IDI_IPM                         874
#define IDI_DBEVENT                     875
#define IDI_SCRATCH                     876
#define IDI_DISCONNECT                  877
#define IDI_CLOSE                       878
#define IDI_ACTIVATE                    879
#define IDI_NODE_ADD                    880
#define IDR_MAINMFTYPE_NOTOI_NOMENU     881
#define IDR_MAINMFTYPE_NOMENU           882
#define IDI_NODE_ALTER                  883
#define IDR_MAINMFTYPE_NOTOI_OBJMENU    884
#define IDR_MAINMFTYPE_OBJMENU          885
#define IDI_NODE_DROP                   886
#define IDR_IPMTYPE_NOMENU              887
#define IDR_IPMTYPE_OBJMENU             888
#define IDD_CREATEDB_SEQUENCE           888
#define IDR_DBEVENTTYPE_NOMENU          889
#define IDR_SQLACTTYPE_NOMENU           890
#define IDD_DOMPROP_SEQ                 890
#define IDD_DOMPROP_SEQ_GRANTEES        891
#define IDD_DOMPROP_DB_SEQS             892
#define IDD_DOMPROP_GROUP_XGRANTED_SEQ  893
#define IDD_DOMPROP_ROLE_XGRANTED_SEQ   894
#define IDD_DOMPROP_USER_XGRANTED_SEQ   895
#define IDD_CREATEDB_ADVANCED           897
#define IDD_XUSER_PRIV                  898
#define IDD_XUSER_SECURITY              899
#define IDD_XUSER_ALTER_PRIV            900
#define IDD_XUSER_ALTER_SEC             900
#define IDD_XROLE_PRIV                  901
#define IDD_XROLE_SEC                   902
#define IDC_MFC_STATIC1                 1000
#define IDC_CHECK_DATABASE              1000
#define IDC_LIST_COLUMNS                1000
#define IDC_MFC_TAB1                    1001
#define IDC_CHECK_WORK                  1001
#define IDC_EDIT_DEFGROUP               1001
#define IDC_LIST_CONSTRAINTS            1001
#define IDC_LIST1                       1001
#define IDC_MFC_LIST1                   1002
#define IDC_CHECK_JOURNAL               1002
#define IDC_EDIT_DEFPROFILE             1002
#define IDC_MFC_SPIN1                   1003
#define IDC_CHECK_CHECKPOINT            1003
#define IDC_MFC_LIST2                   1003
#define IDC_EDIT_EXPIREDATE             1003
#define IDC_MFC_STATIC                  1004
#define IDC_CHECK_DUMP                  1004
#define IDC_EDIT_LIMITSECLABEL          1004
#define IDC_DBUSER                      1004
#define IDC_DEFDBUSER                   1004
#define IDC_MFC_CHECK1                  1005
#define IDC_DISTNAME                    1005
#define IDC_LIST_GROUPS                 1005
#define IDC_MFC_STATIC2                 1006
#define IDC_TOOLBARS_LIST               1006
#define IDC_MFC_CHECK2                  1006
#define IDC_COLUMNSNAMES                1006
#define IDC_MFC_COMBO1                  1007
#define IDC_DISCONNECT_WINDOWSLIST      1007
#define IDC_MFC_CHECK3                  1007
#define IDC_LIST_GRANTEES               1007
#define IDC_CHECK_PERSISTENCE           1007
#define IDC_VALUE                       1007
#define IDC_EXPLORER1                   1007
#define IDC_MFC_CHECK4                  1008
#define IDC_LIST_LOCATIONS              1008
#define IDC_RADIO_HTTP                  1008
#define IDC_MFC_CHECK5                  1009
#define IDC_EDIT_TBLNAME                1009
#define IDC_RADIO_ICE                   1009
#define IDC_EDIT_IDXSCHEMA              1010
#define IDC_MFC_CHECK6                  1010
#define IDC_STATIC_01                   1010
#define IDC_CHECK_COMPRESSION           1011
#define IDC_MFC_CHECK7                  1011
#define IDC_BUNITOWNER                  1011
#define IDC_STATIC_COMPRESSION          1012
#define IDC_EDIT_ALLOCATION             1013
#define IDC_EDIT_EXTEND                 1014
#define IDC_EDIT_FILLFACTOR             1015
#define IDC_EDIT_STRUCT1                1016
#define IDC_EDIT_STRUCT                 1017
#define IDC_TREE                        1018
#define IDC_EDIT_UNIQUE                 1018
#define IDC_BTN_RESET                   1019
#define IDC_EDIT_PGSIZE                 1019
#define IDC_EDIT_STRUCT2                1020
#define IDC_BTN_NAME                    1020
#define IDC_MFC_BUTTON1                 1021
#define IDC_EDIT_STRUCT3                1021
#define IDC_MFC_BUTTON2                 1022
#define IDC_EDIT_STRUCT4                1022
#define IDC_MFC_BUTTON3                 1023
#define IDC_EDIT_ALLOCATEDPAGES         1023
#define IDC_MFC_EDIT1                   1024
#define IDC_MFC_BUTTON4                 1024
#define IDC_MFC_EDIT2                   1025
#define IDC_MFC_EDIT3                   1026
#define IDC_EDIT_INDEX_MIN_X            1027
#define IDC_EDIT_INDEX_MAX_X            1028
#define IDC_EDIT_INDEX_MIN_Y            1029
#define IDC_EDIT_INDEX_MAX_Y            1032
#define IDC_MFC_COMBO2                  1038
#define IDC_MFC_COMBO3                  1039
#define IDC_MFC_COMBO4                  1040
#define IDC_MFC_COMBO5                  1041
#define IDC_MFC_COMBO6                  1042
#define IDC_MFC_COMBO7                  1043
#define IDC_MFC_COMBO8                  1044
#define IDC_MFC_EDIT4                   1050
#define IDC_MFC_EDIT5                   1051
#define IDC_MFC_EDIT6                   1052
#define IDC_LANGUAGE                    1055
#define IDC_DBNAME                      1057
#define IDC_PUBLIC                      1059
#define IDC_PRIVATE                     1060
#define IDC_RADIO_SOFT                  1064
#define IDC_RADIO_HARD                  1065
#define IDC_STATIC_DISTNAME             1091
#define IDC_STATIC_SOURCE               1092
#define IDC_STATIC_LOCALNAME            1093
#define IDC_LOCALNAME                   1094
#define IDC_RADIO_COORDINATOR           1098
#define IDC_RADIO_CUSTOM                1099
#define IDC_CHECK_USEDEFAULTNAME        1100
#define IDC_DOMPROP_TABLE_STORAGE       1102
#define IDC_AREA                        1102
#define IDC_STATIC_STRUCT1              1111
#define IDC_STATIC_STRUCT2              1112
#define IDC_STATIC_STRUCT3              1113
#define IDC_DOMPROP_INTEG_NUM           1113
#define IDC_STATIC_STRUCT4              1114
#define IDC_DOMPROP_INTEG_TXT           1114
#define IDC_DOMPROP_PROC_TXT            1114
#define IDC_DOMPROP_RULE_TXT            1115
#define IDC_DOMPROP_RULE_PROC           1116
#define IDC_DOMPROP_PROC_RULESLIST      1117
#define IDC_CHECK_LIST                  1117
#define IDC_CHECK_PROP                  1118
#define IDC_DOMPROP_DB_OWNER            1118
#define IDC_DOMPROP_DB_LOCDB            1119
#define IDC_DOMPROP_DB_LOCCKP           1120
#define IDC_CHECK_DUPROWS               1120
#define IDC_DOMPROP_DB_LOCJNL           1121
#define IDC_STATIC_FILLFACTOR           1121
#define IDC_DOMPROP_DB_LOCDMP           1122
#define IDC_STATIC_PGSIZE               1122
#define IDC_STATIC_STRUCTURE            1122
#define IDC_DOMPROP_DB_LOCSORT          1123
#define IDC_EDIT_NBROWS                 1123
#define IDC_STATIC_PGSIZE2              1123
#define IDC_STATIC_LOCATION             1123
#define IDC_EDIT_PGALLOCATED            1124
#define IDC_DOMPROP_DB_CDB              1124
#define IDC_EDIT_SCHEMA                 1125
#define IDC_DOMPROP_VIEW_TXT            1126
#define IDC_EDIT_OVERFLOW               1126
#define IDC_EDIT_LDB_DBMSTYPE           1126
#define IDC_EDIT_TBLTOTSIZE             1126
#define IDC_EDIT_NO                     1130
#define IDC_EDIT_COLLISIONMODE          1131
#define IDC_STATIC_CDDS_TBL_COLUMNS     1131
#define IDC_EDIT_NAME                   1132
#define IDC_EDIT_ERRORMODE              1133
#define IDC_DOMPROP_CONN_DESC           1135
#define IDC_DOMPROP_CONN_NUM            1136
#define IDC_DOMPROP_CONN_VNODE          1137
#define IDC_DOMPROP_CONN_DB             1138
#define IDC_DOMPROP_CONN_TYPE           1139
#define IDC_CHECK_LOCALDB               1143
#define IDC_MFC_RADIO1                  1149
#define IDC_MFC_RADIO2                  1150
#define IDC_MFC_RADIO3                  1151
#define IDC_MFC_RADIO4                  1152
#define IDC_MFC_SPIN2                   1154
#define IDC_MFC_RADIO7                  1155
#define IDC_MFC_RADIO8                  1156
#define IDC_MFC_SPIN3                   1157
#define IDC_SPIN1                       1162
#define IDC_ERRTXT                      1163
#define IDC_SPIN_SCALE1                 1163
#define IDC_DETAIL                      1164
#define IDC_SPIN_PREC2                  1164
#define IDC_STATIC_ICON                 1165
#define IDC_SPIN_SCALE2                 1165
#define IDC_EDIT_PAGES                  1167
#define IDC_EDIT_INUSE                  1168
#define IDC_EDIT_FREED                  1169
#define IDC_EDIT_NEVERUSED              1170
#define IDC_COMBO_RATIO                 1171
#define IDC_STATIC_ZEROPCT              1174
#define IDC_STATIC_100PCT               1175
#define IDC_STATIC_PCT                  1176
#define IDC_STATIC_PGPERCELL            1177
#define IDC_STATIC_PG1                  1178
#define IDC_STATIC_CELL1                1179
#define IDC_STATIC_PG2                  1180
#define IDC_STATIC_CELL2                1181
#define IDC_STATIC_PERSIST              1182
#define IDC_STATIC_PG3                  1182
#define IDC_STATIC_CELL3                1183
#define IDC_REPLICQUESTION              1184
#define IDC_STATIC_PG4                  1184
#define IDC_QUESTION                    1185
#define IDC_STATIC_CELL4                1185
#define IDC_STATIC_CELL5                1186
#define IDC_STATIC_PG5                  1187
#define IDC_STATIC_CELL6                1188
#define IDC_EDIT_LDB_DB                 1188
#define IDC_STATIC_PG6                  1189
#define IDC_EDIT_LDB_NODE               1189
#define IDC_STATIC_CELL7                1190
#define IDC_EDIT_LDB_OWNER              1190
#define IDC_STATIC_PG7                  1191
#define IDC_EDIT_LDB_NAME               1191
#define IDC_STATIC_CELL8                1192
#define IDC_EDIT_DDB_OWNER              1192
#define IDC_BUILD_SERVER_LIST           1192
#define IDC_STATIC_PG8                  1193
#define IDC_FORCE_BUILD                 1193
#define IDC_STATIC_CELL9                1194
#define IDC_EDIT_DDB_NAME               1194
#define IDC_MFC_TREE1                   1194
#define IDC_STATIC_PG9                  1195
#define IDC_STATIC_CELL10               1196
#define IDC_STATIC_PG10                 1197
#define IDC_STATIC_CELL11               1198
#define IDC_STATIC_PG11                 1199
#define IDC_STATIC_CELL12               1200
#define IDC_STATIC_PG12                 1201
#define IDC_MFC_BUTTON5                 1203
#define IDC_MFC_BUTTON6                 1204
#define IDC_MFC_BUTTON7                 1205
#define IDC_DISTRIBUTED                 1211
#define IDC_STATIC_CDB                  1212
#define IDC_COORDNAME                   1213
#define IDC_GENFE                       1214
#define IDC_MFC_LIST3                   1218
#define IDC_EDIT_BEFTIME                1226
#define IDC_ANIMATE1                    1227
#define IDC_MFC_CHECK_COM_PRIVATE       1230
#define IDC_MFC_CHECK_LOGIN_PRIVATE     1231
#define IDC_MFC_CHECK_INSTALLATION      1232
#define IDC_BIGTABLE                    1238
#define IDC_EXPIRE                      1239
#define IDC_FRONT_END_LIST              1240
#define IDC_LOC_DATABASE                1241
#define IDC_LOC_WORK                    1242
#define IDC_LOC_JOURNAL                 1243
#define IDC_LOC_CHECKPOINT              1244
#define IDC_LOC_DUMP                    1245
#define IDC_TAB_LOCATION                1249
#define IDC_ALTERNATE_LOC_DATABASE      1251
#define IDC_ALTERNATE_LOC_WORK          1252
#define IDC_WORK_ALTERNATE              1253
#define IDC_STATIC_IMAGE                1254
#define IDC_LIST_INDEX_LOCATION         1259
#define IDC_MFC_SPIN_LEAFFIL            1267
#define IDC_MFC_SPIN_NONLEAFFIL         1268
#define IDC_MFC_SPIN_FILLFACTOR         1269
#define IDC_EDIT_INDEX_NAME             1270
#define IDC_LIST_BASETABLE_COLUMNS      1272
#define IDC_LIST_INDEX_COLUMNS          1273
#define IDC_BUTTON_COLUMN_ADD           1274
#define IDC_BUTTON_COLUMN_REMOVE        1275
#define IDC_BUTTON_COLUMN_UP            1276
#define IDC_BUTTON_COLUMN_DOWN          1277
#define IDC_COMBO_INDEX_TRUCTURE        1278
#define IDC_BUTTON_NAME_NEW             1279
#define IDC_BUTTON_NAME_DELETE          1280
#define IDC_COMBO_INDEX_PAGESIZE        1281
#define IDC_STATIC_MINPAGE              1282
#define IDC_STATIC_MAXPAGE              1283
#define IDC_STATIC_LEAFFILL             1284
#define IDC_STATIC_NONLEAFFILL          1285
#define IDC_STATIC_MIN_X                1286
#define IDC_STATIC_ALLOCATION           1286
#define IDC_STATIC_RANGE                1287
#define IDC_RADIO_UNIQUE_NO             1288
#define IDC_RADIO_UNIQUE_ROW            1289
#define IDC_RADIO_UNIQUE_STATEMENT      1290
#define IDC_CHECK_COMPRESS_KEY          1291
#define IDC_CHECK_COMPRESS_DATA         1292
#define IDC_CHECK_INDEX_PERSISTENCE     1293
#define IDC_EDIT_INDEX_MINPAGE          1294
#define IDC_EDIT_INDEX_MAXPAGE          1295
#define IDC_EDIT_INDEX_LEAFFILL         1296
#define IDC_EDIT_INDEX_NONLEAFFILL      1297
#define IDC_EDIT_INDEX_ALLOCATION       1298
#define IDC_EDIT_INDEX_EXTEND           1299
#define IDC_EDIT_INDEX_FILLFACTOR       1300
#define IDC_STATIC_MAX_X                1301
#define IDC_STATIC_MIN_Y                1302
#define IDC_STATIC_MAX_Y                1303
#define IDC_LIST_INDEX_NAME             1304
#define IDC_STATIC_TEXT                 1305
#define IDC_STATIC_DB                   1306
#define IDC_STATIC_WK                   1307
#define IDC_EDIT_FILE_NAME              1310
#define IDC_BROWSE_FILE                 1311
#define IDC_COMBO_INDEXNAME             1312
#define IDC_COMBO_INDEX                 1313
#define IDC_ICE_ROLE_NAME               1314
#define IDC_COMBO_INDEXNAME2            1314
#define IDC_ROLE_COMMENT                1315
#define IDC_DBU_ALIAS                   1315
#define IDC_ICEUSERNAME                 1315
#define IDC_DBU_NAME                    1316
#define IDC_ALIASS                      1316
#define IDC_DBU_PASSWORD                1317
#define IDC_ICE_NAME                    1317
#define IDC_DBU_CONFIRM                 1318
#define IDC_ICE_DB_USER                 1318
#define IDC_DBU_COMMENT                 1319
#define IDC_NODE                        1319
#define IDC_COMMENT                     1319
#define IDC_DATABASE                    1320
#define IDC_ICE_DBC_COMMENT             1321
#define IDC_ICE_ADMIN                   1322
#define IDC_ADMIN                       1322
#define IDC_SECUR_ADMIN                 1323
#define IDC_EXTENSION                   1323
#define IDC_ICE_UNIT_MANAGER            1324
#define IDC_UNIT_MANAGER                1324
#define IDC_ICE_TIMEOUT                 1325
#define IDC_TIMEOUT                     1325
#define IDC_ICE_MONITORING              1326
#define IDC_MONITORING                  1326
#define IDC_ICE_CWU_COMMENT             1327
#define IDC_ICE_DEF_DB_USER             1328
#define IDC_ICE_CWU_CONFIRM             1329
#define IDC_ICE_CWU_PASSWORD            1330
#define IDC_ICE_USR_NAME                1331
#define IDC_CP_ADMIN                    1332
#define IDC_CP_SECUR_ADMIN              1333
#define IDC_CP_UNIT_MANAGER             1334
#define IDC_CP_MONITORING               1335
#define IDC_CP_NAME                     1336
#define IDC_CP_DEF_DB_USER              1337
#define IDC_CP_TIMEOUT                  1338
#define IDC_STATIC_EXTEND               1339
#define IDC_ICE_DOC_NAME                1341
#define IDC_ICE_ACCESS                  1342
#define IDC_PRE_CACHE                   1343
#define IDC_PERM_CACHE                  1344
#define IDC_SESSION_CACHE               1345
#define IDC_PATH                        1347
#define IDC_ST_REPOSITORY               1348
#define IDC_ST_FILE_SYSTEM              1349
#define IDC_MFC_EDITKEYNAME             1352
#define IDC_ROLE                        1353
#define IDC_EXEC_DOC                    1354
#define IDC_CREATE_DOC                  1355
#define IDC_WEB_USER                    1355
#define IDC_READ_DOC                    1356
#define IDC_USER_UNIT_READ              1356
#define IDC_USER_CREATE_DOC             1357
#define IDC_USER_READ_DOC               1358
#define IDC_LIST_LOCATION               1364
#define IDC_NEW_DB_NAME                 1365
#define IDC_ASSIGN_LOC                  1366
#define IDC_COMMON_STATIC               1367
#define IDC_COMMON_COMBOBOX             1368
#define IDC_COMMON_EDIT                 1371
#define IDC_ICE_USER                    1372
#define IDC_ICE_PASSWORD                1373
#define IDC_ICE_VALUE                   1375
#define IDC_NAME_LOCATION               1376
#define IDC_HTTP                        1377
#define IDC_ICE                         1378
#define IDC_PATH_LOCATION               1379
#define IDC_EXTENSION_LOCATION          1380
#define IDC_ICE_PUBLIC                  1382
#define IDC_STATIC_INDEX                1383
#define IDC_MFC_COMBOPROC               1391
#define IDC_RAD_EXPIRE_NO               1397
#define IDC_RAD_EXPIRE_YES              1398
#define IDC_ICE_DOC_EXT                 1400
#define IDC_ICE_STAT_LOCATION           1401
#define IDC_ICE_LOCATION                1402
#define IDC_ICE_STATIC_PATH             1403
#define IDC_ICE_EDIT_FILENAME           1404
#define IDC_ICE_FILENAME_EXT            1405
#define IDC_ICE_STATIC_SEPARATOR        1406
#define IDC_ICE_STATIC_FILENAME         1407
#define IDC_ICE_STATIC_CACHE            1408
#define IDC_READ_ONLY                   1410
#define IDC_READONLY                    1414
#define IDC_ICE_DOC_NAMEPLUSEXT         1417
#define IDC_ICE_FILENAMEPLUSEXT         1418
#define IDC_REPOSITORY                  1419
#define IDC_FILE_SYSTEM                 1420
#define IDC_ICE_ST_LOC                  1421
#define IDC_ICE_ST_FILENAME             1422
#define IDC_ST_PATH                     1423
#define IDC_ST_PRE_CACHE                1424
#define IDC_ST_PERM_CACHE               1425
#define IDC_ST_SESSION_CACHE            1426
#define IDC_MFC_CHECK8                  1428
#define IDC_COMBO_ROLE_USER             1431
#define IDC_CHECK_EXECUTE               1432
#define IDC_CHECK_READ                  1433
#define IDC_CHECK_UPDATE                1434
#define IDC_CHECK_DELETE                1435
#define IDC_STATIC_TYPE                 1436
#define IDC_EXECUTE                     1437
#define IDC_READ                        1438
#define IDC_UPDATE                      1439
#define IDC_MFC_DELETE                  1440
#define IDC_UNITREAD                    1441
#define IDC_CREATEDOC                   1442
#define IDC_READDOC                     1443
#define IDC_EXECDOC                     1444
#define IDC_MFC_MAXDOCS                 1453
#define IDC_MFC_STATIC_PAGECOUNT        1454
#define IDC_STATIC_I1                   1455
#define IDC_STATIC_I2                   1456
#define IDC_STATIC_I3                   1457
#define IDC_STATIC_I4                   1458
#define IDC_STATIC_I5                   1459
#define IDC_STATIC_I6                   1460
#define IDC_STATIC_I7                   1461
#define IDC_STATIC_I8                   1462
#define IDC_STATIC_I9                   1463
#define IDC_STATIC_L1                   1464
#define IDC_STATIC_L2                   1465
#define IDC_STATIC_L3                   1466
#define IDC_STATIC_L4                   1467
#define IDC_STATIC_L5                   1468
#define IDC_STATIC_L6                   1469
#define IDC_STATIC_L7                   1470
#define IDC_STATIC_L8                   1471
#define IDC_STATIC_L9                   1472
#define IDC_STATIC_V1                   1473
#define IDC_STATIC_V2                   1474
#define IDC_STATIC_V3                   1475
#define IDC_STATIC_V4                   1476
#define IDC_STATIC_V5                   1477
#define IDC_STATIC_V6                   1478
#define IDC_STATIC_V7                   1479
#define IDC_STATIC_V8                   1480
#define IDC_STATIC_V9                   1481
#define IDC_STATIC_L_TOTAL              1482
#define IDC_STATIC_L_LONGEST_OC         1483
#define IDC_RADIOSHADOWTBL              1483
#define IDC_STATIC_L_AVG_OC             1484
#define IDC_RADIOBOTHQUEUE              1484
#define IDC_STATIC_V_TOTAL              1485
#define IDC_STATIC_V_LOC                1486
#define IDC_STATIC_V_ALOC               1487
#define IDC_RADIO_REPOSITORY            1487
#define IDC_RADIO_OPERASYSTEM           1488
#define IDC_STATIC_CONF_PWD             1489
#define IDC_STATIC_PWD                  1490
#define IDC_RAD_JNL_ACTIVE              1491
#define IDC_RAD_JNL_INACTIVE            1492
#define IDC_RAD_JNL_AFTERCKPDB          1493
#define IDC_STATIC_DUPROWS              1494
#define IDC_RAD_UNIQ_NO                 1495
#define IDC_STATIC_UNIQ_NO              1496
#define IDC_ST_STRUCTUNIQ               1497
#define IDC_RAD_UNIQ_ROW                1498
#define IDC_CHECKRELOADFILE             1498
#define IDC_STATIC_UNIQ_ROW             1499
#define IDC_RAD_UNIQ_STMT               1500
#define IDC_STATICRELOADFILE            1500
#define IDC_STATIC_UNIQ_STMT            1501
#define IDC_COMBO_DB                    1507
#define IDC_SPIN_SVR_NUMBER             1510
#define IDC_EDIT_COMMENT                1519
#define IDC_TABLE_COMMENT               1520
#define IDC_COLUMNS_COMMENT             1521
#define IDC_CHECK_NOINTERRUPT           1540
#define IDC_BUTTON_TABLES               1541
#define IDC_CHECK_SPECIF_TABLES         1542
#define IDC_STATIC_TBLNAME              1545
#define IDC_CHECK_TABLES                1546
#define IDC_BUTTON_SPECIFY_TABLES       1547
#define IDC_CHECK_PRINT_DATA_FILES      1548
#define IDC_STATIC_DIR_NAME             1549
#define IDC_STATIC_DIR_SOURCE           1550
#define IDC_STATIC_DIR_DEST             1551
#define IDC_EDIT_DIRECTORY_NAME         1552
#define IDC_EDIT_DIRECTORY_SOURCE       1553
#define IDC_EDIT_DIRECTORY_DESTINATION  1554
#define IDC_LIST_OPTIONS                1556
#define IDC_CHECK_ORDER_CCM             1557
#define IDC_CHECK_ADD_DROP              1558
#define IDC_CHECK_NO_LOC                1559
#define IDC_CHECK_NOINT                 1560
#define IDC_CHECK_RELPATH               1561
#define IDC_STATIC_INFILE               1562
#define IDC_EDIT_INPUT_FILENAME         1563
#define IDC_EDIT_OUTPUT_FILENAME        1564
#define IDC_STATIC_TBL                  1565
#define IDC_EDIT_SELTBL                 1566
#define IDC_EDIT_AREA                   1567
#define IDC_EDIT_LOC_NAME               1568
#define IDC_CHECK_RAW_AREA              1569
#define IDC_CHECKRAWAREA                1570
#define IDC_EDIT_PCT_RAW                1571
#define IDC_STATIC_PCT_RAW              1572
#define IDC_EDIT_PCT_RAW2               1573
#define IDC_STATIC_PCTRAW               1574
#define IDC_STATIC_CHECKAREA            1575
#define IDC_STATICFLOAT4                1576
#define IDC_EDIT_PREC4                  1579
#define IDC_EDIT_SCALE4                 1580
#define IDC_STATICFLOAT8                1581
#define IDC_EDIT_PREC8                  1584
#define IDC_EDIT_SCALE8                 1585
#define IDC_CHECK_EXPONENTIAL4          1586
#define IDC_CHECK_EXPONENTIAL8          1587
#define IDC_SPIN_PREC1                  1588
#define IDC_CHECK_GRANT_REVOKE_RMCMD    1589
#define IDC_STATIC_PARTIAL_GRANT        1590
#define IDC_STATIC_ICON_PARTIALGRANT    1591
#define IDC_GRANT_REVOKE_RMCMD          1592
#define IDC_ICON_PARTIALGRANT           1593
#define IDC_PARTIAL_GRANT               1594
#define IDC_STATIC_USER_GRANTED         1595
#define IDC_STATIC_RMCMD_TITLE          1596
#define IDC_CHECK_UNICODE               1597
#define IDC_STATIC_UNICODE              1600
#define IDC_LIST_PAGE_SIZE              1601
#define IDC_STATIC_CBF_CONFIG           1602
#define IDC_LIST_CHECKPOINT             1603
#define IDC_BUTTON_CHECKPOINT           1604
#define IDC_STATIC_NAME                 1605
#define IDC_EDIT_NUMBER                 1606
#define IDC_CHECK_SPECIFY               1607
#define IDC_RADIO_LAST_CKP              1608
#define IDC_EDIT_START_WITH             1610
#define IDC_RADIO_SPECIFY_CKP           1611
#define IDC_STATIC_START_WITH           1613
#define IDC_EDIT_INCREMENT_BY           1614
#define IDC_STATIC_INCREMENT            1615
#define IDC_STATIC_MAX                  1616
#define IDC_STATIC_MIN                  1617
#define IDC_EDIT_MAX                    1618
#define IDC_EDIT_MIN                    1619
#define IDC_EDIT_CACHE                  1621
#define IDC_CHECK_CACHE                 1628
#define IDC_EDIT_DECIMAL                1632
#define IDC_RADIO_INTEGER               1633
#define IDC_RADIO_DECIMAL               1634
#define IDC_STATIC_PREC                 1635
#define IDC_CHECK_CYCLE                 1636
#define IDC_EDIT_PRECISION              1639
#define IDC_EDIT_MAX_VALUE              1640
#define IDC_EDIT_MIN_VALUE              1641
#define IDC_EDIT_START_W                1642
#define IDC_EDIT_INCREMENT              1643
#define IDC_STATIC_CAT_PAGE_SIZE        1648
#define IDC_COMBO_CAT_PAGE_SIZE         1649
#define IDC_EDIT_CAT_PAGE_SIZE          1651
#define IDC_CHECK_UNICODE2              1653
#define IDC_STATIC_UNICODE2             1655
#define IDC_CHECK_NONUNICODE            1658
#define IDC_MORE_OPTIONS                1659
#define IDC_GROUP_STATIC                1663
#define IDC_TAB1                        1666
#define IDC_XUSER_TAB                   1666
#define IDC_TAB_XROLE                   1667
#define IDC_MFC_STATIC_ACCESSDB         1668
#define IDC_STATIC_PASSWD               1671
#define IDC_STATIC_CPASSWD              1672
#define IDS_NODE                        3446
#define IDS_NODE_NONE                   3447
#define IDS_NODE_OPENWIN                3448
#define IDS_NODE_OPENWIN_NONE           3449
#define IDS_NODE_ADVANCED               3450
#define IDS_NODE_LOGINPSW               3451
#define IDS_NODE_LOGINPSW_NONE          3452
#define IDS_NODE_CONNECTIONDATA         3453
#define IDS_NODE_CONNECTIONDATA_NONE    3454
#define IDS_DOCKINGINFO                 3455
#define IDS_VIRTNODE_TITLE              3456
#define IDS_TM_SESS_LOCK                3469
#define IDS_TM_SESS_DB                  3473
#define IDS_TM_LOCKLIST                 3475
#define IDS_TM_LOCATION                 3483
#define IDS_TM_LOCATION_NONE            3484
#define IDS_TM_LOC_DB                   3485
#define IDS_TM_LOC_DB_NONE              3486
#define IDS_TM_LOGINFO                  3487
#define IDS_RAISEDDBE_TIME              3494
#define IDS_RAISEDDBE_NAME              3495
#define IDS_RAISEDDBE_OWNER             3496
#define IDS_RAISEDDBE_TEXT              3497
#define IDS_DATABASE_NONE               3498
#define IDS_CAPT_IPM                    3499
#define IDS_CAPT_DBEVENT                3500
#define IDS_TM_DB_LOCKEDOTHER           3511
#define IDS_TM_DB_LOCKEDOTHER_NONE      3512
#define IDS_IPMBAR_TITLE                3525
#define IDS_DBEVENT_TITLE               3526
#define IDS_ALLRESOURCETYPES            3527
#define IDS_DOMBAR_TITLE                3528
#define IDS_SQLACTBAR_TITLE             3529
#define IDS_APPBAR_TITLE                3530
#define IDS_TM_ERR_ERR                  3531
#define IDS_TM_ERR_NOGRANT              3532
#define IDS_TM_ERR_TIMEOUT              3533
#define IDS_TAB_TRANSACTION             3538
#define IDS_TAB_SUMMARY                 3543
#define IDS_DBEVENT_RAISE_HEADER        3544
#define IDS_IPMPROPERTY_HEADER          3545
#define IDS_ALTER_NODE_TITLE            3547
#define IDS_DROP_NODE                   3548
#define IDS_DROP_NODE_DATA              3549
#define IDS_DROP_NODE_LOGIN             3550
#define IDS_DROP_NODE_FAILED            3551
#define IDS_DROP_NODE_DATA_FAILED       3552
#define IDS_DROP_NODE_LOGIN_FAILED      3553
#define IDS_ADD_NODE_FAILED             3554
#define IDS_ADD_NODE_DATA_FAILED        3555
#define IDS_ADD_NODE_LOGIN_FAILED       3556
#define IDS_ALTER_NODE_FAILED           3557
#define IDS_ALTER_NODE_DATA_FAILED      3558
#define IDS_ALTER_NODE_LOGIN_FAILED     3559
#define IDS_ALTER_NODE_DATA_TITLE       3560
#define IDS_ALTER_NODE_LOGIN_TITLE      3561
#define IDS_NODE_ALREADY_EXIST          3562
#define IDS_TAB_LOCATIONS_TITLE         3569
#define IDS_TAB_LOCATION_TITLE          3570
#define IDS_TAB_LOGINFO_TITLE           3571
#define IDS_ALTER_NODEDATA_TITLE        3594
#define IDS_ALTER_NODELOGIN_TITLE       3595
#define IDS_RAISEDDBE_NUM               3603
#define IDS_DISCONNECT_CAPTION          3633
#define IDS_ERR_ALTERNODE_OPENNODES     3634
#define IDS_ERR_ALTERNODE_COMPLEX       3635
#define IDS_ERR_MONITOR_NOIMADB         3636
#define IDS_ERR_MONITOR_NOTOIV2         3637
#define IDS_DBECHECKED_HASBEEN_REMOVED  3639
#define IDS_TAB_HEADER_TITLE            3644
#define IDS_LOGINFO_DIAGRAM_CAPT        3645
#define IDS_ERR_ADDNODELOGIN_OPENNODES  3660
#define IDS_ERR_ADDNODECONNECTION_OPENNODES 3661
#define IDS_ERR_ALTERNODELOGIN_OPENNODES 3662
#define IDS_ERR_ALTERNODECONNECTION_OPENNODES 3663
#define IDS_ERR_DROPNODELOGIN_OPENNODES 3664
#define IDS_ERR_DROPNODECONNECTION_OPENNODES 3665
#define IDS_TAB_SUMMARY_LOCATIONS       3666
#define IDS_DISKSPACE_FREE              3667
#define IDS_DISKSPACE_OTHER             3668
#define IDS_DISKSPACE_OTHERLOCATIONS    3672
#define IDS_TAB_LOCATION_PAGE1          3673
#define IDS_TAB_LOCATION_PAGE2          3674
#define IDS_TAB_LOCATION_PAGE1_TITLE    3675
#define IDS_TAB_LOCATION_PAGE2_TITLE    3676
#define IDS_TAB_LOCATION_PAGE3          3677
#define IDS_DISKSPACE_NODATABASES       3678
#define IDS_DISKSPACE_EMPTYDATABASES    3679
#define IDS_DISKSPACE_INVALID_DATABASE  3680
#define IDS_STAR_DATABASE_NONE          3683
#define IDS_STAR_TABLE_NONE             3684
#define IDS_STAR_VIEW_NONE              3685
#define IDS_CAPT_SQLTEST                3686
#define IDS_STAR_PROCEDURE_NONE         3687
#define IDS_TM_REPLIC_NOTINSTALLED      3692
#define IDS_DOMPROP_TABLE_TEST          3693
#define IDS_DOMPROP_TABLE_TITLE         3694
#define IDS_DOMPROP_LOC_TITLE           3707
#define IDS_DOMPROP_LOC                 3708
#define IDS_DOMPROP_USER_TITLE          3709
#define IDS_DOMPROP_USER                3710
#define IDS_DOMPROP_ROLE_TITLE          3711
#define IDS_DOMPROP_ROLE                3712
#define IDS_DOMPROP_PROF_TITLE          3713
#define IDS_ERR_ADDATTRIBUTE_OPENNODES  3714
#define IDS_DOMPROP_INDEX_TITLE         3715
#define IDS_DOMPROP_INDEX               3716
#define IDS_DOMPROP_INTEG_TITLE         3717
#define IDS_DOMPROP_INTEG               3718
#define IDS_DOMPROP_RULE_TITLE          3719
#define IDS_DOMPROP_RULE                3720
#define IDS_DOMPROP_PROC_TITLE          3721
#define IDS_DOMPROP_PROC                3722
#define IDS_DOMPROP_GROUP_TITLE         3723
#define IDS_DOMPROP_GROUP               3724
#define IDS_DOMPROP_DB_TITLE            3725
#define IDS_DOMPROP_DB_ALARMS           3726
#define IDS_DOMPROP_TABLE_ALARMS        3727
#define IDS_DOMPROP_TABLE_GRANTEES      3728
#define IDS_DOMPROP_DB_GRANTEES         3729
#define IDS_DOMPROP_DB                  3730
#define IDS_DOMPROP_TABLE               3731
#define IDS_DOMPROP_VIEW_TITLE          3732
#define IDS_DOMPROP_VIEW_GRANTEES       3733
#define IDS_DOMPROP_VIEW                3734
#define IDS_DOMPROP_CDDS_TITLE          3735
#define IDS_DOMPROP_CDDS                3736
#define IDS_DOMPROP_CDDS_TBL            3737
#define IDS_DOMPROP_CDDS_TBL_COLUMNS    3738
#define IDS_DOMPROP_DBEV_TITLE          3739
#define IDS_DOMPROP_DBEV_GRANTEES       3740
#define IDS_DOMPROP_PROC_GRANTEES       3741
#define IDS_DOMPROP_TABLE_COLUMNS       3742
#define IDS_DOMPROP_REPL_TITLE          3743
#define IDS_DOMPROP_REPL_CDDS           3744
#define IDS_DOMPROP_REPL_CONN           3745
#define IDS_DOMPROP_REPL_MAILU          3746
#define IDS_DOMPROP_REPL_REGTBL         3747
#define IDS_DOMPROP_REPLNO_TITLE        3748
#define IDS_DOMPROP_REPLNA_TITLE        3749
#define IDS_DOMPROP_DB_TBLS             3750
#define IDS_DOMPROP_DB_VIEWS            3751
#define IDS_DOMPROP_DB_PROCS            3752
#define IDS_DOMPROP_DB_SCHEMAS          3753
#define IDS_DOMPROP_DB_SYNS             3754
#define IDS_DOMPROP_DB_EVTS             3755
#define IDS_DISCONNECTSVR_CAPTION       3756
#define IDS_DOMPROP_TABLE_INTEG         3757
#define IDS_DOMPROP_TABLE_RULE          3758
#define IDS_DOMPROP_TABLE_IDX           3759
#define IDS_DOMPROP_TABLE_LOC           3760
#define IDS_DOMPROP_USER_XALARMS        3761
#define IDS_DOMPROP_USER_XGRANTED_DB    3762
#define IDS_DOMPROP_USER_XGRANTED_DBEV  3763
#define IDS_DOMPROP_USER_XGRANTED_PROC  3764
#define IDS_DOMPROP_USER_XGRANTED_ROLE  3765
#define IDS_DOMPROP_USER_XGRANTED_TBL   3766
#define IDS_DOMPROP_USER_XGRANTED_VIEW  3767
#define IDS_DOMPROP_GROUP_XGRANTED_DB   3768
#define IDS_DOMPROP_GROUP_XGRANTED_DBEV 3769
#define IDS_DOMPROP_GROUP_XGRANTED_PROC 3770
#define IDS_DOMPROP_GROUP_XGRANTED_TBL  3771
#define IDS_DOMPROP_GROUP_XGRANTED_VIEW 3772
#define IDS_DOMPROP_ROLE_XGRANTED_DB    3773
#define IDS_DOMPROP_ROLE_XGRANTED_DBEV  3774
#define IDS_DOMPROP_ROLE_XGRANTED_PROC  3775
#define IDS_DOMPROP_ROLE_XGRANTED_TBL   3776
#define IDS_DOMPROP_ROLE_XGRANTED_VIEW  3777
#define IDS_DOMPROP_DB_GRANTEES_TITLE   3778
#define IDS_DOMPROP_DB_ALARMS_TITLE     3779
#define IDS_DOMPROP_TABLE_GRANTEES_TITLE 3780
#define IDS_DOMPROP_TABLE_ALARMS_TITLE  3781
#define IDS_DOMPROP_VIEW_GRANTEES_TITLE 3782
#define IDS_DOMPROP_PROC_GRANTEES_TITLE 3783
#define IDS_ERR_ALTERATTRIBUTE_OPENNODES 3784
#define IDS_DOMPROP_CONNECTION_TITLE    3785
#define IDS_DOMPROP_CONNECTION          3786
#define IDS_DOMPROP_DDB_TITLE           3787
#define IDS_DOMPROP_DDB                 3788
#define IDS_DOMPROP_DDB_TBLS            3789
#define IDS_DOMPROP_DDB_VIEWS           3790
#define IDS_DOMPROP_DDB_PROCS           3791
#define IDS_DOMPROP_STARPROC_L_TITLE    3792
#define IDS_DOMPROP_STARPROC_L          3793
#define IDS_DOMPROP_STARTBL_L_TITLE     3794
#define IDS_DOMPROP_STARTBL_L_IDX       3795
#define IDS_DOMPROP_STARTBL_N_TITLE     3796
#define IDS_DOMPROP_STARVIEW_N_TITLE    3797
#define IDS_DOMPROP_STARVIEW_N          3798
#define IDS_DOMPROP_STARVIEW_L_TITLE    3799
#define IDS_DOMPROP_STARVIEW_L          3800
#define IDS_DOMPROP_SCHEMA_TITLE        3802
#define IDS_DOMPROP_SCHEMA_TBLS         3803
#define IDS_DOMPROP_SCHEMA_VIEWS        3804
#define IDS_DOMPROP_SCHEMA_PROCS        3805
#define IDS_ERR_DBEVENT_NOTOI           3806
#define IDS_DOMPROP_TABLE_PAGES         3807
#define IDS_DOMPROP_TABLE_ROWS          3808
#define IDS_DOMPROP_TABLE_STATISTIC     3809
#define IDS_SVRCLASS                    3810
#define IDS_SVRCLASS_NONE               3811
#define IDS_DOMPROP_INDEX_PAGES         3812
#define IDS_NODEUSER                    3813
#define IDS_NODEUSER_NONE               3814
#define IDS_USER_OPENWIN                3815
#define IDS_USER_OPENWIN_NONE           3816
#define IDS_USER_NOTOI                  3817
#define IDS_DOMPROP_STARTBL_N           3820
#define IDS_DOMPROP_STARTBL_L           3821
#define IDS_DOMPROP_STARDB_COMPONENT    3822
#define IDS_DOMPROP_STARINDEX_L_TITLE   3823
#define IDS_DOMPROP_INDEX_L_SOURCE      3824
#define IDS_DOMPROP_VIEW_L_SOURCE       3825
#define IDS_DOMPROP_VIEW_N_SOURCE       3826
#define IDS_DOMPROP_PROC_L_SOURCE       3827
#define IDS_DOMPROP_TABLE_ROWSNA        3828
#define ID_BUTTON_REMOVEOBJECT          3829
#define IDS_ALREADY_FETCHED_ROW         3829
#define IDS_TOTAL_FETCHED_ROW           3830
#define IDS_DOMPROP_ST_TABLE_TITLE      3831
#define IDS_DOMPROP_ST_STAR_TABLE_TITLE 3832
#define IDS_DOMPROP_ST_VIEW_TITLE       3833
#define IDS_DOMPROP_ST_STAR_VIEW_TITLE  3834
#define IDS_DOMPROP_ST_PROC_TITLE       3835
#define IDS_DOMPROP_ST_STAR_PROC_TITLE  3836
#define IDS_DOM_FAST_CANNOTEXPAND       3837
#define IDS_DOMPROP_ST_SCHEMA_TITLE     3838
#define IDS_DOMPROP_ST_SYN_TITLE        3839
#define IDS_DOMPROP_ST_EVT_TITLE        3840
#define IDS_DOMPROP_ST_INTEG_TITLE      3841
#define IDS_DOMPROP_ST_RULE_TITLE       3842
#define IDS_DOMPROP_ST_INDEX_TITLE      3843
#define IDS_DOMPROP_ST_LOC_TITLE        3844
#define IDS_DOMPROP_ST_STAR_INDEX_TITLE 3845
#define IDS_IPM_FAST_CANNOTEXPAND       3846
#define IDR_HTML_XDLGUSERSECURITY       3847
#define IDR_HTML_XDLGUSERSECURITY1      3849
#define IDR_HTML_XDLGUSERSECURITY2      3851
#define IDR_HTML_XDLGUSERSECURITY3      3853
#define IDS_DOMPROP_ST_GROUPUSER_TITLE  3854
#define IDS_DOMPROP_ST_DB_TITLE         3855
#define IDS_DOMPROP_ST_DB               3856
#define IDS_DOMPROP_ST_PROFILE_TITLE    3857
#define IDS_DOMPROP_ST_PROFILE          3858
#define IDS_DOMPROP_ST_USER_TITLE       3859
#define IDS_DOMPROP_ST_USER             3860
#define IDS_DOMPROP_ST_GROUP_TITLE      3861
#define IDS_DOMPROP_ST_GROUP            3862
#define IDS_DOMPROP_ST_ROLE_TITLE       3863
#define IDS_DOMPROP_ST_ROLE             3864
#define IDS_DOMPROP_ST_LOCATION         3865
#define IDS_DOMPROP_ST_GWDB             3866
#define IDS_DOMPROP_ST_GWDB_TITLE       3867
#define IDS_LOC_TYPE_WORK               3890
#define IDS__LOC_TYPE_AUXILIARY         3891
#define IDS_NODE_ATTRIBUTE              3892
#define IDS_NODE_ATTRIBUTE_NONE         3893
#define IDS_ERR_DROPATTRIBUTE_OPENNODES 3894
#define IDS_DROP_NODE_ATTRIBUTE         3895
#define IDS_DROP_NODE_ATTRIBUTE_FAILED  3896
#define IDS_DROP_INSTALLPASSWORD        3897
#define IDS_TAB_TITLE_ONE               3898
#define IDS_TAB_TITLE_TWO               3899
#define IDS_ALTER_NODE_ATTRIBUTE_TITLE  3900
#define IDS_DOMPROP_ICE_DBUSER_TITLE    3901
#define IDS_DOMPROP_ICE_DBUSER          3902
#define IDS_DOMPROP_ICE_DBCONNECTION_TITLE 3903
#define IDS_DOMPROP_ICE_DBCONNECTION    3904
#define IDS_DOMPROP_ICE_ROLE_TITLE      3905
#define IDS_DOMPROP_ICE_ROLE            3906
#define IDS_DOMPROP_ICE_WEBUSER_TITLE   3907
#define IDS_DOMPROP_ICE_WEBUSER         3908
#define IDS_DOMPROP_ICE_PROFILE_TITLE   3909
#define IDS_DOMPROP_ICE_PROFILE         3910
#define IDS_DOMPROP_ICE_SERVER_VARIABLE_TITLE 3911
#define IDS_DOMPROP_ICE_SERVER_VARIABLE 3912
#define IDS_DOMPROP_ICE_SERVER_LOCATION_TITLE 3913
#define IDS_DOMPROP_ICE_SERVER_LOCATION 3914
#define IDS_DOMPROP_ICE_BUNIT_TITLE     3915
#define IDS_DOMPROP_ICE_BUNIT           3916
#define IDS_DOMPROP_ICE_SEC_ROLES       3917
#define IDS_DOMPROP_ST_ICE_SEC_TITLE    3918
#define IDS_DOMPROP_ICE_SEC_DBCONNS     3919
#define IDS_DOMPROP_ICE_SEC_DBUSERS     3920
#define IDS_DOMPROP_ICE_SEC_PROFILES    3921
#define IDS_DOMPROP_ICE_SEC_WEBUSERS    3922
#define IDS_DOMPROP_ST_ICE_ROLE_TITLE   3923
#define IDS_DOMPROP_ST_ICE_DBUSER_TITLE 3924
#define IDS_DOMPROP_ST_ICE_DBCONN_TITLE 3925
#define IDS_DOMPROP_ST_ICE_WEBUSER_TITLE 3926
#define IDS_DOMPROP_ST_ICE_PROFILE_TITLE 3927
#define IDS_DOMPROP_ICE_WEBUSER_ROLES   3928
#define IDS_DOMPROP_ICE_WEBUSER_CONNECTIONS 3929
#define IDS_DOMPROP_ICE_PROFILE_ROLES   3930
#define IDS_DOMPROP_ICE_PROFILE_CONNECTIONS 3931
#define IDS_DOMPROP_ST_ICE_WEBUSER_ROLE_TITLE 3932
#define IDS_DOMPROP_ST_ICE_WEBUSER_CONNECTION_TITLE 3933
#define IDS_DOMPROP_ST_ICE_PROFILE_ROLE_TITLE 3934
#define IDS_DOMPROP_ST_ICE_PROFILE_CONNECTION_TITLE 3935
#define IDS_DOMPROP_ICE_SERVER_APPLICATIONS 3936
#define IDS_DOMPROP_ICE_SERVER_LOCATIONS 3937
#define IDS_DOMPROP_ICE_SERVER_VARIABLES 3938
#define IDS_DOMPROP_ST_ICE_SERVER_TITLE 3939
#define IDS_DOMPROP_ST_ICE_SERVER_APPLICATION_TITLE 3940
#define IDS_DOMPROP_ST_ICE_SERVER_LOCATION_TITLE 3941
#define IDS_DOMPROP_ST_ICE_SERVER_VARIABLE_TITLE 3942
#define IDS_DOMPROP_INSTLEVEL_AUDITALLUSERS 3969
#define IDS_DOMPROP_INSTLEVEL_ENABLELEVEL 3970
#define IDS_DOMPROP_INSTLEVEL_AUDITLOG  3971
#define IDS_DOMPROP_INSTLEVEL_TITLE     3972
#define IDS_DOMPROP_INSTALL_GRANTEES_TITLE 3973
#define IDS_DOMPROP_INSTALL_ALARMS_TITLE 3974
#define IDS_ICE_ALTER_DATABASE_USER_TITLE 3975
#define IDS_ICE_ALTER_BUSINESS_PAGE_TITLE 3976
#define IDS_ICE_ALTER_BUSINESS_FACET_TITLE 3977
#define IDS_ICE_ALTER_DATABASE_CONNECT_TITLE 3978
#define IDS_ICE_ALTER_PROFILE_TITLE     3979
#define IDS_ICE_ALTER_ROLE_TITLE        3980
#define IDS_ICE_ALTER_WEB_USER_TITLE    3981
#define IDS_ICE_ALTER_BU_ROLE_TITLE     3982
#define IDS_ICE_ALTER_BU_USER_TITLE     3983
#define IDS_ICE_ALTER_BU_LOCATION_TITLE 3984
#define IDS_ICE_ALTER_SVR_VARIABLE_TITLE 3985
#define IDS_ICE_WEBUSER_CONNECTION_TITLE 3986
#define IDS_ICE_WEBUSER_ROLE_TITLE      3987
#define IDS_ICE_PROFILE_CONNECTION_TITLE 3988
#define IDS_ICE_PROFILE_ROLE_TITLE      3989
#define IDS_ICE_BUNIT_LOCATION_TITLE    3990
#define IDS_ICE_BUNIT_TITLE             3991
#define IDS_ICE_SERVER_APPLICATION_TITLE 3992
#define IDS_E_ICE_FILL_COMBO_DBCONNECTION 3993
#define IDS_E_ICE_FILL_COMBO_ROLE       3994
#define IDS_E_ICE_FILL_COMBO_SERVER_LOCATION 3995
#define IDS_E_ICE_ADD_BUNIT_SEC_ROLE_FAILED 3997
#define IDS_E_ICE_ALTER_BUNIT_SEC_ROLE_FAILED 3998
#define IDS_E_ICE_ALTER_BUNIT_SEC_USER_FAILED 3999
#define IDS_E_ICE_ADD_BUNIT_SEC_USER_FAILED 4000
#define IDS_E_ICE_FILL_COMBO_WEB_USER   4001
#define IDS_E_ICE_WEBUSER_CONNECTION_FAILED 4002
#define IDS_E_ICE_WEBUSER_ROLE_FAILED   4003
#define IDS_E_ICE_PROFILE_CONNECTION_FAILED 4004
#define IDS_E_ICE_PROFILE_ROLE_FAILED   4005
#define IDS_E_ICE_BUNIT_LOCATION_FAILED 4006
#define IDS_E_ICE_ADD_DATABASE_USER_FAILED 4007
#define IDS_E_ICE_ALTER_DATABASE_USER_FAILED 4008
#define IDS_E_ICE_BUSINESS_UNIT_FACET_FAILED 4009
#define IDS_E_ICE_BUSINESS_UNIT_PAGE_FAILED 4010
#define IDS_E_ICE_ADD_DATABASE_CONNECTION_FAILED 4011
#define IDS_E_ICE_ALTER_DATABASE_CONNECTION_FAILED 4012
#define IDS_E_ICE_FILL_COMBO_DATABASE   4013
#define IDS_E_ICE_FILL_COMBO_DB_USER    4014
#define IDS_E_ICE_ADD_PROFILE           4017
#define IDS_E_ICE_ALTER_PROFILE         4018
#define IDS_E_ICE_ADD_WEB_USER          4019
#define IDS_E_ICE_ALTER_WEB_USER        4020
#define IDS_E_ICE_ADD_ROLE              4021
#define IDS_E_ICE_ALTER_ROLE            4022
#define IDS_E_ICE_BUSINESS_UNIT_FAILED  4023
#define IDS_E_ICE_SESSION_GROUP_FAILED  4024
#define IDS_E_ICE_ADD_SVR_LOCATION      4025
#define IDS_E_ICE_ALTER_SVR_LOCATION    4026
#define IDS_E_ICE_ADD_SVR_VARIABLE      4027
#define IDS_E_ICE_ALTER_SVR_VARIABLE    4028
#define IDS_DOMPROP_ICE_FACET           4029
#define IDS_DOMPROP_ICE_FACET_TITLE     4030
#define IDS_DOMPROP_ICE_PAGE            4031
#define IDS_DOMPROP_ICE_PAGE_TITLE      4032
#define IDS_ICE_STATIC_DBCONNECTION_INFO 4033
#define IDS_ICE_STATIC_ROLE             4034
#define IDS_ICE_STATIC_USER             4035
#define IDS_ICE_ALTER_BUNIT_FACET_ROLE_TITLE 4036
#define IDS_E_ICE_ALTER_ROLE_FAILED     4037
#define IDS_ICE_BUNIT_FACET_ROLE_TITLE  4038
#define IDS_E_ICE_ADD_ROLE_FAILED       4039
#define IDS_ICE_BUNIT_FACET_USER_TITLE  4040
#define IDS_E_ICE_ALTER_USER_FAILED     4041
#define IDS_E_ICE_ADD_USER_FAILED       4042
#define IDS_ICE_ALTER_BUNIT_PAGE_ROLE_TITLE 4043
#define IDS_ICE_BUNIT_PAGE_ROLE_TITLE   4044
#define IDS_ICE_ALTER_BUNIT_PAGE_USER_TITLE 4045
#define IDS_ICE_BUNIT_PAGE_USER_TITLE   4046
#define IDS_DOMPROP_ICE_BUNIT_FACETROLE_TITLE 4047
#define IDS_DOMPROP_ICE_BUNIT_FACETROLE 4048
#define IDS_DOMPROP_ICE_BUNIT_FACETUSER_TITLE 4049
#define IDS_DOMPROP_ICE_BUNIT_FACETUSER 4050
#define IDS_DOMPROP_ICE_BUNIT_PAGEROLE_TITLE 4051
#define IDS_DOMPROP_ICE_BUNIT_PAGEROLE  4052
#define IDS_DOMPROP_ICE_BUNIT_PAGEUSER_TITLE 4053
#define IDS_DOMPROP_ICE_BUNIT_PAGEUSER  4054
#define IDS_DOMPROP_ST_ICE_BUNIT_TITLE  4055
#define IDS_DOMPROP_ICE_BUNITS          4056
#define IDS_DOMPROP_ICE_SEC_DBUSER_TITLE 4057
#define IDS_DOMPROP_ICE_SEC_DBUSER      4058
#define IDS_DOMPROP_ICE_SEC_ROLE_TITLE  4059
#define IDS_DOMPROP_ICE_SEC_ROLE        4060
#define IDS_DOMPROP_ICE_FACETS          4061
#define IDS_DOMPROP_ST_ICE_FACETS_TITLE 4062
#define IDS_DOMPROP_ICE_PAGES           4063
#define IDS_DOMPROP_ST_ICE_PAGES_TITLE  4064
#define IDS_DOMPROP_ICE_LOCATIONS       4065
#define IDS_DOMPROP_ST_ICE_LOCATIONS_TITLE 4066
#define IDS_DOMPROP_ICE_BUNIT_ROLES     4067
#define IDS_DOMPROP_ST_ICE_BUNIT_ROLES_TITLE 4068
#define IDS_DOMPROP_ICE_BUNIT_USERS     4069
#define IDS_DOMPROP_ST_ICE_BUNIT_USERS_TITLE 4070
#define IDS_DOMPROP_ICE_FACET_ROLES     4071
#define IDS_DOMPROP_ICE_FACET_USERS     4072
#define IDS_DOMPROP_ICE_PAGE_ROLES      4073
#define IDS_DOMPROP_ICE_PAGE_USERS      4074
#define IDS_DOMPROP_ST_ICE_FACET_ROLES_TITLE 4075
#define IDS_DOMPROP_ST_ICE_FACET_USERS_TITLE 4076
#define IDS_DOMPROP_ST_ICE_PAGE_ROLES_TITLE 4077
#define IDS_DOMPROP_ST_ICE_PAGE_USERS_TITLE 4078
#define IDS_DOMPROP_ICE_TABHTML_DISPLAY 4079
#define IDS_TABLE_CHANGEJOURNALING_CAPTION 4084
#define IDS_E_PAGE_INFORMATION          4086
#define IDS_E_GET_SESSION               4087
#define IDS_E_CHANGE_EXPIRATION_DATE    4088
#define IDS_E_BAD_DATE_FORMAT           4089
#define IDS_T_EXPIRE_DATE               4090
#define IDS_FORMAT_DISPLAY              4091
#define IDS_E_DIRECT_ACCESS             4092
#define IDS_DATA_UNAVAILABLE            4093
#define IDS_E_NO_EXTEND_LOC             4094
#define IDS_E_NO_SVR_APP                4095
#define IDS_E_NO_ALARM                  4096
#define IDS_E_NO_DB_EVENT               4097
#define IDS_E_NO_GRANTEE                4098
#define IDS_E_NO_PROCEDURE              4099
#define IDS_E_NO_SCHEMA                 4100
#define IDS_E_NO_SYNONYM                4101
#define IDS_E_NO_TABLE                  4102
#define IDS_E_NO_VIEW                   4103
#define IDS_E_NO_INDEX                  4104
#define IDS_E_NO_USERS                  4105
#define IDS_E_NO_GRANTED_DB             4106
#define IDS_E_NO_GRANT_EVENT            4107
#define IDS_E_NO_GRANTED_PROC           4108
#define IDS_E_NO_GRANTEDTBL             4109
#define IDS_E_GRANTED_VIEW              4110
#define IDS_E_NO_TRIGGER                4111
#define IDS_E_NO_CDDS                   4112
#define IDS_E_NO_CONNECTION             4113
#define IDS_E_NO_MAIL_ALERT_USER        4114
#define IDS_NO_REGISTERED_TABLE         4115
#define IDS_E_NO_DATABASE               4116
#define IDS_E_NO_GWDB                   4117
#define IDS_E_NO_GROUP                  4118
#define IDS_NO_BUSINESS_UNIT            4119
#define IDS_E_NO_PROFILE_CONNECTION     4120
#define IDS_E_NO_ROLE                   4121
#define IDS_E_NO_DBCONN                 4122
#define IDS_E_NO_DB_USER                4123
#define IDS_E_NO_PROFILE                4124
#define IDS_E_NO_WEBUSER                4125
#define IDS_E_NO_SERVER_LOCATION        4126
#define IDS_E_NO_SERVER_VARIABLE        4127
#define IDS_E_NO_WEBUSER_CONNECTION     4128
#define IDS_E_NO_WEBUSER_ROLE           4129
#define IDS_E_NO_LOCATION               4130
#define IDS_E_NO_INTEGRITY              4131
#define IDS_E_NO_RULE                   4132
#define IDS_NOT_AVAILABLE               4133
#define IDS_MAX_NB_CONNECT              4134
#define IDS_E_RUN_INFODB                4135
#define IDS_E_BUILD_SVR                 4136
#define IDS_E_ALTER_DB                  4137
#define IDS_E_CREATE_SQL                4141
#define IDS_E_PERF_MONITOR              4142
#define IDS_E_DBEVENT_TRACE             4143
#define IDS_E_CHANGE_ACCESS             4146
#define IDS_E_EXEC_PROC                 4147
#define IDS_E_ACCESS_INDEX_INFO         4148
#define IDS_E_CHANGE_JOURNALING         4149
#define IDS_E_DUPLICATEDB_FILL_COMBO_LOCATION 4150
#define IDS_I_PASSWORD_REQUIRED         4155
#define IDS_E_NO_GRANT                  4161
#define IDS_E_REGISTER_AS_LINK          4168
#define IDS_E_TAB_NOT_FOUND             4169
#define IDS_E_LOAD_DLG                  4170
#define IDS_E_CONSTRUCT_PROPERTY        4171
#define IDS_E_INITIALIZE_OBJECT         4172
#define IDS_E_SETTING_DEFAULT           4173
#define IDS_E_ALTERDB_AT_LEAST_ONE_WORK 4174
#define IDS_E_II_SYSYTEM_SET            4175
#define IDS_E_DB_LOCKED                 4176
#define IDS_E_DB_EVENT_DELETED          4177
#define IDS_E_DB_DROPPED                4178
#define IDS_E_DB_EVENT_REGISTER         4179
#define IDS_E_REGISTERING_DB_EVENT      4180
#define IDS_E_UNREGISTERING_DB_EVENT    4181
#define IDS_E_UNCHECK                   4182
#define IDS_I_UNCHECK                   4183
#define IDS_DBEVENT_CHECK               4184
#define IDS_E_INITIALIZE_DB_EVENT       4185
#define IDS_E_DB_EVENT_RAISED           4186
#define IDS_E_DB_EVENT_TRACE            4187
#define IDS_E_DB_EVENT_LIST_FULL        4188
#define IDS_I_DB_EVENT_RAISED           4189
#define IDS_E_NEW_VALUE                 4190
#define IDS_E_DISPLAY_DATA              4192
#define IDS_E_LOCATION_SPACE            4193
#define IDS_E_DISK_SPACE                4194
#define IDS_E_STAT_TABLE                4195
#define IDS_E_ALLOCATE_DATA             4196
#define IDS_E_QUERY_RESULT              4198
#define IDS_E_LOAD_RESOURCE             4199
#define IDS_E_SAVE_COMPONENT            4203
#define IDS_E_LOAD_COMPONENT            4204
#define IDS_E_VIRTUAL_NODE              4205
#define IDS_E_CLOSE_ALL_MONITOR         4206
#define IDS_E_CURRENT_DEF               4207
#define IDS_E_MONITOR_WINDOWS           4208
#define IDS_E_NODE_REFERENCED           4209
#define IDS_E_CHANGE_COMBO              4210
#define IDS_E_CHANGE_EDIT               4211
#define IDS_E_CHANGE_CHECK_BOX          4212
#define IDS_E_LAUNCH_FASTLOAD           4214
#define IDS_E_STRUCTURE                 4219
#define IDS_E_STARTING_CONFIGURATION    4220
#define IDS_E_INIT_ENV                  4221
#define IDS_E_SERIALIZATION_ONE         4222
#define IDS_E_SERIALIZATION_TWO         4223
#define IDS_E_SERIALIZATION_THREE       4224
#define IDS_E_SERIALIZATION_FOUR        4225
#define IDS_E_SERIALIZATION_FIVE        4226
#define IDS_E_SERIALIZATION_SIX         4227
#define IDS_E_SERIALIZATION_SEVEN       4228
#define IDS_E_USERS_LIST                4229
#define IDS_E_TITLE_NODE                4230
#define IDS_E_SAVE_CHANGE               4231
#define IDS_E_INIT_APP                  4232
#define IDS_E_COMMAND_SYNTAX            4233
#define IDS_E_CREATE_DOC                4234
#define IDS_E_RESTART_PROG              4235
#define IDS_E_SHUTDOWN_SVR              4236
#define IDS_E_REMOVE_SESS               4237
#define IDS_E_CURRENT_SESSION           4238
#define IDS_E_PROCEDURE_IMA             4239
#define IDS_F_USER_CONNECT              4246
#define IDS_F_USER_CONNECT_STAT         4247
#define IDS_E_CREATE_MUTEX              4248
#define IDS_F_DETAIL_INFO               4249
#define IDS_F_USER_GENERATE_STAT        4250
#define IDS_F_USER_REMOVE_STAT          4251
#define IDS_E_CREATE_CHART              4252
#define IDS_E_COMMAND                   4261
#define IDS_E_ACTIVATE_SESSION          4264
#define IDS_E_CONNECT_SERVICE           4276
#define IDS_E_SERVICE_STATUS            4277
#define IDS_E_GET_SERVICE_NAME          4278
#define IDS_E_CHANGE_SERVICE_CONF       4279
#define IDS_F_DBA_OWNER                 4288
#define IDS_F_RESTORE_DEFAULT           4294
#define IDS_PRODNAME_CAPTION            4297
#define IDS_E_ICE_BUSINESS_UNIT_ALTER_FACET_FAILED 4298
#define IDS_E_ICE_BUSINESS_UNIT_ALTER_PAGE_FAILED 4299
#define IDS_PRODNAME_CAPTION_EDBC       4300
#define IDS_E_SQL_ASSISTANT             4302
#define IDS_E_NODE                      4303
#define IDS_A_COLUMNS_VALUE             4308
#define IDS_E_MUTEX                     4312
#define IDS_E_UNKNOWN                   4313
#define IDS_E_IMAGE_INDEX               4314
#define IDS_E_INSTALL_PASSWORD          4315
#define IDS_E_TEST_NODE_OK              4316
#define IDS_E_TEST_NODE_FAILED          4317
#define IDS_E_TWO_LOGINS                4318
#define IDS_E_PRIVATE_LOG               4319
#define IDS_E_GLOBAL_LOG                4320
#define IDS_I_REMOVE_INSTALL_PASSWORD   4321
#define IDS_I_ALTER_INSTALL_PASSWORD    4322
#define IDS_E_STRUCTURE_COMPLETED       4323
#define IDS_E_SUB_BRANCHES              4324
#define IDS_E_ALTER_NODE_ATTRIBUTE      4325
#define IDS_E_ADD_NODE_ATTRIBUTE        4326
#define IDS_E_ALTER_INSTALL_PASSWD      4327
#define IDS_E_DEFINE_INSTALL_PASSWD     4328
#define IDS_E_RETYPE_PASSWORD           4329
#define IDS_E_AUDIT_LEVEL               4330
#define IDS_E_NULLABLE_COL              4332
#define IDS_E_BEFORE_TIME               4333
#define IDS_E_SPEC_NAME_INDEX           4334
#define IDS_F_CHANGE_INDEX_NAME         4335
#define IDS_F_SPEC_COL_INDEX            4336
#define IDS_F_ONE_COL_INDEX             4337
#define IDS_I_FETCHING_INF              4423
#define IDS_I_GET_LIST_NODES            4424
#define IDS_I_BACKGROUND_REFRESH        4425
#define IDS_I_LST_SVR                   4426
#define IDS_I_EXPAND_BRANCH             4427
#define IDS_I_EXPAND_ALL_BRANCH         4428
#define IDS_I_DUPLI_OBJ                 4429
#define IDS_I_REFRESH_CURR_BRANCH       4430
#define IDS_I_REFRESH_ALL_BRANCH        4431
#define IDS_I_REFRESH_TYPE              4432
#define IDS_I_FETCHING_ROW              4433
#define IDS_TC_NAME                     4437
#define IDS_TC_OWNER                    4438
#define IDS_TC_AREA                     4439
#define IDS_TC_BY                       4441
#define IDS_TC_KEY                      4449
#define IDS_TC_TYPE                     4453
#define IDS_TC_TEXT                     4454
#define IDS_TC_INDEX                    4455
#define IDS_TC_DB_NO                    4456
#define IDS_TC_VNODE                    4457
#define IDS_TC_SVR_NO                   4458
#define IDS_TC_ORIGINATOR               4459
#define IDS_TC_LOCAL                    4460
#define IDS_TC_TARGET                   4461
#define IDS_TC_SCHEMA                   4462
#define IDS_TC_SUPP_OBJECTS             4463
#define IDS_TC_TBL_ACTIVATED            4464
#define IDS_TC_LOOKUP_TBL               4465
#define IDS_TC_PRIORITY_LOOKUP_TBL      4466
#define IDS_TC_KEY_SEQ                  4467
#define IDS_TC_REGISTERED_REPLIC        4468
#define IDS_TC_CONNECT_SUCCESS          4469
#define IDS_TC_CONNECT_FAILURE          4470
#define IDS_TC_DISCONNECT_SUCCESS       4471
#define IDS_TC_DISCONNECT_FAILURE       4472
#define IDS_TC_LOC_NAME                 4473
#define IDS_TC_COL_NAME                 4474
#define IDS_TC_LBD_COL_NAME             4475
#define IDS_TC_PARENT_DB                4476
#define IDS_TC_PRIM_KEY                 4477
#define IDS_TC_PARENT_TBL               4478
#define IDS_TC_COLUMNS                  4479
#define IDS_TC_DEFAULT_SPEC             4480
#define IDS_TC_EXE_DOC                  4481
#define IDS_TC_CREAT_DOC                4482
#define IDS_TC_READ_DOC                 4483
#define IDS_TC_DELETE_MODE              4484
#define IDS_TC_DESCENDING               4485
#define IDS_TC_FUNCTION                 4486
#define IDS_TC_CDDS_NUM                 4487
#define IDS_TC_USR_MAIL_ADDR            4488
#define IDS_TC_VALUE                    4490
#define IDS_TC_LOCAL_NAME               4492
#define IDS_TC_DISTRIB_NAME             4493
#define IDS_A_PLEASE_CHOOSE_GRANTEE     4503
#define IDS_A_PLEASE_CHOOSE_DB          4504
#define IDS_F_LIMIT_PRIVILEGE           4505
#define IDS_A_SPECIFY_PRIVILEGE         4506
#define IDS_F_GRANT_INSTALL             4507
#define IDS_T_INSTALL_PWD               4508
#define IDS_ALL_OWNERS                  4509
#define IDS_NO_CONSTRAINT               4510
#define IDS_INTERRUPTED                 4511
#define IDS_RESTARTED                   4512
#define IDS_ALL_DB                      4513
#define IDS_ALL_USER                    4514
#define IDS_ALL_REAL_USER               4515
#define IDS_ALL_OBJ_NAME                4516
#define IDS_ALL_AUDIT_EVENT             4517
#define IDS_ALL_OBJECT_TYPE             4518
#define IDS_BEGIN_FIRST                 4519
#define IDS_END_LAST                    4520
#define IDS_FOREIGN_KEY                 4521
#define IDS_DEFAULT_GROUP               4522
#define IDS_E_FIRST_TUPLES              4523
#define IDS_DEF_PROFILE                 4524
#define IDS_VIEW_COMPONENTS             4525
#define IDS_NO_ROLE                     4526
#define IDS_NO_USER                     4527
#define IDS_ERROR                       4528
#define IDS_F_FIRST_TUPLES              4531
#define IDS_SYSTEM_GENERATED            4532
#define IDS_USE_DEFAULT                 4533
#define IDS_NO_INDEX                    4534
#define IDS_BASE_TABLE                  4535
#define IDS_EXISTING_INDEX              4536
#define IDS_USER_DEFINED                4537
#define IDS_F_ROWS                      4539
#define IDS_INCONTEXT_DOMTITLE          4541
#define IDS_INCONTEXT_SQL_TITLE         4542
#define IDS_INCONTEXT_MONITORTITLE      4543
#define IDS_INCONTEXT_DBEVENT_TITLE     4544
#define IDS_I_HASH_TABLE_PAGE           4545
#define IDS_I_PAGE_COUNT                4546
#define IDS_I_NOT_OVERFLOW              4547
#define IDS_I_OVERFLOW                  4548
#define IDS_I_FREED                     4549
#define IDS_I_NEVER_USED                4550
#define IDS_F_TOTAL                     4551
#define IDS_I_FREE                      4552
#define IDS_I_DATA                      4553
#define IDS_I_ASSO_DATA                 4554
#define IDS_I_OVERFLOW_LEAF             4555
#define IDS_I_OVERFLOW_DATA             4556
#define IDS_I_ROOT                      4557
#define IDS_I_PAGE_INDEX                4558
#define IDS_I_UNUSED                    4559
#define IDS_I_DATA_WO                   4560
#define IDS_I_EMPTY_WO                  4561
#define IDS_I_DATA_WITH                 4562
#define IDS_I_EMPTY_WITH                4563
#define IDS_I_OVERFLOW_WITH_DTA         4564
#define IDS_I_EMPTY_OVERFLOW            4565
#define IDS_TC_STAT                     4566
#define IDS_TC_COLUMN                   4567
#define IDS_TC_DEF_SPEC                 4568
#define IDS_TC_COUNT                    4569
#define IDS_TC_GRAPH                    4570
#define IDS_TC_REP_FACTOR               4571
#define IDS_RESULT_ERROR                4572
#define IDS_TC_USER                     4576
#define IDS_TC_ENABLED                  4577
#define IDS_TC_AUDIT_FLAG               4578
#define IDS_TC_INIT_LOC                 4593
#define IDS_TC_NEW_LOC                  4594
#define IDS_TC_PRIVILEGE                4596
#define IDS_TC_GRANT                    4597
#define IDS_TC_GRANT_LIM                4598
#define IDS_TC_LIMIT                    4599
#define IDS_TC_NO_PRIV                  4600
#define IDS_TC_DESCRIPTION              4601
#define IDS_TC_NULLABLE                 4602
#define IDS_E_DESC                      4604
#define IDS_T_PRIMARY_KEY               4605
#define IDS_T_UNIQUE_KEY                4606
#define IDS_T_FOREIGN_KEY               4607
#define IDS_T_INDEX_ENFORCEMENT         4608
#define IDS_T_WARNING                   4609
#define IDS_I_KEY_COMPRESS              4615
#define IDS_DATA_COMPRESS               4616
#define IDS_TC_SESSION2                 4627
#define IDS_TF_DUPLICATE_DB             4630
#define IDS_F_ROWS_FETCHED              4631
#define IDS_TOTAL                       4632
#define IDS_COMPUTABLE_STATE            4633
#define IDS_CURRENT                     4634
#define IDS_MAX                         4635
#define IDS_TC_CONNECT                  4636
#define IDS_TC_RESOURCE                 4637
#define IDS_TC_DBA                      4638
#define IDS_TC_EXECUTE                  4639
#define IDS_ALTER_NODE_ATTRIBUTE        4640
#define IDD_REPLIC_ADD_DATABASE         4643
#define IDS_E_DB_COMBO_FILL             4644
#define IDS_E_SVR_COMBO_FILL            4645
#define IDD_XPROFILE                    4645
#define IDS_URP_PRIVILEGE               4646
#define IDD_XROLE                       4646
#define IDS_URP_USER                    4647
#define IDD_XUSER_ALTER                 4647
#define IDS_URP_DEFAULT                 4648
#define IDD_XROLE_ALTER                 4648
#define IDS_URP_ROLE                    4649
#define IDD_LOCATION                    4649
#define IDS_EXPIREDATE_TIMEZONEDIFFERENCE 4651
#define IDS_EXPIREDATE_BADDATEFORMAT    4652
#define IDS_ALL_IPMOBJECT               4653
#define IDS_ALL_DOMOBJECT               4654
#define IDS_E_ERROR_RMCMD               4658
#define IDS_E_NO_GRANTED_ROLE           4659
#define IDS_E_ICE_VERIF_CONNECTION_FAILED 4660
#define IDS_CANNOT_SAVE_BIG_FACETPAGE   4661
#define IDS_CANNOT_LOAD_BIG_FACET_OR_PAGE 4662
#define IDS_DOMPROP_REPL_TITLE2         4663
#define IDS_OBJ_PROPS                   4664
#define IDS_PROP_SESSION                4665
#define IDS_PROP_SERVER                 4666
#define IDS_PROP_REPLICSERVER           4667
#define IDS_TC_COLUMN_COMMENT           4668
#define IDS_E_COMMENTS_FAILED           4669
#define IDS_E_COMMENT_ON_FAILED         4670
#define IDS_SYSTEM_MAINTAINED           4671
#define IDS_NO_SYSTEM_MAINTAINED        4672
#define IDS_PLEASEWAIT                  4673
#define IDS_E_USERMOD                   4674
#define IDS_T_USERMOD                   4675
#define IDS_WITH_TABLES                 4676
#define IDS_WITH_MODIFY                 4677
#define IDS_WITH_DATA                   4678
#define IDS_WITH_INDEX                  4679
#define IDS_WITH_CONSTR                 4680
#define IDS_WITH_VIEWS                  4681
#define IDS_WITH_SYNONYMS               4682
#define IDS_WITH_EVENTS                 4683
#define IDS_WITH_REG                    4684
#define IDS_WITH_RULES                  4685
#define IDS_WITH_ALARMS                 4686
#define IDS_WITH_COMMENTS               4687
#define IDS_WITH_ROLES                  4688
#define IDS_WITH_PERMITS                4690
#define IDS_WITH_PROC                   4691
#define IDS_E_MAX_CHAR_COMMAND          4692
#define IDS_CHOOSEINDEX_NAME            4693
#define IDS_CHOOSEINDEX_OWNER           4694
#define IDS_CHOOSEINDEX_BASETABLE       4695
#define IDS_CHOOSEINDEX_TITLE           4696
#define IDS_MSG_REMOVE_COMPOSITEHIST    4697
#define IDS_E_ALTERLOCRAW               4698
#define IDS_E_UNCHECHECK                4699
#define IDS_MSG_II_SYSTEM_NOT_DEFINED   4700
#define IDS_MSG_FAILED_2_REGISTER_SERVER 4701
#define IDS_E_RETRIEVE_RMCMD_GRANT_FAILED 4702
#define IDS_E_ERROR_RMCMD_GRANT         4703
#define IDS_E_NO_SELECTED_PAGES         4705
#define IDS_E_NO_STORAGE_STRUCTURE      4706
#define IDS_UNKNOWN                     4708
#define IDS_LICENSE_TO                  4709
#define IDS_SITEID                      4710
#define IDS_COPYRIGHT_NOTICE            4711
#define IDS_PRODUCT_VERSION             4712
#define IDS_MSG_FAIL_2_LOCATEDLL        4713
#define IDS_TC_DATE                     4714
#define IDS_TC_CKPSEQUENCE              4715
#define IDS_TC_FIRSTJNL                 4716
#define IDS_TC_LASTJNL                  4717
#define IDS_TC_VALID                    4718
#define IDS_TC_MODE                     4719
#define IDS_MSG_FAIL_2_QUERYINTERFACE_SQLASSISTANT 4720
#define IDS_MSG_FAIL_2_CREATE_SQLASSISTANT 4721
#define IDS_PLEASE_SELECT_DATABASE      4722
#define IDS_MSG_COMMIT_INVITATION       4723
#define IDS_FAILED_2_SAVESTORAGE        4724
#define IDS_E_PASSWORD_ERROR            4725
#define IDS_MSG_LOCAL_VNODE_NOT_DEFINED 4727
#define IDS_E_VNODE_NOT_DEFINE          4728
#define IDS_T_ALTER_SEQUENCE            4729
#define IDS_STATIC_START_WITH           4730
#define IDS_E_CREATE_SEQUENCE_FAILED    4731
#define IDS_E_ALTER_SEQUENCE_FAILED     4732
#define IDS_DOMPROP_SEQ_TITLE           4733
#define IDS_DOMPROP_SEQ_DETAIL          4734
#define IDS_TC_NEXT                     4735
#define IDS_E_NO_SEQUENCE               4736
#define IDS_DOMPROP_SEQ_GRANTEES_TITLE  4737
#define IDS_DOMPROP_SEQ_GRANTEES        4738
#define IDS_DOMPROP_ST_DB_SEQ_TITLE     4739
#define IDS_E_NO_GRANTED_SEQ            4740
#define IDS_DOMPROP_ROLE_XGRANTED_SEQ   4741
#define IDS_DOMPROP_GROUP_XGRANTED_SEQ  4742
#define IDS_DOMPROP_USER_XGRANTED_SEQ   4743
#define IDS_TC_NEXT_ON_SEQ              4744
#define IDS_WITH_SEQUENCES              4745
#define IDS_E_ICE_DATABASE_NOT_FOUND    4746
#define IDS_E_OWNER_CHANGING_CATALOG    4747
#define DELETE_OLD_PASSWD               4748
#define IDS_E_DEL_OLD_PWD               4749
#define IDS_E_UNKNOWN_PAGETYPE          4750
#define IDS_TAB_TITLE_ONE_V2            4751
#define IDS_TAB_TITLE_THREE             4752
#define IDC_STATIC_ACCESSDB             10001
#define IDC_REFRESH2_CURRENT            20063
#define IDC_REFRESH2_CURSUB             20064
#define IDC_REFRESH2_ALL                20065
#define IDC_REFRESH2_BYOBJECT           20066
#define IDC_REFRESH2_OBJECTLIST         20067
#define IDC_ADD_SERVER_NUMBER           20068
#define IDC_ADD_TARGET_TYPE             20069
#define IDC_AUDIT_ALLEVENTS             21010
#define IDC_AUDIT_QUERYTEXT             21019
#define ID_BUTTON_EXPIREDATE            32700
#define IDM_IPMBAR_CLOSESVR             32701
#define IDM_IPMBAR_OPENSVR              32702
#define ID_SETTINGS_SQLTEST             32705
#define ID_SETTINGS_REFRESH             32706
#define ID_SETTINGS_DOM                 32707
#define ID_SETTINGS_SESSIONS            32708
#define ID_SETTINGS_PRINTER             32709
#define ID_SETTINGS_NODES               32710
#define ID_SETTINGS_MONITOR             32711
#define ID_SETTINGS_CLOSE               32712
#define ID_SETTINGS_GENERALDISPLAY      32713
#define ID_DISPLAY_BIGICON              32714
#define ID_DISPLAY_SMALLICON            32715
#define ID_DISPLAY_REPORT               32716
#define ID_DISPLAY_LIST                 32717
#define ID_BUTTON_REPLIC_DEACTIVATE     32718
#define ID_BUTTON_JOURNALING            32719
#define ID_BUTTON_HISTORYERROR          32721
#define ID_BUTTON_COMMENTS              32722
#define ID_BUTTON_USERMOD               32724
#define ID_BUTTON_XML                   32725
#define ID_BUTTON_SETTING               32726
#define IDM_PREFERENCE_SAVE             32728
#define ID_BUTTON_EXPORT                32729
#define ID_BUTTON_ONLINESUPPORT         32733
#define ID_BUTTON_QEP                   32771
#define ID_BUTTON_ADDOBJECT             32772
#define ID_BUTTON_ALTEROBJECT           32773
#define ID_BUTTON_DROPOBJECT            32774
#define ID_BUTTON_CONNECT               32775
#define ID_BUTTON_DISCONNECT            32776
#define ID_BUTTON_PREFERENCES           32777
#define ID_BUTTON_FIND                  32778
#define ID_BUTTON_SQLACT                32779
#define ID_BUTTON_SPACECALC             32780
#define ID_BUTTON_TEAROUT               32784
#define ID_BUTTON_RESTARTFROMPOS        32785
#define ID_BUTTON_SELECTWINDOW          32787
#define ID_BUTTON_WINDOWCLOSEALL        32788
#define ID_BUTTON_HELPINDEX             32789
#define ID_BUTTON_HELPSEARCH            32790
#define ID_BUTTON_CONTEXTHELP           32791
#define ID_BUTTON_GRANT                 32794
#define ID_BUTTON_REVOKE                32795
#define ID_BUTTON_POPULATE              32796
#define ID_BUTTON_LOCATE                32797
#define ID_BUTTON_CLASSB_EXPANDONE      32798
#define ID_BUTTON_CLASSB_EXPANDBRANCH   32799
#define ID_BUTTON_CLASSB_EXPANDALL      32800
#define ID_BUTTON_CLASSB_COLLAPSEONE    32801
#define ID_BUTTON_CLASSB_COLLAPSEBRANCH 32802
#define ID_BUTTON_REFRESH               32804
#define ID_BUTTON_CHMODREFRESH          32805
#define ID_BUTTON_FILTER                32806
#define ID_BUTTON_SHOW_SYSTEM           32807
#define ID_BUTTON_PROPERTIES            32808
#define ID_BUTTON_CHECKPOINT            32810
#define ID_BUTTON_ROLLFORWARD           32811
#define ID_BUTTON_UNLOADDB              32812
#define ID_BUTTON_COPYDB                32813
#define ID_BUTTON_GENSTAT               32814
#define ID_BUTTON_DISPSTAT              32815
#define ID_BUTTON_ALTERDB               32816
#define ID_BUTTON_AUDIT                 32817
#define ID_BUTTON_MODIFYSTRUCT          32818
#define ID_BUTTON_SYSMOD                32819
#define ID_BUTTON_VERIFYDB              32820
#define ID_BUTTON_REPLIC_INSTALL        32821
#define ID_BUTTON_REPLIC_PROPAG         32822
#define ID_BUTTON_REPLIC_BUILDSRV       32823
#define ID_BUTTON_REPLIC_RECONCIL       32824
#define ID_BUTTON_REPLIC_DEREPLIC       32825
#define ID_BUTTON_REPLIC_MOBILE         32826
#define ID_BUTTON_QUERYCLEAR            32827
#define ID_BUTTON_QUERYOPEN             32828
#define ID_BUTTON_QUERYSAVEAS           32829
#define ID_BUTTON_SQLWIZARD             32830
#define ID_BUTTON_QUERYGO               32831
#define ID_BUTTON_QUERYSHOWRES          32832
#define ID_BUTTON_FILTER1               32833
#define ID_BUTTON_SYSOBJECT             32834
#define ID_BUTTON_REFRESH2              32835
#define ID_BUTTON_CLASSB_COLLAPSEALL    32836
#define ID_BUTTON_NEW                   32837
#define ID_BUTTON_OPEN                  32838
#define ID_BUTTON_SAVE                  32839
#define ID_BUTTON_SAVE_AS               32840
#define ID_BUTTON_PRINT                 32841
#define ID_BUTTON_EXIT                  32842
#define ID_BUTTON_DATABASE              32843
#define ID_BUTTON_FILTER2               32844
#define ID_BUTTON_LOAD                  32845
#define ID_BUTTON_FILTER3               32846
#define ID_BUTTON_UNLOAD                32847
#define ID_BUTTON_DOWNLOAD              32849
#define ID_BUTTON_RUNSCRIPTS            32850
#define ID_BUTTON_UPDSTAT               32851
#define ID_BUTTON_NEWWINDOW             32852
#define ID_BUTTON_ABOUT                 32853
#define ID_BUTTON_SQLERRORS             32854
#define ID_GLOBSTATUS_CONNSRV_CAPT      32855
#define ID_GLOBSTATUS_CONNSRV_VAL       32856
#define ID_GLOBSTATUS_CURRSRV_CAPT      32857
#define ID_GLOBSTATUS_CURRSRV_VAL       32858
#define ID_GLOBSTATUS_OBJECTS_CAPT      32859
#define ID_GLOBSTATUS_OBJECTS_VAL       32860
#define ID_BUTTON_IPM1                  32861
#define ID_BUTTON_MONITOR               32862
#define ID_GLOBSTATUS_TIME              32863
#define IDM_DBEVENT_TRACE_REFRESH       32864
#define IDM_DBEVENT_TRACE_DATABASE      32865
#define IDM_DBEVENT_RAISE_POPUP         32866
#define ID_EDIT_CLEARLIST               32866
#define IDM_DBEVENT_RAISE_MAXLINE       32867
#define ID_EDIT_POPUPONRAISE            32867
#define IDM_DBEVENT_RAISE_RESET         32868
#define ID_VIEW_DBEVENTLISTFORCEREFRESH 32868
#define IDM_DBEVENT_TRACE_POPUP         32869
#define IDM_DBEVENT_TRACE_MAXLINE       32870
#define IDM_DBEVENT_TRACE_RESET         32871
#define IDM_DBEVENT_TRACE_MAXLINETEXT   32872
#define IDM_IPMBAR_ALLRESOURCES         32873
#define IDM_IPMBAR_NULLRESOURCE         32874
#define IDM_IPMBAR_INTERNALSESSION      32875
#define IDM_IPMBAR_SYSLOCKLISTS         32876
#define IDM_IPMBAR_INACTIVETRANS        32877
#define IDM_IPMBAR_REFRESH              32878
#define IDM_IPMBAR_SHUTDOWN             32879
#define IDM_DBEVENT_TRACE_SYSDBEVENT    32880
#define IDM_DBEVENT_TRACE_CLEARFIRST    32881
#define ID_SERVERS_VIEWNODESWINDOW      32882
#define ID_SERVERS_HIDENODESWINDOW      32883
#define IDM_TOOLBARS                    32884
#define IDM_VNODEBARSC                  32886
#define ID_BUTTON_VCBF                  32888
#define ID_BUTTON_REGISTERASLINK        32889
#define ID_BUTTON_REFRESHLINK           32890
#define IDM_IPMBAR_REPLICSVR_CHANGERUNNODE 32891
#define IDS_DOMPROP_PROF                32891
#define ID_BUTTON_RAW                   32892
#define ID_BUTTON_REPLIC_ARCCLEAN       32893
#define ID_BUTTON_REPLIC_REPMOD         32894
#define IDM_IPMBAR_EXPRESS_REFRESH      32895
#define IDM_IPMBAR_REFRESH_FREQUENCY    32896
#define IDM_IPMBAR_EXPRESS_REFRESH_ONLYIF 32897
#define IDS_MSG_EDBC_ROOT_NOT_DEFINED   32898
#define IDC_XUSER_PRIV                  32899
#define IDC_XUSER_SECURITY              32900
#define IDS_URP_TAB_PRIV                32901
#define IDS_URP_TAB_SEC                 32902
#define IDC_STATIC_INDEXNAME            65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        903
#define _APS_NEXT_COMMAND_VALUE         32730
#define _APS_NEXT_CONTROL_VALUE         1673
#define _APS_NEXT_SYMED_VALUE           3854
#endif
#endif
