//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by vnodemgr.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_NODE_POPUP                  102
#define IDR_MAINFRAME                   128
#define IDR_VNODEMTYPE                  129
#define IDB_NODETREE                    130
#define IDB_NODETREE_INITIAL            131
#define IDD_XVIRTUALNODE                169
#define IDD_XVNODEDATA                  535
#define IDD_XVNODELOGIN                 536
#define IDD_XVNODE_INSTALLATION_PASSWORD 697
#define IDD_XVNODE_ATTRIBUTE            698
#define IDD_VNODELOGINPROMPT            699
#define IDC_MFC_CHECK_LOGIN_SAVE        1000
#define IDC_MFC_CHECK1                  1005
#define IDC_MFC_COMBO1                  1007
#define IDC_MFC_EDIT1                   1024
#define IDC_MFC_EDIT2                   1025
#define IDC_MFC_EDIT3                   1026
#define IDC_MFC_EDIT4                   1050
#define IDC_MFC_EDIT5                   1051
#define IDC_MFC_EDIT6                   1052
#define IDC_MFC_CHECK_COM_PRIVATE       1230
#define IDC_MFC_CHECK_LOGIN_PRIVATE     1231
#define IDC_MFC_CHECK_INSTALLATION      1232
#define ID_NODE_ADD                     32771
#define ID_NODE_ALTER                   32772
#define ID_NODE_DROP                    32773
#define ID_NODE_REFRESH                 32774
#define ID_NODE_SQLTEST                 32775
#define ID_NODE_ADD_INSTALLATION        32776
#define ID_NODE_TEST                    32777
#define ID_NODE_DOM                     32778
#define ID_NODE_MONITOR                 32780
#define ID_SERVER_ADD                   32781
#define ID_SERVER_ALTER                 32782
#define ID_SERVER_DROP                  32783
#define ID_SERVER_TEST                  32784
#define ID_MANAGE_LOCALVNODE            32789
#define ID_POPUP_NODE_EDIT_VIEW         32791
#define ID_HELP_SUPPORTONLINE           32794
#define ID_NODE_EDIT_VIEW               32792
#define IDS_ALTER_NODEDATA_TITLE        61446
#define IDS_ALTER_NODELOGIN_TITLE       61447
#define IDS_ALTER_NODE_TITLE            61448
#define IDS_DROP_NODE_DATA_FAILED       61449
#define IDS_DROP_NODE_LOGIN_FAILED      61450
#define IDS_ADD_NODE_FAILED             61451
#define IDS_ADD_NODE_DATA_FAILED        61452
#define IDS_ADD_NODE_LOGIN_FAILED       61453
#define IDS_ALTER_NODE_FAILED           61454
#define IDS_ALTER_NODE_DATA_FAILED      61455
#define IDS_ALTER_NODE_LOGIN_FAILED     61456
#define IDS_E_PLEASE_RETYPE_PASSWORD    61457
#define IDS_E_VIRTUAL_NODE              61458
#define IDS_NODE_ALREADY_EXIST          61459
#define IDS_E_CURRENT_DEF               61460
#define IDS_DROP_NODE                   61461
#define IDS_DROP_NODE_FAILED            61462
#define IDS_DROP_NODE_DATA              61463
#define IDS_DROP_NODE_ATTRIBUTE         61464
#define IDS_DROP_NODE_ATTRIBUTE_FAILED  61465
#define IDS_DROP_INSTALLPASSWORD        61466
#define IDS_FOLDER_NODE                 61467
#define IDS_FOLDER_SERVER               61468
#define IDS_FOLDER_LOGIN                61469
#define IDS_FOLDER_CONNECTION           61470
#define IDS_FOLDER_ATTRIBUTE            61471
#define IDS_FOLDER_ADVANCEDNODE         61472
#define IDS_UNAVAILABLE                 61473
#define IDS_NONODES                     61474
#define IDS_NODE_INSTALLATION           61475
#define IDS_NODE_NOTFOUND               61476
#define IDS_NODE_HASADVANCED            61477
#define IDS_NODE_INSTALLATION_EXIST     61478
#define IDS_ONLY_2LOGINS_PERNODE        61479
#define IDS_ALREADY_HAS_PRIVATE         61480
#define IDS_ALREADY_HAS_GLOBAL          61481
#define IDS_SYSTEM_VARIABLE_NOTDEFINED  61482
#define IDS_APP_TITLE                   61483
#define IDS_FOLDER_GATEWAY              61484
#define IDS_FOLDER_ADVANCEDSERVER       61485
#define IDS_SERVER_HASADVANCED          61486
#define IDS_NOSERVERS                   61487
#define IDS_DROP_SERVER                 61488
#define IDS_DROP_SERVER_FAILED          61489
#define IDS_DROP_SERVER_DATA            61490
#define IDS_DROP_SERVER_DATA_FAILED     61491
#define IDS_DROP_SERVER_ATTRIBUTE       61492
#define IDS_DROP_SERVER_LOGIN_FAILED    61493
#define IDS_ADD_SERVER_FAILED           61494
#define IDS_ADD_SERVER_DATA_FAILED      61495
#define IDS_ADD_SERVER_LOGIN_FAILED     61496
#define IDS_ALTER_SERVERDATA_TITLE      61497
#define IDS_ALTER_SERVERLOGIN_TITLE     61498
#define IDS_ALTER_SERVER_TITLE          61499
#define IDS_ALTER_SERVER_FAILED         61500
#define IDS_ALTER_SERVER_DATA_FAILED    61501
#define IDS_ALTER_SERVER_LOGIN_FAILED   61502
#define IDS_SERVER_ALREADY_EXIST        61503
#define IDS_SERVER_NOTFOUND             61504
#define IDS_PRODUCT_VERSION             61505
#define IDS_PRODUCT_VERSION_EDBC        61506
#define IDS_MSG_FAIL_2_LOCATEDLL        61507
#define IDS_REQUEST2START_INSTALLATION  61508
#define IDS_MSG_INSTALLATION_START_FAILED 61509
#define IDS_MSG_II_SYSTEM_NOT_DEFINED   61510
#define IDS_MSG_EDBCROOT_NOT_DEFINED    61511
#define IDS_INGRES                      61512
#define IDS_EDBC                        61513
#define IDS_INVALID_CMDLINE             61514
#define IDS_VNODELOCALTITLE             61515
#define IDS_FOLDER_NET_NODE             61516

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
