//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by sqlquery.rc
//
#define IDS_SQLQUERY                    1
#define IDB_SQLQUERY                    1
#define IDS_SQLQUERY_PPG                2
#define IDS_PRODUCT_VERSION             3
#define IDS_EDBQUERY                    4
#define IDS_EDBQUERY_PPG                5
#define IDR_RICHTEXT_POPUP              103
#define IDR_QEP_TABLE                   104
#define IDR_QEP_PROJ_REST               105
#define IDD_SQLQUERY_STATEMENT          130
#define IDD_SQLQUERY_RESULT             131
#define IDD_QEPBOX                      132
#define IDD_SQLQUERY_PAGEQEP            133
#define IDD_SQLQUERY_PAGERESULT         134
#define IDD_PROPPAGE_SQL                135
#define IDD_SQLQUERY_PAGEGENERIC        137
#define IDD_QEPBOX_STAR                 138
#define IDD_QEPBOX_LEAF                 139
#define IDD_QEPBOX_STAR_LEAF            140
#define IDD_SQLQUERY_PAGEQEP_INDIVIDUAL 141
#define IDD_SQLQUERY_PAGERAW            142
#define IDD_QEPBOX_PREVIEW              143
#define IDD_QEPBOX_STAR_PREVIEW         144
#define IDD_XSQLACT_SETTING             145
#define IDD_QEPBOX_OVERLAPPED           146
#define IDD_QEPBOX_LEAF_OVERLAPPED      147
#define IDD_QEPBOX_STAR_OVERLAPPED      148
#define IDD_QEPBOX_STAR_LEAF_OVERLAPPED 149
#define IDD_SQLQUERY_PAGEXML            150
#define IDD_PROPPAGE_TABLAYOUT          151
#define IDD_PROPPAGE_DISPLAY            152
#define IDS_SQLQUERY_PPG_CAPTION        200
#define IDC_CHECK_SHOWGRID              201
#define IDS_SQLQUERY_PPGTABLAYOUT_CAPTION 201
#define IDC_CHECK_AUTOCOMMIT            202
#define IDS_SQLQUERY_PPGDISPLAY_CAPTION 202
#define IDC_CHECK_READLOCK              203
#define IDC_CHECK_SHOWDONSELECT         204
#define IDC_CHECK_ACTIVATETRACE         205
#define IDC_CHECK_TRACETOP              206
#define IDC_EDIT_F4WIDTH                206
#define IDC_EDIT_F4SCALE                207
#define IDC_CHECK_F4EXPONENTIAL         208
#define IDC_EDIT_F8WIDTH                209
#define IDC_EDIT_TIMEOUT                209
#define IDC_EDIT_F8SCALE                210
#define IDC_EDIT_MAXTUPLE               210
#define IDC_CHECK_F8EXPONENTIAL         211
#define IDC_EDIT_MAXTAB                 211
#define IDC_EDIT_MAXTRACESIZE           212
#define IDB_QEP_C                       556
#define IDB_QEP_D                       557
#define IDB_QEP_DB                      558
#define IDB_QEP_PAGE                    559
#define IDB_QEP_TUPLE                   560
#define IDB_QEP_N                       563
#define IDB_SQLACT_TABS                 574
#define IDB_SQLQUERY_DELETE             847
#define IDC_STATIC1                     1000
#define IDC_TAB1                        1001
#define IDC_LIST1                       1002
#define IDC_LIST2                       1003
#define IDC_SPIN1                       1004
#define IDC_CHECK1                      1005
#define IDC_STATIC2                     1006
#define IDC_CHECK2                      1007
#define IDC_SPIN4                       1007
#define IDC_CHECK3                      1008
#define IDC_EXPLORER1                   1010
#define IDC_CHECK4                      1011
#define IDC_CHECK5                      1012
#define IDC_STATIC4                     1013
#define IDC_CHECK6                      1014
#define IDC_STATIC3                     1015
#define IDC_CHECK7                      1016
#define IDC_BUTTON1                     1021
#define IDC_BUTTON2                     1022
#define IDC_EDIT1                       1024
#define IDC_EDIT2                       1025
#define IDC_EDIT3                       1026
#define IDC_STATIC_PAGE                 1059
#define IDC_STATIC_TUPLE                1061
#define IDC_STATIC_D                    1064
#define IDC_STATIC_C                    1065
#define IDC_STATIC_N                    1066
#define IDC_STATIC_HEADER               1068
#define IDC_BITMAP_PAGE                 1071
#define IDC_BITMAP_TUPLE                1072
#define IDC_BITMAP_C                    1073
#define IDC_BITMAP_D                    1074
#define IDC_BITMAP_N                    1075
#define IDC_BITMAP_DB                   1104
#define IDC_STATIC_DB                   1105
#define IDC_STATIC_NODE                 1106
#define IDC_COLOR                       1147
#define IDC_RADIO1                      1149
#define IDC_RADIO2                      1150
#define IDC_RADIO3                      1151
#define IDC_RADIO4                      1152
#define IDC_SPIN2                       1154
#define IDC_RADIO7                      1155
#define IDC_RADIO8                      1156
#define IDC_SPIN3                       1157
#define IDC_SPIN_SCALE1                 1163
#define IDC_SPIN_PREC2                  1164
#define IDC_SPIN_SCALE2                 1165
#define IDC_CHECK8                      1428
#define IDC_STATICFLOAT4                1576
#define IDC_EDIT_PREC4                  1579
#define IDC_EDIT_SCALE4                 1580
#define IDC_STATICFLOAT8                1581
#define IDC_EDIT_PREC8                  1584
#define IDC_EDIT_SCALE8                 1585
#define IDC_CHECK_EXPONENTIAL4          1586
#define IDC_CHECK_EXPONENTIAL8          1587
#define IDC_SPIN_PREC1                  1588
#define IDS_FILTER_SQL_FILES            2000
#define IDS_FILTER_ALL_FILES            2001
#define IDS_FILTER_SQL_FILES1           2002
#define IDS_FILTER_SQL_FILES2           2003
#define IDS_DATABASE_NONE               2004
#define IDS_ROWS_FETCHED                2005
#define IDS_TITLE_FETCHING_ROW          2006
#define IDS_PREVIEW                     2007
#define IDS_F_ROWS                      2008
#define IDS_TOTAL_FETCHED_ROW           2009
#define IDS_ALREADY_FETCHED_ROW         2010
#define IDS_NOT_AVAILABLE               2011
#define IDS_INIFILENAME                 2012
#define IDS_NON_SELECT_STATEMENT        2013
#define IDS_TRACE_OUTPUT                2014
#define IDS_QEP_NORMAL                  2015
#define IDS_QEP_PREVIEW                 2016
#define IDS_PREVIOUS_LINE_UNAVAILABLE   2017
#define IDS_MAX_TAB_REACHED             2018
#define IDS_NEXT_TUPLES_UNAVAILABLE     2019
#define IDS_MSG_SELECT_DATABASE         3000
#define IDS_MSG_REMOVE_COMMAND1         3001
#define IDS_MSG_REMOVE_COMMAND2         3002
#define IDS_MSG_UNKNOWN_FAIL_2_OPENQUERY 3003
#define IDS_MSG_FAIL_2_OPENQUERY        3004
#define IDS_MSG_UNKNOWN_FAIL_2_SAVEQUERY 3005
#define IDS_MSG_NONSELECT_IN_QEP        3006
#define IDS_MSG_NONSELECT_IN_XML        3007
#define IDS_MSG_FAIL_2_CREATE_PAGERAW   3008
#define IDS_MSG_MULTI_STATEMENT         3009
#define IDS_MSG_STATEMENT_COMMIT        3010
#define IDS_MSG_UNKNOWN_FAIL_2_EXECUTE_STATEMENT 3011
#define IDS_FAIL_2_FETCH_ROW            3012
#define IDS_MSG_INTERRUPT_FETCHING      3013
#define IDS_MSG_NO_FIRST_TUPLES         3014
#define IDS_MSG_FAIL_2_CREATEFONT       3015
#define IDS_MSG_PREC_SCALE              3016
#define IDS_MSG_FAIL_2_GETDATA_FOR_SAVE 3017
#define IDS_MSG_FAIL_2_CREATEBIN_TREE   3018
#define IDS_MSG_FAIL_2_INIT_DRAW_QEP_TREE 3019
#define IDS_MSG_FAIL_2_CREATE_SQL_RESULT 3020
#define IDS_MSG_FAIL_2_CREATE_QEP_RESULT 3021
#define IDS_MSG_SIZE_BUFFER_REACHED     3022
#define IDS_MSG_TRACE_TAB_SIZE_REACHED  3023
#define IDS_MSG_FAIL_2_CREATE_SQL_PANE  3024
#define IDS_MSG_FAIL_2_SAVE_SETTINGS    3025
#define IDS_MSG_FAIL_2_DRAW_QEP_TREE    3026
#define IDS_MSG_FAIL_2_QUERYINTERFACE_SQLASSISTANT 3027
#define IDS_MSG_FAIL_2_CREATE_SQLASSISTANT 3028
#define IDS_MSG_QEPUNAVAIABLE           3029
#define IDS_MSG_IICHAREST_ERROR         3030
#define IDS_MSG_REMOVE_OLD_TAB          3031
#define IDS_MSG_SYSTEM_ERROR            57345
#define IDS_MSG_FAIL_2_LOCATEDLL        57346

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         215
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
