/*
**Copyright (c) 2004 Ingres Corporation
*/

# include   <compat.h>
# include   <lo.h>
# include   <si.h>
# include   <st.h>
# include   <me.h>
# include   "dextern.h"

/*
** Name:	yaccdata.c
**
** Description:	Global data for yacc facility.
**
** History:
**
**	23-sep-96 (canor01)
**	    Created.
**	21-jan-1999 (hanch04)
**	    replace nat and longnat with i4
**	31-aug-2000 (hanch04)
**	    cross change to main
**	    replace nat and longnat with i4
**  26-Jun-2006 (raddo01)
**		bug 116276: SEGV on double free() when $ING_SRC/lib/ doesn't exist.
**	28-feb-08 (smeke01) b120003
**	    On Windows escape all backslashes in the input filename so that the 
**	    emit #line directives option works without warnings.
*/


/* y1.c */

GLOBALDEF i4            tbitset ZERO_FILL;      /* size of lookahead sets */
GLOBALDEF struct looksets lkst[LSETSIZE] ZERO_FILL;
GLOBALDEF i4            nlset = 0;      /* next lookahead set index */
/* flag to suppress lookahead computations */
GLOBALDEF i4            nolook = 0;
/* temp storage for lookahead computations */
GLOBALDEF struct looksets clset ZERO_FILL;
 
/* working set computations */
 
GLOBALDEF struct wset   wsets[WSETSIZE] ZERO_FILL;
GLOBALDEF struct wset   *cwp ZERO_FILL;
 
/* state information */
 
GLOBALDEF i4            nstate = 0;     /* number of states */
/* ptrs to descriptions of the states */
GLOBALDEF struct item   *pstate[NSTATES + 2] ZERO_FILL;
/* contains type info about states */
GLOBALDEF i4            tystate[NSTATES] ZERO_FILL;
/* index to the stored goto table */
GLOBALDEF i4            indgo[NSTATES] ZERO_FILL;
/* states generated by terminal gotos */
GLOBALDEF i4            tstates[NTERMS] ZERO_FILL;
/* states generated by nonterm gotos */
GLOBALDEF i4            ntstates[NNONTERM] ZERO_FILL;
/* chain of ovflows of term/nonterm generation lists */
GLOBALDEF i4            mstates[NSTATES] ZERO_FILL;    
 
/* storage for the actions in the parser */
 
GLOBALDEF i4            amem[ACTSIZE] ZERO_FILL;    /* action table storage */
/* next free action table position */
GLOBALDEF i4            *memp ZERO_FILL;
 
/* other storage areas */
 
/* temp storage, indexed by terms + ntokens or states */
GLOBALDEF i4            temp1[TEMPSIZE] ZERO_FILL;
GLOBALDEF i4            lineno= 1;              /* current input line number */
GLOBALDEF i4            fatfl = 1;              /* if on, error is fatal */    
GLOBALDEF i4            nerrors = 0;            /* number of errors */
 
/* storage for information about the nonterminals */
 
/* vector of pointers to productions yielding each nonterminal */
GLOBALDEF i4            **pres[NNONTERM + 2] ZERO_FILL;
/* vector of pointers to first sets for each nonterminal */
GLOBALDEF struct looksets *pfirst[NNONTERM + 2] ZERO_FILL; 
/* vector of nonterminals nontrivially deriving e */
GLOBALDEF i4            pempty[NNONTERM + 1] ZERO_FILL;

GLOBALDEF struct wset *zzcwp = wsets;
GLOBALDEF i4  zzgoent = 0;
GLOBALDEF i4  zzgobest = 0;
GLOBALDEF i4  zzacent = 0;
GLOBALDEF i4  zzexcp = 0;
GLOBALDEF i4  zzclose = 0;
GLOBALDEF i4  zzsrconf = 0;
GLOBALDEF i4  * zzmemsz = mem0;
GLOBALDEF i4  zzrrconf = 0;

GLOBALDEF int indebug = 0;

GLOBALDEF i4    pidebug = 0; /* debugging flag for putitem */

GLOBALDEF i4    gsdebug = 0;

GLOBALDEF i4    cldebug = 0;    /* debugging flag for closure */


/* y2.c */

 /* communication variables between various I/O routines */
  
GLOBALDEF   char   *infile ZERO_FILL;                   /* input file name */
/*
** There may be '\' characters in the input filepath, in which case 
** we would need to escape the '\' characters. infile2 provides the space  
** to do this. For simplicity just take double the space for a standard filepath.
*/
GLOBALDEF   char   infile2[MAX_LOC + MAX_LOC] ZERO_FILL;
GLOBALDEF   i4      numbval ZERO_FILL;          /* value of an input number */
GLOBALDEF   char    tokname[NAMESIZE] ZERO_FILL;        /* input token name */
 
 /* storage of names */
  
/* place where token and nonterminal names are stored */
GLOBALDEF   char    cnames[CNAMSZ] ZERO_FILL;
GLOBALDEF   i4      cnamsz = CNAMSZ;    /* size of cnames */
GLOBALDEF   char   *cnamp = cnames; /* place where next name is to be put in */
GLOBALDEF   i4      ndefout = 3;    /* number of defined symbols output */
 
 /* storage of types */
GLOBALDEF   i4      ntypes ZERO_FILL;           /* number of types defined */
GLOBALDEF   char   *typeset[NTYPES] ZERO_FILL;  /* pointers to type tags */  
 
 /* symbol tables for tokens and nonterminals */
  
GLOBALDEF   i4      ntokens = 0;
GLOBALDEF   struct toksymb  tokset[NTERMS] ZERO_FILL;
GLOBALDEF   i4      toklev[NTERMS] ZERO_FILL;
GLOBALDEF   i4      nnonter = -1;
GLOBALDEF   struct ntsymb   nontrst[NNONTERM] ZERO_FILL;
GLOBALDEF   i4      start ZERO_FILL;                    /* start symbol */
 
 /* assigned token type values */
GLOBALDEF   i4      extval = 0;  
 
 /* input and output file descriptors */
  
GLOBALDEF   FILE *finput = (FILE *)NULL;         /* yacc input file */
GLOBALDEF   FILE *faction = (FILE *)NULL;        /* file for saving actions */
GLOBALDEF   FILE *fdefine = (FILE *)NULL;        /* file for # defines */
GLOBALDEF   FILE *ftable = (FILE *)NULL;         /* ytab.c file */
GLOBALDEF   FILE *ftemp = (FILE *)NULL;          /* tempfile to pass 2 */
/* where the strings for debugging are stored */
GLOBALDEF   FILE *fdebug = (FILE *)NULL;
GLOBALDEF   FILE *foutput = (FILE *)NULL;        /* y.output file */  
 
 /* storage for grammar rules */
 
GLOBALDEF   i4      mem0[MEMSIZE] ZERO_FILL;            /* production storage */
GLOBALDEF   i4     *mem = mem0;
GLOBALDEF   i4      nprod = 1;          /* number of productions */
GLOBALDEF   i4      ftname[NPROD] ZERO_FILL;    /* function names for actions */
GLOBALDEF   i4      ftncnt = 0;         /* number of functions generated */
GLOBALDEF   i4      casecnt = 0;    /* number of case statements for actions */
/* pointers to descriptions of productions */
GLOBALDEF   i4     *prdptr[NPROD] ZERO_FILL;
/* precedence levels for the productions */
GLOBALDEF   i4      levprd[NPROD] ZERO_FILL;
/* set to 1 if the reduction has action code to do */
GLOBALDEF   char    had_act[NPROD] ZERO_FILL;
/* flag for generating the # line's default is yes */
GLOBALDEF   i4      gen_lines = 1;
/* flag for whether to include runtime debugging */
GLOBALDEF   i4      gen_testing = 0;
GLOBALDEF   i4      functions = FALSE;       
GLOBALDEF   i4      switchsize = DEFCASESIZE;
/* TRUE means make re-entrant parser */
GLOBALDEF   i4      reentrant ZERO_FILL;
/* Control block type for re-entrant parser */
GLOBALDEF   char    argtype[50] ZERO_FILL;
GLOBALDEF   LOCATION    actloc ZERO_FILL;
GLOBALDEF   char    actbuf[MAX_LOC] ZERO_FILL;
GLOBALDEF   LOCATION    temploc ZERO_FILL;
GLOBALDEF   char    tempbuf[MAX_LOC] ZERO_FILL;
GLOBALDEF   LOCATION    debugloc ZERO_FILL;
GLOBALDEF   char    dbgbuf[MAX_LOC] ZERO_FILL;
GLOBALDEF   char    prefix[50] = "yy";  /* Prefix for table names */
/* Name of print function to use for debugging */
GLOBALDEF   char    printfunc[50] = "SIprintf";
/* Name of structure in control block */
GLOBALDEF   char    structname[50] = "yacc";
 
/*
**  This table is for controlling where the various yacc output tables will
**  be written.  For each table, there is a command line option that allows
**  the table to be written into a separate file.  For example,
**              yacc -yypgo abc.c grammar.y
**  would put the table yypgo[] into the file abc.c.
**
**  NOTE: THIS TABLE IS ORDER DEPENDENT.  DO NOT CHANGE THE ORDER OF THE ROWS
**          HERE WITHOUT CHANGING THE CORRESPONDING CONSTANTS IN DEXTERN.H.    
*/
 
GLOBALDEF   struct outfiles Filespecs[NUMSPECS] =  
            {
                "yyexca",   "",     FALSE,  {0},   (FILE *) NULL,
                "yyact",    "",     FALSE,  {0},   (FILE *) NULL,
                "yypact",   "",     FALSE,  {0},   (FILE *) NULL,
                "yypgo",    "",     FALSE,  {0},   (FILE *) NULL,
                "yyr1",     "",     FALSE,  {0},   (FILE *) NULL,
                "yyr2",     "",     FALSE,  {0},   (FILE *) NULL,
                "yychk",    "",     FALSE,  {0},   (FILE *) NULL,
                "yydef",    "",     FALSE,  {0},   (FILE *) NULL,
                "yyfunc",   "",     FALSE,  {0},   (FILE *) NULL
            };

/*
**      This table contains the names of the various parameters to the
**      parser.  These parameters exist outside of the session control
**      block used to control a re-entrant parser.
*/
  
#define             MAXPARMS    10
 
GLOBALDEF   PARMTYPE Params[MAXPARMS] ZERO_FILL;
GLOBALDEF   i4      Numparams = 0;

#define RHS_TEXT_LEN            ( BUFSIZ * 4 )/* length of rhstext */

/* store current lhs (non-terminal) name */
GLOBALDEF char    lhstext[BUFSIZ] ZERO_FILL;
GLOBALDEF char    rhstext[RHS_TEXT_LEN] ZERO_FILL; /* store current rhs list */


/* y3.c */

/* the number of the last reduction of a state */
GLOBALDEF i4      lastred ZERO_FILL;
GLOBALDEF i4      defact[NSTATES] ZERO_FILL; /* the default actions of states */

GLOBALDEF i4      pkdebug = 0;

GLOBALDEF i4      g2debug = 0;


/* y4.c */

GLOBALDEF i4     *ggreed = (i4 *)&lkst[0].lset;
GLOBALDEF i4     *pgo = (i4 *)&wsets[0].ws.lset;
GLOBALDEF i4     *yypgo = &nontrst[0].tvalue;    
 
GLOBALDEF i4      maxspr = 0;           /* maximum spread of any entry */
GLOBALDEF i4      maxoff = 0;           /* maximum offset into a array */
GLOBALDEF i4     *pmem = mem0;
GLOBALDEF i4     *maxa ZERO_FILL;
# define NOMORE -1000
 
GLOBALDEF i4      nxdb = 0;
GLOBALDEF i4      adb = 0; 

