/********************************************************************
//
//  Copyright (C) 2005-2006 Ingres Corporation. All Rights Reserved.
//
//    Project : CA/OpenIngres Visual DBA
//
//    Source : sqltls.h
//    SQL functions defines and typedef 
//
********************************************************************/

#ifndef DBA_SQLTLS
#define DBA_SQLTLS
/////////////////////////////////////////////////////////////////////////////
// SQL functions defines and typedef 
//    Generated only for sql programs since it refers to IISQLDA_TYPE macro
//    part of the INCLUDE SQLDA generated by the Ingres precompiler (ESQLC)
/////////////////////////////////////////////////////////////////////////////
                                  //    TO BE FINISHED see bellow
#define  IISQ_LVCH_TYPE    22     // ---------> WARNING <--------- 
#define  IISQ_BYTE_TYPE    23     // the IISQ_*_TYPE defines are to be.. 
#define  IISQ_VBYTE_TYPE   24     // ... removed as soon as the ...  
#define  IISQ_LBYTE_TYPE   25     // ... EQSQLDA.H is  up to date 
#define  IISQ_OBJ_TYPE     45 
#define  IISQ_HDLR_TYPE    46 
   
typedef IISQLDA FAR *LPSQLDA;         

typedef struct _row {               /* row structure is made of ...     */
   void *lpcol[IISQ_MAX_COLS];      /* ... columns                      */
   short sNullInd[IISQ_MAX_COLS];   /* Null indicator of the variable   */
   struct _row *Prev;
   struct _row *Next;
} ROW, FAR *LPROW;

typedef struct _SQLRowSet {
   HSQL              hsql;       /* Handle of this sql statement */
   LPSQLDA           lpsqlda;    /* pointer to the sqlda */
   LPUCHAR           lpsqlstm;   /* pointer to the sql statement */
   LPROW             lpfirstrow; /* pointer to the first row */
   LPROW             lplastrow;  /* pointer to the last row */
   LPROW             lpcurrrow;  /* pointer to the current row */
} SQLROWSET, FAR * LPSQLROWSET;

typedef struct _FillHostPrm {
   int         ibufln;           /* buffer length */
   LPSQLROWSET lpsqlrowset;      /* ptr to the SQL rowset structure */
   LPUCHAR lpsqlhostbfr;         /* ptr to the host bfr returned by sqldyn */
} FILLHOSTPRM, FAR * LPFILLHOSTPRM;

BOOL FillHosts(void * lpHost);
#endif 
