/*
** Copyright (c) 1998 Ingres Corporation
*/

/*{
** Name: oipfctrs.h
**
** Description:
**  Offset definition file for extensible counter objects and counters
**
**  These "relative" offsets must start at 0 and be multiples of 2 (i.e.
**  even numbers). In the Open Procedure, they will be added to the 
**  "First Counter" and "First Help" values for the device they belong to, 
** 
**  this file is used by the extensible counter DLL code as well as the 
**  counter name and help text definition file (.INI) file that is used
**  by LODCTR to load the names into the registry.
**
** History:
** 	15-oct-1998 (wonst02)
** 	    Created.
** 	14-dec-1998 (wonst02)
** 	    Add definitions for cssampler objects.
** 	10-jan-1999 (wonst02)
** 	    Add definitions for cssampler event objects and lock object.
**	15-sep-1999 (somsa01)
**	    Slightly modified names.
*/

#define PFCTRS_2K_CACHE_OBJ                                   0
#define PFCTRS_2K_CACHE_FIX_COUNT                             2
#define PFCTRS_2K_CACHE_UNFIX_COUNT                           4
#define PFCTRS_2K_CACHE_READ_COUNT                            6
#define PFCTRS_2K_CACHE_WRITE_COUNT                           8
#define PFCTRS_2K_CACHE_GROUP_READ_COUNT                      10
#define PFCTRS_2K_CACHE_GROUP_WRITE_COUNT                     12
#define PFCTRS_2K_CACHE_DIRTY_UNFIX_COUNT                     14
#define PFCTRS_2K_CACHE_FORCE_COUNT                           16
#define PFCTRS_2K_CACHE_IO_WAIT_COUNT                         18
#define PFCTRS_2K_CACHE_HIT_COUNT                             20
#define PFCTRS_2K_CACHE_FREE_BUFFER_COUNT                     22
#define PFCTRS_2K_CACHE_FREE_BUFFER_WAITERS                   24
#define PFCTRS_2K_CACHE_FIXED_BUFFER_COUNT                    26
#define PFCTRS_2K_CACHE_MODIFIED_BUFFER_COUNT                 28
#define PFCTRS_2K_CACHE_FREE_GROUP_BUFFER_COUNT               30
#define PFCTRS_2K_CACHE_FIXED_GROUP_BUFFER_COUNT              32
#define PFCTRS_2K_CACHE_MODIFIED_GROUP_BUFFER_COUNT           34
#define PFCTRS_2K_CACHE_FLIMIT                                36
#define PFCTRS_2K_CACHE_MLIMIT                                38
#define PFCTRS_2K_CACHE_WBSTART                               40
#define PFCTRS_2K_CACHE_WBEND                                 42
#define PFCTRS_4K_CACHE_OBJ                                   44
#define PFCTRS_4K_CACHE_FIX_COUNT                             46
#define PFCTRS_4K_CACHE_UNFIX_COUNT                           48
#define PFCTRS_4K_CACHE_READ_COUNT                            50
#define PFCTRS_4K_CACHE_WRITE_COUNT                           52
#define PFCTRS_4K_CACHE_GROUP_READ_COUNT                      54
#define PFCTRS_4K_CACHE_GROUP_WRITE_COUNT                     56
#define PFCTRS_4K_CACHE_DIRTY_UNFIX_COUNT                     58
#define PFCTRS_4K_CACHE_FORCE_COUNT                           60
#define PFCTRS_4K_CACHE_IO_WAIT_COUNT                         62
#define PFCTRS_4K_CACHE_HIT_COUNT                             64
#define PFCTRS_4K_CACHE_FREE_BUFFER_COUNT                     66
#define PFCTRS_4K_CACHE_FREE_BUFFER_WAITERS                   68
#define PFCTRS_4K_CACHE_FIXED_BUFFER_COUNT                    70
#define PFCTRS_4K_CACHE_MODIFIED_BUFFER_COUNT                 72
#define PFCTRS_4K_CACHE_FREE_GROUP_BUFFER_COUNT               74
#define PFCTRS_4K_CACHE_FIXED_GROUP_BUFFER_COUNT              76
#define PFCTRS_4K_CACHE_MODIFIED_GROUP_BUFFER_COUNT           78
#define PFCTRS_4K_CACHE_FLIMIT                                80
#define PFCTRS_4K_CACHE_MLIMIT                                82
#define PFCTRS_4K_CACHE_WBSTART                               84
#define PFCTRS_4K_CACHE_WBEND                                 86
#define PFCTRS_8K_CACHE_OBJ                                   88
#define PFCTRS_8K_CACHE_FIX_COUNT                             90
#define PFCTRS_8K_CACHE_UNFIX_COUNT                           92
#define PFCTRS_8K_CACHE_READ_COUNT                            94
#define PFCTRS_8K_CACHE_WRITE_COUNT                           96
#define PFCTRS_8K_CACHE_GROUP_READ_COUNT                      98
#define PFCTRS_8K_CACHE_GROUP_WRITE_COUNT                     100
#define PFCTRS_8K_CACHE_DIRTY_UNFIX_COUNT                     102
#define PFCTRS_8K_CACHE_FORCE_COUNT                           104
#define PFCTRS_8K_CACHE_IO_WAIT_COUNT                         106
#define PFCTRS_8K_CACHE_HIT_COUNT                             108
#define PFCTRS_8K_CACHE_FREE_BUFFER_COUNT                     110
#define PFCTRS_8K_CACHE_FREE_BUFFER_WAITERS                   112
#define PFCTRS_8K_CACHE_FIXED_BUFFER_COUNT                    114
#define PFCTRS_8K_CACHE_MODIFIED_BUFFER_COUNT                 116
#define PFCTRS_8K_CACHE_FREE_GROUP_BUFFER_COUNT               118
#define PFCTRS_8K_CACHE_FIXED_GROUP_BUFFER_COUNT              120
#define PFCTRS_8K_CACHE_MODIFIED_GROUP_BUFFER_COUNT           122
#define PFCTRS_8K_CACHE_FLIMIT                                124
#define PFCTRS_8K_CACHE_MLIMIT                                126
#define PFCTRS_8K_CACHE_WBSTART                               128
#define PFCTRS_8K_CACHE_WBEND                                 130
#define PFCTRS_16K_CACHE_OBJ                                  132
#define PFCTRS_16K_CACHE_FIX_COUNT                            134
#define PFCTRS_16K_CACHE_UNFIX_COUNT                          136
#define PFCTRS_16K_CACHE_READ_COUNT                           138
#define PFCTRS_16K_CACHE_WRITE_COUNT                          140
#define PFCTRS_16K_CACHE_GROUP_READ_COUNT                     142
#define PFCTRS_16K_CACHE_GROUP_WRITE_COUNT                    144
#define PFCTRS_16K_CACHE_DIRTY_UNFIX_COUNT                    146
#define PFCTRS_16K_CACHE_FORCE_COUNT                          148
#define PFCTRS_16K_CACHE_IO_WAIT_COUNT                        150
#define PFCTRS_16K_CACHE_HIT_COUNT                            152
#define PFCTRS_16K_CACHE_FREE_BUFFER_COUNT                    154
#define PFCTRS_16K_CACHE_FREE_BUFFER_WAITERS                  156
#define PFCTRS_16K_CACHE_FIXED_BUFFER_COUNT                   158
#define PFCTRS_16K_CACHE_MODIFIED_BUFFER_COUNT                160
#define PFCTRS_16K_CACHE_FREE_GROUP_BUFFER_COUNT              162
#define PFCTRS_16K_CACHE_FIXED_GROUP_BUFFER_COUNT             164
#define PFCTRS_16K_CACHE_MODIFIED_GROUP_BUFFER_COUNT          166
#define PFCTRS_16K_CACHE_FLIMIT                               168
#define PFCTRS_16K_CACHE_MLIMIT                               170
#define PFCTRS_16K_CACHE_WBSTART                              172
#define PFCTRS_16K_CACHE_WBEND                                174
#define PFCTRS_32K_CACHE_OBJ                                  176
#define PFCTRS_32K_CACHE_FIX_COUNT                            178
#define PFCTRS_32K_CACHE_UNFIX_COUNT                          180
#define PFCTRS_32K_CACHE_READ_COUNT                           182
#define PFCTRS_32K_CACHE_WRITE_COUNT                          184
#define PFCTRS_32K_CACHE_GROUP_READ_COUNT                     186
#define PFCTRS_32K_CACHE_GROUP_WRITE_COUNT                    188
#define PFCTRS_32K_CACHE_DIRTY_UNFIX_COUNT                    190
#define PFCTRS_32K_CACHE_FORCE_COUNT                          192
#define PFCTRS_32K_CACHE_IO_WAIT_COUNT                        194
#define PFCTRS_32K_CACHE_HIT_COUNT                            196
#define PFCTRS_32K_CACHE_FREE_BUFFER_COUNT                    198
#define PFCTRS_32K_CACHE_FREE_BUFFER_WAITERS                  200
#define PFCTRS_32K_CACHE_FIXED_BUFFER_COUNT                   202
#define PFCTRS_32K_CACHE_MODIFIED_BUFFER_COUNT                204
#define PFCTRS_32K_CACHE_FREE_GROUP_BUFFER_COUNT              206
#define PFCTRS_32K_CACHE_FIXED_GROUP_BUFFER_COUNT             208
#define PFCTRS_32K_CACHE_MODIFIED_GROUP_BUFFER_COUNT          210
#define PFCTRS_32K_CACHE_FLIMIT                               212
#define PFCTRS_32K_CACHE_MLIMIT                               214
#define PFCTRS_32K_CACHE_WBSTART                              216
#define PFCTRS_32K_CACHE_WBEND                                218
#define PFCTRS_64K_CACHE_OBJ                                  220
#define PFCTRS_64K_CACHE_FIX_COUNT                            222
#define PFCTRS_64K_CACHE_UNFIX_COUNT                          224
#define PFCTRS_64K_CACHE_READ_COUNT                           226
#define PFCTRS_64K_CACHE_WRITE_COUNT                          228
#define PFCTRS_64K_CACHE_GROUP_READ_COUNT                     230
#define PFCTRS_64K_CACHE_GROUP_WRITE_COUNT                    232
#define PFCTRS_64K_CACHE_DIRTY_UNFIX_COUNT                    234
#define PFCTRS_64K_CACHE_FORCE_COUNT                          236
#define PFCTRS_64K_CACHE_IO_WAIT_COUNT                        238
#define PFCTRS_64K_CACHE_HIT_COUNT                            240
#define PFCTRS_64K_CACHE_FREE_BUFFER_COUNT                    242
#define PFCTRS_64K_CACHE_FREE_BUFFER_WAITERS                  244
#define PFCTRS_64K_CACHE_FIXED_BUFFER_COUNT                   246
#define PFCTRS_64K_CACHE_MODIFIED_BUFFER_COUNT                248
#define PFCTRS_64K_CACHE_FREE_GROUP_BUFFER_COUNT              250
#define PFCTRS_64K_CACHE_FIXED_GROUP_BUFFER_COUNT             252
#define PFCTRS_64K_CACHE_MODIFIED_GROUP_BUFFER_COUNT          254
#define PFCTRS_64K_CACHE_FLIMIT                               256
#define PFCTRS_64K_CACHE_MLIMIT                               258
#define PFCTRS_64K_CACHE_WBSTART                              260
#define PFCTRS_64K_CACHE_WBEND                                262
#define PFCTRS_LOCK_OBJ                                      264
#define PFCTRS_LOCK_WAITS_COUNT                              266
#define PFCTRS_LOCK_RESOURCES_COUNT                          268
#define PFCTRS_CSINT_THREAD_OBJ                              270
#define PFCTRS_CSINT_THREAD_NUMTHREADSAMPLES                 272
#define PFCTRS_CSINT_THREAD_STATEFREE                        274
#define PFCTRS_CSINT_THREAD_STATECOMPUTABLE                  276
#define PFCTRS_CSINT_THREAD_STATEEVENT_WAIT                  278
#define PFCTRS_CSINT_THREAD_STATEMUTEX                       280
#define PFCTRS_CSINT_THREAD_FACILITYCLF                      282
#define PFCTRS_CSINT_THREAD_FACILITYADF                      284
#define PFCTRS_CSINT_THREAD_FACILITYDMF                      286
#define PFCTRS_CSINT_THREAD_FACILITYOPF                      288
#define PFCTRS_CSINT_THREAD_FACILITYPSF                      290
#define PFCTRS_CSINT_THREAD_FACILITYQEF                      292
#define PFCTRS_CSINT_THREAD_FACILITYQSF                      294
#define PFCTRS_CSINT_THREAD_FACILITYRDF                      296
#define PFCTRS_CSINT_THREAD_FACILITYSCF                      298
#define PFCTRS_CSINT_THREAD_FACILITYULF                      300
#define PFCTRS_CSINT_THREAD_FACILITYDUF                      302
#define PFCTRS_CSINT_THREAD_FACILITYGCF                      304
#define PFCTRS_CSINT_THREAD_FACILITYRQF                      306
#define PFCTRS_CSINT_THREAD_FACILITYTPF                      308
#define PFCTRS_CSINT_THREAD_FACILITYGWF                      310
#define PFCTRS_CSINT_THREAD_FACILITYSXF                      312
#define PFCTRS_CSINT_THREAD_EVENTDISKIO                      314
#define PFCTRS_CSINT_THREAD_EVENTLOGIO                       316
#define PFCTRS_CSINT_THREAD_EVENTMESSAGEIO                   318
#define PFCTRS_CSINT_THREAD_EVENTLOG                         320
#define PFCTRS_CSINT_THREAD_EVENTLOCK                        322
#define PFCTRS_CSINT_THREAD_EVENTLOGEVENT                    324
#define PFCTRS_CSINT_THREAD_EVENTLOCKEVENT                   326
#define PFCTRS_NORMAL_THREAD_OBJ                             328
#define PFCTRS_NORMAL_THREAD_NUMTHREADSAMPLES                330
#define PFCTRS_NORMAL_THREAD_STATEFREE                       332
#define PFCTRS_NORMAL_THREAD_STATECOMPUTABLE                 334
#define PFCTRS_NORMAL_THREAD_STATEEVENT_WAIT                 336
#define PFCTRS_NORMAL_THREAD_STATEMUTEX                      338
#define PFCTRS_NORMAL_THREAD_FACILITYCLF                     340
#define PFCTRS_NORMAL_THREAD_FACILITYADF                     342
#define PFCTRS_NORMAL_THREAD_FACILITYDMF                     344
#define PFCTRS_NORMAL_THREAD_FACILITYOPF                     346
#define PFCTRS_NORMAL_THREAD_FACILITYPSF                     348
#define PFCTRS_NORMAL_THREAD_FACILITYQEF                     350
#define PFCTRS_NORMAL_THREAD_FACILITYQSF                     352
#define PFCTRS_NORMAL_THREAD_FACILITYRDF                     354
#define PFCTRS_NORMAL_THREAD_FACILITYSCF                     356
#define PFCTRS_NORMAL_THREAD_FACILITYULF                     358
#define PFCTRS_NORMAL_THREAD_FACILITYDUF                     360
#define PFCTRS_NORMAL_THREAD_FACILITYGCF                     362
#define PFCTRS_NORMAL_THREAD_FACILITYRQF                     364
#define PFCTRS_NORMAL_THREAD_FACILITYTPF                     366
#define PFCTRS_NORMAL_THREAD_FACILITYGWF                     368
#define PFCTRS_NORMAL_THREAD_FACILITYSXF                     370
#define PFCTRS_NORMAL_THREAD_EVENTDISKIO                     372
#define PFCTRS_NORMAL_THREAD_EVENTLOGIO                      374
#define PFCTRS_NORMAL_THREAD_EVENTMESSAGEIO                  376
#define PFCTRS_NORMAL_THREAD_EVENTLOG                        378
#define PFCTRS_NORMAL_THREAD_EVENTLOCK                       380
#define PFCTRS_NORMAL_THREAD_EVENTLOGEVENT                   382
#define PFCTRS_NORMAL_THREAD_EVENTLOCKEVENT                  384
#define PFCTRS_MON_THREAD_OBJ                                386
#define PFCTRS_MON_THREAD_NUMTHREADSAMPLES                   388
#define PFCTRS_MON_THREAD_STATEFREE                          390
#define PFCTRS_MON_THREAD_STATECOMPUTABLE                    392
#define PFCTRS_MON_THREAD_STATEEVENT_WAIT                    394
#define PFCTRS_MON_THREAD_STATEMUTEX                         396
#define PFCTRS_MON_THREAD_FACILITYCLF                        398
#define PFCTRS_MON_THREAD_FACILITYADF                        400
#define PFCTRS_MON_THREAD_FACILITYDMF                        402
#define PFCTRS_MON_THREAD_FACILITYOPF                        404
#define PFCTRS_MON_THREAD_FACILITYPSF                        406
#define PFCTRS_MON_THREAD_FACILITYQEF                        408
#define PFCTRS_MON_THREAD_FACILITYQSF                        410
#define PFCTRS_MON_THREAD_FACILITYRDF                        412
#define PFCTRS_MON_THREAD_FACILITYSCF                        414
#define PFCTRS_MON_THREAD_FACILITYULF                        416
#define PFCTRS_MON_THREAD_FACILITYDUF                        418
#define PFCTRS_MON_THREAD_FACILITYGCF                        420
#define PFCTRS_MON_THREAD_FACILITYRQF                        422
#define PFCTRS_MON_THREAD_FACILITYTPF                        424
#define PFCTRS_MON_THREAD_FACILITYGWF                        426
#define PFCTRS_MON_THREAD_FACILITYSXF                        428
#define PFCTRS_MON_THREAD_EVENTDISKIO                        430
#define PFCTRS_MON_THREAD_EVENTLOGIO                         432
#define PFCTRS_MON_THREAD_EVENTMESSAGEIO                     434
#define PFCTRS_MON_THREAD_EVENTLOG                           436
#define PFCTRS_MON_THREAD_EVENTLOCK                          438
#define PFCTRS_MON_THREAD_EVENTLOGEVENT                      440
#define PFCTRS_MON_THREAD_EVENTLOCKEVENT                     442
#define PFCTRS_FC_THREAD_OBJ                                 444
#define PFCTRS_FC_THREAD_NUMTHREADSAMPLES                    446
#define PFCTRS_FC_THREAD_STATEFREE                           448
#define PFCTRS_FC_THREAD_STATECOMPUTABLE                     450
#define PFCTRS_FC_THREAD_STATEEVENT_WAIT                     452
#define PFCTRS_FC_THREAD_STATEMUTEX                          454
#define PFCTRS_FC_THREAD_FACILITYCLF                         456
#define PFCTRS_FC_THREAD_FACILITYADF                         458
#define PFCTRS_FC_THREAD_FACILITYDMF                         460
#define PFCTRS_FC_THREAD_FACILITYOPF                         462
#define PFCTRS_FC_THREAD_FACILITYPSF                         464
#define PFCTRS_FC_THREAD_FACILITYQEF                         466
#define PFCTRS_FC_THREAD_FACILITYQSF                         468
#define PFCTRS_FC_THREAD_FACILITYRDF                         470
#define PFCTRS_FC_THREAD_FACILITYSCF                         472
#define PFCTRS_FC_THREAD_FACILITYULF                         474
#define PFCTRS_FC_THREAD_FACILITYDUF                         476
#define PFCTRS_FC_THREAD_FACILITYGCF                         478
#define PFCTRS_FC_THREAD_FACILITYRQF                         480
#define PFCTRS_FC_THREAD_FACILITYTPF                         482
#define PFCTRS_FC_THREAD_FACILITYGWF                         484
#define PFCTRS_FC_THREAD_FACILITYSXF                         486
#define PFCTRS_FC_THREAD_EVENTDISKIO                         488
#define PFCTRS_FC_THREAD_EVENTLOGIO                          490
#define PFCTRS_FC_THREAD_EVENTMESSAGEIO                      492
#define PFCTRS_FC_THREAD_EVENTLOG                            494
#define PFCTRS_FC_THREAD_EVENTLOCK                           496
#define PFCTRS_FC_THREAD_EVENTLOGEVENT                       498
#define PFCTRS_FC_THREAD_EVENTLOCKEVENT                      500
#define PFCTRS_WB_THREAD_OBJ                                 502
#define PFCTRS_WB_THREAD_NUMTHREADSAMPLES                    504
#define PFCTRS_WB_THREAD_STATEFREE                           506
#define PFCTRS_WB_THREAD_STATECOMPUTABLE                     508
#define PFCTRS_WB_THREAD_STATEEVENT_WAIT                     510
#define PFCTRS_WB_THREAD_STATEMUTEX                          512
#define PFCTRS_WB_THREAD_FACILITYCLF                         514
#define PFCTRS_WB_THREAD_FACILITYADF                         516
#define PFCTRS_WB_THREAD_FACILITYDMF                         518
#define PFCTRS_WB_THREAD_FACILITYOPF                         520
#define PFCTRS_WB_THREAD_FACILITYPSF                         522
#define PFCTRS_WB_THREAD_FACILITYQEF                         524
#define PFCTRS_WB_THREAD_FACILITYQSF                         526
#define PFCTRS_WB_THREAD_FACILITYRDF                         528
#define PFCTRS_WB_THREAD_FACILITYSCF                         530
#define PFCTRS_WB_THREAD_FACILITYULF                         532
#define PFCTRS_WB_THREAD_FACILITYDUF                         534
#define PFCTRS_WB_THREAD_FACILITYGCF                         536
#define PFCTRS_WB_THREAD_FACILITYRQF                         538
#define PFCTRS_WB_THREAD_FACILITYTPF                         540
#define PFCTRS_WB_THREAD_FACILITYGWF                         542
#define PFCTRS_WB_THREAD_FACILITYSXF                         544
#define PFCTRS_WB_THREAD_EVENTDISKIO                         546
#define PFCTRS_WB_THREAD_EVENTLOGIO                          548
#define PFCTRS_WB_THREAD_EVENTMESSAGEIO                      550
#define PFCTRS_WB_THREAD_EVENTLOG                            552
#define PFCTRS_WB_THREAD_EVENTLOCK                           554
#define PFCTRS_WB_THREAD_EVENTLOGEVENT                       556
#define PFCTRS_WB_THREAD_EVENTLOCKEVENT                      558
#define PFCTRS_SI_THREAD_OBJ                                 560
#define PFCTRS_SI_THREAD_NUMTHREADSAMPLES                    562
#define PFCTRS_SI_THREAD_STATEFREE                           564
#define PFCTRS_SI_THREAD_STATECOMPUTABLE                     566
#define PFCTRS_SI_THREAD_STATEEVENT_WAIT                     568
#define PFCTRS_SI_THREAD_STATEMUTEX                          570
#define PFCTRS_SI_THREAD_FACILITYCLF                         572
#define PFCTRS_SI_THREAD_FACILITYADF                         574
#define PFCTRS_SI_THREAD_FACILITYDMF                         576
#define PFCTRS_SI_THREAD_FACILITYOPF                         578
#define PFCTRS_SI_THREAD_FACILITYPSF                         580
#define PFCTRS_SI_THREAD_FACILITYQEF                         582
#define PFCTRS_SI_THREAD_FACILITYQSF                         584
#define PFCTRS_SI_THREAD_FACILITYRDF                         586
#define PFCTRS_SI_THREAD_FACILITYSCF                         588
#define PFCTRS_SI_THREAD_FACILITYULF                         590
#define PFCTRS_SI_THREAD_FACILITYDUF                         592
#define PFCTRS_SI_THREAD_FACILITYGCF                         594
#define PFCTRS_SI_THREAD_FACILITYRQF                         596
#define PFCTRS_SI_THREAD_FACILITYTPF                         598
#define PFCTRS_SI_THREAD_FACILITYGWF                         600
#define PFCTRS_SI_THREAD_FACILITYSXF                         602
#define PFCTRS_SI_THREAD_EVENTDISKIO                         604
#define PFCTRS_SI_THREAD_EVENTLOGIO                          606
#define PFCTRS_SI_THREAD_EVENTMESSAGEIO                      608
#define PFCTRS_SI_THREAD_EVENTLOG                            610
#define PFCTRS_SI_THREAD_EVENTLOCK                           612
#define PFCTRS_SI_THREAD_EVENTLOGEVENT                       614
#define PFCTRS_SI_THREAD_EVENTLOCKEVENT                      616
#define PFCTRS_EVENT_THREAD_OBJ                              618
#define PFCTRS_EVENT_THREAD_NUMTHREADSAMPLES                 620
#define PFCTRS_EVENT_THREAD_STATEFREE                        622
#define PFCTRS_EVENT_THREAD_STATECOMPUTABLE                  624
#define PFCTRS_EVENT_THREAD_STATEEVENT_WAIT                  626
#define PFCTRS_EVENT_THREAD_STATEMUTEX                       628
#define PFCTRS_EVENT_THREAD_FACILITYCLF                      630
#define PFCTRS_EVENT_THREAD_FACILITYADF                      632
#define PFCTRS_EVENT_THREAD_FACILITYDMF                      634
#define PFCTRS_EVENT_THREAD_FACILITYOPF                      636
#define PFCTRS_EVENT_THREAD_FACILITYPSF                      638
#define PFCTRS_EVENT_THREAD_FACILITYQEF                      640
#define PFCTRS_EVENT_THREAD_FACILITYQSF                      642
#define PFCTRS_EVENT_THREAD_FACILITYRDF                      644
#define PFCTRS_EVENT_THREAD_FACILITYSCF                      646
#define PFCTRS_EVENT_THREAD_FACILITYULF                      648
#define PFCTRS_EVENT_THREAD_FACILITYDUF                      650
#define PFCTRS_EVENT_THREAD_FACILITYGCF                      652
#define PFCTRS_EVENT_THREAD_FACILITYRQF                      654
#define PFCTRS_EVENT_THREAD_FACILITYTPF                      656
#define PFCTRS_EVENT_THREAD_FACILITYGWF                      658
#define PFCTRS_EVENT_THREAD_FACILITYSXF                      660
#define PFCTRS_EVENT_THREAD_EVENTDISKIO                      662
#define PFCTRS_EVENT_THREAD_EVENTLOGIO                       664
#define PFCTRS_EVENT_THREAD_EVENTMESSAGEIO                   666
#define PFCTRS_EVENT_THREAD_EVENTLOG                         668
#define PFCTRS_EVENT_THREAD_EVENTLOCK                        670
#define PFCTRS_EVENT_THREAD_EVENTLOGEVENT                    672
#define PFCTRS_EVENT_THREAD_EVENTLOCKEVENT                   674
#define PFCTRS_2PC_THREAD_OBJ                                676
#define PFCTRS_2PC_THREAD_NUMTHREADSAMPLES                   678
#define PFCTRS_2PC_THREAD_STATEFREE                          680
#define PFCTRS_2PC_THREAD_STATECOMPUTABLE                    682
#define PFCTRS_2PC_THREAD_STATEEVENT_WAIT                    684
#define PFCTRS_2PC_THREAD_STATEMUTEX                         686
#define PFCTRS_2PC_THREAD_FACILITYCLF                        688
#define PFCTRS_2PC_THREAD_FACILITYADF                        690
#define PFCTRS_2PC_THREAD_FACILITYDMF                        692
#define PFCTRS_2PC_THREAD_FACILITYOPF                        694
#define PFCTRS_2PC_THREAD_FACILITYPSF                        696
#define PFCTRS_2PC_THREAD_FACILITYQEF                        698
#define PFCTRS_2PC_THREAD_FACILITYQSF                        700
#define PFCTRS_2PC_THREAD_FACILITYRDF                        702
#define PFCTRS_2PC_THREAD_FACILITYSCF                        704
#define PFCTRS_2PC_THREAD_FACILITYULF                        706
#define PFCTRS_2PC_THREAD_FACILITYDUF                        708
#define PFCTRS_2PC_THREAD_FACILITYGCF                        710
#define PFCTRS_2PC_THREAD_FACILITYRQF                        712
#define PFCTRS_2PC_THREAD_FACILITYTPF                        714
#define PFCTRS_2PC_THREAD_FACILITYGWF                        716
#define PFCTRS_2PC_THREAD_FACILITYSXF                        718
#define PFCTRS_2PC_THREAD_EVENTDISKIO                        720
#define PFCTRS_2PC_THREAD_EVENTLOGIO                         722
#define PFCTRS_2PC_THREAD_EVENTMESSAGEIO                     724
#define PFCTRS_2PC_THREAD_EVENTLOG                           726
#define PFCTRS_2PC_THREAD_EVENTLOCK                          728
#define PFCTRS_2PC_THREAD_EVENTLOGEVENT                      730
#define PFCTRS_2PC_THREAD_EVENTLOCKEVENT                     732
#define PFCTRS_RECOVERY_THREAD_OBJ                           734
#define PFCTRS_RECOVERY_THREAD_NUMTHREADSAMPLES              736
#define PFCTRS_RECOVERY_THREAD_STATEFREE                     738
#define PFCTRS_RECOVERY_THREAD_STATECOMPUTABLE               740
#define PFCTRS_RECOVERY_THREAD_STATEEVENT_WAIT               742
#define PFCTRS_RECOVERY_THREAD_STATEMUTEX                    744
#define PFCTRS_RECOVERY_THREAD_FACILITYCLF                   746
#define PFCTRS_RECOVERY_THREAD_FACILITYADF                   748
#define PFCTRS_RECOVERY_THREAD_FACILITYDMF                   750
#define PFCTRS_RECOVERY_THREAD_FACILITYOPF                   752
#define PFCTRS_RECOVERY_THREAD_FACILITYPSF                   754
#define PFCTRS_RECOVERY_THREAD_FACILITYQEF                   756
#define PFCTRS_RECOVERY_THREAD_FACILITYQSF                   758
#define PFCTRS_RECOVERY_THREAD_FACILITYRDF                   760
#define PFCTRS_RECOVERY_THREAD_FACILITYSCF                   762
#define PFCTRS_RECOVERY_THREAD_FACILITYULF                   764
#define PFCTRS_RECOVERY_THREAD_FACILITYDUF                   766
#define PFCTRS_RECOVERY_THREAD_FACILITYGCF                   768
#define PFCTRS_RECOVERY_THREAD_FACILITYRQF                   770
#define PFCTRS_RECOVERY_THREAD_FACILITYTPF                   772
#define PFCTRS_RECOVERY_THREAD_FACILITYGWF                   774
#define PFCTRS_RECOVERY_THREAD_FACILITYSXF                   776
#define PFCTRS_RECOVERY_THREAD_EVENTDISKIO                   778
#define PFCTRS_RECOVERY_THREAD_EVENTLOGIO                    780
#define PFCTRS_RECOVERY_THREAD_EVENTMESSAGEIO                782
#define PFCTRS_RECOVERY_THREAD_EVENTLOG                      784
#define PFCTRS_RECOVERY_THREAD_EVENTLOCK                     786
#define PFCTRS_RECOVERY_THREAD_EVENTLOGEVENT                 788
#define PFCTRS_RECOVERY_THREAD_EVENTLOCKEVENT                790
#define PFCTRS_LGW_THREAD_OBJ                                792
#define PFCTRS_LGW_THREAD_NUMTHREADSAMPLES                   794
#define PFCTRS_LGW_THREAD_STATEFREE                          796
#define PFCTRS_LGW_THREAD_STATECOMPUTABLE                    798
#define PFCTRS_LGW_THREAD_STATEEVENT_WAIT                    800
#define PFCTRS_LGW_THREAD_STATEMUTEX                         802
#define PFCTRS_LGW_THREAD_FACILITYCLF                        804
#define PFCTRS_LGW_THREAD_FACILITYADF                        806
#define PFCTRS_LGW_THREAD_FACILITYDMF                        808
#define PFCTRS_LGW_THREAD_FACILITYOPF                        810
#define PFCTRS_LGW_THREAD_FACILITYPSF                        812
#define PFCTRS_LGW_THREAD_FACILITYQEF                        814
#define PFCTRS_LGW_THREAD_FACILITYQSF                        816
#define PFCTRS_LGW_THREAD_FACILITYRDF                        818
#define PFCTRS_LGW_THREAD_FACILITYSCF                        820
#define PFCTRS_LGW_THREAD_FACILITYULF                        822
#define PFCTRS_LGW_THREAD_FACILITYDUF                        824
#define PFCTRS_LGW_THREAD_FACILITYGCF                        826
#define PFCTRS_LGW_THREAD_FACILITYRQF                        828
#define PFCTRS_LGW_THREAD_FACILITYTPF                        830
#define PFCTRS_LGW_THREAD_FACILITYGWF                        832
#define PFCTRS_LGW_THREAD_FACILITYSXF                        834
#define PFCTRS_LGW_THREAD_EVENTDISKIO                        836
#define PFCTRS_LGW_THREAD_EVENTLOGIO                         838
#define PFCTRS_LGW_THREAD_EVENTMESSAGEIO                     840
#define PFCTRS_LGW_THREAD_EVENTLOG                           842
#define PFCTRS_LGW_THREAD_EVENTLOCK                          844
#define PFCTRS_LGW_THREAD_EVENTLOGEVENT                      846
#define PFCTRS_LGW_THREAD_EVENTLOCKEVENT                     848
#define PFCTRS_CD_THREAD_OBJ                                 850
#define PFCTRS_CD_THREAD_NUMTHREADSAMPLES                    852
#define PFCTRS_CD_THREAD_STATEFREE                           854
#define PFCTRS_CD_THREAD_STATECOMPUTABLE                     856
#define PFCTRS_CD_THREAD_STATEEVENT_WAIT                     858
#define PFCTRS_CD_THREAD_STATEMUTEX                          860
#define PFCTRS_CD_THREAD_FACILITYCLF                         862
#define PFCTRS_CD_THREAD_FACILITYADF                         864
#define PFCTRS_CD_THREAD_FACILITYDMF                         866
#define PFCTRS_CD_THREAD_FACILITYOPF                         868
#define PFCTRS_CD_THREAD_FACILITYPSF                         870
#define PFCTRS_CD_THREAD_FACILITYQEF                         872
#define PFCTRS_CD_THREAD_FACILITYQSF                         874
#define PFCTRS_CD_THREAD_FACILITYRDF                         876
#define PFCTRS_CD_THREAD_FACILITYSCF                         878
#define PFCTRS_CD_THREAD_FACILITYULF                         880
#define PFCTRS_CD_THREAD_FACILITYDUF                         882
#define PFCTRS_CD_THREAD_FACILITYGCF                         884
#define PFCTRS_CD_THREAD_FACILITYRQF                         886
#define PFCTRS_CD_THREAD_FACILITYTPF                         888
#define PFCTRS_CD_THREAD_FACILITYGWF                         890
#define PFCTRS_CD_THREAD_FACILITYSXF                         892
#define PFCTRS_CD_THREAD_EVENTDISKIO                         894
#define PFCTRS_CD_THREAD_EVENTLOGIO                          896
#define PFCTRS_CD_THREAD_EVENTMESSAGEIO                      898
#define PFCTRS_CD_THREAD_EVENTLOG                            900
#define PFCTRS_CD_THREAD_EVENTLOCK                           902
#define PFCTRS_CD_THREAD_EVENTLOGEVENT                       904
#define PFCTRS_CD_THREAD_EVENTLOCKEVENT                      906
#define PFCTRS_GC_THREAD_OBJ                                 908
#define PFCTRS_GC_THREAD_NUMTHREADSAMPLES                    910
#define PFCTRS_GC_THREAD_STATEFREE                           912
#define PFCTRS_GC_THREAD_STATECOMPUTABLE                     914
#define PFCTRS_GC_THREAD_STATEEVENT_WAIT                     916
#define PFCTRS_GC_THREAD_STATEMUTEX                          918
#define PFCTRS_GC_THREAD_FACILITYCLF                         920
#define PFCTRS_GC_THREAD_FACILITYADF                         922
#define PFCTRS_GC_THREAD_FACILITYDMF                         924
#define PFCTRS_GC_THREAD_FACILITYOPF                         926
#define PFCTRS_GC_THREAD_FACILITYPSF                         928
#define PFCTRS_GC_THREAD_FACILITYQEF                         930
#define PFCTRS_GC_THREAD_FACILITYQSF                         932
#define PFCTRS_GC_THREAD_FACILITYRDF                         934
#define PFCTRS_GC_THREAD_FACILITYSCF                         936
#define PFCTRS_GC_THREAD_FACILITYULF                         938
#define PFCTRS_GC_THREAD_FACILITYDUF                         940
#define PFCTRS_GC_THREAD_FACILITYGCF                         942
#define PFCTRS_GC_THREAD_FACILITYRQF                         944
#define PFCTRS_GC_THREAD_FACILITYTPF                         946
#define PFCTRS_GC_THREAD_FACILITYGWF                         948
#define PFCTRS_GC_THREAD_FACILITYSXF                         950
#define PFCTRS_GC_THREAD_EVENTDISKIO                         952
#define PFCTRS_GC_THREAD_EVENTLOGIO                          954
#define PFCTRS_GC_THREAD_EVENTMESSAGEIO                      956
#define PFCTRS_GC_THREAD_EVENTLOG                            958
#define PFCTRS_GC_THREAD_EVENTLOCK                           960
#define PFCTRS_GC_THREAD_EVENTLOGEVENT                       962
#define PFCTRS_GC_THREAD_EVENTLOCKEVENT                      964
#define PFCTRS_FA_THREAD_OBJ                                 966
#define PFCTRS_FA_THREAD_NUMTHREADSAMPLES                    968
#define PFCTRS_FA_THREAD_STATEFREE                           970
#define PFCTRS_FA_THREAD_STATECOMPUTABLE                     972
#define PFCTRS_FA_THREAD_STATEEVENT_WAIT                     974
#define PFCTRS_FA_THREAD_STATEMUTEX                          976
#define PFCTRS_FA_THREAD_FACILITYCLF                         978
#define PFCTRS_FA_THREAD_FACILITYADF                         980
#define PFCTRS_FA_THREAD_FACILITYDMF                         982
#define PFCTRS_FA_THREAD_FACILITYOPF                         984
#define PFCTRS_FA_THREAD_FACILITYPSF                         986
#define PFCTRS_FA_THREAD_FACILITYQEF                         988
#define PFCTRS_FA_THREAD_FACILITYQSF                         990
#define PFCTRS_FA_THREAD_FACILITYRDF                         992
#define PFCTRS_FA_THREAD_FACILITYSCF                         994
#define PFCTRS_FA_THREAD_FACILITYULF                         996
#define PFCTRS_FA_THREAD_FACILITYDUF                         998
#define PFCTRS_FA_THREAD_FACILITYGCF                         1000
#define PFCTRS_FA_THREAD_FACILITYRQF                         1002
#define PFCTRS_FA_THREAD_FACILITYTPF                         1004
#define PFCTRS_FA_THREAD_FACILITYGWF                         1006
#define PFCTRS_FA_THREAD_FACILITYSXF                         1008
#define PFCTRS_FA_THREAD_EVENTDISKIO                         1010
#define PFCTRS_FA_THREAD_EVENTLOGIO                          1012
#define PFCTRS_FA_THREAD_EVENTMESSAGEIO                      1014
#define PFCTRS_FA_THREAD_EVENTLOG                            1016
#define PFCTRS_FA_THREAD_EVENTLOCK                           1018
#define PFCTRS_FA_THREAD_EVENTLOGEVENT                       1020
#define PFCTRS_FA_THREAD_EVENTLOCKEVENT                      1022
#define PFCTRS_AUDIT_THREAD_OBJ                              1024
#define PFCTRS_AUDIT_THREAD_NUMTHREADSAMPLES                 1026
#define PFCTRS_AUDIT_THREAD_STATEFREE                        1028
#define PFCTRS_AUDIT_THREAD_STATECOMPUTABLE                  1030
#define PFCTRS_AUDIT_THREAD_STATEEVENT_WAIT                  1032
#define PFCTRS_AUDIT_THREAD_STATEMUTEX                       1034
#define PFCTRS_AUDIT_THREAD_FACILITYCLF                      1036
#define PFCTRS_AUDIT_THREAD_FACILITYADF                      1038
#define PFCTRS_AUDIT_THREAD_FACILITYDMF                      1040
#define PFCTRS_AUDIT_THREAD_FACILITYOPF                      1042
#define PFCTRS_AUDIT_THREAD_FACILITYPSF                      1044
#define PFCTRS_AUDIT_THREAD_FACILITYQEF                      1046
#define PFCTRS_AUDIT_THREAD_FACILITYQSF                      1048
#define PFCTRS_AUDIT_THREAD_FACILITYRDF                      1050
#define PFCTRS_AUDIT_THREAD_FACILITYSCF                      1052
#define PFCTRS_AUDIT_THREAD_FACILITYULF                      1054
#define PFCTRS_AUDIT_THREAD_FACILITYDUF                      1056
#define PFCTRS_AUDIT_THREAD_FACILITYGCF                      1058
#define PFCTRS_AUDIT_THREAD_FACILITYRQF                      1060
#define PFCTRS_AUDIT_THREAD_FACILITYTPF                      1062
#define PFCTRS_AUDIT_THREAD_FACILITYGWF                      1064
#define PFCTRS_AUDIT_THREAD_FACILITYSXF                      1066
#define PFCTRS_AUDIT_THREAD_EVENTDISKIO                      1068
#define PFCTRS_AUDIT_THREAD_EVENTLOGIO                       1070
#define PFCTRS_AUDIT_THREAD_EVENTMESSAGEIO                   1072
#define PFCTRS_AUDIT_THREAD_EVENTLOG                         1074
#define PFCTRS_AUDIT_THREAD_EVENTLOCK                        1076
#define PFCTRS_AUDIT_THREAD_EVENTLOGEVENT                    1078
#define PFCTRS_AUDIT_THREAD_EVENTLOCKEVENT                   1080
#define PFCTRS_CPTIMER_THREAD_OBJ                            1082
#define PFCTRS_CPTIMER_THREAD_NUMTHREADSAMPLES               1084
#define PFCTRS_CPTIMER_THREAD_STATEFREE                      1086
#define PFCTRS_CPTIMER_THREAD_STATECOMPUTABLE                1088
#define PFCTRS_CPTIMER_THREAD_STATEEVENT_WAIT                1090
#define PFCTRS_CPTIMER_THREAD_STATEMUTEX                     1092
#define PFCTRS_CPTIMER_THREAD_FACILITYCLF                    1094
#define PFCTRS_CPTIMER_THREAD_FACILITYADF                    1096
#define PFCTRS_CPTIMER_THREAD_FACILITYDMF                    1098
#define PFCTRS_CPTIMER_THREAD_FACILITYOPF                    1100
#define PFCTRS_CPTIMER_THREAD_FACILITYPSF                    1102
#define PFCTRS_CPTIMER_THREAD_FACILITYQEF                    1104
#define PFCTRS_CPTIMER_THREAD_FACILITYQSF                    1106
#define PFCTRS_CPTIMER_THREAD_FACILITYRDF                    1108
#define PFCTRS_CPTIMER_THREAD_FACILITYSCF                    1110
#define PFCTRS_CPTIMER_THREAD_FACILITYULF                    1112
#define PFCTRS_CPTIMER_THREAD_FACILITYDUF                    1114
#define PFCTRS_CPTIMER_THREAD_FACILITYGCF                    1116
#define PFCTRS_CPTIMER_THREAD_FACILITYRQF                    1118
#define PFCTRS_CPTIMER_THREAD_FACILITYTPF                    1120
#define PFCTRS_CPTIMER_THREAD_FACILITYGWF                    1122
#define PFCTRS_CPTIMER_THREAD_FACILITYSXF                    1124
#define PFCTRS_CPTIMER_THREAD_EVENTDISKIO                    1126
#define PFCTRS_CPTIMER_THREAD_EVENTLOGIO                     1128
#define PFCTRS_CPTIMER_THREAD_EVENTMESSAGEIO                 1130
#define PFCTRS_CPTIMER_THREAD_EVENTLOG                       1132
#define PFCTRS_CPTIMER_THREAD_EVENTLOCK                      1134
#define PFCTRS_CPTIMER_THREAD_EVENTLOGEVENT                  1136
#define PFCTRS_CPTIMER_THREAD_EVENTLOCKEVENT                 1138
#define PFCTRS_CKTERM_THREAD_OBJ                             1140
#define PFCTRS_CKTERM_THREAD_NUMTHREADSAMPLES                1142
#define PFCTRS_CKTERM_THREAD_STATEFREE                       1144
#define PFCTRS_CKTERM_THREAD_STATECOMPUTABLE                 1146
#define PFCTRS_CKTERM_THREAD_STATEEVENT_WAIT                 1148
#define PFCTRS_CKTERM_THREAD_STATEMUTEX                      1150
#define PFCTRS_CKTERM_THREAD_FACILITYCLF                     1152
#define PFCTRS_CKTERM_THREAD_FACILITYADF                     1154
#define PFCTRS_CKTERM_THREAD_FACILITYDMF                     1156
#define PFCTRS_CKTERM_THREAD_FACILITYOPF                     1158
#define PFCTRS_CKTERM_THREAD_FACILITYPSF                     1160
#define PFCTRS_CKTERM_THREAD_FACILITYQEF                     1162
#define PFCTRS_CKTERM_THREAD_FACILITYQSF                     1164
#define PFCTRS_CKTERM_THREAD_FACILITYRDF                     1166
#define PFCTRS_CKTERM_THREAD_FACILITYSCF                     1168
#define PFCTRS_CKTERM_THREAD_FACILITYULF                     1170
#define PFCTRS_CKTERM_THREAD_FACILITYDUF                     1172
#define PFCTRS_CKTERM_THREAD_FACILITYGCF                     1174
#define PFCTRS_CKTERM_THREAD_FACILITYRQF                     1176
#define PFCTRS_CKTERM_THREAD_FACILITYTPF                     1178
#define PFCTRS_CKTERM_THREAD_FACILITYGWF                     1180
#define PFCTRS_CKTERM_THREAD_FACILITYSXF                     1182
#define PFCTRS_CKTERM_THREAD_EVENTDISKIO                     1184
#define PFCTRS_CKTERM_THREAD_EVENTLOGIO                      1186
#define PFCTRS_CKTERM_THREAD_EVENTMESSAGEIO                  1188
#define PFCTRS_CKTERM_THREAD_EVENTLOG                        1190
#define PFCTRS_CKTERM_THREAD_EVENTLOCK                       1192
#define PFCTRS_CKTERM_THREAD_EVENTLOGEVENT                   1194
#define PFCTRS_CKTERM_THREAD_EVENTLOCKEVENT                  1196
#define PFCTRS_SAW_THREAD_OBJ                                1198
#define PFCTRS_SAW_THREAD_NUMTHREADSAMPLES                   1200
#define PFCTRS_SAW_THREAD_STATEFREE                          1202
#define PFCTRS_SAW_THREAD_STATECOMPUTABLE                    1204
#define PFCTRS_SAW_THREAD_STATEEVENT_WAIT                    1206
#define PFCTRS_SAW_THREAD_STATEMUTEX                         1208
#define PFCTRS_SAW_THREAD_FACILITYCLF                        1210
#define PFCTRS_SAW_THREAD_FACILITYADF                        1212
#define PFCTRS_SAW_THREAD_FACILITYDMF                        1214
#define PFCTRS_SAW_THREAD_FACILITYOPF                        1216
#define PFCTRS_SAW_THREAD_FACILITYPSF                        1218
#define PFCTRS_SAW_THREAD_FACILITYQEF                        1220
#define PFCTRS_SAW_THREAD_FACILITYQSF                        1222
#define PFCTRS_SAW_THREAD_FACILITYRDF                        1224
#define PFCTRS_SAW_THREAD_FACILITYSCF                        1226
#define PFCTRS_SAW_THREAD_FACILITYULF                        1228
#define PFCTRS_SAW_THREAD_FACILITYDUF                        1230
#define PFCTRS_SAW_THREAD_FACILITYGCF                        1232
#define PFCTRS_SAW_THREAD_FACILITYRQF                        1234
#define PFCTRS_SAW_THREAD_FACILITYTPF                        1236
#define PFCTRS_SAW_THREAD_FACILITYGWF                        1238
#define PFCTRS_SAW_THREAD_FACILITYSXF                        1240
#define PFCTRS_SAW_THREAD_EVENTDISKIO                        1242
#define PFCTRS_SAW_THREAD_EVENTLOGIO                         1244
#define PFCTRS_SAW_THREAD_EVENTMESSAGEIO                     1246
#define PFCTRS_SAW_THREAD_EVENTLOG                           1248
#define PFCTRS_SAW_THREAD_EVENTLOCK                          1250
#define PFCTRS_SAW_THREAD_EVENTLOGEVENT                      1252
#define PFCTRS_SAW_THREAD_EVENTLOCKEVENT                     1254
#define PFCTRS_WA_THREAD_OBJ                                 1256
#define PFCTRS_WA_THREAD_NUMTHREADSAMPLES                    1258
#define PFCTRS_WA_THREAD_STATEFREE                           1260
#define PFCTRS_WA_THREAD_STATECOMPUTABLE                     1262
#define PFCTRS_WA_THREAD_STATEEVENT_WAIT                     1264
#define PFCTRS_WA_THREAD_STATEMUTEX                          1266
#define PFCTRS_WA_THREAD_FACILITYCLF                         1268
#define PFCTRS_WA_THREAD_FACILITYADF                         1270
#define PFCTRS_WA_THREAD_FACILITYDMF                         1272
#define PFCTRS_WA_THREAD_FACILITYOPF                         1274
#define PFCTRS_WA_THREAD_FACILITYPSF                         1276
#define PFCTRS_WA_THREAD_FACILITYQEF                         1278
#define PFCTRS_WA_THREAD_FACILITYQSF                         1280
#define PFCTRS_WA_THREAD_FACILITYRDF                         1282
#define PFCTRS_WA_THREAD_FACILITYSCF                         1284
#define PFCTRS_WA_THREAD_FACILITYULF                         1286
#define PFCTRS_WA_THREAD_FACILITYDUF                         1288
#define PFCTRS_WA_THREAD_FACILITYGCF                         1290
#define PFCTRS_WA_THREAD_FACILITYRQF                         1292
#define PFCTRS_WA_THREAD_FACILITYTPF                         1294
#define PFCTRS_WA_THREAD_FACILITYGWF                         1296
#define PFCTRS_WA_THREAD_FACILITYSXF                         1298
#define PFCTRS_WA_THREAD_EVENTDISKIO                         1300
#define PFCTRS_WA_THREAD_EVENTLOGIO                          1302
#define PFCTRS_WA_THREAD_EVENTMESSAGEIO                      1304
#define PFCTRS_WA_THREAD_EVENTLOG                            1306
#define PFCTRS_WA_THREAD_EVENTLOCK                           1308
#define PFCTRS_WA_THREAD_EVENTLOGEVENT                       1310
#define PFCTRS_WA_THREAD_EVENTLOCKEVENT                      1312
#define PFCTRS_RA_THREAD_OBJ                                 1314
#define PFCTRS_RA_THREAD_NUMTHREADSAMPLES                    1316
#define PFCTRS_RA_THREAD_STATEFREE                           1318
#define PFCTRS_RA_THREAD_STATECOMPUTABLE                     1320
#define PFCTRS_RA_THREAD_STATEEVENT_WAIT                     1322
#define PFCTRS_RA_THREAD_STATEMUTEX                          1324
#define PFCTRS_RA_THREAD_FACILITYCLF                         1326
#define PFCTRS_RA_THREAD_FACILITYADF                         1328
#define PFCTRS_RA_THREAD_FACILITYDMF                         1330
#define PFCTRS_RA_THREAD_FACILITYOPF                         1332
#define PFCTRS_RA_THREAD_FACILITYPSF                         1334
#define PFCTRS_RA_THREAD_FACILITYQEF                         1336
#define PFCTRS_RA_THREAD_FACILITYQSF                         1338
#define PFCTRS_RA_THREAD_FACILITYRDF                         1340
#define PFCTRS_RA_THREAD_FACILITYSCF                         1342
#define PFCTRS_RA_THREAD_FACILITYULF                         1344
#define PFCTRS_RA_THREAD_FACILITYDUF                         1346
#define PFCTRS_RA_THREAD_FACILITYGCF                         1348
#define PFCTRS_RA_THREAD_FACILITYRQF                         1350
#define PFCTRS_RA_THREAD_FACILITYTPF                         1352
#define PFCTRS_RA_THREAD_FACILITYGWF                         1354
#define PFCTRS_RA_THREAD_FACILITYSXF                         1356
#define PFCTRS_RA_THREAD_EVENTDISKIO                         1358
#define PFCTRS_RA_THREAD_EVENTLOGIO                          1360
#define PFCTRS_RA_THREAD_EVENTMESSAGEIO                      1362
#define PFCTRS_RA_THREAD_EVENTLOG                            1364
#define PFCTRS_RA_THREAD_EVENTLOCK                           1366
#define PFCTRS_RA_THREAD_EVENTLOGEVENT                       1368
#define PFCTRS_RA_THREAD_EVENTLOCKEVENT                      1370
#define PFCTRS_REPQ_THREAD_OBJ                               1372
#define PFCTRS_REPQ_THREAD_NUMTHREADSAMPLES                  1374
#define PFCTRS_REPQ_THREAD_STATEFREE                         1376
#define PFCTRS_REPQ_THREAD_STATECOMPUTABLE                   1378
#define PFCTRS_REPQ_THREAD_STATEEVENT_WAIT                   1380
#define PFCTRS_REPQ_THREAD_STATEMUTEX                        1382
#define PFCTRS_REPQ_THREAD_FACILITYCLF                       1384
#define PFCTRS_REPQ_THREAD_FACILITYADF                       1386
#define PFCTRS_REPQ_THREAD_FACILITYDMF                       1388
#define PFCTRS_REPQ_THREAD_FACILITYOPF                       1390
#define PFCTRS_REPQ_THREAD_FACILITYPSF                       1392
#define PFCTRS_REPQ_THREAD_FACILITYQEF                       1394
#define PFCTRS_REPQ_THREAD_FACILITYQSF                       1396
#define PFCTRS_REPQ_THREAD_FACILITYRDF                       1398
#define PFCTRS_REPQ_THREAD_FACILITYSCF                       1400
#define PFCTRS_REPQ_THREAD_FACILITYULF                       1402
#define PFCTRS_REPQ_THREAD_FACILITYDUF                       1404
#define PFCTRS_REPQ_THREAD_FACILITYGCF                       1406
#define PFCTRS_REPQ_THREAD_FACILITYRQF                       1408
#define PFCTRS_REPQ_THREAD_FACILITYTPF                       1410
#define PFCTRS_REPQ_THREAD_FACILITYGWF                       1412
#define PFCTRS_REPQ_THREAD_FACILITYSXF                       1414
#define PFCTRS_REPQ_THREAD_EVENTDISKIO                       1416
#define PFCTRS_REPQ_THREAD_EVENTLOGIO                        1418
#define PFCTRS_REPQ_THREAD_EVENTMESSAGEIO                    1420
#define PFCTRS_REPQ_THREAD_EVENTLOG                          1422
#define PFCTRS_REPQ_THREAD_EVENTLOCK                         1424
#define PFCTRS_REPQ_THREAD_EVENTLOGEVENT                     1426
#define PFCTRS_REPQ_THREAD_EVENTLOCKEVENT                    1428
#define PFCTRS_LKC_THREAD_OBJ                                1430
#define PFCTRS_LKC_THREAD_NUMTHREADSAMPLES                   1432
#define PFCTRS_LKC_THREAD_STATEFREE                          1434
#define PFCTRS_LKC_THREAD_STATECOMPUTABLE                    1436
#define PFCTRS_LKC_THREAD_STATEEVENT_WAIT                    1438
#define PFCTRS_LKC_THREAD_STATEMUTEX                         1440
#define PFCTRS_LKC_THREAD_FACILITYCLF                        1442
#define PFCTRS_LKC_THREAD_FACILITYADF                        1444
#define PFCTRS_LKC_THREAD_FACILITYDMF                        1446
#define PFCTRS_LKC_THREAD_FACILITYOPF                        1448
#define PFCTRS_LKC_THREAD_FACILITYPSF                        1450
#define PFCTRS_LKC_THREAD_FACILITYQEF                        1452
#define PFCTRS_LKC_THREAD_FACILITYQSF                        1454
#define PFCTRS_LKC_THREAD_FACILITYRDF                        1456
#define PFCTRS_LKC_THREAD_FACILITYSCF                        1458
#define PFCTRS_LKC_THREAD_FACILITYULF                        1460
#define PFCTRS_LKC_THREAD_FACILITYDUF                        1462
#define PFCTRS_LKC_THREAD_FACILITYGCF                        1464
#define PFCTRS_LKC_THREAD_FACILITYRQF                        1466
#define PFCTRS_LKC_THREAD_FACILITYTPF                        1468
#define PFCTRS_LKC_THREAD_FACILITYGWF                        1470
#define PFCTRS_LKC_THREAD_FACILITYSXF                        1472
#define PFCTRS_LKC_THREAD_EVENTDISKIO                        1474
#define PFCTRS_LKC_THREAD_EVENTLOGIO                         1476
#define PFCTRS_LKC_THREAD_EVENTMESSAGEIO                     1478
#define PFCTRS_LKC_THREAD_EVENTLOG                           1480
#define PFCTRS_LKC_THREAD_EVENTLOCK                          1482
#define PFCTRS_LKC_THREAD_EVENTLOGEVENT                      1484
#define PFCTRS_LKC_THREAD_EVENTLOCKEVENT                     1486
#define PFCTRS_LKD_THREAD_OBJ                                1488
#define PFCTRS_LKD_THREAD_NUMTHREADSAMPLES                   1490
#define PFCTRS_LKD_THREAD_STATEFREE                          1492
#define PFCTRS_LKD_THREAD_STATECOMPUTABLE                    1494
#define PFCTRS_LKD_THREAD_STATEEVENT_WAIT                    1496
#define PFCTRS_LKD_THREAD_STATEMUTEX                         1498
#define PFCTRS_LKD_THREAD_FACILITYCLF                        1500
#define PFCTRS_LKD_THREAD_FACILITYADF                        1502
#define PFCTRS_LKD_THREAD_FACILITYDMF                        1504
#define PFCTRS_LKD_THREAD_FACILITYOPF                        1506
#define PFCTRS_LKD_THREAD_FACILITYPSF                        1508
#define PFCTRS_LKD_THREAD_FACILITYQEF                        1510
#define PFCTRS_LKD_THREAD_FACILITYQSF                        1512
#define PFCTRS_LKD_THREAD_FACILITYRDF                        1514
#define PFCTRS_LKD_THREAD_FACILITYSCF                        1516
#define PFCTRS_LKD_THREAD_FACILITYULF                        1518
#define PFCTRS_LKD_THREAD_FACILITYDUF                        1520
#define PFCTRS_LKD_THREAD_FACILITYGCF                        1522
#define PFCTRS_LKD_THREAD_FACILITYRQF                        1524
#define PFCTRS_LKD_THREAD_FACILITYTPF                        1526
#define PFCTRS_LKD_THREAD_FACILITYGWF                        1528
#define PFCTRS_LKD_THREAD_FACILITYSXF                        1530
#define PFCTRS_LKD_THREAD_EVENTDISKIO                        1532
#define PFCTRS_LKD_THREAD_EVENTLOGIO                         1534
#define PFCTRS_LKD_THREAD_EVENTMESSAGEIO                     1536
#define PFCTRS_LKD_THREAD_EVENTLOG                           1538
#define PFCTRS_LKD_THREAD_EVENTLOCK                          1540
#define PFCTRS_LKD_THREAD_EVENTLOGEVENT                      1542
#define PFCTRS_LKD_THREAD_EVENTLOCKEVENT                     1544
#define PFCTRS_SAMPLER_THREAD_OBJ                            1546
#define PFCTRS_SAMPLER_THREAD_NUMTHREADSAMPLES               1548
#define PFCTRS_SAMPLER_THREAD_STATEFREE                      1550
#define PFCTRS_SAMPLER_THREAD_STATECOMPUTABLE                1552
#define PFCTRS_SAMPLER_THREAD_STATEEVENT_WAIT                1554
#define PFCTRS_SAMPLER_THREAD_STATEMUTEX                     1556
#define PFCTRS_SAMPLER_THREAD_FACILITYCLF                    1558
#define PFCTRS_SAMPLER_THREAD_FACILITYADF                    1560
#define PFCTRS_SAMPLER_THREAD_FACILITYDMF                    1562
#define PFCTRS_SAMPLER_THREAD_FACILITYOPF                    1564
#define PFCTRS_SAMPLER_THREAD_FACILITYPSF                    1566
#define PFCTRS_SAMPLER_THREAD_FACILITYQEF                    1568
#define PFCTRS_SAMPLER_THREAD_FACILITYQSF                    1570
#define PFCTRS_SAMPLER_THREAD_FACILITYRDF                    1572
#define PFCTRS_SAMPLER_THREAD_FACILITYSCF                    1574
#define PFCTRS_SAMPLER_THREAD_FACILITYULF                    1576
#define PFCTRS_SAMPLER_THREAD_FACILITYDUF                    1578
#define PFCTRS_SAMPLER_THREAD_FACILITYGCF                    1580
#define PFCTRS_SAMPLER_THREAD_FACILITYRQF                    1582
#define PFCTRS_SAMPLER_THREAD_FACILITYTPF                    1584
#define PFCTRS_SAMPLER_THREAD_FACILITYGWF                    1586
#define PFCTRS_SAMPLER_THREAD_FACILITYSXF                    1588
#define PFCTRS_SAMPLER_THREAD_EVENTDISKIO                    1590
#define PFCTRS_SAMPLER_THREAD_EVENTLOGIO                     1592
#define PFCTRS_SAMPLER_THREAD_EVENTMESSAGEIO                 1594
#define PFCTRS_SAMPLER_THREAD_EVENTLOG                       1596
#define PFCTRS_SAMPLER_THREAD_EVENTLOCK                      1598
#define PFCTRS_SAMPLER_THREAD_EVENTLOGEVENT                  1600
#define PFCTRS_SAMPLER_THREAD_EVENTLOCKEVENT                 1602
#define PFCTRS_SORT_THREAD_OBJ                               1604
#define PFCTRS_SORT_THREAD_NUMTHREADSAMPLES                  1606
#define PFCTRS_SORT_THREAD_STATEFREE                         1608
#define PFCTRS_SORT_THREAD_STATECOMPUTABLE                   1610
#define PFCTRS_SORT_THREAD_STATEEVENT_WAIT                   1612
#define PFCTRS_SORT_THREAD_STATEMUTEX                        1614
#define PFCTRS_SORT_THREAD_FACILITYCLF                       1616
#define PFCTRS_SORT_THREAD_FACILITYADF                       1618
#define PFCTRS_SORT_THREAD_FACILITYDMF                       1620
#define PFCTRS_SORT_THREAD_FACILITYOPF                       1622
#define PFCTRS_SORT_THREAD_FACILITYPSF                       1624
#define PFCTRS_SORT_THREAD_FACILITYQEF                       1626
#define PFCTRS_SORT_THREAD_FACILITYQSF                       1628
#define PFCTRS_SORT_THREAD_FACILITYRDF                       1630
#define PFCTRS_SORT_THREAD_FACILITYSCF                       1632
#define PFCTRS_SORT_THREAD_FACILITYULF                       1634
#define PFCTRS_SORT_THREAD_FACILITYDUF                       1636
#define PFCTRS_SORT_THREAD_FACILITYGCF                       1638
#define PFCTRS_SORT_THREAD_FACILITYRQF                       1640
#define PFCTRS_SORT_THREAD_FACILITYTPF                       1642
#define PFCTRS_SORT_THREAD_FACILITYGWF                       1644
#define PFCTRS_SORT_THREAD_FACILITYSXF                       1646
#define PFCTRS_SORT_THREAD_EVENTDISKIO                       1648
#define PFCTRS_SORT_THREAD_EVENTLOGIO                        1650
#define PFCTRS_SORT_THREAD_EVENTMESSAGEIO                    1652
#define PFCTRS_SORT_THREAD_EVENTLOG                          1654
#define PFCTRS_SORT_THREAD_EVENTLOCK                         1656
#define PFCTRS_SORT_THREAD_EVENTLOGEVENT                     1658
#define PFCTRS_SORT_THREAD_EVENTLOCKEVENT                    1660
#define PFCTRS_FACT_THREAD_OBJ                               1662
#define PFCTRS_FACT_THREAD_NUMTHREADSAMPLES                  1664
#define PFCTRS_FACT_THREAD_STATEFREE                         1666
#define PFCTRS_FACT_THREAD_STATECOMPUTABLE                   1668
#define PFCTRS_FACT_THREAD_STATEEVENT_WAIT                   1670
#define PFCTRS_FACT_THREAD_STATEMUTEX                        1672
#define PFCTRS_FACT_THREAD_FACILITYCLF                       1674
#define PFCTRS_FACT_THREAD_FACILITYADF                       1676
#define PFCTRS_FACT_THREAD_FACILITYDMF                       1678
#define PFCTRS_FACT_THREAD_FACILITYOPF                       1680
#define PFCTRS_FACT_THREAD_FACILITYPSF                       1682
#define PFCTRS_FACT_THREAD_FACILITYQEF                       1684
#define PFCTRS_FACT_THREAD_FACILITYQSF                       1686
#define PFCTRS_FACT_THREAD_FACILITYRDF                       1688
#define PFCTRS_FACT_THREAD_FACILITYSCF                       1690
#define PFCTRS_FACT_THREAD_FACILITYULF                       1692
#define PFCTRS_FACT_THREAD_FACILITYDUF                       1694
#define PFCTRS_FACT_THREAD_FACILITYGCF                       1696
#define PFCTRS_FACT_THREAD_FACILITYRQF                       1698
#define PFCTRS_FACT_THREAD_FACILITYTPF                       1700
#define PFCTRS_FACT_THREAD_FACILITYGWF                       1702
#define PFCTRS_FACT_THREAD_FACILITYSXF                       1704
#define PFCTRS_FACT_THREAD_EVENTDISKIO                       1706
#define PFCTRS_FACT_THREAD_EVENTLOGIO                        1708
#define PFCTRS_FACT_THREAD_EVENTMESSAGEIO                    1710
#define PFCTRS_FACT_THREAD_EVENTLOG                          1712
#define PFCTRS_FACT_THREAD_EVENTLOCK                         1714
#define PFCTRS_FACT_THREAD_EVENTLOGEVENT                     1716
#define PFCTRS_FACT_THREAD_EVENTLOCKEVENT                    1718
#define PFCTRS_LIC_THREAD_OBJ                                1720
#define PFCTRS_LIC_THREAD_NUMTHREADSAMPLES                   1722
#define PFCTRS_LIC_THREAD_STATEFREE                          1724
#define PFCTRS_LIC_THREAD_STATECOMPUTABLE                    1726
#define PFCTRS_LIC_THREAD_STATEEVENT_WAIT                    1728
#define PFCTRS_LIC_THREAD_STATEMUTEX                         1730
#define PFCTRS_LIC_THREAD_FACILITYCLF                        1732
#define PFCTRS_LIC_THREAD_FACILITYADF                        1734
#define PFCTRS_LIC_THREAD_FACILITYDMF                        1736
#define PFCTRS_LIC_THREAD_FACILITYOPF                        1738
#define PFCTRS_LIC_THREAD_FACILITYPSF                        1740
#define PFCTRS_LIC_THREAD_FACILITYQEF                        1742
#define PFCTRS_LIC_THREAD_FACILITYQSF                        1744
#define PFCTRS_LIC_THREAD_FACILITYRDF                        1746
#define PFCTRS_LIC_THREAD_FACILITYSCF                        1748
#define PFCTRS_LIC_THREAD_FACILITYULF                        1750
#define PFCTRS_LIC_THREAD_FACILITYDUF                        1752
#define PFCTRS_LIC_THREAD_FACILITYGCF                        1754
#define PFCTRS_LIC_THREAD_FACILITYRQF                        1756
#define PFCTRS_LIC_THREAD_FACILITYTPF                        1758
#define PFCTRS_LIC_THREAD_FACILITYGWF                        1760
#define PFCTRS_LIC_THREAD_FACILITYSXF                        1762
#define PFCTRS_LIC_THREAD_EVENTDISKIO                        1764
#define PFCTRS_LIC_THREAD_EVENTLOGIO                         1766
#define PFCTRS_LIC_THREAD_EVENTMESSAGEIO                     1768
#define PFCTRS_LIC_THREAD_EVENTLOG                           1770
#define PFCTRS_LIC_THREAD_EVENTLOCK                          1772
#define PFCTRS_LIC_THREAD_EVENTLOGEVENT                      1774
#define PFCTRS_LIC_THREAD_EVENTLOCKEVENT                     1776
#define PFCTRS_UNKNOWN_THREAD_OBJ                            1778
#define PFCTRS_UNKNOWN_THREAD_NUMTHREADSAMPLES               1780
#define PFCTRS_UNKNOWN_THREAD_STATEFREE                      1782
#define PFCTRS_UNKNOWN_THREAD_STATECOMPUTABLE                1784
#define PFCTRS_UNKNOWN_THREAD_STATEEVENT_WAIT                1786
#define PFCTRS_UNKNOWN_THREAD_STATEMUTEX                     1788
#define PFCTRS_UNKNOWN_THREAD_FACILITYCLF                    1790
#define PFCTRS_UNKNOWN_THREAD_FACILITYADF                    1792
#define PFCTRS_UNKNOWN_THREAD_FACILITYDMF                    1794
#define PFCTRS_UNKNOWN_THREAD_FACILITYOPF                    1796
#define PFCTRS_UNKNOWN_THREAD_FACILITYPSF                    1798
#define PFCTRS_UNKNOWN_THREAD_FACILITYQEF                    1800
#define PFCTRS_UNKNOWN_THREAD_FACILITYQSF                    1802
#define PFCTRS_UNKNOWN_THREAD_FACILITYRDF                    1804
#define PFCTRS_UNKNOWN_THREAD_FACILITYSCF                    1806
#define PFCTRS_UNKNOWN_THREAD_FACILITYULF                    1808
#define PFCTRS_UNKNOWN_THREAD_FACILITYDUF                    1810
#define PFCTRS_UNKNOWN_THREAD_FACILITYGCF                    1812
#define PFCTRS_UNKNOWN_THREAD_FACILITYRQF                    1814
#define PFCTRS_UNKNOWN_THREAD_FACILITYTPF                    1816
#define PFCTRS_UNKNOWN_THREAD_FACILITYGWF                    1818
#define PFCTRS_UNKNOWN_THREAD_FACILITYSXF                    1820
#define PFCTRS_UNKNOWN_THREAD_EVENTDISKIO                    1822
#define PFCTRS_UNKNOWN_THREAD_EVENTLOGIO                     1824
#define PFCTRS_UNKNOWN_THREAD_EVENTMESSAGEIO                 1826
#define PFCTRS_UNKNOWN_THREAD_EVENTLOG                       1828
#define PFCTRS_UNKNOWN_THREAD_EVENTLOCK                      1830
#define PFCTRS_UNKNOWN_THREAD_EVENTLOGEVENT                  1832
#define PFCTRS_UNKNOWN_THREAD_EVENTLOCKEVENT                 1834
#define PFCTRS_SAMP_OBJ                                      1836
#define PFCTRS_SAMP_NUMSAMPLES_COUNT                         1838
#define PFCTRS_SAMP_NUMTLSSAMPLES_COUNT                      1840
#define PFCTRS_SAMP_NUMTLSSLOTS_COUNT                        1842
#define PFCTRS_SAMP_NUMTLSPROBES_COUNT                       1844
#define PFCTRS_SAMP_NUMTLSREADS_COUNT                        1846
#define PFCTRS_SAMP_NUMTLSDIRTY_COUNT                        1848
#define PFCTRS_SAMP_NUMTLSWRITES_COUNT                       1850
