//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ijactrl.rc
//
#define IDS_IJACTRL                     1
#define IDB_IJACTRL                     1
#define IDI_ABOUTDLL                    1
#define IDS_IJACTRL_PPG                 2
#define IDR_MAINFRAME                   128
#define IDB_IJAIMAGELIST                130
#define IDB_IJAIMAGELIST2               131
#define IDB_HEADERORDER                 132
#define IDS_IJACTRL_PPG_CAPTION         200
#define IDD_PROPPAGE_IJACTRL            200
#define IDC_EDIT1                       201
#define IDD_DATABASE                    201
#define IDS_DETAIL_TRANSACTION1         201
#define IDC_EDIT2                       202
#define IDD_TABLE                       202
#define IDS_DETAIL_TRANSACTION2         202
#define IDC_CHECK1                      203
#define IDD_XRECOVER                    203
#define IDS_OWNERxITEM                  203
#define IDC_CHECK2                      204
#define IDD_XREDO                       204
#define IDS_PLEASE_SELECTPANE           204
#define IDC_EDIT3                       205
#define IDD_XEDITTEXT                   205
#define IDD_XDATABASE                   206
#define IDC_COMBO1                      207
#define IDD_LISTHEADER                  207
#define IDC_CHECK3                      208
#define IDC_COMBO2                      208
#define IDD_TEXTDETAIL_PROPPAGE1        208
#define IDC_BUTTON1                     209
#define IDC_COMBO3                      209
#define IDD_MESSAGE                     209
#define IDC_CHECK4                      210
#define IDC_COMBO4                      210
#define IDC_BUTTON9                     210
#define IDC_LIST1                       211
#define IDC_COMBO5                      211
#define IDC_STATIC_DETAIL4TX            212
#define IDC_CHECK7                      212
#define IDC_BUTTON2                     213
#define IDC_BUTTON3                     214
#define IDC_LIST2                       215
#define IDC_BUTTON5                     215
#define IDC_BUTTON4                     216
#define IDC_BUTTON6                     216
#define IDC_RADIO1                      217
#define IDC_CHECK5                      217
#define IDC_RADIO2                      218
#define IDC_CHECK6                      218
#define IDC_BUTTON7                     218
#define IDC_STATIC_CHECK1               219
#define IDC_BUTTON8                     219
#define IDC_CHECK8                      219
#define IDC_DATETIMEPICKER1             220
#define IDC_DATETIMEPICKER2             221
#define IDC_TAB1                        222
#define IDC_CHECKPOINT_LIST_BUTTON      223
#define IDC_BUTTON_CHECKPOINT_LIST      224
#define IDS_HEADER_ACTION               400
#define IDS_HEADER_TABLE                401
#define IDS_HEADER_DATA                 402
#define IDS_HEADER_TRANSACTION          403
#define IDS_HEADER_USER                 404
#define IDS_HEADER_BEGIN                405
#define IDS_HEADER_DURATION             406
#define IDS_HEADER_INSERT               407
#define IDS_HEADER_DELETE               408
#define IDS_HEADER_UPDATE               409
#define IDS_HEADER_TOTAL                410
#define IDS_HEADER_DATE                 411
#define IDS_HEADER_OPERATION            412
#define IDS_HEADER_NAME                 413
#define IDS_HEADER_END                  414
#define IDS_HEADER_LSN                  415
#define IDS_HEADER_COMMITDATE           416
#define IDS_MSG_II_SYSTEM_NOT_DEFINED   417
#define IDS_RECOVER_SCRIPT              418
#define IDS_RECOVERNOW_SCRIPT           419
#define IDS_REDO_SCRIPT                 420
#define IDS_REDONOW_SCRIPT              421
#define IDS_HEADER_RULE                 422
#define IDS_HEADER_CONSTRAINT           423
#define IDS_HEADER_RULENAME             424
#define IDS_HEADER_RULEOWNER            425
#define IDS_HEADER_RULEONTABLE          426
#define IDS_HEADER_CONSTRAINTTYPE       427
#define IDS_HEADER_CONSTRAINTTTEXT      428
#define IDS_HEADER_CONSTRAINTONTABLE    429
#define IDS_PROPSHT_CAPTION             430
#define IDS_HEADER_CONSTRAINTNAME       431
#define IDS_RECOVERREDO_IMPOSSIBLE      432
#define IDS_RUNSCRIPT_COMMIT_WARNING    433
#define IDS_INSERTxUPDATE_NO_AFFECTROW_WARNING 434
#define IDS_INSERTxUPDATE_AFFECTROWS_WARNING 435
#define IDS_REDO                        436
#define IDS_RECOVER                     437
#define IDS_REDOxRECOVER_NORULExCONSTRAINT 438
#define IDS_HEADER_INTEGRITY            439
#define IDS_HEADER_INTEGRITYTEXT        440
#define IDS_RECOVER_PATIAL              441
#define IDS_NOT_SELECT_ALLTRANS         442
#define IDS_ONLY_INSxUPDxDELxALLOWED_RECOVER 443
#define IDS_RECOVER_NON_JOURNAL_TRANS   444
#define IDS_UNDO_ROLLBACK_TRANS         445
#define IDS_SCANTOTHEEND_MSG1           446
#define IDS_SCANTOTHEEND_MSG2           447
#define IDS_AxDROP                      448
#define IDS_AxDELETE                    449
#define IDS_AxALTER                     450
#define IDS_AxUPDATE                    451
#define IDS_AxMORE                      452
#define IDS_RECOVERNOW_MSG1             453
#define IDS_STRING454IDS_RECOVERNOW_MSG2 454
#define IDS_RECOVER_SUCCESSFUL          455
#define IDS_RECOVER_GENSCRIPT_MSG1      456
#define IDS_RECOVER_GENSCRIPT_MSG2      457
#define IDS_RECOVER_GENSCRIPT_MSG3      458
#define IDS_RECOVER_GENSCRIPT_MSG4      459
#define IDS_REDO_PATIAL                 460
#define IDS_ONLY_INSxUPDxDELxALLOWED_REDO 461
#define IDS_REDONOW_MSG1                462
#define IDS_REDONOW_MSG2                463
#define IDS_REDONOW_MSG3                464
#define IDS_REDONOW_SUCCESSFUL          465
#define IDS_REDO_GENSCRIPT_MSG1         466
#define IDS_REDO_GENSCRIPT_MSG2         467
#define IDS_REDO_GENSCRIPT_MSG3         468
#define IDS_REDO_GENSCRIPT_MSG4         469
#define IDS_REDONOW_SCRIPT_MSG1         470
#define IDS_VIEW_DATABASE_INCONSISTENT  471
#define IDS_CANNOT_CONNECT_TO           472
#define IDS_FAIL_TO_GETSESSION          473
#define IDS_FAIL_TO_QUERY_RELATED_TRANS 474
#define IDS_NOTSET_II_DATE_CENTURY_BOUNDARY 475
#define IDS_SELECT_B4xAFTER_UPDATE      476
#define IDS_RECOVERxREDO_ORDER_TRANS_CHANGED 477
#define IDS_FAIL_TO_QUERY_TABLE_COLUMNS 478
#define IDS_AUDITDB_SYNTAX1             479
#define IDS_EXECUTE_SCRIPT_ON           480
#define IDS_EXECUTE_EXTERNALSCRIPT_ON   481
#define IDS_FAILURE_ON_RUN_1            482
#define IDS_FAILURE_ON_RUN_2            483
#define IDS_RUN_REDO_SCRIPT_SUCCESSFULLY 484
#define IDS_RUN_RECOVER_SCRIPT_SUCCESSFULLY 485
#define IDS_FAILED_TO_GET_JOURNALED_TRANS 486
#define IDS_FAIL_TO_EXECUTE_AUDITDB     487
#define IDS_FAIL_TO_GENERATE_TEMPFILE   488
#define IDS_AUDITDB_FAILS_TO_CREATE_FILE 489
#define IDS_FAIL_TO_EXECUTE_ADBTOFST    490
#define IDS_PARSE_ERROR1                491
#define IDS_PARSE_ERROR2                492
#define IDS_LOWLEVEL_ERROR_INTERNAL     493
#define IDS_LOWLEVEL_ERROR_TEMPFILE     494
#define IDS_LOWLEVEL_ERROR_1            495
#define IDS_LOWLEVEL_ERROR_2            496
#define IDS_LOWLEVEL_ERROR_3            497
#define IDS_LOWLEVEL_ERROR_4            498
#define IDS_LOWLEVEL_ERROR_5            499
#define IDS_LOWLEVEL_ERROR_6            501
#define IDS_LOWLEVEL_ERROR_7            502
#define IDS_LOWLEVEL_ERROR_8            504
#define IDS_LOWLEVEL_ERROR_9            505
#define IDS_LOWLEVEL_ERROR_10           506
#define IDS_LOWLEVEL_ERROR_11           507
#define IDS_LOWLEVEL_ERROR_12           508
#define IDS_LOWLEVEL_ERROR_13           509
#define IDS_LOWLEVEL_ERROR_14           510
#define IDS_LOWLEVEL_ERROR_15           511
#define IDS_SCANTOTHEEND_MSG3           512
#define IDS_RECOVERNOW_MSG2             513
#define IDS_RECOVERNOW_SCRIPT_MSG1      514
#define IDS_PRODUCT_VERSION             515
#define IDS_MSG_FAIL_2_LOCATEDLL        516
#define IDS_TC_DATE                     517
#define IDS_TC_CKPSEQUENCE              518
#define IDS_TC_FIRSTJNL                 519
#define IDS_TC_LASTJNL                  520
#define IDS_TC_VALID                    521
#define IDS_TC_MODE                     522
#define IDD_CHECKPOINT_LIST             524
#define IDC_LIST_CHECKPOINT             525
#define IDS_FAIL_DROP_TEMP_TABLE        526
#define IDS_FAIL_TO_GENERATE_TEMPTABLE  527
#define IDS_RMCMD_INTERNAL_ERROR        528
#define IDS_RMCMD_ACCESS_ERROR          529
#define IDS_RMCMD_COMMAND_NOT_ACCEPTED  530
#define IDS_RMCMD_NO_ANSWER             531
#define IDS_RMCMD_ACCESSING_OUTPOUT     532
#define IDS_RMCMD_MANUALLY              533
#define IDS_TOOLSTIP_BUTTON_DOWN        534
#define IDS_TOOLSTIP_BUTTON_UP          535
#define IDS_TOOLSTIP_BUTTON_SEL         536
#define IDS_TOOLSTIP_BUTTON_ORDER       537
#define IDD_XMESSAGEBOX                 854
#define IDC_MFC_CHECK1                  1005
#define IDC_STATIC_01                   1010
#define IDC_STATIC_IMAGE                1254

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        212
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         225
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
