/*
**	Copyright (c) 1986, 2004 Ingres Corporation
*/

# include	<compat.h>
# include	<gl.h>
# include	<sl.h>
# include	<iicommon.h>
# include	<fe.h>
#include "ioistd.h"
#include <ds.h>
#include <feds.h>
#include <ifrmobj.h>
#ifdef MSDOS
#include <clstatus.h>
#endif

/**
** Name:	ioifrm.c - read frames
**
** Description:
**	image file frame read.
**
**  History:
**	10/14/92 (dkh) - Removed use of ArrayOf in favor of DSTARRAY.
**			 ArrayOf confused the alpha C compiler.
**      07-May-96 (fanra01)
**          bug# 76270
**          Added a call to frm_init which initialises the template structure.
**          This call has been added to facilitate the initialisation of
**          the template structure with items which are not constant at compile
**          time.
*/

#ifdef PCINGRES
GLOBALREF bool ME_recoverable;
#endif

GLOBALREF DSTARRAY Frm_template;

/*{
** Name:	IIOIfrFrmRead - frame read
**
** Description:
**	Read an OSL frame from an open image file.
**
** Inputs:
**	fp	image file
**	pos	frame position in file
**	tag	storage tag for allocated memory
**
** Outputs:
**	frm	returned frame
**
**	return:
**		OK		success
**
** Side Effects:
**
** History:
**	9/86 (rlm)	written
**      07-May-96 (fanra01)
**          Added a call to frm_init which initialises the template structure.
**
*/

STATUS
IIOIfrFrmRead(ohdr,pos,tag,frm)
OLIMHDR *ohdr;
i4 pos;
i2 tag;
IFRMOBJ **frm;
{
	PTR frmptr;		/* temp required for proper casting on DG */
	SH_DESC	sh_desc;
	FILE *fp;
	STATUS DSload();
	STATUS rc;
#ifdef PCINGRES
	bool oldreco;
#endif
        frm_init();
	fp = ohdr->fp;

	if (SIfseek(fp,pos,SI_P_START) != OK)
		return (ILE_FRDWR);

	sh_desc.sh_type = IS_RACC;
	sh_desc.sh_reg.file.fp = fp;
	sh_desc.sh_keep = TRUE;
	sh_desc.sh_tag = tag;

	/*
	** For PCINGRES, DSload call is bracketed with flag setting for ME
	** to handle allocation failure.  This flag allows DS to handle
	** an exception generated by ME, rather than causing a syserr()
	*/
#ifdef PCINGRES
	oldreco = ME_recoverable;
	ME_recoverable = TRUE;
	rc = DSload(&sh_desc, (i4 **) frm, &Frm_template);
	ME_recoverable = oldreco;
#else
	/*
	** Data General distinguishes between byte and word pointers.  On DG
	** a PTR is a CHAR *.  DSload expects a PTR * so we must therefore
	** cast frm to a PTR (a byte pointer) before calling DSload.  We
	** must cast it back after the call (kenl).
	*/
	frmptr = (PTR) *frm;
	rc = DSload(&sh_desc, &frmptr, &Frm_template);
	*frm = (IFRMOBJ *) frmptr;
#endif

	switch ((int) rc)
	{
	case OK:
		return (OK);
#ifdef MSDOS
	case ME_GONE:
		return (ILE_NOMEM);
#endif
	default:
		return (ILE_FRDWR);
	}
}
