#!/bin/sh
#
#	/**********************************************************
#	* Simple RC script for giving permissions to system files *
#       * needed by INGRES.                                       *
#	**********************************************************/
#
#   We comment the run level id as 420 in this sample script.  To prevent
#   confusion, you should change 420 in the next comment if you assign a 
#   different sequence number.
#
# /usr/sbin/init.d/rc.ingres   420  
#

PATH=/sbin:/usr/sbin:/usr/bin

         chmod 777 /dev/kmem

#	 If you are using a raw log device for INGRES, remove the comment
#	 character from the chown statement below and substitute the name
#        of your raw log device.  If you switch back to a regular log file,
#        be sure to re-add the comment character to the chown statement below.

#        chown ingres /dev/rdsk/raw_device_name
