/*
**	iitbdata.c
**
**	Copyright (c) 2004 Ingres Corporation
**	All rights reserved.
*/

# include	<compat.h>
# include	<gl.h>
# include	<sl.h>
# include	<iicommon.h>
# include	<fe.h>
# include	<ft.h>
# include	<fmt.h>
# include	<adf.h>
# include	<frame.h>
# include	<menu.h>
# include	<runtime.h>
# include	<er.h>
# include	"ertb.h"
# include	<rtvars.h>

/**
** Name:	iitbdata.c	-	TABLEDATA support routines
**
** Description:
**
**	Public (extern) routines defined:
**		IItdata()
**		IItdatend()
**	Private (static) routines defined:
**
** History:
**	08/14/87 (dkh) - ER changes.
**	21-jan-1999 (hanch04)
**	    replace nat and longnat with i4
**	31-aug-2000 (hanch04)
**	    cross change to main
**	    replace nat and longnat with i4
**	21-Aug-2009 (kschendel) 121804
**	    Update some of the function declarations to fix gcc 4.3 problems.
**/

static	i4		oldcolumn = 0;		/* original current column */
static	i2		inloop = 0;		/* set when entering loop */
static	TBSTRUCT	*tbl = NULL;		/* table field to loop thru */

FUNC_EXTERN	char		*FDfldnm();

/*{
** Name:	IItdata		-	Execute TABLEDATA while loop
**
** Description:
**
**	If the current field is a table field, then save the current
**	column and set a flag that the while loop has been started.
**	On each iteration of the loop update the current column.  On
**	reaching the last column reset the current column to its
**	original value.
**
**	This routine is part of TBACC's external interface.
**	The code generated by EQUEL looks like this:
**
**		while (IItdata() != 0)			Start loop
**
**		IItdatend();				End loop
**
**
** Inputs:
**
** Outputs:
**
** Returns:
**	i4	TRUE
**		FALSE
**
** Exceptions:
**	none
**
** Examples and Code Generation:
**	## tabledata { }
**
**	while (IItdata() != 0) {
**	}
**	IItdatend();
**
** Side Effects:
**
** History:
**		4-mar-1983	- written (ncg)
**
*/

IItdata()
{
	register	TBLFLD	*tfld;

	if (!RTchkfrs(IIstkfrm))
		return (FALSE);

	/*
	** If this is first time through the while loop, and we're on a table
	** table field, then set current values and start at first column.
	*/
	if (!inloop)
	{
		if ((tbl = IItfind(IIstkfrm, FDfldnm(IIstkfrm->fdrunfrm))) == NULL)
		{
			oldcolumn = 0;		/* as a safety measure */
			return (FALSE);
		}

		tfld = tbl->tb_fld;
		inloop = 1;
		oldcolumn = tfld->tfcurcol;
		tfld->tfcurcol = 0;
		return (TRUE);			/* first time through */
	}

	/* second or more times through loop */
	/*
	** Check to see what the state is - if a user nested tabledata's
	** or did a 'goto' out of the loop, the state will be corrupted.
	*/
	if (tbl == NULL)
	{
		/* somehow reset during while loop */
		IItbug(ERget(S_TB0004_IItdata_table_reset));
		IItdatend();
		return (FALSE);
	}

	tfld = tbl->tb_fld;
	if (++tfld->tfcurcol >= tfld->tfcols)
	{
		IItdatend();			/* exit while loop */
		return (FALSE);
	}
	return (TRUE);				/* continue while loop */
}

/*{
** Name:	IItdatend	-	End a tabledata loop
**
** Description:
**	A call to this routine should be generated by a
**	'## ENDLOOP' statement inside of a TABLEDATA loop.
**
**	This routine is part of TBACC's external interface.
**
** Inputs:
**
** Outputs:
**
** Returns:
**	i4	TRUE
**		FALSE
**
** Exceptions:
**	none
**
** Side Effects:
**
** History:
**
*/

IItdatend()
{
	/*
	** Should only be called for a ## ENDLOOP inside a TABLEDATA loop.
	** If not then to avoid a core dump check that tfld is not NULL.
	*/
	if (tbl != NULL)
	{
		tbl->tb_fld->tfcurcol = oldcolumn;
	}
	inloop = 0;
	oldcolumn = 0;
	tbl = NULL;
}
