$ ctsnodes	== 4
$ total_nodes	== 4
$ master_node	== "swift"
$ master_que	== "mts1$batch"
$ node1		== "swift"
$ node2		== "cuckoo"
$ node3		== "ws73d"
$ node4		== "damsel"
$ node1que	== "mts1$batch"
$ node2que	== "mts2$batch"
$ node3que	== "mts3$batch"
$ node4que	== "mts4$batch"
