/*
**  Copyright (c) 2004 Ingres Corporation
*/

/**
** Name:	ervt.msg -	Message file for class VT
**
** Description:
**	This file defines the messages for class VT.
**
** History:
**	14-aug-1987 (dave)
**		Created.
**/

# define	_VT_CLASS	67
/*
**	vtgetstr.c
*/
E_VT0001_VTgetedit_buffer_ove	"VTgetedit: buffer overflow\n"	/* DIAG */
F_VT0001_INSERT	"INSERT"
F_VT0002_OVSTRK	"OVSTRK"
F_VT0003_Truncating_string	
	"Truncating string to %d characters. [PRESS RETURN]"
F_VT0004_input	" input[%s]"
