//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by vcbf.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_HTML_UDLGDASVRPARAMETER     103
#define IDR_MAINFRAME                   128
#define IDR_VCBFTYPE                    129
#define IDR_MAINFRAME_SAVE              129
#define IDD_MAINTAB_DLG                 130
#define IDB_CHECK                       130
#define IDR_TREE_POPUP                  130
#define IDD_HISTORY                     131
#define IDD_PREFERENCES                 132
#define IDD_CONFIG                      133
#define IDB_BITMAP1                     134
#define IDB_BITMAP2                     135
#define IDD_CONFIG_RIGHT                136
#define IDD_DBMS_PAGE_PARAMETER         137
#define IDD_DBMS_PAGE_DATABASE          138
#define IDD_DBMS_PAGE_CACHE             139
#define IDD_DBMS_PAGE_DERIVED           140
#define IDD_NET_PAGE_PARAMETER          141
#define IDD_NET_PAGE_PROTOCOL           142
#define IDD_NAME_PAGE_PARAMETER         143
#define IDD_CONFIG_LEFT                 144
#define IDD_DBMS_PAGE_CACHE_PARAMETER   150
#define IDD_LOGFILE_CREATE              151
#define IDD_CACHE_TAB                   153
#define IDD_LAYOUTCTRLEDIT2             154
#define IDD_LOGFILE_PAGE_CONFIGURE      155
#define IDD_CACHE_LIST                  156
#define IDD_BRIDGE_PAGE_PARAMETER       157
#define IDD_CONFIG_LEFT_PROPERTIES      159
#define IDR_DELETE_AVI                  160
#define IDR_COPY_AVI                    161
#define IDB_CHOOSEDIR                   162
#define IDB_RED                         163
#define IDB_YELLOW                      164
#define IDD_DBMS_PAGE_CACHE_DERIVED     165
#define IDB_GREEN                       165
#define IDD_SECURITY_PAGE_OPTION        166
#define IDD_SECURITY_PAGE_DERIVED       167
#define IDD_SECURITY_PAGE_AUDITING      168
#define IDD_SECURITY_PAGE_AUDITDERIVED  169
#define IDD_SECURITY_PAGE_LOGFILE       170
#define IDD_LOCKINGSYS_PAGE_PARAMETER   171
#define IDD_LOCKINGSYS_PAGE_DERIVED     172
#define IDD_LOGGINGSYS_PAGE_PARAMETER   173
#define IDD_LOGGINGSYS_PAGE_DERIVED     174
#define IDD_STAR_PAGE_DERIVED           175
#define IDD_STAR_PAGE_PARAMETER         176
#define IDD_INTERNET_PAGE_PARAMETER     177
#define IDD_LOGFILE_PAGE_SECONDARY      178
#define IDD_BRIDGE_PAGE_PROTOCOL        179
#define IDD_GENERIC_PAGE_STARTUP_COUNT  182
#define IDD_WAIT_DIALOG2                183
#define IDD_WAIT_DIALOG1                183
#define IDD_RECOVERY_PAGE_PARAMETER     184
#define IDC_AVI                         184
#define IDD_RECOVERY_PAGE_DERIVED       185
#define IDR_CLOCK_AVI                   185
#define IDD_WAIT_DIALOG                 186
#define IDD_LOGFILE_ADDFILE             187
#define IDD_FIND_DIALOG                 188
#define IDR_TRANSLOG_AVI                189
#define IDD_WAIT_DIALOG_PROGRESS        189
#define IDD_GW_ORACLE_PAGE_PARAMETER    190
#define IDD_GW_INFORMIX_PAGE_PARAMETER  191
#define IDD_GW_SYBASE_PAGE_PARAMETER    192
#define IDD_GW_ODBC_PAGE_PARAMETER      193
#define IDD_XVNODE                      194
#define IDD_GW_MSSQL_PAGE_PARAMETER     195
#define IDD_JDBC_PAGE_PARAMETER         196
#define IDD_DASVR_PAGE_PROTOCOL         197
#define IDD_SECURITY_PAGE_SYSTEM        198
#define IDD_SECURITY_PAGE_MECHANISM     199
#define IDD_NET_PAGE_REGISTRY           200
#define IDD_BRIDGE_PAGE_VNODE           201
#define IDD_DASVR_PAGE_PARAMETER        202
#define IDD_GW_DB2UDB_PAGE_PARAMETER	203
#define IDC_TAB1                        1000
#define IDC_EDIT1                       1001
#define IDC_CHECK1                      1002
#define IDC_COMBO1                      1002
#define IDC_COMPONENT                   1002
#define IDC_LIST1                       1003
#define IDC_ENABLED_SECONDARY           1003
#define IDC_EDIT2                       1004
#define IDC_STARTUP_COUNT               1004
#define IDC_SPIN1                       1005
#define IDC_SPIN2                       1006
#define IDC_EDIT3                       1007
#define IDC_SPIN3                       1008
#define IDC_EDIT4                       1009
#define IDC_BUTTON1                     1010
#define IDC_BUTTON2                     1011
#define IDC_BUTTON3                     1012
#define IDC_BUTTON4                     1013
#define IDC_BUTTON5                     1014
#define IDC_STATIC1                     1015
#define IDC_LIST_DATABASES              1016
#define IDC_BUTTON_ASSIST2              1020
#define IDC_STATIC_STATUS               1020
#define IDC_FILE_PRIMARY                1021
#define IDC_SIZE_PRIMARY                1022
#define IDC_FILE_SECONDARY              1023
#define IDC_SIZE_SECONDARY              1024
#define IDC_ENABLED_PRIMARY             1025
#define IDC_FILE                        1026
#define IDC_SIZEINK                     1027
#define IDC_ENABLED                     1028
#define IDC_STATIC_HOST                 1029
#define IDC_STATIC_INSTALL              1030
#define IDC_SIZE_LOG                    1030
#define IDC_SIZE_TOTAL                  1030
#define IDC_STATIC_II_SYSTEM            1031
#define IDC_SIZE_PER_FILE               1031
#define IDC_STATIC_NAME_INSTALL         1032
#define IDC_TREE1                       1032
#define IDC_STATIC_IISYSTEM_NAME        1033
#define IDC_NAME                        1034
#define IDC_TEXT                        1035
#define IDC_ADD                         1038
#define IDC_REMOVE                      1039
#define IDC_FILENAME_LIST               1040
#define IDC_LOG_FILENAME                1041
#define IDC_BROWSE                      1042
#define IDC_RB_UP                       1043
#define IDC_RB_DOWN                     1044
#define IDB_FIND_NEXT                   1045
#define IDC_MATCH_CASE                  1046
#define IDC_FIND_TEXT                   1047
#define IDC_ROOT_LOCS                   1048
#define IDC_PROGRESS1                   1050
#define IDC_SIZE_LOG_TEXT               1051
#define IDC_STATUS_BITMAP               1052
#define ID_MENU_EDITNAME                32771
#define ID_MENU_EDITCOUNT               32772
#define ID_MENU_DUPLICATE               32773
#define ID_MENU_DUPLICATE_DEFAULT       32774
#define ID_MENU_DELETE                  32775
#define ID_MENU_PROPERTIES              32776
#define ID_MENUITEM32777                32777
#define ID_MENUITEM32778                32778
#define ID_MENUITEM32779                32779
#define ID_MENUITEM32780                32780
#define ID_MENUITEM32783                32783
#define IDS_TAB_MAIN_CONFIGURE          61446
#define IDS_TAB_MAIN_HISTORY            61447
#define IDS_TAB_MAIN_PREFERENCES        61448
#define IDS_TAB_CONFRIGHT_CACHE         61449
#define IDS_TAB_CONFRIGHT_DATABASES     61450
#define IDS_TAB_CONFRIGHT_DERIVED       61451
#define IDS_TAB_CONFRIGHT_PARAMETERS    61452
#define IDS_TAB_CONFRIGHT_PROTOCOL      61453
#define IDS_TAB_CONFRIGHT_CONFIGURE     61454
#define IDS_TAB_CONFRIGHT_OPTION        61455
#define IDS_TAB_CONFRIGHT_AUDITING      61456
#define IDS_TAB_CONFRIGHT_AUDITDERIVED  61457
#define IDS_TAB_CONFRIGHT_LOGFILE       61458
#define IDS_TAB_CONFRIGHT_PRIMARYLOG    61459
#define IDS_TAB_CONFRIGHT_SECONDARYLOG  61460
#define IDS_TAB_CONFRIGHT_STARTUP_COUNT 61463
#define IDS_APP_EDBC_TITLE              61464
#define IDS_TAB_CONFRIGHT_SYSTEM        61465
#define IDS_TAB_CONFRIGHT_MECHANISM     61466
#define IDS_TAB_CONFRIGHT_REGISTRY      61467
#define IDS_TAB_CONFRIGHT_VNODE         61468
#define IDS_CHOOSE_FOLDER               61469
#define IDS_BUTTON_EDIT_VALUE           61470
#define IDS_BUTTON_RESTORE              61471
#define IDS_BUTTON_RECALCULATE          61472
#define IDS_BUTTON_LISTEN_ADDRESS       61473
#define IDS_BUTTON_ADD                  61474
#define IDS_BUTTON_DELETE               61475
#define IDS_BUTTON_REMOVE               61476
#define IDS_BUTTON_REFORMAT             61477
#define IDS_BUTTON_DISABLE              61478
#define IDS_BUTTON_ERASE                61479
#define IDS_BUTTON_DESTROY              61480
#define IDS_BUTTON_CREATE               61481
#define IDS_COL_PROTOCOL                61482
#define IDS_COL_STATUS                  61483
#define IDS_COL_LISTEN_ADDRESS          61484
#define IDS_COL_VNODE                   61485
#define IDS_COL_CACHE                   61486
#define IDS_COL_COMPONENT               61487
#define IDS_COL_CONFIG                  61488
#define IDS_COL_STARTUP                 61489
#define IDS_COL_ENABLED                 61490
#define IDS_COL_MECHANISM               61491
#define IDS_COL_CROSSHATCH              61492
#define IDS_COL_AUDIT_LOG               61493
#define IDS_COL_PARAMETER               61494
#define IDS_COL_VALUE                   61495
#define IDS_COL_UNIT                    61496
#define IDS_COL_PROTECTED               61497
#define IDS_ERR_CREATE_LIST             61498
#define IDS_ERR_DELETE_ITEM             61499
#define IDS_CONFIRM_DELETE              61500
#define IDS_CHANGE_STARTUP_COUNT        61501
#define IDS_ENTER_NAME                  61502
#define IDS_ENTER_STARTUP_COUNT         61503
#define IDS_PATH_FOR_TRANSAC_LOG        61504
#define IDS_EMPTY_DBNAME                61505
#define IDS_INVALID_DBNAME              61506
#define IDS_MAX_LOG_FILES               61507
#define IDS_TRANSACTION_LOG_ONE         61508
#define IDS_ERR_TRANSACTION_PART        61509
#define IDS_AT_LEAST_ONE_LOG            61510
#define IDS_ERR_NOT_SPACE               61512
#define IDS_ERR_CREATE_DIR              61513
#define IDS_ERR_UNDERSCORE              61514
#define IDS_ERR_DUPLICATE_NAME          61515
#define IDS_ERR_NOT_FOUND               61516
#define IDS_ERR_LOAD_HISTORY            61517
#define IDS_CONTINUE_AND_LOSE           61518
#define IDS_ERR_CREATE_PROTO_LIST       61519
#define IDS_ERR_INITIALIZE              61520
#define IDS_CONFIGURATION_FILE_LOCKED   61521
#define IDS_MENU_DUPLICATE_DEFAULT      61523
#define IDS_MENU_DUPLICATE_BASED        61524
#define IDS_MENU_DUPLICATE              61525
#define IDS_MENU_DELETE                 61526
#define IDS_WAIT_DELETE                 61527
#define IDS_WAIT_CREATING               61528
#define IDS_WAIT_UPDATING               61529
#define IDS_TITLE_PROPERTIES            61530
#define IDS_TOOLSTIP_RIGHT_CLICK        61531
#define IDS_USAGE_ERROR                 61532

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        195
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
