/*
**  iiufsys.h
**
**  Copyright (c) 2004 Ingres Corporation
**
**  History:
**	2/19/87 (daveb) -- created to consolidate & hide details of the
**			   fortran runtime system that are different
**			   on various systems.  Prompted by apollo.
**	6/1/88 (markd)  -- added LEN_BEFORE_VAR case.
**	10/6/88 (russ)  -- added STRUCT_VAR case.
**	12/31/89 (dkh) - Integrated UNIX porting change "ingresug 90806"/
**			 (terry) - Added NO_UNDSCR def for ps2_us5 case.
**			 This is necessary for vsfortran support.
**	23-jan-90 (mgw)
**		Took new fortran compiler on SEQUENT which doesn't use
**		the LEN_BEFORE_VAR format for character string passing,
**		so take that #ifdef back out.
**	27-feb-90 (russ)
**		Added information for LPI FORTRAN on odt_us5.  Also
**		introduced the MIXEDCASE_FORTRAN define for FORTRAN
**		compilers which support mixed-case global symbols.
**	05-mar-90 (rog (from twong)) - add new define (DOUBLEDEREF) for
**			    machines that need to de-reference Fortran args
**			    twice (i.e. maybe structures.)
**	05-apr-90 (russ)
**		Add DOUBLEDEREF for odt_us5.
**	12 -apr-90 (kathryn)
**		Added ISC 386/ix defines with odt for LPI fortran specifics.
**		Add MIXEDCASE_FORTAN - DOUBLEDREF
**	7-jun-90 (thomasm)
**		No underscore for ris_us5 Fortran symbols
**	06-jul-90 (fredb)
**		Added cases for HP3000 MPE/XL (hp9_mpe).
**      26-sep-91 (jillb/jroy--DGC) (from 6.3)
**              Added cases for MIXEDCASE_FORTRAN and LEN_AFTER_VAR
**              for LPI Fortran on dg8_us5.
**	29-Jul-1992 (fredv)
**		Defined NO_UNDSCR and MIXEDCASE_FORTRAN for m88_us5.
**      31-jul-92 (kevinm)
**              Removed dg8_us5 entry for LEN_AFTER_VAR because Data
**              General is no longer supporting LPI fortan.
**	22-jul-92 (sweeney)
**		apl_us5 f77 puts immediate string length on stack.
**		LEN_AFTER_VAR *not* needed (I checked).
**      10-feb-95 (chech02)
**   		added rs4_us5 for AIX 4.1.
**      18-may-95 (wolf) 
**		Move the test for rs4_us5 into a separate if; the original 
**		change used a continuation character, which caused VMS warnings.
**      14-jul-95 (morayf) 
**		Added sos_us5 to odt_us5 ifdefs as SCO still uses LPI-FORTRAN
**      01-feb-95 (morayf) 
**		Added rmx_us5 to those setting MIXEDCASE_FORTRAN.
**		However this causes problems when building
**		shared libraries (libq) using mkshlib => mkshlibs removes
**		iiufutil.o just before makeing libq for rmx_us5.
**		Make rmx_us5 use structure (STRUCT_VAR).
**		This is for Siemens-Nixdorf RMx00 port. Uses SINIX F77.
**	07-Nov-98 (hweho01)
**              The EPC Fortran77 compiler (version 2.6.7) on DG/M88k 
**              does not append underscore to the symbol names, so  
**              defined NO_UNDSCR for dg8_us5. 
**	10-may-1999 (walro03)
**		Remove obsolete version string ix3_us5, odt_us5, ps2_us5.
**      03-jul-1999 (podni01)
**              Added support for ReliantUNIX V 5.44 - rux_us5 (same as rmx_us5)
**              
**	21-jan-1999 (hanch04)
**	    replace nat and longnat with i4
**	31-aug-2000 (hanch04)
**	    cross change to main
**	    replace nat and longnat with i4
**      17-apr-2001 (mcgem01)
**          Implement Embedded Fortran Support on Windows.
**	13-Aug-2003 (bonro01)
**	    Fortran f90 on i64_hpu appends underscores on function names.
**	19-Sep-2003 (bonro01)
**	    COBOL for i64_hpu requires DOUBLEDREF parameter.
**	22-Jun-2009 (kschendel) SIR 122138
**	    Use any_aix, sparc_sol, any_hpux symbols as needed.
**	23-Nov-2010 (kschendel)
**	    Drop obsolete ports.
*/

/* Most compilers append an underscore to all external symbol names 
** (as well truncate them to 6 chars), e.g. the external symbol name
** generated by the compiler for IIwrit() is iiwrit_().  Therefore all
** the "interface layer" routines use this format (see libqsys/iiflibq.c
** or runsys/iifrunt.c).
** If your compiler does NOT behave as described above then you must
** define NO_UNDSCR
*/ 

# if defined(any_aix)
# define NO_UNDSCR
# endif
# if defined(any_hpux) && !defined(i64_hpu)
# define NO_UNDSCR
# endif

/*
** MIXEDCASE_FORTRAN is defined for fortrans which support mixed case
** global symbols with no underscore.
*/

# ifdef NT_GENERIC
# define MIXEDCASE_FORTRAN
# endif

/*
** define DOUBLEDEREF if your Fortran compiler must de-reference
** Fortran argument twice (i.e iiaddf (exform)
*/

/*#define DOUBLEDEREF*/

# if defined(i64_hpu)
# define DOUBLEDEREF
# endif

#ifndef FSTRLEN

/*
** Hide details of fortran compiler supplied string lengths.
** The length of the string is passed somehow by the compiler as another
** argument.  FLENTYPE is how to declare the argument, and FLENTYPE is
** how to get the value.
*/
	typedef		i4	FLENTYPE;
#	define		FSTRLEN(l)	(l)

# endif

/* If you have defined LEN_AFTER_VAR in forgen.h then you must also
** define it here to indicate that the formal parameter list for "return-
** ing" functions (returns a value in the user's var) will be different. 
*/
# if defined(any_hpux) || defined(NT_GENERIC)
# define LEN_AFTER_VAR
# endif

/* If you have defined LEN_BEFORE_VAR in forgen.h then you must also
** define it here to indicate that the formal parameter list for "return-
** ing" functions (returns a value in the user's var) will be different. 
*/
