/*
**Copyright (c) 2004 Ingres Corporation
*/

#include	<compat.h>
#include    	<erglf.h>
#include	<gl.h>
#include	<sl.h>
#include        <cs.h>
#include	<st.h>
#include	<tr.h>
#include	<ex.h>
#include	<sp.h>
#include	<me.h>
#include	<mo.h>

#include	<iicommon.h>
#include	<dbdbms.h>
#include	<ddb.h>
#include	<ulf.h>
#include	<ulm.h>
#include	<scf.h>
#include	<ulh.h>
#include	<adf.h>
#include	<dmf.h>
#include	<dmtcb.h>
#include	<dmrcb.h>
#include	<qefmain.h>
#include        <qsf.h>
#include	<qefrcb.h>
#include	<qefcb.h>
#include	<qefqeu.h>
#include	<rdf.h>
#include	<rqf.h>
#include	<rdfddb.h>
#include	<rdfint.h>

/*
** Name:	rdfdata.c
**
** Description:	Global data for rdf facility.
**
** History:
**
**	23-sep-96 (canor01)
**	    Created.
**	21-jan-1999 (hanch04)
**	    replace nat and longnat with i4
**	31-aug-2000 (hanch04)
**	    cross change to main
**	    replace nat and longnat with i4
**	10-Jan-2001 (jenjo02)
**	    RDI_SVCB *svcb is now a GLOBALREF, added macros 
**	    GET_RDF_SESSCB macro to extract *RDF_SESSCB directly
**	    from SCF's SCB, added (ADF_CB*)rds_adf_cb,
**	    deprecating rdu_gcb(), rdu_adfcb(), rdu_gsvcb()
**	    functions.
**	19-mar-02 (inkdo01)
**	    Added classes for sequence statistics.
**	24-sep-2002 (abbjo03)
**	    Change rdi_svcb to static to avoid linkage problems on VMS.
**	11-jan-2004 (schka24)
**	    cluster nodes in ima data twice, fix.
**	5-Aug-2004 (schka24)
**	    Another new rdfcall dispatch.
**	29-Sep-2004 (drivi01)
**	    Added LIBRARY jam hint to put this file into IMPRDFLIBDATA
**	    in the Jamfile.
**	17-Nov-2005 (schka24)
**	    Change invalidate to not need session data.  Indeed, when an
**	    invalidation is propagated via dbevent, the other servers
**	    have no valid session.
*/

/*
**
LIBRARY = IMPRDFLIBDATA
**
*/

/* Server-wide RDF control block */
static RDI_SVCB	rdi_svcb	ZERO_FILL;
GLOBALDEF	RDI_SVCB	*Rdi_svcb = &rdi_svcb;

/*
** data from rdfcall.c
*/

GLOBALDEF   i4 RDF_privctr = 0;        /* used with RDU_BLD_PRIVATE trace*/


GLOBALDEF const	RDF_CALL_INFO Rdf_call_info[RDF_MAX_OP+1] = 
{
	/* cb-type, need-session-id, can-pass-ulm-rcb */
	{-1, FALSE, FALSE},			/* 0  unused */
	{RDF_CCB_TYPE, FALSE, FALSE},		/* 1  RDF_INITIALIZE */
	{RDF_CCB_TYPE, FALSE, FALSE},		/* 2  RDF_TERMINATE */
	{RDF_CB_TYPE, TRUE, TRUE},		/* 3  RDF_GETDESC */
	{RDF_CB_TYPE, TRUE, TRUE},		/* 4  RDF_UNFIX */
	{RDF_CB_TYPE, TRUE, TRUE},		/* 5  RDF_GETINFO */
	{RDF_CB_TYPE, TRUE, TRUE},		/* 6  RDF_UPDATE */
	{RDF_CCB_TYPE, FALSE, FALSE},		/* 7  RDF_STARTUP */
	{RDF_CCB_TYPE, TRUE, FALSE},		/* 8  RDF_BGN_SESSION */
	{RDF_CCB_TYPE, FALSE, FALSE},		/* 9  RDF_SHUTDOWN */
	{RDF_CB_TYPE, FALSE, TRUE},		/* 10 RDF_INVALIDATE */
	{RDF_CB_TYPE, TRUE, TRUE},		/* 11 RDF_PART_COPY */
	{RDF_CB_TYPE, TRUE, FALSE},		/* 12 RDF_PART_UPDATE */
	{RDF_CB_TYPE, TRUE, TRUE},		/* 13 RDF_DDB */
	{RDF_CCB_TYPE, TRUE, FALSE},		/* 14 RDF_END_SESSION */
	{-1, FALSE, FALSE},			/* 15 RDF_AUTOCOMMIT */
	{-1, FALSE, FALSE},			/* 16 RDF_NO_AUTOCOMMIT */
	{-1, FALSE, FALSE},			/* 17 RDF_COMMIT */
	{-1, FALSE, FALSE},			/* 18 RDF_TRANSACTION */
	{RDF_CB_TYPE, TRUE, TRUE},		/* 19 RDF_PART_FINISH */
	{RDF_CB_TYPE, FALSE, FALSE},		/* 20 RDU_INFO_DUMP */
	{RDF_CB_TYPE, FALSE, FALSE},		/* 21 RDU_REL_DUMP */
	{RDF_CB_TYPE, FALSE, FALSE},		/* 22 RDU_ATTR_DUMP */
	{RDF_CB_TYPE, FALSE, FALSE},		/* 23 RDU_INDX_DUMP */
	{RDF_CB_TYPE, FALSE, FALSE},		/* 24 RDU_ATTHSH_DUMP */
	{RDF_CB_TYPE, FALSE, FALSE},		/* 25 RDU_KEYS_DUMP */
	{RDF_CB_TYPE, FALSE, FALSE},		/* 26 RDU_HIST_DUMP */
	{RDF_CB_TYPE, FALSE, FALSE},		/* 27 RDU_ITUPLE_DUMP */
	{RDF_CB_TYPE, FALSE, FALSE},		/* 28 RDU_PTUPLE_DUMP */
	{RDF_CB_TYPE, TRUE, FALSE},		/* 29 RDF_PART_COMPAT */
	{RDF_CB_TYPE, TRUE, TRUE},		/* 30 RDF_PACK_QTEXT */
	{RDF_CB_TYPE, TRUE, TRUE},		/* 31 RDF_PACK_QTREE */
	{RDF_CCB_TYPE, FALSE, FALSE},		/* 32 RDF_ULM_TRACE */
	{RDF_CB_TYPE, TRUE, TRUE}		/* 33 RDF_READTUPLES */
};

/*
** data from rdfmo.c
*/

MO_GET_METHOD rdf_state_get;
MO_GET_METHOD rdf_avg_get;

# define RDF_STATISTICS_ADDR   NULL

GLOBALDEF MO_CLASS_DEF rdf_stat_classes[] =
{
    /* special avg get methods */

  { 0, "exp.rdf.stat.n1_avg_col",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_n1_avg_col),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_n1_avg_col), rdf_avg_get, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },

  { 0, "exp.rdf.stat.n2_avg_idx",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_n2_avg_idx),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_n2_avg_idx), rdf_avg_get, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },

      /* standard MO get methods */

  { 0, "exp.rdf.stat.r0_exists",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_r0_exists),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_r0_exists), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.c0_exists",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_c0_exists),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_c0_exists), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.b0_exists",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_b0_exists),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_b0_exists), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.z0_exists",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_z0_exists),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_z0_exists), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.r1_core",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_r1_core),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_r1_core), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.c1_core",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_c1_core),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_c1_core), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.b1_core",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_b1_core),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_b1_core), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.z1_core",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_z1_core),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_z1_core), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.r2_permit",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_r2_permit),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_r2_permit), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.c2_permit",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_c2_permit),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_c2_permit), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.b2_permit",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_b2_permit),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_b2_permit), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.a2_permit",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_a2_permit),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_a2_permit), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.d2_permit",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_d2_permit),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_d2_permit), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.r3_integ",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_r3_integ),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_r3_integ), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.c3_integ",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_c3_integ),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_c3_integ), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.b3_integ",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_b3_integ),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_b3_integ), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.a3_integ",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_a3_integ),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_a3_integ), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.d3_integ",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_d3_integ),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_d3_integ), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.r4_view",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_r4_view),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_r4_view), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.c4_view",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_c4_view),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_c4_view), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.b4_view",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_b4_view),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_b4_view), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.a4_view",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_a4_view),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_a4_view), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.d4_view",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_d4_view),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_d4_view), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.r5_proc",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_r5_proc),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_r5_proc), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.c5_proc",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_c5_proc),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_c5_proc), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.b5_proc",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_b5_proc),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_b5_proc), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.a5_proc",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_a5_proc),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_a5_proc), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.d5_proc",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_d5_proc),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_d5_proc), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.r6_rule",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_r6_rule),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_r6_rule), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.c6_rule",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_c6_rule),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_c6_rule), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.b6_rule",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_b6_rule),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_b6_rule), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.a6_rule",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_a6_rule),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_a6_rule), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.d6_rule",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_d6_rule),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_d6_rule), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.r7_event",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_r7_event),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_r7_event), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.b7_event",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_b7_event),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_b7_event), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.a7_event",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_a7_event),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_a7_event), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.d7_event",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_d7_event),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_d7_event), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.a8_alltoall",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_a8_alltoall),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_a8_alltoall), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.d8_alltoall",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_d8_alltoall),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_d8_alltoall), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.a9_rtoall",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_a9_rtoall),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_a9_rtoall), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.d9_rtoall",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_d9_rtoall),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_d9_rtoall), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.a10_dbdb",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_a10_dbdb),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_a10_dbdb), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.d10_dbdb",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_d10_dbdb),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_d10_dbdb), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.o10_dbdb",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_o10_dbdb),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_o10_dbdb), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.r11_stat",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_r11_stat),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_r11_stat), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.c11_stat",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_c11_stat),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_c11_stat), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.b11_stat",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_b11_stat),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_b11_stat), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.r16_syn",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_r16_syn),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_r16_syn), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.b16_syn",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_b16_syn),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_b16_syn), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.a16_syn",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_a16_syn),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_a16_syn), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.d16_syn",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_d16_syn),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_d16_syn), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.z16_syn",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_z16_syn),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_z16_syn), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.a17_comment",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_a17_comment),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_a17_comment), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.d17_comment",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_d17_comment),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_d17_comment), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.r21_seqs",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_r21_seqs),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_r21_seqs), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.b21_seqs",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_b21_seqs),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_b21_seqs), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.a21_seqs",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_a21_seqs),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_a21_seqs), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.d21_seqs",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_d21_seqs),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_d21_seqs), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.r12_itups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_r12_itups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_r12_itups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.b12_itups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_b12_itups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_b12_itups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.c12_itups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_c12_itups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_c12_itups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.m12_itups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_m12_itups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_m12_itups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.z12_itups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_z12_itups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_z12_itups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.r13_etups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_r13_etups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_r13_etups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.b13_etups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_b13_etups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_b13_etups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.m13_etups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_m13_etups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_m13_etups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.z13_etups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_z13_etups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_z13_etups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.r14_ptups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_r14_ptups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_r14_ptups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.b14_ptups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_b14_ptups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_b14_ptups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.c14_ptups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_c14_ptups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_c14_ptups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.m14_ptups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_m14_ptups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_m14_ptups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.z14_ptups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_z14_ptups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_z14_ptups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.r15_rtups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_r15_rtups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_r15_rtups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.b15_rtups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_b15_rtups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_b15_rtups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.c15_rtups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_c15_rtups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_c15_rtups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.m15_rtups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_m15_rtups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_m15_rtups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.z15_rtups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_z15_rtups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_z15_rtups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.r18_pptups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_r18_pptups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_r18_pptups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.b18_pptups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_b18_pptups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_b18_pptups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.c18_pptups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_c18_pptups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_c18_pptups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.m18_pptups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_m18_pptups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_m18_pptups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.z18_pptups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_z18_pptups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_z18_pptups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.r19_ktups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_r19_ktups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_r19_ktups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.b19_ktups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_b19_ktups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_b19_ktups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.c19_ktups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_c19_ktups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_c19_ktups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.m19_ktups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_m19_ktups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_m19_ktups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.z19_ktups",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_z19_ktups),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_z19_ktups), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.i1_obj_invalid",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_i1_obj_invalid),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_i1_obj_invalid), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.i2_p_invalid",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_i2_p_invalid),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_i2_p_invalid), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.i3_flushed",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_i3_flushed),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_i3_flushed), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.i4_class_invalid",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_i4_class_invalid),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_i4_class_invalid), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.i5_tree_invalid",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_i5_tree_invalid),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_i5_tree_invalid), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.i6_qtcache_invalid",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_i6_qtcache_invalid),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_i6_qtcache_invalid), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.i7_cache_invalid",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_i7_cache_invalid),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_i7_cache_invalid), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.i8_cache_invalid",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_i8_cache_invalid),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_i8_cache_invalid), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.n0_tables",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_n0_tables),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_n0_tables), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.n7_exceptions",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_n7_exceptions),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_n7_exceptions), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.n8_QTmem_claim",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_n8_QTmem_claim),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_n8_QTmem_claim), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.n9_relmem_claim",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_n9_relmem_claim),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_n9_relmem_claim), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.n10_nomem",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_n10_nomem),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_n10_nomem), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.n11_LDBmem_claim",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_n11_LDBmem_claim),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_n11_LDBmem_claim), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.rdf_n12_default_claim",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rdf_n12_default_claim),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rdf_n12_default_claim), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.x1_relation",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_x1_relation),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_x1_relation), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.x2_qtree",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_x2_qtree),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_x2_qtree), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.u0_protect",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_u0_protect),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_u0_protect), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.u1_integrity",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_u1_integrity),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_u1_integrity), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.u2_procedure",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_u2_procedure),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_u2_procedure), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.u3_rule",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_u3_rule),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_u3_rule), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.u4p_protect",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_u4p_protect),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_u4p_protect), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.u5p_integrity",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_u5p_integrity),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_u5p_integrity), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.u6p_procedure",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_u6p_procedure),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_u6p_procedure), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.u7p_rule",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_u7p_rule),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_u7p_rule), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.u8_invalid",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_u8_invalid),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_u8_invalid), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.u9_fail",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_u9_fail),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_u9_fail), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.u10_private",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_u10_private),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_u10_private), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.u11_shared",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_u11_shared),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_u11_shared), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.f0_relation",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_f0_relation),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_f0_relation), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.f1_integrity",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_f1_integrity),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_f1_integrity), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.f2_procedure",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_f2_procedure),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_f2_procedure), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.f3_protect",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_f3_protect),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_f3_protect), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.f4_rule",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_f4_rule),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_f4_rule), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.l0_private",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_l0_private),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_l0_private), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.l1_private",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_l1_private),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_l1_private), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.l2_supdate",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_l2_supdate),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_l2_supdate), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },
  { 0, "exp.rdf.stat.l3_supdate",
	MO_SIZEOF_MEMBER( RDF_STATISTICS, rds_l3_supdate),
	MO_READ,  0,
	CL_OFFSETOF( RDF_STATISTICS, rds_l3_supdate), MOintget, MOnoset,
	RDF_STATISTICS_ADDR, MOcdata_index },

  { 0 }
};

# define RDI_SVCB_ADDR	    NULL

GLOBALDEF MO_CLASS_DEF rdf_svci_classes[] =
{
  /* READ ONLY */

  { 0, "exp.rdf.rdi.state_num",
	MO_SIZEOF_MEMBER( RDI_SVCB, rdv_state),
	MO_READ,  0,
	CL_OFFSETOF( RDI_SVCB, rdv_state ),
	MOintget, MOnoset,
	RDI_SVCB_ADDR, MOcdata_index },

  { 0, "exp.rdf.rdi.state_str",
	MO_SIZEOF_MEMBER( RDI_SVCB, rdv_state),
	MO_READ,  0,
	CL_OFFSETOF( RDI_SVCB, rdv_state ),
	rdf_state_get, MOnoset,
	RDI_SVCB_ADDR, MOcdata_index },

  { 0, "exp.rdf.rdi.cache.size",
	MO_SIZEOF_MEMBER( RDI_SVCB, rdv_pool_size),
	MO_READ,  0,
	CL_OFFSETOF( RDI_SVCB, rdv_pool_size ),
	MOintget, MOnoset,
	RDI_SVCB_ADDR, MOcdata_index },

  { 0, "exp.rdf.rdi.cache.max_tables",
	MO_SIZEOF_MEMBER( RDI_SVCB, rdv_cnt0_rdesc),
	MO_READ,  0,
	CL_OFFSETOF( RDI_SVCB, rdv_cnt0_rdesc ),
	MOintget, MOnoset,
	RDI_SVCB_ADDR, MOcdata_index },

  { 0, "exp.rdf.rdi.cache.max_qtree_objs",
	MO_SIZEOF_MEMBER( RDI_SVCB, rdv_cnt1_qtree),
	MO_READ,  0,
	CL_OFFSETOF( RDI_SVCB, rdv_cnt1_qtree ),
	MOintget, MOnoset,
	RDI_SVCB_ADDR, MOcdata_index },

  { 0, "exp.rdf.rdi.cache.max_ldb_descs",
	MO_SIZEOF_MEMBER( RDI_SVCB, rdv_cnt2_dist),
	MO_READ,  0,
	CL_OFFSETOF( RDI_SVCB, rdv_cnt2_dist ),
	MOintget, MOnoset,
	RDI_SVCB_ADDR, MOcdata_index },

  { 0, "exp.rdf.rdi.cache.max_defaults",
	MO_SIZEOF_MEMBER( RDI_SVCB, rdv_cnt3_default),
	MO_READ,  0,
	CL_OFFSETOF( RDI_SVCB, rdv_cnt3_default ),
	MOintget, MOnoset,
	RDI_SVCB_ADDR, MOcdata_index },

      /* ------------- startup ------------------ */

  { 0, "exp.rdf.rdi.startup.memory",
	MO_SIZEOF_MEMBER( RDI_SVCB, rdv_in0_memory),
	MO_READ,  0,
	CL_OFFSETOF( RDI_SVCB, rdv_in0_memory ),
	MOintget, MOnoset,
	RDI_SVCB_ADDR, MOcdata_index },

  { 0, "exp.rdf.rdi.startup.max_tables",
	MO_SIZEOF_MEMBER( RDI_SVCB, rdv_in1_max_tables),
	MO_READ,  0,
	CL_OFFSETOF( RDI_SVCB, rdv_in1_max_tables ),
	MOintget, MOnoset,
	RDI_SVCB_ADDR, MOcdata_index },

  { 0, "exp.rdf.rdi.startup.table_columns",
	MO_SIZEOF_MEMBER( RDI_SVCB, rdv_in2_table_columns),
	MO_READ,  0,
	CL_OFFSETOF( RDI_SVCB, rdv_in2_table_columns ),
	MOintget, MOnoset,
	RDI_SVCB_ADDR, MOcdata_index },

  { 0, "exp.rdf.rdi.startup.table_synonyms",
	MO_SIZEOF_MEMBER( RDI_SVCB, rdv_in3_table_synonyms),
	MO_READ,  0,
	CL_OFFSETOF( RDI_SVCB, rdv_in3_table_synonyms),
	MOintget, MOnoset,
	RDI_SVCB_ADDR, MOcdata_index },

  { 0, "exp.rdf.rdi.startup.cache_ddbs",
	MO_SIZEOF_MEMBER( RDI_SVCB, rdv_in4_cache_ddbs),
	MO_READ,  0,
	CL_OFFSETOF( RDI_SVCB, rdv_in4_cache_ddbs ),
	MOintget, MOnoset,
	RDI_SVCB_ADDR, MOcdata_index },

  { 0, "exp.rdf.rdi.startup.avg_ldbs",
	MO_SIZEOF_MEMBER( RDI_SVCB, rdv_in5_average_ldbs),
	MO_READ,  0,
	CL_OFFSETOF( RDI_SVCB, rdv_in5_average_ldbs ),
	MOintget, MOnoset,
	RDI_SVCB_ADDR, MOcdata_index },

  { 0, "exp.rdf.rdi.num.memleft",
	MO_SIZEOF_MEMBER( RDI_SVCB, rdv_memleft),
	MO_READ,  0,
	CL_OFFSETOF( RDI_SVCB, rdv_memleft ),
	MOintget, MOnoset,
	RDI_SVCB_ADDR, MOcdata_index },

  { 0, "exp.rdf.rdi.num.max_sessions",
	MO_SIZEOF_MEMBER( RDI_SVCB, rdv_max_sessions),
	MO_READ,  0,
	CL_OFFSETOF( RDI_SVCB, rdv_max_sessions ),
	MOintget, MOnoset,
	RDI_SVCB_ADDR, MOcdata_index },

  { 0, "exp.rdf.rdi.num.ddbs_caches",
	MO_SIZEOF_MEMBER( RDI_SVCB, rdv_cnt),
	MO_READ,  0,
	CL_OFFSETOF( RDI_SVCB, rdv_cnt ),
	MOintget, MOnoset,
	RDI_SVCB_ADDR, MOcdata_index },

  { 0, "exp.rdf.rdi.num.cluster_nodes",
	MO_SIZEOF_MEMBER( RDI_SVCB, rdv_num_nodes),
	MO_READ,  0,
	CL_OFFSETOF( RDI_SVCB, rdv_num_nodes ),
	MOintget, MOnoset,
	RDI_SVCB_ADDR, MOcdata_index },

  { 0, "exp.rdf.rdi.num.bad_cksums",
	MO_SIZEOF_MEMBER( RDI_SVCB, rdv_bad_cksum_ctr),
	MO_READ,  0,
	CL_OFFSETOF( RDI_SVCB, rdv_bad_cksum_ctr ),
	MOintget, MOnoset,
	RDI_SVCB_ADDR, MOcdata_index },

  { 0, "exp.rdf.rdi.flags.cost_set",
	MO_SIZEOF_MEMBER( RDI_SVCB, rdv_cost_set),
	MO_READ,  0,
	CL_OFFSETOF( RDI_SVCB, rdv_cost_set ),
	MOintget, MOnoset,
	RDI_SVCB_ADDR, MOcdata_index },

  { 0 }
};
