/*
**	Copyright (c) 2004 Ingres Corporation
*/
/*
**	GKS long and short to vms name map
**	
**	This only works if your system handles long names 31 chars
**	in the C compiler, C preprocessor and linker.
**	@(#)gkslong.h	1.3	11/2/85
*/

#ifndef _NAMEMAP

#define _NAMEMAP

#ifndef FLEXNAMES

#define gqnt	GKS$gqnt
#define guwk	GKS$guwk
#define gtx	GKS$gtx
#define gswkwn	GKS$gswkwn
#define gswkvp	GKS$gswkvp
#define gswn	GKS$gswn
#define gsvis	GKS$gsvis
#define gsvpip	GKS$gsvpip
#define gsvp	GKS$gsvp
#define gsvlm	GKS$gsvlm
#define gstxr	GKS$gstxr
#define gsttxp	GKS$gstxp
#define gstxi	GKS$gstxi
#define gstxfp	GKS$gstxfp
#define gstxci	GKS$gstxci
#define gstxal	GKS$gstxal
#define gsskm	GKS$gsskm
#define gsstm	GKS$gsstm
#define gssgt	GKS$gssgt
#define gssgp	GKS$gssgp
#define gspkm	GKS$gspkm
#define gspkid	GKS$gspkid
#define gspa	GKS$gspa
#define gspar	GKS$gspar
#define gsparf	GKS$gsparf
#define gsmk	GKS$gsmk
#define gsmksc	GKS$gsmksc
#define gspmr	GKS$gspmr
#define gspmi	GKS$gspmi
#define gspmci	GKS$gspmci
#define gslcm	GKS$gslcm
#define gslwsc	GKS$gslwsc
#define gsln	GKS$gsln
#define gsplr	GKS$gsplr
#define gspli	GKS$gspli
#define gsplci	GKS$gsplci
#define gshlit	GKS$gshlit
#define gsfasi	GKS$gsfasi
#define gsfar	GKS$gsfar
#define gsfais	GKS$gsfais
#define gsfai	GKS$gsfai
#define gsfaci	GKS$gsfaci
#define gsdtec	GKS$gsdtec
#define gsds	GKS$gsds
#define gscr	GKS$gscr
#define gsclip	GKS$gsclip
#define gschm	GKS$gschm
#define gschup	GKS$gschup
#define gschsp	GKS$gschsp
#define gschh	GKS$gschh
#define gschxp	GKS$gschxp
#define gsasf	GKS$gsasf
#define gselnt	GKS$gselnt
#define grqvl	GKS$grqvl
#define grqsk	GKS$grqsk
#define grqst	GKS$grqst
#define grqpk	GKS$grqpk
#define grqlc	GKS$grqlc
#define grqch	GKS$grqch
#define grensg	GKS$grensg
#define grsgwk	GKS$grsgwk
#define gpm	GKS$gpm
#define gpl	GKS$gpl
#define gopwk	GKS$gopwk
#define gopks	GKS$gopks
#define gqsgt	GKS$gqsgt
#define gqvis	GKS$gqvis
#define gqhlit	GKS$gqhlit
#define gqsgp	GKS$gqsgp
#define gqdet	GKS$gqdet
#define gqpkid	GKS$gqpkid
#define ginsg	GKS$ginsg
#define gqwkt	GKS$gqwkt
#define gqwks	GKS$gqwks
#define gqwkm	GKS$gqwkm
#define gqwkdu	GKS$gqwkdu
#define gqwkc	GKS$gqwkc
#define gqwkcl	GKS$gqwkcl
#define gqwkca	GKS$gqwkca
#define gqwn	GKS$gqwn
#define gqvp	GKS$gqvp
#define gqvls	GKS$gqvls
#define gqtxr	GKS$gqtxr
#define gqtxp	GKS$gqtxp
#define gqltxi	GKS$gqltxi
#define gqtxi	GKS$gqtxi
#define gqtxfp	GKS$gqtxfp
#define gqtxf	GKS$gqtxf
#define gqtxx	GKS$gqtxx
#define gqtxci	GKS$gqtxci
#define gqtxal	GKS$gqtxal
#define gqsks	GKS$gqsks
#define gqsts	GKS$gqsts
#define gqsgwk	GKS$gqsgwk
#define gqsgus	GKS$gqsgus
#define gqptxr	GKS$gqptxr
#define gqppar	GKS$gqppar
#define gqppmr	GKS$gqppmr
#define gqpplr	GKS$gqpplr
#define gqpfar	GKS$gqpfar
#define gqpcr	GKS$gqpcr
#define gqpxad	GKS$gqpxad
#define gqpxa	GKS$gqpxa
#define gqpx	GKS$gqpx
#define gqpks	GKS$gqpks
#define gqpcr	GKS$gqpcr
#define gqpa	GKS$gqpa
#define gqpar	GKS$gqpar
#define gqparf	GKS$gqparf
#define gqlpai	GKS$gqlpai
#define gqpaf	GKS$gqpaf
#define gqops	GKS$gqops
#define gqopwk	GKS$gqopwk
#define gqsgps	GKS$gqsgps
#define gqli	GKS$gqli
#define gqlntn	GKS$gqlntn
#define gqopsg	GKS$gqopsg
#define gqdwka	GKS$gqdwka
#define gqdsga	GKS$gqdsga
#define gqlwk	GKS$gqlwk
#define gqmntn	GKS$gqmntn
#define gqmds	GKS$gqmds
#define gqpmf	GKS$gqpmf
#define gqmk	GKS$gqmk
#define gqmksc	GKS$gqmksc
#define gqpmr	GKS$gqpmr
#define gqlpmi	GKS$gqlpmi
#define gqpmi	GKS$gqpmi
#define gqpmci	GKS$gqpmci
#define gqlcs	GKS$gqlcs
#define gqlwsc	GKS$gqlwsc
#define gqln	GKS$gqln
#define gqplr	GKS$gqplr
#define gqlpli	GKS$gqlpli
#define gqpli	GKS$gqpli
#define gqplf	GKS$gqplf
#define gqplci	GKS$gqplci
#define gqlvks	GKS$gqlvks
#define gqgdp	GKS$gqgdp
#define gqfasi	GKS$gqfasi
#define gqfar	GKS$gqfar
#define gqfais	GKS$gqfais
#define gqlfai	GKS$gqlfai
#define gqfai	GKS$gqfai
#define gqfaf	GKS$gqfaf
#define gqfaci	GKS$gqfaci
#define gqdvl	GKS$gqdvl
#define gqdsk	GKS$gqdsk
#define gqdst	GKS$gqdst
#define gqdpk	GKS$gqdpk
#define gqdlc	GKS$gqdlc
#define gqdds	GKS$gqdds
#define gqdch	GKS$gqdch
#define gqcntn	GKS$gqcntn
#define gqcr	GKS$gqcr
#define gqlci	GKS$gqlci
#define gqcf	GKS$gqcf
#define gqclip	GKS$gqclip
#define gqchs	GKS$gqchs
#define gqchup	GKS$gqchup
#define gqchsp	GKS$gqchsp
#define gqchh	GKS$gqchh
#define gqchxp	GKS$gqchxp
#define gqavwk	GKS$gqavwk
#define gqlgdp	GKS$gqlgdp
#define gqaswk	GKS$gqaswk
#define gqasf	GKS$gqasf
#define gqacwk	GKS$gqacwk
#define ginvl	GKS$ginvl
#define ginsk	GKS$ginsk
#define ginst	GKS$ginst
#define ginpk	GKS$ginpk
#define ginlc	GKS$ginlc
#define ginch	GKS$ginch
#define gfa	GKS$gfa
#define gevtm	GKS$gevtm
#define gesc	GKS$gesc
#define gerlog	GKS$gerlog
#define gerhnd	GKS$gerhnd
#define geclks	GKS$geclks
#define gdsgwk	GKS$gdsgwk
#define gdsg	GKS$gdsg
#define gdacwk	GKS$gdacwk
#define gcrsg	GKS$gcrsg
#define gcsgwk	GKS$gcsgwk
#define gclwk	GKS$gclwk
#define gclsg	GKS$gclsg
#define gclks	GKS$gclks
#define gclrwk	GKS$gclrwk
#define gca	GKS$gca
#define gasgwk	GKS$gasgwk
#define gacwk	GKS$gacwk
#define gactm	GKS$gactm
#define gaptr	GKS$gaptr
#define gshlc	GKS$gshlc
#define gwitm	GKS$gwitm
#define ggtitm	GKS$ggtitm
#define grditm	GKS$grditm
#define giitm	GKS$giitm
#define ggdp	GKS$ggdp
#define gwsid	GKS$gwsid
#define gidws	GKS$gidws

#else

#define gupdatews	GKS$guwk
#define gtext	GKS$gtx
#define gsetwswindow	GKS$gswkwn
#define gsetwsviewport	GKS$gswkvp
#define gsetwindow	GKS$gswn
#define gsetvis	GKS$gsvis
#define gsetviewportpri	GKS$gsvpip
#define gsetviewport	GKS$gsvp
#define gsetvalmode	GKS$gsvlm
#define gsettextrep	GKS$gstxr
#define gsettextpath	GKS$gstxp
#define gsettextindex	GKS$gstxi
#define gsettextfontprec	GKS$gstxfp
#define gsettextcolour	GKS$gstxci
#define gsettextalign	GKS$gstxal
#define gsetstrokemode	GKS$gsskm
#define gsetstringmode	GKS$gsstm
#define gsetsegtran	GKS$gssgt
#define gsetsegpri	GKS$gssgp
#define gsetpickmode	GKS$gspkm
#define gsetpickid	GKS$gspkid
#define gsetpatsize	GKS$gspa
#define gsetpatrep	GKS$gspar
#define gsetpatrefpoint	GKS$gsparf
#define gsetmarkertype	GKS$gsmk
#define gsetmarkersize	GKS$gsmksc
#define gsetmarkerrep	GKS$gspmr
#define gsetmarkerindex	GKS$gspmi
#define gsetmarkercolour	GKS$gspmci
#define gsetlocmode	GKS$gslcm
#define gsetlinewidth	GKS$gslwsc
#define gsetlinetype	GKS$gsln
#define gsetlinerep	GKS$gsplr
#define gsetlineindex	GKS$gspli
#define gsetlinecolour	GKS$gsplci
#define gsethighlight	GKS$gshlit
#define gsetfillstyleindex	GKS$gsfasi
#define gsetfillrep	GKS$gsfar
#define gsetfillintstyle	GKS$gsfais
#define gsetfillindex	GKS$gsfai
#define gsetfillcolour	GKS$gsfaci
#define gsetdet	GKS$gsdtec
#define gsetdeferral	GKS$gsds
#define gsetcolourrep	GKS$gscr
#define gsetclip	GKS$gsclip
#define gsetchoicemode	GKS$gschm
#define gsetcharup	GKS$gschup
#define gsetcharspace	GKS$gschsp
#define gsetcharheight	GKS$gschh
#define gsetcharexp	GKS$gschxp
#define gsetasf	GKS$gsasf
#define gselnormtran	GKS$gselnt
#define greqval	GKS$grqvl
#define greqstroke	GKS$grqsk
#define greqstring	GKS$grqst
#define greqpick	GKS$grqpk
#define greqloc	GKS$grqlc
#define greqchoice	GKS$grqch
#define grenameseg	GKS$grensg
#define gredrawsegws	GKS$grsgwk
#define gpolymarker	GKS$gpm
#define gpolyline	GKS$gpl
#define gopenws	GKS$gopwk
#define gopengks	GKS$gopks
#define ginqsegtran	GKS$gqsgt
#define ginqvis	GKS$gqvis
#define ginqhighlight	GKS$gqhlit
#define ginqsegpri	GKS$gqsgp
#define ginqdet	GKS$gqdet
#define ginqpickid	GKS$gqpkid
#define ginsertseg	GKS$ginsg
#define ginqwstran	GKS$gqwkt
#define ginqwsstate	GKS$gqwks
#define ginqwsmaxnum	GKS$gqwkm
#define ginqwsdeferralupdate	GKS$gqwkdu
#define ginqwsconntype	GKS$gqwkc
#define ginqwsclass	GKS$gqwkcl
#define ginqwscategory	GKS$gqwkca
#define ginqwindow	GKS$gqwn
#define ginqviewport	GKS$gqvp
#define ginqvalstate	GKS$gqvls
#define ginqtextrep	GKS$gqtxr
#define ginqtextpath	GKS$gqtxp
#define ginqtextindices	GKS$gqltxi
#define ginqtextindex	GKS$gqtxi
#define ginqtextfontprec	GKS$gqtxfp
#define ginqtextfac	GKS$gqtxf
#define ginqtextextent	GKS$gqtxx
#define ginqtextcolour	GKS$gqtxci
#define ginqtextalign	GKS$gqtxal
#define ginqstrokestate	GKS$gqsks
#define ginqstringstate	GKS$gqsts
#define ginqsegnamesws	GKS$gqsgwk
#define ginqsegnames	GKS$gqsgus
#define ginqpretextrep	GKS$gqptxr
#define ginqprepatrep	GKS$gqppar
#define ginqpremarkrep	GKS$gqppmr
#define ginqprelinerep	GKS$gqpplr
#define ginqprefillrep	GKS$gqpfar
#define ginqprecolourrep	GKS$gqpcr
#define ginqpixelarraydim	GKS$gqpxad
#define ginqpixelarray	GKS$gqpxa
#define ginqpixel	GKS$gqpx
#define ginqpickstate	GKS$gqpks
#define ginqpdcolourrep	GKS$gqpcr
#define ginqpatsize	GKS$gqpa
#define ginqpatrep	GKS$gqpar
#define ginqpatrefpoint	GKS$gqparf
#define ginqpatindices	GKS$gqlpai
#define ginqpatfac	GKS$gqpaf
#define ginqopstate	GKS$gqops
#define ginqopenws	GKS$gqopwk
#define ginqnumsegpri	GKS$gqsgps
#define ginqnumavailinput	GKS$gqli
#define ginqnormtrannum	GKS$gqlntn
#define ginqnameopenseg	GKS$gqopsg
#define ginqmodws	GKS$gqdwka
#define ginqmodeseg	GKS$gqdsga
#define ginqmaxwstables	GKS$gqlwk
#define ginqmaxnormtrannum	GKS$gqmntn
#define ginqmaxdisplaysize	GKS$gqmds
#define ginqmarkfac	GKS$gqpmf
#define ginqmarkertype	GKS$gqmk
#define ginqmarkersize	GKS$gqmksc
#define ginqmarkerrep	GKS$gqpmr
#define ginqmarkerindices	GKS$gqlpmi
#define ginqmarkerindex	GKS$gqpmi
#define ginqmarkercolour	GKS$gqpmci
#define ginqlocstate	GKS$gqlcs
#define ginqlinewidth	GKS$gqlwsc
#define ginqlinetype	GKS$gqln
#define ginqlinerep	GKS$gqplr
#define ginqlineindices	GKS$gqlpli
#define ginqlineindex	GKS$gqpli
#define ginqlinefac	GKS$gqplf
#define ginqlinecolour	GKS$gqplci
#define ginqlevelgks	GKS$gqlvks
#define ginqgdp	GKS$gqgdp
#define ginqfillstyleindex	GKS$gqfasi
#define ginqfillrep	GKS$gqfar
#define ginqfillintstyle	GKS$gqfais
#define ginqfillindices	GKS$gqlfai
#define ginqfillindex	GKS$gqfai
#define ginqfillfac	GKS$gqfaf
#define ginqfillcolour	GKS$gqfaci
#define ginqdefval	GKS$gqdvl
#define ginqdefstroke	GKS$gqdsk
#define ginqdefstring	GKS$gqdst
#define ginqdefpick	GKS$gqdpk
#define ginqdefloc	GKS$gqdlc
#define ginqdefdeferral	GKS$gqdds
#define ginqdefchoice	GKS$gqdch
#define ginqcurnormtrannum	GKS$gqcntn
#define ginqcolourrep	GKS$gqcr
#define ginqcolourindices	GKS$gqlci
#define ginqcolourfac	GKS$gqcf
#define ginqclip	GKS$gqclip
#define ginqchoicestate	GKS$gqchs
#define ginqcharup	GKS$gqchup
#define ginqcharspace	GKS$gqchsp
#define ginqcharheight	GKS$gqchh
#define ginqcharexp	GKS$gqchxp
#define ginqavailwstypes	GKS$gqavwk
#define ginqavailgdp	GKS$gqlgdp
#define ginqassocws	GKS$gqaswk
#define ginqasf	GKS$gqasf
#define ginqactivews	GKS$gqacwk
#define ginitval	GKS$ginvl
#define ginitstroke	GKS$ginsk
#define ginitstring	GKS$ginst
#define ginitpick	GKS$ginpk
#define ginitloc	GKS$ginlc
#define ginitchoice	GKS$ginch
#define gfillarea	GKS$gfa
#define gevaltran	GKS$gevtm
#define gescape	GKS$gesc
#define gerrorlog	GKS$gerlog
#define gerrorhand	GKS$gerhnd
#define gemergencyclosegks	GKS$geclks
#define gdeletesegws	GKS$gdsgwk
#define gdeleteseg	GKS$gdsg
#define gdeactivatews	GKS$gdacwk
#define gcreateseg	GKS$gcrsg
#define gcopysegws	GKS$gcsgwk
#define gclosews	GKS$gclwk
#define gcloseseg	GKS$gclsg
#define gclosegks	GKS$gclks
#define gclearws	GKS$gclrwk
#define gcellarray	GKS$gca
#define gassocsegws	GKS$gasgwk
#define gactivatews	GKS$gacwk
#define gaccumtran	GKS$gactm
#define gsetpickaptr	GKS$gaptr
#define gsethiliteclr	GKS$gshlc
#define gwritegksm	GKS$gwitm
#define ggetgksm	GKS$ggtitm
#define greadgksm	GKS$grditm
#define ginterpret	GKS$giitm
#define ginqnormtran	GKS$gqnt
#define ggdp	GKS$ggdp
#define gwsid	GKS$gwsid
#define gidws	GKS$gidws

#endif /* FLEXNAMES */
#endif /* _NAMEMAP */
