.PU
.TH ACHILLES 1 local
.SH NAME
achilles \- Stress Test program driver.
.SH SYNOPSIS
.ll +8
.B achilles -d dbname -f cfg --o outdir -a duration
.ll -8

.SH DESCRIPTION
Achilles is used with stress testing to driver various test programs.
.PP
The exit status is normally 0;
if an error occurs, the exit status is 1.
.SH "SEE ALSO"
.SH "DIAGNOSTICS"
