//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingres.Client.Design {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ingres.Client.Design.resources", typeof(resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        internal static string RESX_Category_DataType {
            get {
                return ResourceManager.GetString("RESX_Category_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Identifier).
        /// </summary>
        internal static string RESX_Category_Identifier {
            get {
                return ResourceManager.GetString("RESX_Category_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to the Ingres database using the .NET Framework Data Provider for Ingres..
        /// </summary>
        internal static string RESX_DataProvider_Description {
            get {
                return ResourceManager.GetString("RESX_DataProvider_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework Data Provider 2.1 for Ingres.
        /// </summary>
        internal static string RESX_DataProvider_DisplayName {
            get {
                return ResourceManager.GetString("RESX_DataProvider_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingres .NET Data Provider 2.1.
        /// </summary>
        internal static string RESX_DataProvider_ShortName {
            get {
                return ResourceManager.GetString("RESX_DataProvider_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string RESX_DataView_Tables {
            get {
                return ResourceManager.GetString("RESX_DataView_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string RESX_DataView_Views {
            get {
                return ResourceManager.GetString("RESX_DataView_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the column in the Ingres table..
        /// </summary>
        internal static string RESX_Description_ColumnName {
            get {
                return ResourceManager.GetString("RESX_Description_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ingres owner&apos;s username of the table that contains the column..
        /// </summary>
        internal static string RESX_Description_ColumnSchema {
            get {
                return ResourceManager.GetString("RESX_Description_ColumnSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Ingres table containing the column..
        /// </summary>
        internal static string RESX_Description_ColumnTable {
            get {
                return ResourceManager.GetString("RESX_Description_ColumnTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the default, if the column has one, which is inserted into the column automatically if no value is specified during an insert operation..
        /// </summary>
        internal static string RESX_Description_Default {
            get {
                return ResourceManager.GetString("RESX_Description_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length in characters for a character data type or the length in bytes for a binary data type.  Otherwise, 0..
        /// </summary>
        internal static string RESX_Description_Length {
            get {
                return ResourceManager.GetString("RESX_Description_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to true if the application can set the column to a null value or if the data provider cannot determine if the application can set the column to a null value. Set to false if it is known that the application is not permitted to set the column to a null. Note that a column value may be null even if the application is not permitted to set the null value..
        /// </summary>
        internal static string RESX_Description_Nullable {
            get {
                return ResourceManager.GetString("RESX_Description_Nullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of the column in the object&apos;s create statement, beginning with 1..
        /// </summary>
        internal static string RESX_Description_Ordinal {
            get {
                return ResourceManager.GetString("RESX_Description_Ordinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum precision of the column if the column is a numeric or date data type..
        /// </summary>
        internal static string RESX_Description_Precision {
            get {
                return ResourceManager.GetString("RESX_Description_Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of decimal places in the column if the column is a numeric data type..
        /// </summary>
        internal static string RESX_Description_Scale {
            get {
                return ResourceManager.GetString("RESX_Description_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The native Ingres data type..
        /// </summary>
        internal static string RESX_Description_SystemType {
            get {
                return ResourceManager.GetString("RESX_Description_SystemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Ingres table..
        /// </summary>
        internal static string RESX_Description_TableName {
            get {
                return ResourceManager.GetString("RESX_Description_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ingres owner&apos;s username that is the creator of this table..
        /// </summary>
        internal static string RESX_Description_TableSchema {
            get {
                return ResourceManager.GetString("RESX_Description_TableSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the column in the Ingres view..
        /// </summary>
        internal static string RESX_Description_ViewColumnName {
            get {
                return ResourceManager.GetString("RESX_Description_ViewColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ingres owner&apos;s username of the view that contains the column..
        /// </summary>
        internal static string RESX_Description_ViewColumnSchema {
            get {
                return ResourceManager.GetString("RESX_Description_ViewColumnSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Ingres view containing the column..
        /// </summary>
        internal static string RESX_Description_ViewColumnTable {
            get {
                return ResourceManager.GetString("RESX_Description_ViewColumnTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Ingres view..
        /// </summary>
        internal static string RESX_Description_ViewName {
            get {
                return ResourceManager.GetString("RESX_Description_ViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ingres owner&apos;s username that is the creator of this view..
        /// </summary>
        internal static string RESX_Description_ViewSchema {
            get {
                return ResourceManager.GetString("RESX_Description_ViewSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        internal static string RESX_Property_Default {
            get {
                return ResourceManager.GetString("RESX_Property_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string RESX_Property_Length {
            get {
                return ResourceManager.GetString("RESX_Property_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string RESX_Property_Name {
            get {
                return ResourceManager.GetString("RESX_Property_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable.
        /// </summary>
        internal static string RESX_Property_Nullable {
            get {
                return ResourceManager.GetString("RESX_Property_Nullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinal.
        /// </summary>
        internal static string RESX_Property_Ordinal {
            get {
                return ResourceManager.GetString("RESX_Property_Ordinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision.
        /// </summary>
        internal static string RESX_Property_Precision {
            get {
                return ResourceManager.GetString("RESX_Property_Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string RESX_Property_Scale {
            get {
                return ResourceManager.GetString("RESX_Property_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        internal static string RESX_Property_Schema {
            get {
                return ResourceManager.GetString("RESX_Property_Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Type.
        /// </summary>
        internal static string RESX_Property_SystemType {
            get {
                return ResourceManager.GetString("RESX_Property_SystemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string RESX_Property_Table {
            get {
                return ResourceManager.GetString("RESX_Property_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string RESX_Property_View {
            get {
                return ResourceManager.GetString("RESX_Property_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string RESX_Type_Table {
            get {
                return ResourceManager.GetString("RESX_Type_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Column.
        /// </summary>
        internal static string RESX_Type_TableColumn {
            get {
                return ResourceManager.GetString("RESX_Type_TableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string RESX_Type_View {
            get {
                return ResourceManager.GetString("RESX_Type_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Column.
        /// </summary>
        internal static string RESX_Type_ViewColumn {
            get {
                return ResourceManager.GetString("RESX_Type_ViewColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingres.
        /// </summary>
        internal static string RESX_Value_Ingres {
            get {
                return ResourceManager.GetString("RESX_Value_Ingres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string RESX_Value_No {
            get {
                return ResourceManager.GetString("RESX_Value_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string RESX_Value_Yes {
            get {
                return ResourceManager.GetString("RESX_Value_Yes", resourceCulture);
            }
        }
    }
}
