//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by dp.rc
//
#define IDS_DIALOGFAILURE               1
#define IDS_STRUCTSIZE                  2
#define IDS_INITIALIZATION              3
#define IDS_NOTEMPLATE                  4
#define IDS_NOHINSTANCE                 5
#define IDS_LOADSTRFAILURE              6
#define IDS_FINDRESFAILURE              7
#define IDS_LOADRESFAILURE              8
#define IDS_LOCKRESFAILURE              9
#define IDS_MEMALLOCFAILURE             10
#define IDS_MEMLOCKFAILURE              11
#define IDS_NOHOOK                      12
#define IDS_SETUPFAILURE                13
#define IDS_PARSEFAILURE                14
#define IDS_RETDEFFAILURE               15
#define IDS_LOADDRVFAILURE              16
#define IDS_GETDEVMODEFAIL              17
#define IDS_INITFAILURE                 18
#define IDS_NODEVICES                   19
#define IDS_NODEFAULTPRN                20
#define IDS_DNDMMISMATCH                21
#define IDS_CREATEICFAILURE             22
#define IDS_PRINTERNOTFOUND             23
#define IDS_NOFONTS                     24
#define IDS_SUBCLASSFAILURE             25
#define IDS_INVALIDFILENAME             26
#define IDS_BUFFERTOOSMALL              27
#define IDS_UNKNOWNERROR                29
#define IDS_TITLE                       30
#define IDS_INVALID_STRUCTNAME          31
#define IDS_WAIT_HEADING                32
#define IDS_FAIL_HEADING                33
#define IDS_SUCCESS_HEADING             34
#define IDS_NO_IISYSTEM                 35
#define IDS_NO_FILEEXIST                36
#define IDS_INVALID_AUTH                37
#define IDS_INVALID_AUTH2               38
#define IDS_NO_DBNAME                   39
#define IDS_NEED_CONNUSER               40
#define IDS_NEED_TABLES                 41
#define IDS_NEED_FILES                  42
#define IDS_BAD_FILEEDIT                43
#define IDS_NEED_OUTFILE                44
#define IDS_NEED_ERRFILE                45
#define IDS_NEED_OPTFILE                46
#define IDS_NEED_SQLFILE                47
#define IDS_AUTH_HEADER                 48
#define IDS_AUTH_TITLE                  49
#define IDS_FILENAME_HEADER             50
#define IDS_BUTTON_BROWSE               51
#define IDS_OK                          52
#define IDS_CANCEL                      53
#define IDS_TBNAME_HEADING              54
#define IDS_BUTTON_ERRFILE              55
#define IDS_LOC_HEADING                 56
#define IDS_RADIO_CONNECT               57
#define IDS_GROUP_CONNECT               58
#define IDS_DB_NAME                     59
#define IDS_CONN_ID                     60
#define IDS_BUTON_ADD                   61
#define IDS_BUTTON_DELETE               62
#define IDS_RADIO_FILE                  63
#define IDS_GROUP_FILEINFO              64
#define IDS_OPTIONS2_HEADING            65
#define IDS_CHECK_BS                    66
#define IDS_CHECK_FF                    67
#define IDS_CHECK_OF                    68
#define IDS_CHECK_MS                    69
#define IDC_IPEDIT                      101
#define IDC_IPSPIN                      102
#define IDD_AUTH_PAGE                   103
#define IDD_SPLASH                      104
#define IDD_LOC_PAGE                    105
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_FILENAME             131
#define IDD_OPTIONS_PAGE                132
#define IDD_DIALOG_TBNAME               133
#define IDD_OPTIONS2_PAGE               134
#define IDD_OPTIONS3_PAGE               135
#define IDD_OPTIONS4_PAGE               136
#define IDD_WAIT_DIALOG                 137
#define IDR_CLOCK_AVI                   138
#define IDD_FAIL_DIALOG                 138
#define IDI_ICON_EXCL                   139
#define IDD_SUCCESS_DIALOG              139
#define IDI_ICON_INFO                   140
#define IDC_IMAGE                       1000
#define IDC_EDIT_AUTH                   1001
#define IDC_RADIO_CONNECT               1002
#define IDC_EDIT_DBNAME                 1003
#define IDC_RADIO_FILE                  1005
#define IDC_LIST_FILES                  1008
#define IDC_LIST_TABLES                 1009
#define IDC_BUTTON_DELETE               1013
#define IDC_BUTTON_ADD                  1014
#define IDC_EDIT_FILENAME               1015
#define IDC_BUTTON_DELETE2              1015
#define IDC_BUTTON_BROWSE               1016
#define IDC_BUTTON_ADD2                 1016
#define IDC_EDIT_OUTPUT_LOG             1017
#define IDC_EDIT_ERROR_LOG              1018
#define IDC_EDIT_OPTIONS_LOG            1019
#define IDC_EDIT_SQL_COPY               1020
#define IDC_EDIT_STRUCTNAME             1022
#define IDC_EDIT_USERID                 1023
#define IDC_CHECK_PN                    1024
#define IDC_EDIT_MODPAGES               1025
#define IDC_SPIN1                       1026
#define IDC_SPIN_MODPAGES               1026
#define IDC_CHECK_RE                    1027
#define IDC_COMBO_VERSION               1029
#define IDC_CHECK_II                    1030
#define IDC_COMBO_II                    1031
#define IDC_CHECK_TS                    1032
#define IDC_EDIT_NUMPAGES               1033
#define IDC_CHECK_RW                    1034
#define IDC_EDIT_NUMBYTES               1035
#define IDC_CHECK_LB                    1037
#define IDC_EDIT_LOGSIZE                1038
#define IDC_CHECK_PB                    1039
#define IDC_EDIT_START                  1040
#define IDC_CHECK_PE                    1041
#define IDC_EDIT_END                    1042
#define IDC_CHECK_PS                    1043
#define IDC_COMBO_PAGESIZE              1045
#define IDC_CHECK_TP                    1046
#define IDC_CHECK_OT                    1047
#define IDC_CHECK_OS                    1048
#define IDC_CHECK_OM                    1049
#define IDC_EDIT_TRACEPT                1051
#define IDC_SPIN2                       1052
#define IDC_BUTTON_OUTFILE              1053
#define IDC_BUTTON_ERRFILE              1054
#define IDC_BUTTON_OPTFILE              1055
#define IDC_BUTTON_SQLFILE              1056
#define IDC_CHECK_HC                    1057
#define IDC_CHECK_CK8                   1058
#define IDC_CHECK_CK5                   1059
#define IDC_CHECK_CK6                   1060
#define IDC_CHECK_CK4                   1061
#define IDC_CHECK_CK0                   1062
#define IDC_CHECK_CK1                   1063
#define IDC_CHECK_CK2                   1064
#define IDC_CHECK_CK3                   1065
#define IDC_CHECK_CK7                   1066
#define IDC_CHECK_SQLFILE               1067
#define IDC_CHECK_OPTFILE               1068
#define IDC_CHECK_ERRFILE               1069
#define IDC_CHECK_OUTFILE               1070
#define IDC_CHECK_OD                    1071
#define IDC_CHECK_OK                    1072
#define IDC_CHECK_OH                    1073
#define IDC_CHECK_FX                    1074
#define IDC_CHECK_BG79416RW             1075
#define IDC_CHECK_BG79416RO             1076
#define IDC_CHECK_MH                    1077
#define IDS_CHECK_BG79416RO             1077
#define IDC_CHECK_OF                    1078
#define IDS_CHECK_BG79416RW             1078
#define IDC_CHECK_FF                    1079
#define IDS_CHECK_FX                    1079
#define IDC_CHECK_BS                    1080
#define IDS_CHECK_OH                    1080
#define IDS_CHECK_OK                    1081
#define IDC_AVI                         1082
#define IDS_CHECK_OD                    1082
#define IDC_WAIT_HEADING                1083
#define IDS_CHECK_OT                    1083
#define IDS_CHECK_OS                    1084
#define IDS_CHECK_OM                    1085
#define IDC_FAIL_HEADING                1086
#define IDS_OPTIONS3_HEADING            1086
#define IDC_SUCCESS_HEADING             1087
#define IDS_CHECK_CK0                   1087
#define IDS_CHECK_CK1                   1088
#define IDC_AUTH_HEADER                 1089
#define IDS_CHECK_CK2                   1089
#define IDC_AUTH_TITLE                  1090
#define IDS_CHECK_CK3                   1090
#define IDC_FILENAME_HEADER             1091
#define IDS_CHECK_CK4                   1091
#define IDC_TBNAME_HEADING              1092
#define IDS_CHECK_CK5                   1092
#define IDC_LOC_HEADING                 1093
#define IDS_CHECK_CK6                   1093
#define IDC_GROUP_CONNECT               1094
#define IDS_CHECK_CK7                   1094
#define IDC_DB_NAME                     1095
#define IDS_CHECK_CK8                   1095
#define IDC_CONN_ID                     1096
#define IDS_CHECK_HC                    1096
#define IDC_GROUP_FILEINFO              1097
#define IDS_OPTIONS4_HEADING            1097
#define IDC_OPTIONS2_HEADING            1098
#define IDS_CHECK_OUTFILE               1098
#define IDC_OPTIONS3_HEADING            1099
#define IDS_CHECK_ERRFILE               1099
#define IDC_OPTIONS4_HEADING            1100
#define IDS_CHECK_OPTFILE               1100
#define IDS_CHECK_SQLFILE               1101
#define IDC_OPTIONS_HEADING             1101
#define IDS_BUTTON_OUTFILE              1102
#define IDS_BUTTON_ERRFILE2             1103
#define IDS_BUTTON_OPTFILE              1104
#define IDS_BUTTON_SQLFILE              1105
#define IDS_OPTIONS_HEADING             1106
#define IDS_CHECK_RE                    1107
#define IDS_CHECK_PN                    1108
#define IDS_CHECK_II                    1109
#define IDS_CHECK_TS                    1110
#define IDS_CHECK_RW                    1111
#define IDS_CHECK_LB                    1112
#define IDS_CHECK_PB                    1113
#define IDS_CHECK_PE                    1114
#define IDS_CHECK_PS                    1115
#define IDS_CHECK_TP                    1116
#define IDS_BUTTON_OUTFILE2             1117
#define IDS_BAD_NUMPAGES                1118

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
