/*
**	Copyright (c) 2004 Ingres Corporation
**	All rights reserved.
*/

# include	<compat.h>
# include	<gl.h>
# include	<sl.h>
# include	<iicommon.h>
# include	<fe.h>
# include	<ft.h>
# include	<fmt.h>
# include	<adf.h>
# include	<frame.h>
# include	<menu.h>
# include	<runtime.h> 
# include	<rtvars.h>

/**
** Name:	iichkfld.c
**
** Description:
**	Validate a field in the current frame.  This is used when
**	in a VALIDATE FIELD statement.
**
**	Public (extern) routines defined:
**		IIvalfld()
**	Private (static) routines defined:
**
** History:
**	22-feb-1983  -  Extracted from original runtime.c (jen)
**	21-jan-1999 (hanch04)
**	    replace nat and longnat with i4
**	31-aug-2000 (hanch04)
**	    cross change to main
**	    replace nat and longnat with i4
**	24-Aug-2009 (kschendel) 121804
**	    Update some of the function declarations to fix gcc 4.3 problems.
**/

/*{
** Name:	IIvalfld	-	Validate a field
**
** Description:
**	A call to this routine is generated by a "##VALIDATE FIELD"
**	statement.
**
**	Uses the name of the field provided by the caller, assumes it
**	is in the currently displayed form.  Actual validation is
**	done differently depending on the 'mode' of the form (i.e.
**	query mode is special).
**
**	This routine is part of RUNTIME's external interface.
**	
** Inputs:
**	strvar		Name of the field to validate
**
** Outputs:
**
** Returns:
**	i4	TRUE
**		FALSE
**
** Exceptions:
**	none
**
** Example and Code Generation:
**	## validate field f1
**
**	if (IIvalfld("f1") == 0) goto IIfdBegin1;
**
** Side Effects:
**
** History:
*/

IIvalfld(strvar)
char	*strvar;
{
	FRAME	*frm;
	char	*name;
	char	fbuf[MAXFRSNAME+1];

	/*
	**	Check all variables make sure they are valid.
	**	Also check to see that the forms system has been
	**	initialized and that there is a current frame.
	*/
	if (strvar == NULL)
		return(FALSE);

	name = IIstrconv(II_CONV, strvar, fbuf, (i4)MAXFRSNAME);
	
	if (!RTchkfrs(IIstkfrm))
		return (FALSE);

	/*
	**	Make a call to the frame driver routine that checks the
	**	field.  This routine differs depending on the mode that
	**	the frame driver is in.  QUERY mode must check fields
	**	differently.
	*/
	frm = IIstkfrm->fdrunfrm;
	if (IIstkfrm->fdrunmd == fdrtQRY)
	{
		return (FDckqfld(frm, name));
	}
	else
	{
		return (FDckffld(frm, name));
	}
}

