/*
**	Copyright (c) 2004 Ingres Corporation
**	All rights reserved.
*/

# include	<compat.h>
# include	<gl.h>
# include	<sl.h>
# include	<iicommon.h>
# include	<fe.h>
# include	<ft.h>
# include	<fmt.h>
# include	<adf.h>
# include	<frame.h>
# include	<menu.h>
# include	<runtime.h> 
# include	<rtvars.h>

/**
**	IIchkfrm.c - Validate all the fields in the frame.
**	
**	Validate all the fields in the current frame.  This is used when
**	an enddisplay has been called or in a VALIDATE statement.
**
**	History:
**		22-feb-1983  -  Extracted from original runtime.c (jen)
**	21-jan-1999 (hanch04)
**	    replace nat and longnat with i4
**	31-aug-2000 (hanch04)
**	    cross change to main
**	    replace nat and longnat with i4
**/


/*{
** Name:	IIchkfrm	-	Validate all fields in frame
**
** Description:
**	A call to this routine is generated by a ## VALIDATE statement
**	or by a ## ENDDISPLAY statement.  It will validate all
**	fields in the frame by calling the appropriate FRAME routine
**	depending on the mode of the form.
**
**	This routine is part of RUNTIME's external interface.
**
** Inputs:
**
** Outputs:
**
** Returns:
**	i4	TRUE
**		FALSE
**
** Exceptions:
**	none
**
** Side Effects:
**
** History:
**	?????
*/

IIchkfrm()
{
	FRAME	*frm;

	/*
	**	Check to see that the forms system has been
	**	initialized and that there is a current frame.
	*/
	if (!RTchkfrs(IIstkfrm))
		return (FALSE);

	/*
	**	Make a call to the frame driver routine that checks all
	**	fields.  This routine differs depending on the mode that
	**	the frame driver is in.  QUERY mode must check fields
	**	differently.
	*/
	frm = IIstkfrm->fdrunfrm;
	if (IIstkfrm->fdrunmd == fdrtQRY)
	{
		return(FDchkqry(frm));
	}
	else
	{
		return(FDchkfrm(frm));
	}
}
