/*
**	iiclrscr.c
**
**	Copyright (c) 2004 Ingres Corporation
**	All rights reserved.
*/

# include	<compat.h>
# include	<gl.h>
# include	<sl.h>
# include	<iicommon.h>
# include	<fe.h>
# include	<ft.h>
# include	<fmt.h>
# include	<adf.h>
# include	<frame.h>
# include	<menu.h>
# include	<runtime.h>
# include	<si.h>
# include	<er.h>
# include	<rtvars.h>
# include	<lqgdata.h>

/**
** Name:	iiclrscr.c	-	clear the screen
**
** Description:
**
**
** History:
**	22-feb-1983  -  Extracted from original runtime.c (jen)
**	08/14/87 (dkh) - ER changes.
**	11/02/90 (dkh) - Replaced IILIBQgdata with IILQgdata().
**	21-jan-1999 (hanch04)
**	    replace nat and longnat with i4
**	31-aug-2000 (hanch04)
**	    cross change to main
**	    replace nat and longnat with i4
**/

/*{
** Name:	IIclrscr	-	Clear the screen
**
** Description:
**	Clears the screen.  A call to this routine is generated by
**	the EQUEL '## CLEAR SCREEN' statement.
**
**	This routine is part of RUNTIME's external interface.
**	
** Inputs:
**
** Outputs:
**
** Returns:
**	i4	TRUE
**		FALSE
**
** Exceptions:
**	none
**
** Example and Code Generation:
**	## clear screen
**
**	IIclrscr();
**
** Side Effects:
**
** History:
**
*/

IIclrscr()
{
	i4	i;

	if(!IILQgdata()->form_on)
	{
		for (i = 0; i < 24; i++);
			SIfprintf(stdout, ERx("\n"));
	}
	else
	{
		FTclear();
	}

	if (IIstkfrm)
	{
		IIstkfrm->fdrunfrm->frmflags |= fdREDRAW;
	}
}
