/*
**	iigotofld.c
**
**	Copyright (c) 2004 Ingres Corporation
**	All rights reserved.
*/

# include	<compat.h>
# include	<gl.h>
# include	<sl.h>
# include	<iicommon.h>
# include	<fe.h>
# include	<ft.h>
# include	<fmt.h>
# include	<adf.h>
# include	<frame.h>
# include	<menu.h>
# include	<runtime.h>
# include	<frserrno.h>
# include	<rtvars.h>
# include       <er.h>

/**
** Name:	iigotofld.c
**
** Description:
**
**	Public (extern) routines defined:
**		IIresfld()	-	Resume to a specified field
**
**	Private (static) routines defined:
**
** History:
**	22-feb-1983  -  Extracted from original runtime.c (jen)
**	08/26/87 (dkh) - Changes for 8000 series error numbers.
**	09/01/87 (dkh) - Added explicit include of <frserrno.h>.
**	21-mar-94 (smc) Bug #60829
**		Added #include header(s) required to define types passed
**		in prototyped external function calls.
**	21-jan-1999 (hanch04)
**	    replace nat and longnat with i4
**	31-aug-2000 (hanch04)
**	    cross change to main
**	    replace nat and longnat with i4
**	24-Aug-2009 (kschendel) 121804
**	    Update some of the function declarations to fix gcc 4.3 problems.
**/

/*{
** Name:	IIresfld	-	Resume to a field
**
** Description:
**	A call to this routine is generated by the EQUEL '## RESUME FIELD'
**	statement.  Sets the 'next' field in the frame to be the named
**	field by calling FDgotofld.
**
**	This routine is part of RUNTIME's external interface.
**	
** Inputs:
**	strvar		Name of the field to resume to
**
** Outputs:
**
** Returns:
**	i4	TRUE	
**		FALSE
**
** Exceptions:
**	none
**
** Example and Code Generation:
**	## resume field f1
**
**	IIresfld("f1");
**	goto IIfdBegin1;
**
** Side Effects:
**
** History:
**	
*/

IIresfld(strvar)
char	*strvar;
{
	char	*name;
	char		fbuf[MAXFRSNAME+1];

	/*
	**	Check all variables make sure they are valid.
	**	Also check to see that the forms system has been
	**	initialized and that there is a current frame.
	*/
	if (strvar == NULL)
		return(FALSE);

	name = IIstrconv(II_CONV, strvar, fbuf, (i4)MAXFRSNAME);
	
	if (!RTchkfrs(IIstkfrm))
		return (FALSE);

	if(FDgotofld(IIstkfrm->fdrunfrm, name) == TRUE)
		return (TRUE);
	else
	{
		/* BUG 1764 - Print error if cannot resume on field */
		IIFDerror(RTRESFLD, 1, name);
		return (FALSE);
	}
}
