//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by svriia.rc
//
#define IDS_TITLE_IMPORT                1
#define IDS_TITLE_EXPORT                2
#define IDS_OWNERxITEM                  3
#define IDS_TABLE_EMPTY                 4
#define IDS_COPY                        5
#define IDS_COPY_WITH_TEMPORARY_FILE    6
#define IDS_TABLE_EMPTY_NOT             7
#define IDS_COLUMN_LAYOUT               8
#define IDS_INPUTTABLE_CHARACTERISTICS  9
#define IDS_HEADER_SEPARATORS           10
#define IDS_HEADER_TEXTQUALIFIER        11
#define IDS_HEADER_CS_ASONE             12
#define IDS_HEADER_LINE_NUMBER          13
#define IDS_HEADER_LINE_TEXT            14
#define IDS_IIA_STEP_1                  15
#define IDS_IIA_STEP_2                  16
#define IDS_IIA_STEP_3                  17
#define IDS_IIA_STEP_4                  18
#define IDS_IEA_STEP_1                  19
#define IDS_IEA_STEP_2                  20
#define IDS_EXPORT_CSV                  50
#define IDS_EXPORT_DBF                  51
#define IDS_EXPORT_FIXED                52
#define IDS_EXPORT_COPY                 53
#define IDS_EXPORT_XML                  54
#define IDS_EXPORT_2_CSV                60
#define IDS_EXPORT_2_XML                61
#define IDS_EXPORT_2_DBF                62
#define IDS_EXPORT_2_FIXED              63
#define IDS_EXPORT_2_COPY               64
#define IDS_INGRES_COLUMN_NAME          100
#define IDS_INGRES_COLUMN_TYPE          101
#define IDS_INGRES_COLUMN_LENGTH        102
#define IDS_INGRES_COLUMN_NULLABILITY   103
#define IDD_PROPPAGE1                   104
#define IDS_INGRES_COLUMN_DEFAULT       104
#define IDD_PROPPAGE2                   105
#define IDS_SOURCE_FILE_FORMAT          105
#define IDD_PROPPAGE3                   106
#define IDS_NOT_IMPORTED                106
#define IDD_PROPPAGE4                   107
#define IDS_SOURCE_DATA                 107
#define IDS_MULTIPLE_TEXT_QUALIFIER     108
#define IDS_CONFIRM_CHOICE_WITH_CHECKBOX 109
#define IDS_FAIL_TO_CALCULATE_FILE_SIZE 110
#define IDS_ALREADY_IMPORT_ROWS         111
#define IDS_ALREADY_IMPORT_BYTES        112
#define IDS_SCANNING_FILE_ERROR         113
#define IDS_UNSUPPORT_DBF_FILE          114
#define IDS_UNSUPPORT_DBF_WITH_MEMO     115
#define IDS_COLUMNCOUNT_ERROR_IN_DBFxTABLE 116
#define IDS_UNSUPPORT_DBF_DATATYPE      117
#define IDS_FAIL_TO_OPEN_FILE           118
#define IDS_LINE_TOO_LONG_ERROR         119
#define IDS_FAIL_TO_INITIALIZE_TABLES   120
#define IDS_LOADPARAM_ERR_FILE_NOT_EXIST 121
#define IDS_LOADPARAM_ERR_STEP1_NO_MATCH 122
#define IDS_LOADPARAM_ERR_NO_MATCH_SOLUTION 123
#define IDS_LOADPARAM_ERR_NO_MATCH_FORMAT 124
#define IDS_LOADPARAM_ERR_NO_MATCH_COLUMN_COUNT 125
#define IDS_LOADPARAM_ERR_NO_MATCH_COLUMN_LAYOUT 126
#define IDS_SELECT_PARAM_FILE           127
#define IDS_TOO_MANY_FORMAT1            128
#define IDS_TOO_MANY_FORMAT2            129
#define IDS_NO_TEXT_QUALIFIERxPARTIAL_SCAN 130
#define IDS_NO_CONSECUTIVE_SEPARATORxPARTIAL_SCAN 131
#define IDS_FAIL_TO_CONSTRUCT_FORMAT_IDENTIFICATION 132
#define IDS_FAIL_TO_CHECK_FILE_STATUS   133
#define IDS_PLEASE_SELECT_FILE_TO_IMPORT 134
#define IDS_FILE_TO_IMPORT_NOT_EXIST    135
#define IDS_FILE_HAS_NO_CRLF            136
#define IDS_PLEASE_SELECT_TABLE         137
#define IDS_PLEASE_ENTER_TABLE_NAME     138
#define IDS_RECORD_EXCEEDS_FIXWIDTH_LIMIT 139
#define IDS_NOT_PROPOSE_AMBIGEOUS_FIXEDWIDTH 140
#define IDS_CHECK_ONEOF_PROPOSED_SOLUTION 141
#define IDS_FIXEDWIDTH_COLUMNxNOT_MATCH_TABLE_COLUMNS 142
#define IDS_FILE_HAS_NO_RECORDS         143
#define IDS_REJECTED_INFO1              144
#define IDS_REJECTED_INFO2              145
#define IDS_NEWTABLE_NEEDS_COLUMNS      146
#define IDS_COLUMN_NEEDS_LENGTH1        147
#define IDS_COLUMN_NEEDS_LENGTH2        148
#define IDS_COLUMN_NEEDS_LENGTH3        149
#define IDS_COLUMN_NEEDS_LENGTH4        150
#define IDS_DUPLICATE_COLUMN_NAME       151
#define IDS_PLEASE_SPECIFY_AT_LEAST_1COLUMN 152
#define IDS_COLUMN_HAS_TOOSHORT_LEN     153
#define IDS_EMPTY_TABLE                 154
#define IDS_NOT_EMPTY_TABLE             155
#define IDS_IMPORT_OPERATION_CANCELLED  156
#define IDS_FAIL_TO_LOAD_DLL            157
#define IDS_IMPORT_OPERATION_CUCCESS    158
#define IDS_IMPORT_OPERATION_INTERRUPTxCOMMIT 159
#define IDS_IMPORT_OPERATION_INTERRUPTxROLLBACK 160
#define IDS_IMPORT_OPERATION_INTERRUPTxCONFIRM1 161
#define IDS_IMPORT_OPERATION_INTERRUPTxCONFIRM2 162
#define IDS_SQLCOPY_RETURN_SMALL_LEN    163
#define IDS_INTERRUPT_KILL_TASK         164
#define IDS_SCROLL_TOLINE               165
#define IDS_TASK_NOT_RESPOND1           166
#define IDS_TASK_NOT_RESPOND2           167
#define IDS_IMPORT_ANOTHER_FILE         168
#define IDS_IMPORT_OPERATION_INTERRUPTxCONFIRM3 169
#define IDS_IMPORT_OPERATION_INTERRUPTxCONFIRM4 170
#define IDS_IMPORT_OPERATION_INTERRUPTxCOMMIT2 171
#define IDS_IMPORT_ERRORxPARTIAL_COMMIT 172
#define IDS_IMPORT_OPERATION_STOPPED    173
#define IDS_QUERYING_RECORD_NofP        174
#define IDS_INTERRUPT_DETECTING         175
#define IDS_ANIMATE_TITLE_DETECTING     176
#define IDS_ANIMATE_TITLE_QUERYING      177
#define IDS_ANIMATE_TITLE_IMPORTING     178
#define IDS_STOP_QUERYING_RECORD        179
#define IDS_HEADER_IGNORE_TS            180
#define IDS_TABLE_WRONGDESC             182
#define IDS_STOP_QUERYING_RECORD2       183
#define IDS_COLUMN_LAYOUT2              184
#define IDS_LOADPARAM_ERR_STEP4_COPYOPTION 185
#define IDS_DBF_NOT_SUPPORTED           186
#define IDS_DELIMITER_COMMA             187
#define IDS_DELIMITER_SEMICOLON         188
#define IDS_QUOTE_SINGLE                189
#define IDS_QUOTE_DOUBLE                190
#define IDS_MSG_SELECT_DATABASE         191
#define IDS_MSG_SPECIFY_SELECT          192
#define IDS_MSG_SPECIFY_EXPORT_FILE     193
#define IDS_MSG_WRONG_EXTxFORMAT        194
#define IDS_MSG_FAIL_2_CREATE_SQLASSISTANT 195
#define IDS_MSG_FAIL_2_QUERY_SQLASSISTANT_INF 196
#define IDS_MSG_DBFEXPORT_EXCEED_COLUMNSIZE 197
#define IDS_MSG_DBFEXPORT_EXCEED_RECORDSIZE 198
#define IDS_MSG_DBFEXPORT_TRUNCATE_COLUMNNAME 199
#define IDS_MSG_SELECT_EXPORT_PARAM_FILE 200
#define IDC_COMBO1                      201
#define IDC_CHECK1                      201
#define IDD_PROPPAGE_FORMAT_DBF         201
#define IDS_MSG_NOROWS_TO_EXPORT        201
#define IDC_BUTTON1                     202
#define IDC_CHECK2                      202
#define IDD_PROPPAGE_FORMAT_FIX         202
#define IDS_MSG_INTERRUPT_EXPORT        202
#define IDC_CHECK3                      203
#define IDD_PROPPAGE_FORMAT_CSV         203
#define IDS_FETCH_EXPORTING             203
#define IDC_BUTTON2                     204
#define IDC_LIST1                       204
#define IDC_CHECK4                      204
#define IDS_MSG_EXPORT_COMPLETE         204
#define IDC_TREE1                       205
#define IDS_TITLE_EXPORT_ANIMATION      205
#define IDC_RADIO1                      206
#define IDS_TITLE_EXPORT_ANIMATION_PREFETCH 206
#define IDC_CHECK5                      206
#define IDC_RADIO2                      207
#define IDS_FETCHING_ROWS               207
#define IDC_RADIO3                      208
#define IDC_SPIN1                       208
#define IDS_MSG_EXPORT_FILEDS_TRUNCATED 208
#define IDC_RADIO4                      209
#define IDC_TAB1                        209
#define IDS_EXPORT_HEADER_TEXT          209
#define IDC_SPIN2                       209
#define IDC_EDIT1                       210
#define IDS_EXPORT_COLUMN               210
#define IDC_EDIT2                       211
#define IDC_RADIO5                      211
#define IDS_EXPORT_LENGTH               211
#define IDC_RADIO6                      212
#define IDS_EXPORT_NULL_AS              212
#define IDC_SPIN3                       212
#define IDC_STATIC_EMPTYTABLE           213
#define IDS_EXPORT_FORMAT               213
#define IDC_SPIN4                       213
#define IDS_SOURCE_FORMAT               214
#define IDS_AUTO                        215
#define IDS_MSG_EXPORT_ANOTHER_FILE     216
#define IDS_MSG_LOAD_EXPORT_PARAMFILE_ERROR 217
#define IDS_MSG_EXPORT_RESULT_CHANGE    218
#define IDS_MSG_FAIL_TO_INITIALIZE_EXPORT_STEP1 219
#define IDS_MSG_CREATE_EMPTY_TABLE      220
#define IDS_INPUTTABLE_CHARACTERISTICS_CREATEONLY 221
#define IDS_MSG_CREATE_TABLE_OK         222
#define IDS_DBFRECORDLEN_ERROR          223
#define IDS_MSG_CANNOT_EXPORT_DATATYPE  225
#define IDS_OVERWRITE_FILE              226
#define IDS_EXPORTFILE_EXIST            227
#define IDS_MSG_ERROR_HEADERLINE        228
#define IDS_MSG_DBF_LIMIT_FIELDLENGTH   229
#define IDS_MSG_DBF_LIMIT_RECORDLENGTH  230
#define IDS_MSG_DBF_LIMIT_FIELDCOUNT    231
#define IDS_MSG_INVALID_FILE_PATH       232
#define IDS_MSG_POSITIVE_INTEGER_ONLY   233
#define IDC_STATIC_FRAME                2001
#define IDD_XDETECTION_INFO             2001
#define IDD_XNOSOLUTION_INFO            2002
#define IDC_CHECK6                      2003
#define IDC_CHECK_CUSTOM_SEPARATOR      2003
#define IDC_STATIC1                     2004
#define IDC_STATIC2                     2005
#define IDI_ICON_LOAD                   2005
#define IDC_STATIC3                     2006
#define IDI_ICON_SAVE                   2006
#define IDC_COMBO2                      2007
#define IDD_IEAPAGE1                    2007
#define IDC_EDIT3                       2008
#define IDC_COMBO3                      2008
#define IDD_IEAPAGE2_CSV                2008
#define IDI_ICON_ASSISTANT              2008
#define IDC_EDIT4                       2009
#define IDD_IEAPAGE2_COMMON             2009
#define IDC_STATICFILE_SIZE             2010
#define IDC_EDIT5                       2011
#define IDC_STATIC_IMAGE1               2012
#define IDC_STATIC_TEXT1                2013
#define IDC_EDIT6                       2014
#define IDC_STATIC_TEXT2                2014
#define IDC_STATIC_CHECKMARK            2015
#define IDC_STATIC_SKIPFIRSTLINE        2016
#define IDC_STATIC_FIRSTLINE            2017
#define IDC_BUTTON3                     2018
#define IDC_STATIC_DELIMITER            2019
#define IDC_STATIC_QUOTE                2020
#define IDS_MSG_SUGGEST_OPTIMIZEDB      2021
#define IDS_FILE_EMPTY			2022

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2009
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2020
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
