/*
**	dtokens.h
**
**	Copyright (c) 2004 Ingres Corporation
**	All rights reserved.
*/

/**
** Name:	dtokens.h - Declaration of tokens for derivation parser.
**
** Description:
**	This file defines the tokens structure for the derivation parser.
**
** History:
**	06/05/89 (dkh) - Initial version.
**/

/*}
** Name:	struct dspec - Token strucuture declaration.
**
** Description:
**	Declaration of tokens structure used by derivation parser.
**	Values for the tokens are generated by running yacc on
**	dgrammar.y.
**
** History:
**	06/05/89 (dkh) - Initial version.
**	06/12/92 (dkh) - Added support for decimal datatype for 6.5.
**	10-nov-1999  (kitch01)
**		Bug 98227. Added comma to the list of valid tokens
*/
GLOBALDEF struct dspec	IIFVdTokens =
{
	I4CONST,		/* integer constant token */
	F8CONST,		/* float constant token */
	NAME,			/* name token */
	LPAREN,			/* left parenthesis token */
	RPAREN,			/* right parenthesis token */
	LBRAK,			/* left bracket token */
	RBRAK,			/* right bracket token */
	PERIOD,			/* the period token */
	COMMA,			/* the comma token */
	SVCONST,		/* the (varchar) string token */
	PLUS,			/* the plus operator token */
	MINUS,			/* the minus operator token */
	TIMES,			/* the multiply operator token */
	DIV,			/* the divide operator token */
	EXP,			/* the exponentiation operator token */
	SUM,			/* the sum aggregate token */
	MAX,			/* the max aggregate token */
	MIN,			/* the min aggregate token */
	AVERAGE,		/* the average aggregate token */
	COUNT,			/* the count aggregate token */
	SCONST,			/* the string constant token */
	DECCONST		/* the decimal constant token */
};
