/*
** Copyright Ingres Corporation 2006. All rights reserved
*/

# ifndef _RFAPILOCAL_H
# define _RFAPILOCAL_H

#include <si.h>

/* 
** Name: rfapilocal.h - Private Header for RFAPI
**
** Description:
**	This file contains macros, definitions and prototypes private to
**	the rfapi module. 
**
** History:
**	16-Sep-2006 (hanje04)
**	    SIR 116907
**	    Created.
**	13-Nov-2006 (hanje04)
**	    SIR 116907
**	    Add section headers to make response file more user readable.
**	    Format used is Windows .ini file and lines are "commented" on 
**	    Linux and UNIX.
**	02-feb-2007 (upake01)
**	    Include si.h for VMS.
**	20-May-2010 (hanje04)
**	    SIR 123791
**	    Add GLOBALREF for VW config array ivw_cfg_ops[]
**	13-Jul-2010 (hanje04)
**	    BUG 123081
**	    Add header for use when appending to existing response file.
**	    Add structure and typedef for rfapiopsinfo[] array.
*/

/* Macros */
/* 
** Name: RFAPI_REMOVE_PARAM_MARCO
**
** Description:
** 	Remove entry from parameter list:
**
**	p is am RFAPI_PARAMS pointer
**	h is an II_RFAPI_HANDLE pointer
*/
# define RFAPI_REMOVE_PARAM_MACRO(p, h) if ( p->prev ) \
					    p->prev->next = p->next ; \
					else \
					    (*h)->param_list = p->next ; \
					if ( p->next ) p->next->prev = p->prev  
	
/* Definitions */
/*
** Name: RFAPI_COMMENT
**
** Description:
** 	Platform dependent "Comment" character
*/
# define RFAPI_COMMENT ( ( (*handle)->output_format & \
					II_RF_DP_WINDOWS ) ? \
					";" : "#" ) 

/*
** Name: RFAPI_RESPONSE_FILE_HEADER
**
** Description:
**	Text header for new response file
*/
# define RFAPI_RESPONSE_FILE_HEADER \
	"%s Ingres Response File\n%s Generated by the Ingres Response File API\n%s Created: %s\n", \
	RFAPI_COMMENT, \
	RFAPI_COMMENT, \
	RFAPI_COMMENT

/*
** Name: RFAPI_RESPONSE_FILE_APPEND_HEADER
**
** Description:
**	Text header for update to existing response file
*/
# define RFAPI_RESPONSE_FILE_APPEND_HEADER \
	"\n%s Appended by the Ingres Response File API\n%s Updated: %s\n", \
	RFAPI_COMMENT, \
	RFAPI_COMMENT

/* 
** Name: RFAPI_SECTION_HEADER
**
** Description:
**	Descriptive header for "types" of response file variables
**
*/
# define RFAPI_SECTION_HEADER \
	 ( ( (*handle)->output_format & II_RF_DP_WINDOWS ) ? \
	    "\n[ %s ]\n" : "\n# [ %s ]\n" )

/*
** Name: RFAPI_DATE_FORMAT
**
** Description:
**	Format for date string:
**
**	     Thu Sep 28 13:14:24 2006
**	
*/
# define RFAPI_DATE_FORMAT "%s %s %s %s:%s:%s %s\n"

/* Globals */
typedef struct _RFAPI_VAR_INFO RFAPI_VAR_INFO;
struct _RFAPI_VAR_INFO {
	RFAPI_VAR **ops;
	char	*ophdr;
	};

GLOBALREF RFAPI_VAR_INFO rfapiopsinfo[];

/* Prototypes */
void
rfapi_getDateTime	( char *dtbuf );

II_RFAPI_STATUS
rfapi_writeRFHeader	( II_RFAPI_HANDLE *handle,
			FILE *fd );

II_RFAPI_STATUS
rfapi_writeRFParams	( II_RFAPI_HANDLE *handle,
			FILE *fd );

RFAPI_PARAMS *
rfapi_findParam		( II_RFAPI_HANDLE *handle,
			II_RFAPI_PNAME pname );

II_RFAPI_STATUS 
rfapi_doWrite		( II_RFAPI_HANDLE *handle,
			RFAPI_VAR **var_list,
			FILE	*fd );

# endif /* _RFAPILOCAL_H */
