//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by svrsqlas.rc
//
#define IDS_FAIL_TO_LOAD_DLL            1
#define IDS_HEADER_COLUMN               2
#define IDS_HEADER_SORT_TYPE            3
#define IDS_SORT_NONE                   4
#define IDS_SORT_ASC                    5
#define IDS_SORT_DESC                   6
#define IDS_SELECTALL                   7
#define IDS_HEADER_VALUE                8
#define IDS_OWNERxITEM                  9
#define IDS_HEADER_VIEW                 10
#define IDS_HEADER_OWNER                11
#define IDS_HEADER_TABLE                12
#define IDS_H_DATACONV1_BYTE            500
#define IDS_H_DATACONV1_C               501
#define IDS_H_DATACONV1_CHAR            502
#define IDS_H_DATACONV1_DATE            503
#define IDS_H_DATACONV1_DECIMAL         504
#define IDS_H_DATACONV1_DOW             505
#define IDS_H_DATACONV1_FLOAT4          506
#define IDS_H_DATACONV1_FLOAT8          507
#define IDS_H_DATACONV1_HEX             508
#define IDS_H_DATACONV1_INT1            509
#define IDS_H_DATACONV1_INT2            510
#define IDS_H_DATACONV1_INT4            511
#define IDS_H_DATACONV1_LONGBYTE        512
#define IDS_H_DATACONV1_LONGVARCHAR     513
#define IDS_H_DATACONV1_MONEY           514
#define IDS_H_DATACONV1_OBJECTKEY       515
#define IDS_H_DATACONV1_TABLEKEY        516
#define IDS_H_DATACONV1_TEXT            517
#define IDS_H_DATACONV1_VARBYTE         518
#define IDS_H_DATACONV1_VARCHAR         519
#define IDS_H_NUMERIC_ABS               520
#define IDS_H_NUMERIC_ATAN              521
#define IDS_H_NUMERIC_COS               522
#define IDS_H_NUMERIC_EXP               523
#define IDS_H_NUMERIC_LOG               524
#define IDS_H_NUMERIC_MOD               525
#define IDS_H_NUMERIC_SIN               526
#define IDS_H_NUMERIC_SQRT              527
#define IDS_H_STRING_CHAREXTRACT        528
#define IDS_H_STRING_CONCAT             529
#define IDS_H_STRING_LEFT               530
#define IDS_H_STRING_LENGTH             531
#define IDS_H_STRING_LOCATE             532
#define IDS_H_STRING_LOWERCASE          533
#define IDS_H_STRING_PAD                534
#define IDS_H_STRING_RIGHT              535
#define IDS_H_STRING_SHIFT              536
#define IDS_H_STRING_SIZE               537
#define IDS_H_STRING_SQUEEZE            538
#define IDS_H_STRING_TRIM               539
#define IDS_H_STRING_NOTRIM             540
#define IDS_H_STRING_UPPERCS            541
#define IDS_H_DATE_DATETRUNC            542
#define IDS_H_DATE_DATEPART             543
#define IDS_H_DATE_GMT                  544
#define IDS_H_DATE_INTERVAL             545
#define IDS_H_DATE_DATE                 546
#define IDS_H_DATE_TIME                 547
#define IDS_H_AGG_ANY                   548
#define IDS_H_AGG_COUNT                 549
#define IDS_H_AGG_SUM                   550
#define IDS_H_AGG_AVG                   551
#define IDS_H_AGG_MAX                   552
#define IDS_H_AGG_MIN                   553
#define IDS_H_IF_IFNULL                 554
#define IDS_H_PRED_COMPARISON           555
#define IDS_H_PRED_LIKE                 556
#define IDS_H_PRED_BETWEEN              557
#define IDS_H_PRED_IN                   558
#define IDS_H_PRED_ANY                  559
#define IDS_H_PRED_ALL                  560
#define IDS_H_PRED_EXISTS               561
#define IDS_H_PRED_ISNULL               562
#define IDS_H_PREDCOMB_AND              563
#define IDS_H_PREDCOMB_OR               564
#define IDS_H_PREDCOMB_NOT              565
#define IDS_H_DB_COLUMN                 566
#define IDS_H_DB_TABLE                  567
#define IDS_H_DB_DATABASE               568
#define IDS_H_DB_USER                   569
#define IDS_H_DB_GROUP                  570
#define IDS_H_DB_ROLE                   571
#define IDS_H_DB_PROFILE                572
#define IDS_H_DB_LOCATION               573
#define IDS_H_SUBSEL                    574
#define IDS_ANIMATE_TITLE_QUERYOBJECT   575
#define IDD_EXPR_MAIN                   657
#define IDD_EXPR_FUNCTION_PARAMETER     658
#define IDD_EXPR_DBOBJECT               659
#define IDD_EXPR_AGGREGATE_PARAMETER    660
#define IDD_EXPR_ANYALLEXIST_PARAMETER  661
#define IDD_EXPR_COMPARE                662
#define IDD_EXPR_IN_PARAMETER           663
#define IDD_SQLWIZARD_MAIN              664
#define IDD_SQLWIZARD_SELECT1           665
#define IDD_SQLWIZARD_SELECT2           666
#define IDD_SQLWIZARD_INSERT1           667
#define IDD_SQLWIZARD_UPDATE2           668
#define IDD_SQLWIZARD_INSERT2           670
#define IDD_SQLWIZARD_SELECT3           671
#define IDD_SQLWIZARD_UPDATE1           672
#define IDD_SQLWIZARD_UPDATE3           673
#define IDD_SQLWIZARD_DELETE1           674
#define IDS_ASSIST_EXPRESSION           1000
#define IDC_RADIO1                      1001
#define IDS_ASSIST_OPT_LENGTH           1001
#define IDC_RADIO2                      1002
#define IDS_ASSIST_OPT_PREC             1002
#define IDC_RADIO3                      1003
#define IDS_ASSIST_OPT_SCALE            1003
#define IDC_RADIO4                      1004
#define IDS_ASSIST_ARGUMENT             1004
#define IDC_EDIT1                       1005
#define IDS_ASSIST_STRING               1005
#define IDC_EDIT2                       1006
#define IDS_ASSIST_STRING1              1006
#define IDC_EDIT3                       1007
#define IDS_ASSIST_STRING2              1007
#define IDC_EDIT4                       1008
#define IDS_ASSIST_NB_CHARS             1008
#define IDC_STATIC1                     1009
#define IDS_ASSIST_MODULO               1009
#define IDC_STATIC2                     1010
#define IDS_ASSIST_OCC_IN_STRING        1010
#define IDC_STATIC3                     1011
#define IDS_ASSIST_NB_PLACES            1011
#define IDC_STATIC4                     1012
#define IDS_ASSIST_UNIT                 1012
#define IDC_STATIC5                     1013
#define IDS_ASSIST_DATE                 1013
#define IDC_STATIC6                     1014
#define IDS_ASSIST_DATE_INTERVAL        1014
#define IDC_STATIC7                     1015
#define IDS_ASSIST_CHAR_STRING          1015
#define IDC_STATIC8                     1016
#define IDS_ASSIST_PREDICATE            1016
#define IDC_STATIC9                     1017
#define IDS_ASSIST_CHECKED_ARGS         1017
#define IDC_STATIC10                    1018
#define IDS_ASSIST_RETVAL_IFNULL        1018
#define IDC_STATIC11                    1019
#define IDS_ASSIST_PATTERN              1019
#define IDC_STATIC12                    1020
#define IDS_ASSIST_ESCAPE_CHAR          1020
#define IDC_BUTTON1                     1021
#define IDS_ASSIST_CHECKED4NULL         1021
#define IDC_BUTTON2                     1022
#define IDS_ASSIST_SELECT_STMT          1022
#define IDC_BUTTON3                     1023
#define IDS_ASSIST_COMP_OPERATOR        1023
#define IDS_ASSIST_SUBQUERY             1024
#define IDC_BUTTON5                     1025
#define IDS_ASSIST_NUMBER               1025
#define IDC_BUTTON6                     1026
#define IDS_ASSIST_DBAREA               1026
#define IDC_BUTTON7                     1027
#define IDS_ASSIST_STO_GROUP            1027
#define IDC_BUTTON8                     1028
#define IDS_ASSIST_COL                  1028
#define IDC_BUTTON9                     1029
#define IDS_ASSIST_TABLE                1029
#define IDC_BUTTON10                    1030
#define IDS_ASSIST_DATABASE             1030
#define IDC_BUTTON11                    1031
#define IDS_ASSIST_USER                 1031
#define IDC_COMBO1                      1032
#define IDS_ASSIST_GROUP                1032
#define IDS_ASSIST_ROLE                 1033
#define IDS_ASSIST_PROFILE              1034
#define IDS_ASSIST_LOCATION             1035
#define IDS_ASSIST_X_RAD                1036
#define IDS_ASSIST_POS_ARG              1037
#define IDS_ASSIST_POSORNULL_X          1038
#define IDS_ASSIST_INT_RATE             1039
#define IDS_ASSIST_FUT_VALUE            1040
#define IDS_ASSIST_PRES_VALUE           1041
#define IDC_LIST1                       1042
#define IDS_ASSIST_PMT                  1042
#define IDC_LIST2                       1043
#define IDS_ASSIST_INT                  1043
#define IDC_LIST3                       1044
#define IDS_ASSIST_N                    1044
#define IDS_ASSIST_PRINCIPAL            1045
#define IDS_ASSIST_INTEREST             1046
#define IDS_ASSIST_PERIODS              1047
#define IDS_ASSIST_N_PERIODS            1048
#define IDS_ASSIST_COST                 1049
#define IDS_ASSIST_SALVAGE              1050
#define IDC_CHECK1                      1051
#define IDS_ASSIST_LIFE                 1051
#define IDC_CHECK2                      1052
#define IDS_ASSIST_FV                   1052
#define IDS_ASSIST_YEAR                 1053
#define IDS_ASSIST_MONTH                1054
#define IDS_ASSIST_DAY                  1055
#define IDS_ASSIST_PICTURE              1056
#define IDS_ASSIST_DATE_STRING          1057
#define IDS_ASSIST_HOUR                 1058
#define IDS_ASSIST_MINUTE               1059
#define IDS_ASSIST_SECOND               1060
#define IDS_ASSIST_TIME                 1061
#define IDS_ASSIST_POS                  1062
#define IDS_ASSIST_START                1063
#define IDS_ASSIST_LENGTH               1064
#define IDS_ASSIST_SCALE                1065
#define IDC_RADIO5                      1153
#define IDC_RADIO6                      1154
#define IDC_IMAGE_OPENING               1501
#define IDC_IMAGE_DELETE                1502
#define IDC_IMAGE_INSERT                1503
#define IDC_IMAGE_FINISH                1504
#define IDC_IMAGE_SELECT                1505
#define IDC_IMAGE_UPDATE                1506
#define IDS_MSG_CHANGE_EDIT             2000
#define IDS_MSG_CHANGE_COMBO            2001
#define IDS_MSG_SORTORDER               2002
#define IDS_MSG_SQL_ASSISTANT           2003
#define IDS_MSG_FAIL_2_QUERY_OBJECT     2004
#define IDS_MSG_FAIL_2_QUERY_TABLE      2005
#define IDS_MSG_FAIL_2_QUERY_VIEW       2006
#define IDS_MSG_FAIL_2_GENERATE_STATEMENT 2007
#define IDS_MSG_FAIL_2_QUERY_COLUMN     2008
#define IDS_MSG_COLUMNS_VALUE           2009
#define IDS_MSG_FAIL_2_QUERY_TABLExVIEW 2010

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1000
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
