//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by perfwiz.rc
//
#define IDS_INGRES_DOWN                 1
#define IDS_TITLE                       2
#define IDS_NO_SERVERS                  3
#define IDS_NO_SERVER_SELECTED          4
#define IDS_CANNOT_CONNECT              5
#define IDS_SQL_ERROR                   6
#define IDS_PGLIST_COLUMN               7
#define IDS_DUPLICATE_GROUP             8
#define IDS_NEED_INPUT_GROUP            9
#define IDS_NO_GROUPS                   10
#define IDS_PERSLIST_COLNAME            11
#define IDS_NOCTRS_SELECTED             12
#define IDS_PCLIST_COLUMN               13
#define IDS_UPDATE_HELP                 14
#define IDS_COUNTLIST_COLNAME           15
#define IDS_READINIT_WAIT               16
#define IDS_GETVNODE_WAIT               17
#define IDS_INTRO_HEADING               18
#define IDS_CHECK_INTRO                 19
#define IDS_CHECK_PERSONAL              20
#define IDS_PERSONAL_GROUP_HEADING      21
#define IDS_BUTTON_ADD_GROUP            22
#define IDS_BUTTON_EDIT_GROUP           23
#define IDS_BUTTON_DELETE_GROUP         24
#define IDS_EDIT_OBJ_NAME               25
#define IDS_EDIT_OBJ_DESC               26
#define IDS_PERSONAL_COUNTER_HEADING    27
#define IDS_PERSONAL_GROUP_NAME         28
#define IDS_PERSONAL_COUNTER_COMBO      29
#define IDS_INGRES_OBJECT               30
#define IDS_PERSONAL_HELP_HEADING       31
#define IDS_PERSONAL_HELP_COMBO         32
#define IDS_HELP_DESC                   33
#define IDS_BUTTON_SAVE_HELP            34
#define IDS_BUTTON_RESET                35
#define IDS_SERVER_HEADING              36
#define IDS_BUTTON_REFRESH              37
#define IDS_SERVER_COMBO                38
#define IDS_OK                          39
#define IDS_CANCEL                      40
#define IDS_FINISH_PERS                 41
#define IDS_ADDING_GROUPS               42
#define IDS_CHECK_REMOVE                43
#define IDS_REMOVING_GROUPS             44
#define IDS_FINISH_REMOVE               45
#define IDS_GROUP_PERSONAL              46
#define IDS_CHECK_GROUP_MODIFY          47
#define IDS_FINAL_HEADING               48
#define IDS_HELP_DESC2                  49
#define IDS_CHART_STRING                52
#define IDS_INTRO_HEADING2              53
#define IDS_NEED_CHARTFILE              54
#define IDS_DIALOGFAILURE               56
#define IDS_STRUCTSIZE                  57
#define IDS_INITIALIZATION              58
#define IDS_NOTEMPLATE                  59
#define IDS_NOHINSTANCE                 60
#define IDS_LOADSTRFAILURE              61
#define IDS_FINDRESFAILURE              62
#define IDS_LOADRESFAILURE              63
#define IDS_LOCKRESFAILURE              64
#define IDS_MEMALLOCFAILURE             65
#define IDS_MEMLOCKFAILURE              66
#define IDS_NOHOOK                      67
#define IDS_SETUPFAILURE                68
#define IDS_PARSEFAILURE                69
#define IDS_RETDEFFAILURE               70
#define IDS_LOADDRVFAILURE              71
#define IDS_GETDEVMODEFAIL              72
#define IDS_INITFAILURE                 73
#define IDS_NODEVICES                   74
#define IDS_NODEFAULTPRN                75
#define IDS_DNDMMISMATCH                76
#define IDS_CREATEICFAILURE             77
#define IDS_PRINTERNOTFOUND             78
#define IDS_NOFONTS                     79
#define IDS_SUBCLASSFAILURE             80
#define IDS_INVALIDFILENAME             81
#define IDS_BUFFERTOOSMALL              82
#define IDS_UNKNOWNERROR                83
#define IDS_CREATE_CHARTFILE            84
#define IDS_CHART_EXISTS                85
#define IDS_BUTTON_SELECT               86
#define IDS_BUTTON_DESELECT             87
#define IDS_NO_COUNTERS                 88
#define IDS_CANNOT_CREATE_CHART         89
#define IDS_ERROR_LODCTR                90
#define IDS_READINIT_ERR                91
#define IDS_GETVNODE_ERR                92
#define IDS_RADIO_CREATE                93
#define IDS_RADIO_USE_EXISTING          94
#define IDS_BUTTON_BROWSE               95
#define IDS_WIZARD_GROUP                96
#define IDS_ADDING_GROUPS_INFO          97
#define IDS_CHARTFILE_NOEXIST           98
#define IDS_REMOVE_CONFIRM              99
#define IDS_COUNTER_CREATION_HEADING    100
#define IDB_SPLASH256                   100
#define IDC_IPEDIT                      101
#define IDS_BUTTON_CREATE_COUNTER       101
#define IDC_IPSPIN                      102
#define IDS_BUTTON_EDIT_COUNTER         102
#define IDS_BUTTON_DELETE_COUNTER       103
#define IDS_PERSONAL_COUNTERS_COLUMN    104
#define IDS_DUPLICATE_COUNTER           105
#define IDS_NEED_CTRNAME                106
#define IDS_NEED_SCALE                  107
#define IDS_NEED_DBNAME                 108
#define IDS_NEED_QUERY                  109
#define IDS_NEED_CTRDESC                110
#define IDS_CANNOT_DELETE_CTR           111
#define IDS_INVALID_SCALE               112
#define IDS_EDIT_COUNTER_NAME           113
#define IDS_COUNTER_SCALE               114
#define IDS_DB_NAME                     115
#define IDS_COUNTER_QUERY               116
#define IDS_EDIT_COUNTER_DESC           117
#define IDS_CHKQRY_ERROR                118
#define IDS_COPYRIGHT                   119
#define IDS_UNKNOWN                     120
#define IDS_LICENSE_TO                  121
#define IDS_SITEID                      122
#define IDR_MAINFRAME                   128
#define IDD_SPLASH                      129
#define IDD_INTRO_PAGE                  133
#define IDD_SERVER_PAGE                 134
#define IDB_NODETREE                    134
#define IDD_FINAL_PAGE                  135
#define IDD_PERSONAL_GROUP_PAGE         136
#define IDD_EDIT_OBJ_DIALOG             137
#define IDD_PERSONAL_COUNTER_PAGE       138
#define IDR_CLOCK_AVI                   138
#define IDD_PERSONAL_HELP_PAGE          139
#define IDD_WAIT_DIALOG                 140
#define IDB_LV_STATEIMAGE               141
#define IDD_COUNTER_CREATION_PAGE       142
#define IDD_EDIT_COUNTER_DIALOG         143
#define IDC_IMAGE                       1000
#define IDC_CHECK_PERSONAL              1001
#define IDC_TREE_SERVERS                1004
#define IDC_BUTTON_REFRESH              1005
#define IDC_SERVER_ID                   1006
#define IDC_PERSONAL_GROUP_LIST         1009
#define IDC_BUTTON_ADD_GROUP            1010
#define IDC_BUTTON_EDIT_GROUP           1011
#define IDC_BUTTON_DELETE_GROUP         1012
#define IDC_EDIT_NAME                   1013
#define IDC_EDIT_DESCRIPTION            1014
#define IDC_COMBO_GROUPS                1016
#define IDC_COUNTER_LIST                1017
#define IDC_COMBO_OBJECTS               1019
#define IDC_PERSONAL_COUNTER_LIST       1020
#define IDC_BUTTON_ADD                  1021
#define IDC_BUTTON_DELETE               1022
#define IDC_PG_LIST                     1025
#define IDC_PC_LIST                     1026
#define IDC_EDIT_HELP                   1027
#define IDC_BUTTON_SAVE_HELP            1028
#define IDC_BUTTON_RESET                1029
#define IDC_AVI                         1032
#define IDC_WAIT_HEADING                1033
#define IDC_INTRO_HEADING               1034
#define IDC_CHECK_INTRO                 1035
#define IDC_PERSONAL_GROUP_HEADING      1036
#define IDC_EDIT_OBJ_NAME               1037
#define IDC_EDIT_OBJ_DESC               1038
#define IDC_PERSONAL_COUNTER_HEADING    1039
#define IDC_PERSONAL_GROUP_NAME         1040
#define IDC_PERSONAL_COUNTER_COMBO      1041
#define IDC_INGRES_OBJECT               1042
#define IDC_PERSONAL_HELP_HEADING       1043
#define IDC_PERSONAL_HELP_COMBO         1044
#define IDC_HELP_DESC                   1045
#define IDC_SERVER_HEADING              1046
#define IDC_SERVER_COMBO                1047
#define IDC_OBJECTS_COMBO               1048
#define IDC_CHECK_REMOVE                1050
#define IDC_CHECK_GROUP_MODIFY          1052
#define IDC_GROUP_PERSONAL              1053
#define IDC_CHARTLOC_COMBO              1055
#define IDC_BUTTON_BROWSE               1056
#define IDC_BUTTON_SELECT               1056
#define IDC_COUNTER_DESC                1057
#define IDC_EDIT_DBNAME                 1057
#define IDC_FINAL_HEADING               1058
#define IDC_HELP_DESC2                  1060
#define IDC_CHART_STRING                1063
#define IDC_INTRO_HEADING2              1065
#define IDC_BUTTON_DESELECT             1066
#define IDC_RADIO_CREATE                1067
#define IDC_RADIO_USE_EXISTING          1068
#define IDC_BUTTON_BROWSE2              1070
#define IDC_WIZARD_GROUP                1071
#define IDC_BUTTON_CREATE_COUNTER       1072
#define IDC_BUTTON_EDIT_COUNTER         1073
#define IDC_BUTTON_DELETE_COUNTER       1074
#define IDC_COUNTER_CREATION_HEADING    1075
#define IDC_EDIT_COUNTER_NAME           1076
#define IDC_EDIT_COUNTER_DESC           1077
#define IDC_DB_NAME                     1078
#define IDC_EDIT_QUERY                  1079
#define IDC_COUNTER_QUERY               1080
#define IDC_COUNTER_SCALE               1081
#define IDC_EDIT_SCALE                  1082

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1083
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
