.\"	$Header: /cmlib1/ingres63p.lib/unix/tools/port/shell/arc_unlock.1,v 1.1 90/03/09 09:18:19 source Exp $
.TH ARC_UNLOCK 1 "rti" "Relational Technology, Inc." "Relational Technology, Inc."
.ta 8n 16n 24n 32n 40n 48n 56n
.SH NAME
arc_unlock \- unlock an archive
.SH ORIGIN
Relational Technology, Inc.
.SH SYNOPSIS
.B arc_unlock archive_name
.SH DESCRIPTION
.I arc_unlock
removes a lock on an archive.
