.TH COPYCONV 1 "Ingres" "Ingres Corporation" "Ingres Corporation"
.\" History:
.\"	14-sep-1990 (boba)
.\"		Written.
.ta 8n 16n 24n 32n 40n 48n 56n
.SH NAME
copyconv \- Copy 5.0 pieces of conversion tools to \fB$ING_BUILD\fP.
.SH ORIGIN
Ingres Corporation
.SH SYNOPSIS
.B copyconv
.SH DESCRIPTION
.I Copyconv
copies the files for \fBconvto60\fP and the conversion utilities
that are built in the 5.0 porting environment into \fB$ING_BUILD\fP.
.PP
.I Copyconv
must be run as \fBingres\fP.
ING_HOME must be set to the top of the 5.0 build installation.
