.\"	$Header: /cmlib1/ingres63p.lib/unix/tools/port/shell/dirname.1,v 1.1 90/03/09 09:18:23 source Exp $
.TH DIRNAME 1 "rti" "Relational Technology, Inc." "Relational Technology, Inc."
.\" History: 
.\"     18-dec-1989 (boba) 
.\"             Make name in title all caps like other porting tool man pages.
.ta 8n 16n 24n 32n 40n 48n 56n
.SH NAME
dirname \- return the directory given a path.
.SH ORIGIN
Relational Technology, Inc.
.SH SYNOPSIS
.B dirname
pathname
.SH DESCRIPTION
.I dirname
returns the complement of basename(1), giving you the directory holding
the argument pathname.
