.TH GETEXTRA 1 "Ingres" "Ingres Corporation" "Ingres Corporation"
.\" History:
.\"	dd-mmm-yyyy (user)
.\"		Written.
.\"	10-nov-1192 (lauraw)
.\"		Obsoleted.
.ta 8n 16n 24n 32n 40n 48n 56n
.SH NOTE
With the passing of Piccolo 1.0,
.I getextra
is now obsolete.
However,
.I mkgetlist
is available to do a similar thing with Piccolo 2.0.


