.TH LOUF 1 "rti" "Relational Technology, Inc." "Relational Technology, Inc."
.ta 8n 16n 24n 32n 40n 48n 56n
.SH NAME
louf \- lint output filter
.SH ORIGIN
Relational Technology, Inc.
.SH SYNOPSIS
.B louf
[ files ]
.SH DESCRIPTION
.B louf
reads its standard input (or the named files) and filters out
``uninteresting'' messages produced by lint passes 1 and 2. 
.SH BUGS
Just 'cause it's voluminous doesn't mean the stuff we're throwing away
isn't important.


