.TH PROGRAM 1 "Ingres" "Ingres Corporation" "Ingres Corporation"
.\" History:
.\"	dd-mmm-yyyy (user)
.\"		Written.
.ta 8n 16n 24n 32n 40n 48n 56n
.SH NAME
program \- what it does
.SH ORIGIN
Ingres Corporation
.SH SYNOPSIS
.B program
[ options ]
.SH DESCRIPTION
.I Program
does whatever it does.
.PP
Another paragraph of description.
.SH OPTIONS
.TP
.B -v
``verbose'' prints the program's name and indents the output one tab stop.
.TP
.BI -f " file"
Specify file name for input.
.SH FILES
.TP
.B /file1
is used for this
.TP
.B /file2
is used for something else
.SH "SEE ALSO"
.BR whatever(1),
.BR etcetc(1)
.SH BUGS
.I Program's
assumptions and limits should be listed here.
