.TH MKW4DIR 1 "ask" "ASK/Ingres, Inc." "ASK/Ingres, Inc."
.\" History:
.\"	1/19/92 (jab)
.\"		Created
.ta 8n 16n 24n 32n 40n 48n 56n
.SH NAME
mk3glfiles \- perform port-specific steps to craft Windows4GL 3GL support
.SH ORIGIN
The ASK Group
.SH SYNOPSIS
.B mk3glfiles
.SH DESCRIPTION
.I Mk3glfiles
invokes whatever shell commands are necessary to put 3GL support
onto a particular platform.
Its sole purpose is to formalize whatever might be done `by hand'
to make it possible to invoke user-provided C and FORTRAN object files
from Windows4GL.
.PP
.I Mkw4dir
is normally run by `ming' in the directory w4gl/fleas/specials.
SH BUGS
