.TH MKFECAT 1 "rti" "Relational Technology, Inc." "Relational Technology, Inc."
.ta 8n 16n 24n 32n 40n 48n 56n
.SH NAME
mkfecat \- make fe.cat.msg
.SH ORIGIN
Relational Technology, Inc.
.SH SYNOPSIS
.B mkfecat
.SH DESCRIPTION
.I mkfecat
creates the file fe.cat.msg, which is the concatonation of
all *.msg files from the Release 6 front directory tree.
