.TH MKFILL 1 "rti" "Relational Technology, Inc." "Relational Technology, Inc."
.\" History:
.\"	31-jul-1989 (boba)
.\"		Change conf to tools/port/conf.
.\"	10-jan-1990 (boba)
.\"		Add the -l option.
.\"	14-dec-1990 (boba)
.\"		Add info on unsubscribe/subscribe.
.\"		Replace bogus BUGS section.
.\"	10-nov-1992 (lauraw)
.\"		Obsoleted.
.ta 8n 16n 24n 32n 40n 48n 56n
.SH NOTE
With the passing of Piccolo 1.0,
.I mkfill
is now obsolete.
A new tool called
.I newclient
is available to do a similar thing in Piccolo 2.0.
See the 
.I newclient
man page.
