.\"	$Header: /cmlib1/ingres63p.lib/unix/tools/port/shell/mksecret.1,v 1.1 90/03/09 09:18:32 source Exp $
.TH MKSECRET 1 "rti" "Relational Technology, Inc." "Relational Technology, Inc."
.\" History: 
.\"     18-dec-1989 (boba) 
.\"             Make name in title all caps like other porting tool man pages.
.ta 8n 16n 24n 32n 40n 48n 56n
.SH NAME
mksecret \- create INGRES 6.1 `clsecret.h' for this machine
.SH ORIGIN
Relational Technology, Inc.
.SH SYNOPSIS
.B mksecret
.SH DESCRIPTION
.I mksecret
creates a \fBclsecret.h\fR file in the current directory customized for
the current machine.  The output file should be moved into the
\fBcl!cl!hdr\fR directory before building a system.
.SH SEE ALSO
.I mkbzarch
.I cl!cl!hdr!clconfig.h,
which includes clsecret.h, and documents all possible defined symbols.
