.TH MKSPHCAT 1 "Ingres" "Ingres Corporation" "Ingres Corporation"
.\" History:
.\"	25-Jan-1991 (andys)
.\"		Written.
.ta 8n 16n 24n 32n 40n 48n 56n
.SH NAME
mkw4cat \- build the Windows\04GL message files.
.SH ORIGIN
Ingres Corporation
.SH SYNOPSIS
.B mkw4cat
.SH DESCRIPTION
.I Mkw4glcat
finds all the message files in the Windows\04GL source tree, concatenates and 
sorts them,
and then builds the message files.
.SH OPTIONS
.TP
None.
.SH FILES
.TP
.B $ING_BUILD/files/english/fw4gv3.mnx
is the fast message file.
.TP
.B $ING_BUILD/files/english/sw4gv3.mnx
is the slow message file.
.SH "SEE ALSO"
.BR mkfecat(1),
.SH BUGS
None known.
