.TH MKW4DIR 1 "ask" "ASK/Ingres, Inc." "ASK/Ingres, Inc."
.\" History:
.\"	1/19/92 (jab)
.\"		Created
.ta 8n 16n 24n 32n 40n 48n 56n
.SH NAME
mkw4dir \- creat iW4GL IIinstallation directories
.SH ORIGIN
ASK/Ingres Inc.
.SH SYNOPSIS
.B mkw4dir
.SH DESCRIPTION
.I Mkw4dir
creates all of the directories needed under \fB$ING_BUILD\fP for a working
W4GL II installation.  Permissions are set explicitly for each of the
directories created.
.PP
.I Mkw4dir
must be run by the "ingres" user.
.SH "SEE ALSO"
.BR w4prerls(1)
SH BUGS
