.TH PICALL 1 "rti" "Relational Technology, Inc." "Relational Technology, Inc."
.\" History:
.\"	21-dec-1990 (boba)
.\"		Written.
.\"	27-dec-1991 (hallman)
.\"		Created from ingres6202p version.
.\"	30-oct-1992 (lauraw)
.\"		Obsolete for Piccolo 2.0
.ta 8n 16n 24n 32n 40n 48n 56n
.SH NOTE
Piccolo 2.0 has made
.I picall
obsolete.
You can use almost any Piccolo client command with a list.
For information about Piccolo 2.0, use the 
.I "p2 help"
command.
