.\"	$Header: /cm4/src/ingres.lib/ingres/cpe_tools/unix/tools/port/shell/project.1,v 1.1 1990/10/04 21:37:10 source Exp $
.TH PROJECT 1 "rti" "Relational Technology, Inc." "Relational Technology, Inc."
.\" History:
.\"	31-jul-1989 (boba)
.\"		Change conf to tools/port/conf.
.\"	30-oct-1992 (lauraw)
.\"		Obsolete.
.ta 8n 16n 24n 32n 40n 48n 56n
.SH NOTE
The
.I
project
command is obsolete.
.PP
To find out the name of your Piccolo client, use
.IP
p2 here | awk '{print $2}'
.LP
