.TH RCOMPALL 1 "ASK" "ASK/Ingres, Inc." "ASK/Ingres, Inc."
.\" History:
.\"	21-dec-1990 (BobA)
.\"		Written.
.\"	02-aug-91 (brett)
.\"		Added code to check port_branch directories.  Add the file's
.\"		version to the rcompare.  Make more extensive checks on each
.\"		file.
.\"	14-aug-91 (brett)
.\"		Add the explaination section for extended error messages.
.\"	09-nov-92 (lauraw)
.\"		Obsolete with Piccolo 2.0.
.ta 8n 16n 24n 32n 40n 48n 56n
.SH NOTE
Piccolo 2.0 has made
.I rcompall
obsolete.
A new tool called
.I checksrc
is now available to check source files on your client for consistency 
with Piccolo 2.0 libraries.
See the
.I checksrc
man page for information.
