.\"	$Header: /cmlib1/ingres63p.lib/unix/tools/port/shell/rofix.1,v 1.1 90/03/09 09:18:34 source Exp $
.TH ROFIX 1 "rti" "Relational Technology, Inc." "Relational Technology, Inc."
.\" History: 
.\"     18-dec-1989 (boba) 
.\"             Make name in title all caps like other porting tool man pages.
.ta 8n 16n 24n 32n 40n 48n 56n
.SH NAME
rofix \- Changes .data to .text in .s files
.SH ORIGIN
Relational Technology, Inc.
.SH SYNOPSIS
.B rofix
file [ file ... ]
.SH DESCRIPTION
.I rofix
edits the specified assembler .s files to change .data declarations to .text.
This can be used to move constant data from the per\-user data space to the
shared code space.
.SH "SEE ALSO"
yyfix(1)
.SH BUGS
.I rofix
is a hack used primarily for 
.I yacc
parser tables.

