.TH VERS 1 "Ingres" "Ingres Corporation" "Ingres Corporation"
.\" History:
.\"	27-oct-1992 (lauraw)
.\"		Written.
.\"	17-nov-1992 (lauraw)
.\"		Corrected "default build" info.
.\"	13-jul-1993 (lauraw)
.\"		VERS can now be in $ING_SRC, too.
.ta 8n 16n 24n 32n 40n 48n 56n
.SH NAME
VERS \- the version identifier file
.SH ORIGIN
Ingres Corporation
.SH DESCRIPTION
The VERS file contains release-specific version information about
the INGRES port you are building. 
It is used by
.I readvers
in many porting tools.
For example, it is used by
.I genrelid
to generate the release id of your build.
The barest VERS file contains a single entry of the form:
.IP
config=xxx_yyy
.LP
where 
.I xxx_yyy
is the "config string" for your port.
You can't build INGRES without a config string.
.PP
Your VERS file can also identify the build level of your release.
The default build level is "00", but you could override the default
by adding something like this to the VERS file:
.IP
build=02
.LP
.PP
Additional configuration options that are specific to your build but
not to the platform are identified with the 
.I option
keyword. For example, a W4GL port must include
.IP
option=W4GL
.LP
in the VERS file. A double-byte port must include:
.IP
option=DBL
.LP
.PP
The VERS file may also contain comment lines, which begin with "#".
.SH EXAMPLE
A VERS file might look like:
.IP
.nf
# HP9000/800 double-byte build
config=hp8_us5
option=DBL
.fi
.LP
.PP
If this were a 6.5/01 port, 
the release identifier that would be generated by the
build tools is:
.IP
6.5/01 (hp8.us5/01)DBL
.LP
Note that the "6.5/01" is set in CONFIG and applies to all ports built
with that particular code line.
.SH FILES
.nf
$ING_SRC/tools/port/conf/VERS
$ING_SRC/tools/port/conf/CONFIG
$ING_SRC/bin/readvers
$ING_SRC/bin/genrelid
$ING_SRC/VERS
.fi
.PP
Historically, the VERS file has always been located in $ING_SRC/tools/port/conf.
If your environment does not have a tools/port/conf/VERS file
(as in a private path of a "baroque" development environment)
$ING_SRC/VERS will be used by readvers.
.SH "SEE ALSO"
.BR ccpp(1)
