.\"	$Header: /cmlib1/ingres63p.lib/unix/tools/port/shell/whoami.1,v 1.1 90/03/09 09:18:35 source Exp $
.TH WHOAMI 1 "rti" "Relational Technology, Inc." "Relational Technology, Inc."
.ta 8n 16n 24n 32n 40n 48n 56n
.SH NAME
whoami \- echo the effective user's name
.SH ORIGIN
Relational Technology, Inc.
.SH SYNOPSIS
.B whoami
.SH DESCRIPTION
.I whoami
echos the name of the current effective user.
