/* 
** Copyright (c) 2006, Ingres Corporation 
*/ 
/** 
** Name: tracefn.h - Ingres ODBC CLI private trace function pointers.
** 
** Description: 
**   This file describes ODBC CLI trace function pointers.
**
** History:
**    13-Oct-2005 (Jeremy Hankinson)
**        Created.
**    19-June-2006 (Ralph Loen) Added setCLI() and bind_sym() to silence
**        compiler warnings on Windows.
**   15-Nov-2010 (stial01) SIR 124685 Prototype Cleanup
**        Changes to eliminate compiler prototype warnings.
** 
*/

GLOBALREF void setCLI(void);
GLOBALREF void bind_sym(PTR *dlHandle, char *driverSym, IIODBC_DRIVER_FN *fcn);

/*
**  ODBC trace function entry points.
*/

GLOBALREF IIODBC_DRIVER_FN IITraceReturn;
/*IIODBC_DRIVER_FN TraceOpenLogFile;
GLOBALREF IIODBC_DRIVER_FN TraceCloseLogFile;
GLOBALREF IIODBC_DRIVER_FN TraceVersion;
*/
GLOBALREF IIODBC_DRIVER_FN IITraceSQLAllocConnect;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLAllocEnv;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLAllocStmt;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLBindCol;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLCancel;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLColAttributes;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLColAttributesW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLConnect;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLConnectW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLDescribeCol;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLDescribeColW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLDisconnect;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLError;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLErrorW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLExecDirect;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLExecDirectW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLExecute;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLFetch;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLFreeConnect;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLFreeEnv;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLFreeStmt;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetCursorName;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetCursorNameW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLNumResultCols;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLPrepare;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLPrepareW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLRowCount;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLSetCursorName;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLSetCursorNameW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLSetParam;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLTransact;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLColumns;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLColumnsW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLDriverConnect;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLDriverConnectW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetConnectOption;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetConnectOptionW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetData;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetFunctions;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetInfo;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetInfoW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetStmtOption;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetTypeInfo;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetTypeInfoW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLParamData;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLPutData;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLSetConnectOption;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLSetConnectOptionW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLSetStmtOption;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLSpecialColumns;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLSpecialColumnsW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLStatistics;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLStatisticsW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLTables;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLTablesW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLBrowseConnect;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLBrowseConnectW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLColumnPrivileges;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLColumnPrivilegesW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLDataSources;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLDataSourcesW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLDescribeParam;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLExtendedFetch;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLForeignKeys;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLForeignKeysW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLMoreResults;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLNativeSql;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLNativeSqlW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLNumParams;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLParamOptions;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLPrimaryKeys;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLPrimaryKeysW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLProcedureColumns;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLProcedureColumnsW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLProcedures;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLProceduresW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLSetPos;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLSetScrollOptions;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLTablePrivileges;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLTablePrivilegesW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLDrivers;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLDriversW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLBindParameter;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLAllocHandle;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLBindParam;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLCloseCursor;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLColAttribute;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLColAttributeW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLCopyDesc;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLEndTran;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLFetchScroll;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLFreeHandle;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetConnectAttr;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetConnectAttrW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetDescField;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetDescFieldW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetDescRec;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetDescRecW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetDiagField;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetDiagFieldW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetDiagRec;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetDiagRecW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetEnvAttr;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetStmtAttr;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLGetStmtAttrW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLSetConnectAttr;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLSetConnectAttrW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLSetDescField;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLSetDescFieldW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLSetDescRec;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLSetEnvAttr;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLSetStmtAttr;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLSetStmtAttrW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLAllocHandleStd;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLAllocHandleStdW;
GLOBALREF IIODBC_DRIVER_FN IITraceSQLBulkOperations;
