/*
** Copyright (c) 1990, 2000 Ingres Corporation
** All Rights Reserved
*/

#include    <compat.h>
#include    <dbms.h>
#include    <adf.h>
#include    <add.h>
#include    "gwrmsdt.h"
#include    "gwrmsdtmap.h"
#include    "gwrmserr.h"

/**
**
**  Name: GWRMSDT.C - Code for adding all RMS types as user-defined types
**
**  Description:
**	For the RMS gateway, we add all supported RMS datatypes as
**	user-defined datatypes (unless there is an INGRES-compatible datatype
**	for it, in which case we just use the INGRES datatype).
**
**	This file constructs the block for SCF to add the new datatypes.
**
**	    RMSGW_INT		    1,2,4,8, or 16 byte signed integer
**	    RMSGW_UNSINT	    1,2,4,8, or 16 byte unsigned integer
**	    RMSGW_FFLOAT	    4 byte f-float
**          RMSGW_DFLOAT            8 byte d-float
**          RMSGW_GFLOAT            8 byte g-float
**          RMSGW_HFLOAT            16 byte h-float
**          RMSGW_SFLOAT            IEEE 4 byte s-float (alpha)
**          RMSGW_TFLOAT            IEEE 8 byte t-float (alpha)
**	    
**	    RMSGW_BL_FIXSTR	    Blank-padded fixed-length string
**	    RMSGW_NL_FIXSTR	    Null-padded fixed-length string
**	    RMSGW_BL_VARSTR	    Blank-padded "varying-length" string
**	    RMSGW_NL_VARSTR	    Null-padded "varying-length" string
**	    
**	    RMSGW_VAXDATE	    VAX date (8 bytes)
**	    
**	    RMSGW_PACKED_DEC	    Packed decimal
**	    RMSGW_LEADING_NUM	    Leading numeric string
**	    RMSGW_ZONED_NUM	    Zoned numeric string
**	    RMSGW_UNS_NUM	    Unsigned numeric string
**	    RMSGW_OVR_NUM	    Overpunched numeric string
**	    RMSGW_TRL_NUM	    Trailing separate numeric string
**          RMSGW_IMAGINE           repeating group phantom data type
**
**
**  History:
**	21-mar-90 (jrb)
**	    Created.
**	14-jun-90 (jrb)
**	    Added blank-padded fixed strings.
**	22-jun-90 (edwin)
**	    Add RMSGW_NATFLOAT.
**	26-jun-90 (linda)
**	    Add RMSGW_BL_VARSTR, RMSGW_NL_VARSTR string types.
**	7-sep-90 (linda)
**	    Added support for "trailing separate numeric" datatype.  This type
**	    is a string type, one byte per ascii digit, with a separate sign
**	    byte at the end.  It is generated by COBOL PIC statements.  Its
**	    internal type definition is RMSGW_TRL_NUM.
**      17-dec-1992 (schang)
**          prototype
**      27-Jul-1993 (fred)
**          Modified OME declarations to match new add.h changes for 
**          large object support.
**      25-may-1993 (schang)
**          add RMSGW_IMAGE data type for repeating group support
**      21-sep-93 (schang)
**          change ADD_FISTART to ADD_USER_FISTART because the first one
**          is replaced by the latter by stevet to support class object.
**      26-feb-97 (schang)
**          modify floating point support, now we have explicit RMS floating
**          data type f-,d-,g-,h-,s-,t- types
**      31-dec-97 (chash01)
**          add support for byte datatypes
**      03-mar-1999 (chash01)
**          integrate all changes since ingres 6.4.
**      28-jun-1999 (chash01)
**          add one more member into rms_dts
**      21-mar-2000 (chash01)
**          somehow ingres deciaml datatype support is missing.
**	28-feb-2001	(kinte01)
**	    Bug 103393 - removed nat, longnat, u_nat, & u_longnat
**	    from RMS GW code as the use is no longer allowed
**/

/*
[@forward_type_references@]
*/


/*
**  Forward and/or External function references.
*/

    /* First, we list all external functions used for implementing the coercions
    ** needed for the gateway.
    */

FUNC_EXTERN	DB_STATUS	rms_iintcvt();
FUNC_EXTERN	DB_STATUS	rms_ifltcvt();
FUNC_EXTERN	DB_STATUS	rms_istrcvt();
FUNC_EXTERN	DB_STATUS	rms_idtecvt();
FUNC_EXTERN	DB_STATUS	rms_imnycvt();
FUNC_EXTERN	DB_STATUS	rms_cvttoidec();

FUNC_EXTERN	DB_STATUS	rms_rintcvt();
FUNC_EXTERN	DB_STATUS	rms_runscvt();
FUNC_EXTERN	DB_STATUS	rms_rfltcvt();
FUNC_EXTERN	DB_STATUS	rms_rdtecvt();
FUNC_EXTERN	DB_STATUS	rms_rstrcvt();
FUNC_EXTERN	DB_STATUS	rms_rdeccvt();

    /* This is a dummy routine which always returns E_DB_OK */
FUNC_EXTERN	DB_STATUS	rms_dummy();

/*
[@function_reference@]...
*/


/*
**  Defines of other constants.
*/

/*
[@group_of_defined_constants@]...
*/



/*
[@type_definitions@]
[@global_variable_definitions@]
*/


/*
**  Definition of static variables and forward static functions.
*/

    /* The following list defines all RMS datatypes we are going to add to
    ** the DBMS.
    */

static  ADD_DT_DFN  rms_dts[] =
	{
	    { ADD_O_INTERNDT, {""}, RMSGW_INT, DB_NODT, 0,
		  rms_dummy, 0, 0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	    { ADD_O_INTERNDT, {""}, RMSGW_UNSINT, DB_NODT, 0,
		  rms_dummy, 0, 0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	    { ADD_O_INTERNDT, {""}, RMSGW_FFLOAT, DB_NODT, 0,
		  rms_dummy, 0, 0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	    { ADD_O_INTERNDT, {""}, RMSGW_DFLOAT, DB_NODT, 0,
		  rms_dummy, 0, 0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	    { ADD_O_INTERNDT, {""}, RMSGW_GFLOAT, DB_NODT, 0,
		  rms_dummy, 0, 0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	    { ADD_O_INTERNDT, {""}, RMSGW_HFLOAT, DB_NODT, 0,
		  rms_dummy, 0, 0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	    { ADD_O_INTERNDT, {""}, RMSGW_SFLOAT, DB_NODT, 0,
		  rms_dummy, 0, 0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	    { ADD_O_INTERNDT, {""}, RMSGW_TFLOAT, DB_NODT, 0,
		  rms_dummy, 0, 0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	    { ADD_O_INTERNDT, {""}, RMSGW_BL_FIXSTR, DB_NODT, 0,
		  rms_dummy, 0, 0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	    { ADD_O_INTERNDT, {""}, RMSGW_NL_FIXSTR, DB_NODT, 0,
		  rms_dummy, 0, 0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	    { ADD_O_INTERNDT, {""}, RMSGW_BL_VARSTR, DB_NODT, 0,
		  rms_dummy, 0, 0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	    { ADD_O_INTERNDT, {""}, RMSGW_NL_VARSTR, DB_NODT, 0,
		  rms_dummy, 0, 0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	    { ADD_O_INTERNDT, {""}, RMSGW_VAXDATE, DB_NODT, 0,
		  rms_dummy, 0, 0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	    { ADD_O_INTERNDT, {""}, RMSGW_PACKED_DEC, DB_NODT, 0,
		  rms_dummy, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	    { ADD_O_INTERNDT, {""}, RMSGW_LEADING_NUM, DB_NODT, 0,
		  rms_dummy, 0, 0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	    { ADD_O_INTERNDT, {""}, RMSGW_ZONED_NUM, DB_NODT, 0,
		  rms_dummy, 0, 0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	    { ADD_O_INTERNDT, {""}, RMSGW_UNS_NUM, DB_NODT, 0,
		  rms_dummy, 0, 0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	    { ADD_O_INTERNDT, {""}, RMSGW_OVR_NUM, DB_NODT, 0,
		  rms_dummy, 0, 0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	    { ADD_O_INTERNDT, {""}, RMSGW_TRL_NUM, DB_NODT, 0,
		  rms_dummy, 0, 0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	    { ADD_O_INTERNDT, {""}, RMSGW_IMAGINE, DB_NODT, 0,
		  rms_dummy, 0, 0, 0, 0, 0, 0, 
		0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
	};


    /* Next we define the function instances we will use for coercing between
    ** the various types (both INGRES and RMS types).  Of course we don't
    ** bother add coercions between types which are compatible between INGRES
    ** and RMS since those are already in the system.
    */

    /* First set up all function instance parameters; this is just a list
    ** of all "from" types for all coercions.  We point to them in our function
    ** instance entries later on.
    */

static	DB_DT_ID rms_int_parm[]		=   { DB_INT_TYPE };
static	DB_DT_ID rms_flt_parm[]		=   { DB_FLT_TYPE };
static	DB_DT_ID rms_c_parm[]		=   { DB_CHR_TYPE };
static	DB_DT_ID rms_text_parm[]	=   { DB_TXT_TYPE };
static	DB_DT_ID rms_char_parm[]	=   { DB_CHA_TYPE };
static	DB_DT_ID rms_varchar_parm[]	=   { DB_VCH_TYPE };
static	DB_DT_ID rms_date_parm[]	=   { DB_DTE_TYPE };
static	DB_DT_ID rms_money_parm[]	=   { DB_MNY_TYPE };
/* chash01: decimal datatype */
static	DB_DT_ID rms_deci_parm[]	=   { DB_DEC_TYPE };
static	DB_DT_ID rms_tabkey_parm[]	=   { DB_TABKEY_TYPE };
static	DB_DT_ID rms_logkey_parm[]	=   { DB_LOGKEY_TYPE };
static	DB_DT_ID rms_rint_parm[]	=   { RMSGW_INT };
static	DB_DT_ID rms_unsint_parm[]	=   { RMSGW_UNSINT };
static	DB_DT_ID rms_fflt_parm[]	=   { RMSGW_FFLOAT };
static	DB_DT_ID rms_dflt_parm[]	=   { RMSGW_DFLOAT };
static	DB_DT_ID rms_gflt_parm[]	=   { RMSGW_GFLOAT };
static	DB_DT_ID rms_hflt_parm[]	=   { RMSGW_HFLOAT };
static	DB_DT_ID rms_sflt_parm[]	=   { RMSGW_SFLOAT };
static	DB_DT_ID rms_tflt_parm[]	=   { RMSGW_TFLOAT };
static	DB_DT_ID rms_blfix_parm[]	=   { RMSGW_BL_FIXSTR };
static	DB_DT_ID rms_nlfix_parm[]	=   { RMSGW_NL_FIXSTR };
static	DB_DT_ID rms_blvar_parm[]	=   { RMSGW_BL_VARSTR };
static	DB_DT_ID rms_nlvar_parm[]	=   { RMSGW_NL_VARSTR };
static	DB_DT_ID rms_vaxdate_parm[]	=   { RMSGW_VAXDATE };
static	DB_DT_ID rms_dec_parm[]		=   { RMSGW_PACKED_DEC };
static	DB_DT_ID rms_leadnum_parm[]	=   { RMSGW_LEADING_NUM };
static	DB_DT_ID rms_zonednum_parm[]    =   { RMSGW_ZONED_NUM };
static	DB_DT_ID rms_unsnum_parm[]	=   { RMSGW_UNS_NUM };
static	DB_DT_ID rms_ovrnum_parm[]	=   { RMSGW_OVR_NUM };
static	DB_DT_ID rms_trlnum_parm[]	=   { RMSGW_TRL_NUM };
static  DB_DT_ID rms_imagine_parm[]     =   { RMSGW_IMAGINE };

static	DB_DT_ID rms_lvchar_parm[]	=   { DB_LVCH_TYPE };
static	DB_DT_ID rms_byte_parm[]	=   { DB_BYTE_TYPE };
static	DB_DT_ID rms_vbyte_parm[]	=   { DB_VBYTE_TYPE };
static	DB_DT_ID rms_lbyte_parm[]	=   { DB_LBYTE_TYPE };

static	DB_DT_ID rms_rlvchar_parm[]	=   { RMSGW_NL_FIXSTR };
static	DB_DT_ID rms_rbyte_parm[]	=   { RMSGW_NL_FIXSTR };
static	DB_DT_ID rms_rvbyte_parm[]	=   { RMSGW_NL_FIXSTR };
static	DB_DT_ID rms_rlbyte_parm[]	=   { RMSGW_NL_FIXSTR };


    /* And finally, all function instances.  All of these are coercions, so
    ** they will all have two parameters (listed above).  Also, we arbitrarily
    ** assign function instance ids since in this release of the gateway we
    ** will not allow users to add datatypes (if we did, we would have to
    ** document which datatype ids and function instance ids we are reserving
    ** for the gateway).  Also, because these function instance ids will never
    ** be exposed to any code which stores them (e.g. ABF), they can be
    ** freely assigned and altered between releases without worry.  This is
    ** not true of normal ADF function instances.
    */

static ADD_FI_DFN	rms_fis[] =
    {
/* to INGRES signed integer */
    { ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_rint_parm, DB_INT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_iintcvt, 0 },	
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_unsint_parm, DB_INT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_iintcvt, 0 },	
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_fflt_parm, DB_INT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_iintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_dflt_parm, DB_INT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_iintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_gflt_parm, DB_INT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_iintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_hflt_parm, DB_INT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_iintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_sflt_parm, DB_INT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_iintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_tflt_parm, DB_INT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_iintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_blfix_parm, DB_INT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_iintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_nlfix_parm, DB_INT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_iintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_blvar_parm, DB_INT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_iintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_nlvar_parm, DB_INT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_iintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_dec_parm, DB_INT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_iintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_leadnum_parm, DB_INT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_iintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_zonednum_parm, DB_INT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_iintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_unsnum_parm, DB_INT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_iintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_ovrnum_parm, DB_INT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_iintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_trlnum_parm, DB_INT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_iintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_imagine_parm, DB_INT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_iintcvt, 0 },

/* to INGRES f4 or f8 */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_rint_parm, DB_FLT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_ifltcvt, 0 },	
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_unsint_parm, DB_FLT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_ifltcvt, 0 },	
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_fflt_parm, DB_FLT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_ifltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_dflt_parm, DB_FLT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_ifltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_gflt_parm, DB_FLT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_ifltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_hflt_parm, DB_FLT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_ifltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_sflt_parm, DB_FLT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_ifltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_tflt_parm, DB_FLT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_ifltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_blfix_parm, DB_FLT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_ifltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_nlfix_parm, DB_FLT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_ifltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_blvar_parm, DB_FLT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_ifltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_nlvar_parm, DB_FLT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_ifltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_dec_parm, DB_FLT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_ifltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_leadnum_parm, DB_FLT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_ifltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_zonednum_parm, DB_FLT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_ifltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_unsnum_parm, DB_FLT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_ifltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_ovrnum_parm, DB_FLT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_ifltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_trlnum_parm, DB_FLT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_ifltcvt, 0 },

/* to INGRES 'C' type */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_rint_parm, DB_CHR_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },	
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_unsint_parm, DB_CHR_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },	
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_fflt_parm, DB_CHR_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_dflt_parm, DB_CHR_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_gflt_parm, DB_CHR_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_hflt_parm, DB_CHR_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_sflt_parm, DB_CHR_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_tflt_parm, DB_CHR_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_blfix_parm, DB_CHR_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_nlfix_parm, DB_CHR_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_blvar_parm, DB_CHR_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_nlvar_parm, DB_CHR_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_vaxdate_parm, DB_CHR_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_dec_parm, DB_CHR_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_leadnum_parm, DB_CHR_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_zonednum_parm, DB_CHR_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_unsnum_parm, DB_CHR_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_ovrnum_parm, DB_CHR_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_trlnum_parm, DB_CHR_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },

/* to INGRES 'TEXT' type (also known as 'VCHAR') */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_rint_parm, DB_TXT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },	
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_unsint_parm, DB_TXT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },	
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_fflt_parm, DB_TXT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_dflt_parm, DB_TXT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_gflt_parm, DB_TXT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_hflt_parm, DB_TXT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_sflt_parm, DB_TXT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_tflt_parm, DB_TXT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_blfix_parm, DB_TXT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_nlfix_parm, DB_TXT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_blvar_parm, DB_TXT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_nlvar_parm, DB_TXT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_vaxdate_parm, DB_TXT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_dec_parm, DB_TXT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_leadnum_parm, DB_TXT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_zonednum_parm, DB_TXT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_unsnum_parm, DB_TXT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_ovrnum_parm, DB_TXT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_trlnum_parm, DB_TXT_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },

/* to INGRES 'CHAR' type */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_rint_parm, DB_CHA_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },	
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_unsint_parm, DB_CHA_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },	
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_fflt_parm, DB_CHA_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_dflt_parm, DB_CHA_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_gflt_parm, DB_CHA_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_hflt_parm, DB_CHA_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_sflt_parm, DB_CHA_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_tflt_parm, DB_CHA_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_blfix_parm, DB_CHA_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_nlfix_parm, DB_CHA_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_blvar_parm, DB_CHA_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_nlvar_parm, DB_CHA_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_vaxdate_parm, DB_CHA_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_dec_parm, DB_CHA_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_leadnum_parm, DB_CHA_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_zonednum_parm, DB_CHA_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_unsnum_parm, DB_CHA_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_ovrnum_parm, DB_CHA_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_trlnum_parm, DB_CHA_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },

/* to INGRES 'VARCHAR' type */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_rint_parm, DB_VCH_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },	
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_unsint_parm, DB_VCH_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },	
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_fflt_parm, DB_VCH_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_dflt_parm, DB_VCH_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_gflt_parm, DB_VCH_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_hflt_parm, DB_VCH_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_sflt_parm, DB_VCH_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_tflt_parm, DB_VCH_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_blfix_parm, DB_VCH_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_nlfix_parm, DB_VCH_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_blvar_parm, DB_VCH_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_nlvar_parm, DB_VCH_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_vaxdate_parm, DB_VCH_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_dec_parm, DB_VCH_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_leadnum_parm, DB_VCH_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_zonednum_parm, DB_VCH_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_unsnum_parm, DB_VCH_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_ovrnum_parm, DB_VCH_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_trlnum_parm, DB_VCH_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
/*
**  added to convert to ingres long varchar, byte, varbyte and long byte type
*/
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_rlvchar_parm, DB_LVCH_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_rbyte_parm, DB_BYTE_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_rvbyte_parm, DB_VBYTE_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_rlbyte_parm, DB_LBYTE_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_istrcvt, 0 },

/* to INGRES date */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_rint_parm, DB_DTE_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_idtecvt, 0 },	
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_unsint_parm, DB_DTE_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_idtecvt, 0 },	
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_blfix_parm, DB_DTE_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_idtecvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_nlfix_parm, DB_DTE_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_idtecvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_blvar_parm, DB_DTE_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_idtecvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_nlvar_parm, DB_DTE_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_idtecvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_vaxdate_parm, DB_DTE_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_idtecvt, 0 },

/* to INGRES money type */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_rint_parm, DB_MNY_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_imnycvt, 0 },	
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_unsint_parm, DB_MNY_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_imnycvt, 0 },	
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_fflt_parm, DB_MNY_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_imnycvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_dflt_parm, DB_MNY_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_imnycvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_gflt_parm, DB_MNY_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_imnycvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_hflt_parm, DB_MNY_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_imnycvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_sflt_parm, DB_MNY_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_imnycvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_tflt_parm, DB_MNY_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_imnycvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_blfix_parm, DB_MNY_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_imnycvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_nlfix_parm, DB_MNY_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_imnycvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_blvar_parm, DB_MNY_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_imnycvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_nlvar_parm, DB_MNY_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_imnycvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_dec_parm, DB_MNY_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_imnycvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_leadnum_parm, DB_MNY_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_imnycvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_zonednum_parm, DB_MNY_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_imnycvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_unsnum_parm, DB_MNY_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_imnycvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_ovrnum_parm, DB_MNY_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_imnycvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_trlnum_parm, DB_MNY_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_imnycvt, 0 },

/* chash01 decimal datatype coercion */
/* to INGRES decimal type */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1,
            rms_rint_parm, DB_DEC_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_cvttoidec, 0 },	
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1,
            rms_unsint_parm, DB_DEC_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_cvttoidec, 0 },	
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1,
            rms_fflt_parm, DB_DEC_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_cvttoidec, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1,
            rms_dflt_parm, DB_DEC_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_cvttoidec, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1,
            rms_gflt_parm, DB_DEC_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_cvttoidec, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1,
            rms_hflt_parm, DB_DEC_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_cvttoidec, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1,
            rms_sflt_parm, DB_DEC_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_cvttoidec, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1,
            rms_tflt_parm, DB_DEC_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_cvttoidec, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1,
            rms_blfix_parm, DB_DEC_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_cvttoidec, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
            rms_nlfix_parm, DB_DEC_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_cvttoidec, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1,
            rms_blvar_parm, DB_DEC_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_cvttoidec, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1,
            rms_nlvar_parm, DB_DEC_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_cvttoidec, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1,
            rms_dec_parm, DB_DEC_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_cvttoidec, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1,
            rms_leadnum_parm, DB_DEC_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_cvttoidec, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	    rms_zonednum_parm, DB_DEC_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_cvttoidec, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1,
            rms_unsnum_parm, DB_DEC_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_cvttoidec, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1,
            rms_ovrnum_parm, DB_DEC_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_cvttoidec, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1,
            rms_trlnum_parm, DB_DEC_TYPE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_cvttoidec, 0 },

/* to RMS signed integer */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_int_parm, RMSGW_INT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_flt_parm, RMSGW_INT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_c_parm, RMSGW_INT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_text_parm, RMSGW_INT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_char_parm, RMSGW_INT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_varchar_parm, RMSGW_INT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_date_parm, RMSGW_INT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_money_parm, RMSGW_INT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rintcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_deci_parm, RMSGW_INT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rintcvt, 0 },

/* to RMS unsigned integer */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_int_parm, RMSGW_UNSINT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_runscvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_flt_parm, RMSGW_UNSINT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_runscvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_c_parm, RMSGW_UNSINT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_runscvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_text_parm, RMSGW_UNSINT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_runscvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_char_parm, RMSGW_UNSINT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_runscvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_varchar_parm, RMSGW_UNSINT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_runscvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_date_parm, RMSGW_UNSINT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_runscvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_money_parm, RMSGW_UNSINT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_runscvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_deci_parm, RMSGW_UNSINT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_runscvt, 0 },

/* to RMS f_float */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_int_parm, RMSGW_FFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt},
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_flt_parm, RMSGW_FFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt},
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_c_parm, RMSGW_FFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt},
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_text_parm, RMSGW_FFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt},
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_char_parm, RMSGW_FFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt},
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_varchar_parm, RMSGW_FFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt},
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_money_parm, RMSGW_FFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt},
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_deci_parm, RMSGW_FFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt},

/* to RMS d_float */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_int_parm, RMSGW_DFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt},
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_flt_parm, RMSGW_DFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt},
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_c_parm, RMSGW_DFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt},
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_text_parm, RMSGW_DFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt},
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_char_parm, RMSGW_DFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt},
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_varchar_parm, RMSGW_DFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt},
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_money_parm, RMSGW_DFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt},
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_deci_parm, RMSGW_DFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt},

/* to RMS g_float */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_int_parm, RMSGW_GFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_flt_parm, RMSGW_GFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_c_parm, RMSGW_GFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_text_parm, RMSGW_GFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_char_parm, RMSGW_GFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_varchar_parm, RMSGW_GFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_money_parm, RMSGW_GFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_deci_parm, RMSGW_GFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },

/* to RMS h_float */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_int_parm, RMSGW_HFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_flt_parm, RMSGW_HFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_c_parm, RMSGW_HFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_text_parm, RMSGW_HFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_char_parm, RMSGW_HFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_varchar_parm, RMSGW_HFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1,rms_money_parm, RMSGW_HFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1,rms_deci_parm, RMSGW_HFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },

/* to RMS s_float */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_int_parm, RMSGW_SFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_flt_parm, RMSGW_SFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_c_parm, RMSGW_SFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_text_parm, RMSGW_SFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_char_parm, RMSGW_SFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_varchar_parm, RMSGW_SFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1,rms_money_parm, RMSGW_SFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1,rms_deci_parm, RMSGW_SFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },

/* to RMS t_float */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_int_parm, RMSGW_TFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_flt_parm, RMSGW_TFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_c_parm, RMSGW_TFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_text_parm, RMSGW_TFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },           
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_char_parm, RMSGW_TFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_varchar_parm, RMSGW_TFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1,rms_money_parm, RMSGW_TFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1,rms_deci_parm, RMSGW_TFLOAT,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rfltcvt, 0 },

/* to RMS VAX date */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_c_parm, RMSGW_VAXDATE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdtecvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_text_parm, RMSGW_VAXDATE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdtecvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_char_parm, RMSGW_VAXDATE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdtecvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_varchar_parm, RMSGW_VAXDATE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdtecvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_date_parm, RMSGW_VAXDATE,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdtecvt, 0 },

/* to RMS blank-padded fixed-length string */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_int_parm, RMSGW_BL_FIXSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_flt_parm, RMSGW_BL_FIXSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_c_parm, RMSGW_BL_FIXSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_text_parm, RMSGW_BL_FIXSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_char_parm, RMSGW_BL_FIXSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_varchar_parm, RMSGW_BL_FIXSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_date_parm, RMSGW_BL_FIXSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_money_parm, RMSGW_BL_FIXSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_deci_parm, RMSGW_BL_FIXSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },

/* to RMS null-padded fixed-length string */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_int_parm, RMSGW_NL_FIXSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_flt_parm, RMSGW_NL_FIXSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_c_parm, RMSGW_NL_FIXSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_text_parm, RMSGW_NL_FIXSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_char_parm, RMSGW_NL_FIXSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_varchar_parm, RMSGW_NL_FIXSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_date_parm, RMSGW_NL_FIXSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_money_parm, RMSGW_NL_FIXSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_deci_parm, RMSGW_NL_FIXSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_byte_parm, RMSGW_NL_FIXSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_vbyte_parm, RMSGW_NL_FIXSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_lbyte_parm, RMSGW_NL_FIXSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_lvchar_parm, RMSGW_NL_FIXSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },

/* to RMS blank-padded varying string */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_int_parm, RMSGW_BL_VARSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_flt_parm, RMSGW_BL_VARSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_c_parm, RMSGW_BL_VARSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_text_parm, RMSGW_BL_VARSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_char_parm, RMSGW_BL_VARSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_varchar_parm, RMSGW_BL_VARSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_date_parm, RMSGW_BL_VARSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_money_parm, RMSGW_BL_VARSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_deci_parm, RMSGW_BL_VARSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },

/* to RMS null-padded varying string */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_int_parm, RMSGW_NL_VARSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_flt_parm, RMSGW_NL_VARSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_c_parm, RMSGW_NL_VARSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_text_parm, RMSGW_NL_VARSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_char_parm, RMSGW_NL_VARSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_varchar_parm, RMSGW_NL_VARSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_date_parm, RMSGW_NL_VARSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_money_parm, RMSGW_NL_VARSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_deci_parm, RMSGW_NL_VARSTR,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rstrcvt, 0 },

/* to RMS packed decimal */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_int_parm, RMSGW_PACKED_DEC,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_flt_parm, RMSGW_PACKED_DEC,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_c_parm, RMSGW_PACKED_DEC,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_text_parm, RMSGW_PACKED_DEC,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_char_parm, RMSGW_PACKED_DEC,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_varchar_parm, RMSGW_PACKED_DEC,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_money_parm, RMSGW_PACKED_DEC,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_deci_parm, RMSGW_PACKED_DEC,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },

/* to RMS leading numeric */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_int_parm, RMSGW_LEADING_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_flt_parm, RMSGW_LEADING_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_c_parm, RMSGW_LEADING_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_text_parm, RMSGW_LEADING_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_char_parm, RMSGW_LEADING_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_varchar_parm, RMSGW_LEADING_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_money_parm, RMSGW_LEADING_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_deci_parm, RMSGW_LEADING_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },

/* to RMS zoned numeric */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_int_parm, RMSGW_ZONED_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_flt_parm, RMSGW_ZONED_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_c_parm, RMSGW_ZONED_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_text_parm, RMSGW_ZONED_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_char_parm, RMSGW_ZONED_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_varchar_parm, RMSGW_ZONED_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_money_parm, RMSGW_ZONED_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_deci_parm, RMSGW_ZONED_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },

/* to RMS unsigned numeric */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_int_parm, RMSGW_UNS_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_flt_parm, RMSGW_UNS_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_c_parm, RMSGW_UNS_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_text_parm, RMSGW_UNS_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_char_parm, RMSGW_UNS_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_varchar_parm, RMSGW_UNS_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_money_parm, RMSGW_UNS_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_deci_parm, RMSGW_UNS_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },

/* to RMS overpunched numeric */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_int_parm, RMSGW_OVR_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_flt_parm, RMSGW_OVR_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_c_parm, RMSGW_OVR_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_text_parm, RMSGW_OVR_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_char_parm, RMSGW_OVR_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_varchar_parm, RMSGW_OVR_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_money_parm, RMSGW_OVR_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_deci_parm, RMSGW_OVR_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },

/* to RMS trailing separate numeric */
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_int_parm, RMSGW_TRL_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_flt_parm, RMSGW_TRL_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_c_parm, RMSGW_TRL_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_text_parm, RMSGW_TRL_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_char_parm, RMSGW_TRL_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, 
	      rms_varchar_parm, RMSGW_TRL_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_money_parm, RMSGW_TRL_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 },
	{ ADD_O_FUNCTION_INSTANCE, 0, ADD_NO_FI, ADI_NOOP,
	    ADI_COERCION, ADI_F0_NOFIFLAGS, 0, 1, rms_deci_parm, RMSGW_TRL_NUM,
	    ADI_RESLEN, 0, ADD_FI_PSVALID, rms_rdeccvt, 0 }
    };


    /* Now fill in the registration cb to add datatypes and coercions to the
    ** gateway.
    */

static  ADD_DEFINITION	rms_reg_cb =
{
    (ADD_DEFINITION *) 0, (ADD_DEFINITION *) 0,
    sizeof(ADD_DEFINITION), ADD_DFN_TYPE_V2,
    0, 0, 0, 0,
    ADD_INCONSISTENT,			    /* no recovery on RMS types */
    1, 0,				    /* major and minor ids */
    21,	"RMS Gateway Datatypes",	    /* length of desc and desc */
    ADD_T_LOG_MASK,
	/* jrbfix -- take out tracing later */
    0,					    /* we'll fill this in later */
    (sizeof(rms_dts)/sizeof(ADD_DT_DFN)),
    rms_dts,
    0,					    /* we're not adding any operators */
    NULL,			    
    (sizeof(rms_fis)/sizeof(ADD_FI_DFN)),
    rms_fis
};

/*
[@static_variable_or_function_definition@]...
*/


/*{
** Name: IIudadt_register	- Add RMS datatypes and coercions to gateway
**
** Description:
**
** Inputs:
**      add_cb                      Pointer to info add cb
**
** Outputs:
**      *add_cb			    We set this to our rms_reg_cb to add the
**				    RMS types and coercions
**
**	Returns:
**	    DB_STATUS
**	Exceptions:
**	    none
**
** Side Effects:
**	    rms_fis[].fid_id is belatedly initialized dynamically.
**
** History:
**	26-mar-90 (jrb)
**	    Created for RMS Gateway project.
**	22-jun-90 (edwin)
**	    Initialize rms_fis[].fid_id dynamically here.
**      21-sep-93 (schang)
**          change ADD_FISTART to ADD_USER_FISTART because the first one
**          is replaced by the latter by stevet to support class object.
[@history_template@]...
*/
DB_STATUS
IIudadt_register
(
    ADD_DEFINITION   **add_cb,
    ADD_CALLBACKS    *callbacks
)
{
    i4	    j;
    i4	    id = ADD_USER_FISTART;

    /*
    **  To avoid having to rewrite the initialization of the fid_id field
    **  every time we modify the definition of rms_fis, do it dynamically here.
    */
    for (j = 0; j < rms_reg_cb.add_fi_cnt; j++)
	rms_fis[j].fid_id = id++;

    rms_reg_cb.add_count = rms_reg_cb.add_dt_cnt +
			   rms_reg_cb.add_fo_cnt +
			   rms_reg_cb.add_fi_cnt;
    *add_cb = &rms_reg_cb;

    return(E_DB_OK);
}

/*{
** Name: rms_dummy - Always return E_DB_OK
**
** Description:
**	This routine ignores any parameters and just returns E_DB_OK.  It's
**  used when we don't care about implementing certain datatype functions for
**  RMS gateway datatypes.  (Currently it's used only for lenchk, and lenchk
**  really needs only be a defined routine when ADF has been compiled with
**  xDEBUG on... so we need this for development work.)
**
** Inputs:
**	none
**
** Outputs:
**	none
**
**	Returns:
**	    DB_STATUS		    always E_DB_OK
**	Exceptions:
**	    none
**
** Side Effects:
**	    none
**
** History:
**	29-mar-90 (jrb)
**	    Created for RMS Gateway project.
*/
DB_STATUS
rms_dummy()
{
    return (E_DB_OK);
}
