/*
**	Copyright (c) 1985, 2000 Ingres Corporation
**	All rights reserved.
*/

# include	<compat.h>
# include	<gl.h>
# include	<st.h>
# include	<er.h>
# include	<ex.h>
# include	<cs.h>
# include	<descrip.h>
# include	<chfdef.h>
# include       <evset.h>
# include	<lib$routines.h>
# include	<exinternal.h>

GLOBALDEF void (*Ex_print_stack)(CS_SCB *, void *, PTR, TR_OUTPUT_FCN *, i4);
GLOBALDEF       i4      Ex_core_enabled = 0;      /* 1 = allow core          */
FUNC_EXTERN	VOID	EXdump();

static volatile bool  in_sysrep = FALSE;      /* Used to prevent recursion
                                                 in case exception happens
                                                 in dump. */
/*
**
** Name:    ex_print_error() -        print ex message to errlog.log
**
** Description:
**    Function passed to CS_dump_stack to print message to errlog.log.
**    Called through TRformat hence first argument is a dummy for us.
**
** Inputs:
**    arg1                    ignored.
**    msg_length              length of message.
**    msg_buffer              bufer for message.
**
** Returns:
**    void
**
** History:
**    05-dec-1995 (whitfield)
**            Integrated from VAX version of exsysrep.
**    07-dec-1995 (whitfield)
**	    Use ANSI fn definitions.
**    24-jan-1996 (dougb)
**	    Remove TRdisplay() call.  Correct ERsend() parameters.
**    11-jun-1998 (kinte01)
** 	    Cross integrate change 435890 from oping12
**          19-may-1998 (horda03) X-Integrate Change 427896.
**              03-Oct-1996 (mckba02)
**                Add call to EXdump(), for diags + call to cs_dump_stack
**                for general error log diagnostics.
**	19-jul-2000 (kinte01)
**	   Correct prototype definitions by adding missing includes and
**	   add external function references
**	01-dec-2000	(kinte01)
**	    Bug 103393 - removed nat, longnat, u_nat, & u_longnat
**	    from VMS CL as the use is no longer allowed
**      07-sep-2010 (joea)
**          For i64_vms, move EXsetclient to exsignal.c.
*/
static STATUS
ex_print_error(PTR arg1, i4 msg_length, char *msg_buffer)
{
    CL_ERR_DESC err_code;

    ERsend( ER_ERROR_MSG, msg_buffer, msg_length, &err_code );
    RETURN (OK);
}

/*{
** Name:    EXsys_report() -	Report System/Hardware Exceptions.
**
** Description:
**	Reports if an exception was generated by hardware or the operating
**	system.  When this is the case, an appropriate message is copied into
**	the buffer and TRUE is returned.  Otherwise, FALSE is returned.
**
** Inputs:
**	exarg	{EX_ARGS *}  The exception argument structure.
**	buffer	{char *}  The address of the buffer that can contain the
**			  message for the hardware/system execption.
**
** Returns:
**	{bool}	TRUE, if hardware or operating system exception.
**		FALSE otherwise.
**
** History:
**	??/85 (fhc) -- Originally written by Fred as 'EXaccvio()'.
**	12/86 (jhw) -- Generalized for all hardware/system execptions.
**			07/87 VAX/VMS.
**	12/90 (Mike S) -- Distinguish VMS from INGRES exceptions.  Fix
	    		problems with argument count; use lib$sys_faol.
**	24-aug-92 (walt)
**	    added angle brackets to <descrip.h> above.
**	29-oct-92 (walt)
**	    Removed reference to &EXsignal_PC which nolonger exists.
**	25-jun-1993 (huffman)
**	    Change include file references from xx.h to xxcl.h.
**      11-aug-93 (ed)
**          added missing includes
**      23-mar-94 (dkh)
**              Added new entry point EXsetclient().  It is just
**              a stub for now.
**      30-mar-94 (huffman)
**              Somewhere down the road, the 'exch.h' did not get 
**              converted to 'ex.h' for the cmn_hdr.
**      05-dec-1995 (whitfield)
**          Added support for stack dumps.  Use ANSI fn definitions.
**	24-jan-1996 (dougb)
**	    Correct call to EX_print_stack().
**	16-Nov-2010 (kschendel) SIR 124865
**	    Another print-stack call update.
*/

#if 0
GLOBALREF EXsignal_PC;		/* PC where lib$signal returns to EXsignal */
#endif

bool
EXsys_report( register EX_ARGS	*exargs, char *buffer )
{
    /* 
    ** Number of message arguments; we add 2 because the PC and PSL are
    ** present in exarg_array (which is simply the exception signal vector)
    ** but aren't counted in exarg_count.
    */
    i4 arg_count = exargs->exarg_count + 2;
    
    /* Report Hardware Exceptions
    **
    **	This should report all hardware or system exceptions (including
    **	those that get mapped into internal Ingres exceptions.  All available
    **  program information should be formatted and printed into the output
    **	buffer.
    **
    **  We return FALSE for normal INGRES exceptions.  These are exceptions
    **  where:
    **	1.	The exception number is in the correct range for INGRES
    **		exceptions.  Unfortunately, this will also be true if someone
    **		signals an RMS failure.  So in addition, we check that:
    **	2.	The signal array's PC is where lib$signal returns to EXsignal,
    **		meaning that EXsignal signaled this exception.
    */
/*
**    if (CLERROR(exargs->exarg_num) && 
**        exargs->exarg_array[arg_count-2] == &EXsignal_PC)
*/
	if (CLERROR(exargs->exarg_num))
    {
	return FALSE;
    }
    else
    {
	char	bufs[256];
	$DESCRIPTOR(buf, bufs);
	unsigned short	len;
	unsigned char	info[4];

        EXdump(EV_SIGVIO_DUMP);

	if ( !in_sysrep )
	{
	    in_sysrep = TRUE;

	    if (Ex_print_stack)
	    {
		Ex_print_stack(NULL, NULL, NULL, ex_print_error, TRUE);
	    }

	    in_sysrep = FALSE;
	}

	lib$sys_getmsg(&exargs->exarg_num, &len, &buf, 0, info);
	if (info[1] == 0 || arg_count < info[1])
	{
	    /* 
	    ** No args or insufficient args; don't try to format it.
	    */
	    STlcopy(bufs, buffer, len);
	}
	else
	{
	    $DESCRIPTOR(obuf, buffer);

	    /* Format it.  Use lib$sys_faol, so any number of args works */
	    obuf.dsc$w_length = buf.dsc$w_length;
	    buf.dsc$w_length = len;
	    lib$sys_faol(&buf, &len, &obuf, exargs->exarg_array);
	    buffer[len] = '\0';
	}
	return TRUE;
    }
}

/*{
** Name:    EXsigarr_sys_report() -	Report System/Hardware Exceptions.
**
** Description:
**	Like EXsys_report, but it takes a VMS signal array as the first
**	argument instead of an EX_ARGS pointer.  An internal CL routine.
**
** Inputs:
**	sigarr {i4*}  The exception signal array.
**	buffer	{char *}  The address of the buffer that can contain the
**			  message for the hardware/system execption.
**
** Returns:
**	{bool}	TRUE, if hardware or operating system exception.
**		FALSE otherwise.
**
** History:
**	12/90 (Mike S) Initial version.  Written to be called from
**		frontstart.c's top-level exception handler.
**	07-dec-1995 (whitfield)
**	    Use ANSI fn definitions.
*/
bool
EXsigarr_sys_report( i4 *sigarr, char *buffer )
{
    bool result;

    /* 
    ** We convert from signal array to EXARGS by reducing the argument count
    ** by 3; EX doesn't consider the exception number part of the argument
    ** array, nor does it include PC and PSL.
    */
    sigarr[0] -= 3;
    result = EXsys_report((EX_ARGS *)sigarr, buffer);
    sigarr[0] += 3;
    return result;
}

#if defined(axm_vms)
/*{
** Name:	EXsetclient - Set client information for the EX subsystem
**
** Description:
**	This routine informs the EX subsystem as to the type of client
**	that it is dealing with.  The client type information is
**	important in that it allows EX to modify its behavior dependent
**	on the client
**
**	For user applications, EX will only intercept access violation and
**	floating point exceptions.  This becomes the default behavior for EX.
**	It is up to the user application to deal with any other exceptions.
**
**	If the client is the Ingres DBMS, then EX will need to intercept
**	any exceptions that will cause a process to exit (current behavior).
**
**	In the case of Ingres Tools, EX will also intercept user generated
**	exit exceptions (such as interrupt) in addition to the access
**
**	FOR VMS, THIS ROUTINE IS A NO-OP.
**
** Inputs:
**	EX_INGRES_DBMS		Client is the Ingres DBMS or any application
**				that desires the trap all behavior.
**
**	EX_INGRES_TOOL		Client is one of the Ingres Tools.
**
**	EX_USER_APPLICATION	Client is a user written application.  This
**				is actually unnecessary since this is the
**				default.  It is defined here just for
**				completeness.
**
** Outputs:
**
**	Returns:
**		EX_OK			If everything succeeded.
**		EXSETCLIENT_LATE	If the EX subsystem has already
**					been initialized when this is called.
**		EXSETCLIENT_BADCLEINT	If an unknown client was passed in.
**
** Exceptions:
**	None.
**
** Side Effects:
**	None.
**
** History:
**	21-mar-94 (dkh) - Initial version.
*/
STATUS
EXsetclient(i4 client)
{
    return(EX_OK1);
}
#endif
