//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ipm.rc
//
#define IDS_IPM                         1
#define IDB_IPM                         1
#define IDS_IPM_PPG                     2
#define IDD_MESSAGEBOX                  105
#define IDS_IPM_PPG_CAPTION             200
#define IDD_PROPPAGE_IPM                200
#define IDC_TAB1                        201
#define IDD_IPMDETAIL_LOCK              201
#define IDC_EDIT1                       202
#define IDD_IPMDETAIL_LOCKINFO          202
#define IDC_EDIT2                       203
#define IDD_IPMDETAIL_LOCKLIST          203
#define IDC_EDIT3                       204
#define IDD_IPMDETAIL_LOGINFO           204
#define IDC_EDIT4                       205
#define IDD_IPMDETAIL_PROCESS           205
#define IDC_EDIT5                       206
#define IDD_IPMDETAIL_RESOURCE          206
#define IDC_EDIT6                       207
#define IDD_IPMDETAIL_SERVER            207
#define IDC_EDIT7                       208
#define IDD_IPMDETAIL_SESSION           208
#define IDC_EDIT8                       209
#define IDD_IPMDETAIL_TRANSACTION       209
#define IDC_EDIT9                       210
#define IDD_IPMICEDETAIL_ACTIVEUSER     210
#define IDC_EDIT10                      211
#define IDD_IPMICEDETAIL_CACHEPAGE      211
#define IDC_EDIT11                      212
#define IDD_IPMICEDETAIL_CONNECTEDUSER  212
#define IDC_EDIT12                      213
#define IDD_IPMICEDETAIL_CURSOR         213
#define IDC_EDIT13                      214
#define IDD_IPMICEPAGE_CACHEPAGE        214
#define IDC_EDIT14                      215
#define IDD_IPMICEDETAIL_DATABASECONNECTION 215
#define IDC_EDIT15                      216
#define IDD_IPMICEDETAIL_HTTPSERVERCONNECTION 216
#define IDC_EDIT16                      217
#define IDD_IPMICEDETAIL_TRANSACTION    217
#define IDC_EDIT17                      218
#define IDD_IPMICEPAGE_ACTIVEUSER       218
#define IDC_EDIT18                      219
#define IDD_IPMICEPAGE_CONNECTEDUSER    219
#define IDC_EDIT19                      220
#define IDD_IPMICEPAGE_CURSOR           220
#define IDC_EDIT20                      221
#define IDD_IPMICEPAGE_DATABASECONNECTION 221
#define IDC_EDIT21                      222
#define IDD_IPMICEPAGE_HTTPSERVERCONNECTION 222
#define IDC_EDIT22                      223
#define IDD_IPMICEPAGE_TRANSACTION      223
#define IDC_EDIT23                      224
#define IDD_IPMPAGE_ACTIVEDB            224
#define IDC_EDIT24                      225
#define IDD_IPMPAGE_CLIENT              225
#define IDC_STATIC1                     226
#define IDD_IPMPAGE_HEADER              226
#define IDC_STATIC2                     227
#define IDD_IPMPAGE_LOCKEDRESOURCES     227
#define IDC_STATIC3                     228
#define IDD_IPMPAGE_LOCKEDTABLES        228
#define IDC_STATIC4                     229
#define IDD_IPMPAGE_LOCKLISTS           229
#define IDC_STATIC5                     230
#define IDD_IPMPAGE_LOCKS               230
#define IDC_STATIC6                     231
#define IDD_IPMPAGE_LOGFILE             231
#define IDC_STATIC7                     232
#define IDD_IPMPAGE_PROCESSES           232
#define IDC_STATIC8                     233
#define IDD_IPMPAGE_SESSIONS            233
#define IDC_STATIC9                     234
#define IDD_IPMPAGE_STATIC_ACTIVEUSERS  234
#define IDC_STATIC10                    235
#define IDD_IPMPAGE_STATIC_DATABASES    235
#define IDC_STATIC11                    236
#define IDD_IPMPAGE_STATIC_REPLICATIONS 236
#define IDC_STATIC12                    237
#define IDD_IPMPAGE_STATIC_SERVERS      237
#define IDC_STATIC13                    238
#define IDD_IPMPAGE_TRANSACTIONS        238
#define IDC_STATIC14                    239
#define IDD_REPCOLLISION_PAGE_RIGHT     239
#define IDC_STATIC15                    240
#define IDD_REPCOLLISION_PAGE_RIGHT2    240
#define IDC_STATIC16                    241
#define IDD_REPSERVER_PAGE_ASSIGNMENT   241
#define IDC_STATIC17                    242
#define IDD_REPSERVER_PAGE_RAISEEVENT   242
#define IDC_STATIC18                    243
#define IDD_REPSERVER_PAGE_STARTSETTING 243
#define IDC_BUTTON1                     244
#define IDD_REPSERVER_PAGE_STATUS       244
#define IDC_BUTTON2                     245
#define IDD_REPSTATIC_PAGE_ACTIVITY     245
#define IDC_BUTTON3                     246
#define IDD_REPSTATIC_PAGE_ACTIVITY_TAB_DATABASE 246
#define IDC_BUTTON4                     247
#define IDD_REPSTATIC_PAGE_ACTIVITY_TAB_TABLE 247
#define IDC_BUTTON_STARTUP              248
#define IDD_REPSTATIC_PAGE_COLLISION    248
#define IDC_BUTTON_NOW                  249
#define IDD_REPSTATIC_PAGE_DISTRIB      249
#define IDC_COMBO1                      250
#define IDD_REPSTATIC_PAGE_INTEGRITY    250
#define IDC_CHECK1                      251
#define IDD_REPSTATIC_PAGE_RAISEEVENT   251
#define IDC_LIST1                       252
#define IDD_REPSTATIC_PAGE_SERVER       252
#define IDC_EDIT_RESERVED               253
#define IDD_XREPLICATION_SERVER_LIST    253
#define IDC_COMBO2                      254
#define IDB_TM_REPLIC_SERVER            254
#define IDC_COMBO3                      255
#define IDB_TM_REPLIC_SERVER_STARTED    255
#define IDC_COMBO4                      256
#define IDB_TM_REPLIC_SERVER_STOPPED    256
#define IDC_CHECK2                      257
#define IDB_TM_REPLIC_SERVER_ERROR      257
#define IDC_CHECK3                      258
#define IDB_COLLISION_IMAGE             258
#define IDC_CHECK4                      259
#define IDB_DATABASEOBJECT              259
#define IDC_CHECK5                      260
#define IDB_TM_LOGINFO                  260
#define IDC_EDIT_LOG_COMMIT_CURRENT     261
#define IDB_TM_LOGPROCESS               261
#define IDC_EDIT_LOG_COMMIT_MIN         262
#define IDB_TM_CONNECT_DATA_USER        262
#define IDC_EDIT_LOG_COMMIT_AVERAGE     263
#define IDB_TM_ICE_ACTIVE_USER          263
#define IDC_EDIT_LOG_COMMIT_MAX         264
#define IDB_TM_ICE_CURSOR               264
#define IDC_EDIT_LOG_WRITE_CURRENT      265
#define IDB_TM_ICE_TRANSACTION          265
#define IDC_EDIT_LOG_WRITE_MIN          266
#define IDB_TM_ICE_FILEINFO_USER        266
#define IDC_EDIT_LOG_WRITE_AVERAGE      267
#define IDB_TM_ICE_CONNECTED_USER       267
#define IDC_EDIT_LOG_WRITE_MAX          268
#define IDB_TM_ICE_HTTP_CONNECTION      268
#define IDC_RADIO1                      269
#define IDB_TM_ICE_DB_CONNECTION        269
#define IDC_RADIO2                      270
#define IDR_POPUP_IPM                   270
#define IDC_SPIN1                       270
#define IDC_RADIO3                      271
#define IDR_POPUP_IPM_REPLICSVR         271
#define IDD_XREPLICATION_RUNNODE        271
#define IDC_SPIN2                       271
#define IDC_STATIC19                    272
#define IDR_POPUP_IPM_SERVER            272
#define IDC_EDIT_TIMEOUT                272
#define IDC_STATIC_LOG_SECOND           273
#define IDC_EDIT_FREQUENCY              273
#define IDC_STATIC_LOG_CURRENT          274
#define IDC_CHECK_ACTIVATEREFRESH       274
#define IDC_STATIC_LOG_AVERAGE          275
#define IDC_CHECK_SHOWGRID              275
#define IDC_STATIC_LOG_MIN              276
#define IDC_EDIT_MAXSESSION             276
#define IDC_STATIC1_DATE1               276
#define IDC_STATIC_LOG_MAX              277
#define IDC_SPIN3                       277
#define IDC_STATIC1_DATE2               277
#define IDC_STATIC_LOG_WRITE            278
#define IDC_STATIC2_DATE1               278
#define IDC_STATIC_LOG_WRITE_CURRENT    279
#define IDC_STATIC2_DATE2               279
#define IDC_STATIC_LOG_WRITE_MIN        280
#define IDC_STATIC3_DATE1               280
#define IDC_STATIC_LOG_WRITE_AVERAGE2   281
#define IDC_STATIC3_DATE2               281
#define IDC_STATIC_LOG_WRITE_MAX        282
#define IDC_STATIC4_DATE1               282
#define IDC_IMAGE1                      283
#define IDC_STATIC4_DATE2               283
#define IDC_UP                          284
#define IDC_STATIC_REACH1               284
#define IDC_DOWN                        285
#define IDC_STATIC_REACH2               285
#define IDC_GO                          286
#define IDC_STATIC_SUBDIALOG1           286
#define IDC_SERVER_LIST                 287
#define ID_YES                          287
#define IDC_LISTEN_STATE                288
#define ID_NO                           288
#define IDC_LISTEN_STATE_EDIT           289
#define IDC_STATIC_MSG                  289
#define IDC_STATIC_LOGDIAGRAM_CONTROL   290
#define IDC_STATIC_PIC                  290
#define IDC_STATIC_AVAILABLE            291
#define IDS_TC_NAME                     300
#define IDS_TC_OWNER                    301
#define IDS_TC_CONNECT_TO_DB            302
#define IDS_TC_REQUESTER                303
#define IDS_TC_COUNTER                  304
#define IDS_TC_TIME_OUT                 305
#define IDS_TC_STATUS                   306
#define IDS_TC_REQUEST                  307
#define IDS_TC_EXIT_FILE                308
#define IDS_TC_KEY                      309
#define IDS_TC_QUERY                    310
#define IDS_TC_USR_SESS                 311
#define IDS_TC_CONNECT_KEY              312
#define IDS_TC_TYPE                     313
#define IDS_TC_LOCAL                    314
#define IDS_TC_TARGET                   315
#define IDS_TC_PARAM                    316
#define IDS_TC_VALUE                    317
#define IDS_TC_UNIT                     318
#define IDS_TC_SVR_FLAG                 319
#define IDS_TC_EVENT                    320
#define IDS_TC_ACTION                   321
#define IDS_TC_DB_NAME                  322
#define IDS_TC_CDDS_NAME                323
#define IDS_TC_TARGET_TYPE              324
#define IDS_TC_RUN_NODE                 325
#define IDS_TC_LOCAL_DB                 326
#define IDS_TC_ACTION2                  327
#define IDS_TC_EVENT2                   328
#define IDS_TC_SVR_FLAG2                329
#define IDS_TC_COLUMN                   330
#define IDS_TC_NAME_COOKIES             331
#define IDS_TC_ICE_USER                 332
#define IDS_TC_ACTIVE_SESSION           333
#define IDS_TC_USER_COOKIE              334
#define IDS_TC_SESSION                  335
#define IDS_TC_HTTP_HOST                336
#define IDS_TC_ERRORS                   337
#define IDS_TC_DRIVER                   338
#define IDS_TC_CURRENTLY_USED           339
#define IDS_TC_REAL_USER                340
#define IDS_TC_ID                       341
#define IDS_TC_STATE                    342
#define IDS_TC_WAIT_REASON              343
#define IDS_TC_KEY2                     344
#define IDS_TC_SESS_ID                  345
#define IDS_TC_TTY                      346
#define IDS_TC_DATABASE                 347
#define IDS_TC_FACILITY                 348
#define IDS_TC_LISTEN_ADD               349
#define IDS_TC_CLASS                    350
#define IDS_TC_EXT_TRANSACTION          351
#define IDS_TC_WRITE                    352
#define IDS_TC_SPLIT                    353
#define IDS_TC_SVR_TYPE                 354
#define IDS_TC_INTERNAL_ID              355
#define IDS_TC_OP_SYS_ID                356
#define IDS_TC_LOCKS                    357
#define IDS_TC_LOGICAL                  358
#define IDS_TC_MAXL                     359
#define IDS_TC_RQ                       360
#define IDS_TC_TABLE                    361
#define IDS_TC_PAGE                     362
#define IDS_TC_GR                       363
#define IDS_TC_CV                       364
#define IDS_TC_LOCK_TYPE                365
#define IDS_TC_OPENDB                   366
#define IDS_TC_FORCE                    367
#define IDS_TC_WAIT                     368
#define IDS_TC_BEGIN                    369
#define IDS_TC_END                      370
#define IDS_TC_EMPTY                    371
#define IDS_TC_TX_CNT                   372
#define IDS_TC_READ                     373
#define IDS_TC_NUMSIGN                  374
#define IDS_TC_DATABASE_NUM             375
#define IDS_TC_CDDS                     376
#define IDS_TC_LOCATION                 377
#define IDS_TC_INSERT                   378
#define IDS_TC_INSERTS                  379
#define IDS_TC_UPDATE                   380
#define IDS_TC_UPDATES                  381
#define IDS_TC_DELETE                   382
#define IDS_TC_DELETES                  383
#define IDS_TC_TOTAL                    384
#define IDS_TC_TRANSACTION              385
#define IDS_TC_TRANSACTIONS             386
#define IDS_TC_OUTGOING                 387
#define IDS_TC_INCOMING                 388
#define IDS_TC_INBOUND                  389
#define IDS_TC_OUTBOUND                 390
#define IDS_TAB_DETAIL                  500
#define IDS_TAB_SESSION                 501
#define IDS_TAB_LOCK                    502
#define IDS_TAB_LOCKLIST                503
#define IDD_IPMCAT02                    504
#define IDS_TAB_TRANSACTION             504
#define IDS_TAB_LOCKRESOURCE            505
#define IDS_TAB_PROCESS                 506
#define IDS_TAB_ACTIVEDB                507
#define IDS_TAB_SUMMARY                 508
#define IDS_TAB_DATABASE                509
#define IDS_TAB_SERVER_TITLE            510
#define IDS_TAB_SESSION_TITLE           511
#define IDS_TAB_LOCKLIST_TITLE          512
#define IDS_TAB_DATABASE_TITLE          513
#define IDS_TAB_TRANSACTION_TITLE       514
#define IDS_TAB_RESOURCE_TITLE          515
#define IDS_TAB_LOGINFO_TITLE           516
#define IDS_TAB_ACTIVEUSER_TITLE        517
#define IDS_TAB_PROCESS_TITLE           518
#define IDS_TAB_LOCK_TITLE              519
#define IDS_TAB_HEADER                  520
#define IDS_TAB_LOCKINFO_TITLE          521
#define IDS_TAB_CLIENT                  522
#define IDS_TAB_REPSERVER_STATUS        523
#define IDS_TAB_REPSERVER_STARTUP_SETTING 524
#define IDS_TAB_REPSERVER_RAISE_EVENT   525
#define IDS_TAB_REPSERVER_ASSIGNMENT    526
#define IDS_TAB_REPSTATIC_ACTIVITY      527
#define IDS_TAB_REPSTATIC_SERVER        528
#define IDS_TAB_REPSTATIC_RAISE_EVENT   529
#define IDS_TAB_REPSTATIC_COLLISION     530
#define IDS_TAB_REPSTATIC_INTEGRITY     531
#define IDS_TAB_REPSTATIC_DISTRIB       532
#define IDS_TAB_LOGFILE                 533
#define IDS_TAB_STATIC_SESS_TITLE       534
#define IDS_TAB_STATIC_LOCKLIST_TITLE   535
#define IDS_TAB_STATIC_LOCK_TITLE       536
#define IDS_TAB_STATIC_TRANSAC_TITLE    537
#define IDS_TAB_STATIC_PROCESS_TITLE    538
#define IDS_TAB_STATIC_ACTIVEDB_TITLE   539
#define IDS_TAB_STATIC_LOGTRANSAC_TITLE 540
#define IDS_TAB_STATIC_SERVER_TITLE     541
#define IDS_TAB_STATIC_SERVER_TITLE2    542
#define IDS_TAB_STATIC_DATABASE_TITLE   543
#define IDS_TAB_STATIC_DATABASE         544
#define IDS_TAB_STATIC_ACTIVEUSER_TITLE 545
#define IDS_TAB_STATIC_ACTIVEUSER       546
#define IDS_TAB_STATIC_REPLICATION_TITLE 547
#define IDS_TAB_STATIC_REPLICATION      548
#define IDS_TAB_ICE_CONNECTEDUSER       549
#define IDS_TAB_ICE_TRANSACTION         550
#define IDS_TAB_ICE_CURSOR              551
#define IDS_TAB_ICE_CACHEPAGE           552
#define IDS_TAB_ICE_ACTIVEUSER          553
#define IDS_TAB_ICE_HTTP_SERVER         554
#define IDS_TAB_ICE_DATABASECONNECTION  555
#define IDS_TAB_ICE_TITLE_STATIC_CONNECTEDUSER 556
#define IDS_TAB_ICE_TITLE_STATIC_ACTIVEUSER 557
#define IDS_TAB_ICE_TITLE_STATIC_TRANSACTION 558
#define IDS_TAB_ICE_TITLE_STATIC_CACHEPAGE 559
#define IDS_TAB_ICE_TITLE_STATIC_HTTP_SERVER 560
#define IDS_TAB_ICE_TITLE_STATIC_DATABASECONNECTION 561
#define IDS_TAB_ICE_TITLE_STATIC_CURSOR 562
#define IDS_TAB_ICE_TITLE_CONNECTEDUSER 563
#define IDS_TAB_ICE_TITLE_ACTIVEUSER    564
#define IDS_TAB_ICE_TITLE_TRANSACTION   565
#define IDS_TAB_ICE_TITLE_CACHEPAGE     566
#define IDS_TAB_ICE_TITLE_HTTP_SERVER   567
#define IDS_TAB_ICE_TITLE_DATABASECONNECTION 568
#define IDS_TAB_ICE_TITLE_CURSOR        569
#define IDS_TAB_TABLE                   570
#define IDS_TAB_STATIC_SERVER           571
#define IDD_XREPLICATION_QUESTION       644
#define IDD_XSERVICE_ACCOUNT            651
#define IDD_IPMDETAIL_NETTRAFIC         652
#define IDS_TM_SERVER                   700
#define IDS_TM_SERVER_NONE              701
#define IDS_TM_SESSION                  702
#define IDS_TM_SESSION_NONE             703
#define IDS_TM_SESS_LOCKLIST            704
#define IDS_TM_SESS_LOCKLIST_NONE       705
#define IDS_TM_SESS_LOCKLIST_LOCK       706
#define IDS_TM_SESS_LOCKLIST_LOCK_NONE  707
#define IDS_TM_LOCK_RESOURCE            708
#define IDS_TM_LOCK_RESOURCE_NONE       709
#define IDS_TM_SESS_LOCKLIST_BL_LOCK    710
#define IDS_TM_SESS_LOCKLIST_BL_LOCK_NONE 711
#define IDS_TM_SESS_LOCK                712
#define IDS_TM_SESS_LOCK_NONE           713
#define IDS_TM_SESS_TRANSAC             714
#define IDS_TM_SESS_TRANSAC_NONE        715
#define IDS_TM_SESS_DB                  716
#define IDS_TM_SESS_DB_NONE             717
#define IDS_TM_LOCKLIST                 718
#define IDS_TM_LOCKLIST_NONE            719
#define IDS_TM_LOCK                     720
#define IDS_TM_LOCK_NONE                721
#define IDS_TM_TRANSAC                  722
#define IDS_TM_TRANSAC_NONE             723
#define IDS_TM_DB                       724
#define IDS_TM_DB_NONE                  725
#define IDS_TM_LOGINFO                  728
#define IDS_TM_LOGPROCESS               729
#define IDS_TM_LOGPROCESS_NONE          730
#define IDS_TM_LOGDB                    731
#define IDS_TM_LOGDB_NONE               732
#define IDS_TM_LOGTRANSAC               733
#define IDS_TM_LOGTRANSAC_NONE          734
#define IDS_TM_ALLDB                    735
#define IDS_TM_ALLDB_NONE               736
#define IDS_TM_DB_ALLTBL                737
#define IDS_TM_DB_ALLTBL_NONE           738
#define IDS_TM_DB_LOCKLIST              739
#define IDS_TM_DB_LOCKLIST_NONE         740
#define IDS_TM_DB_LOCK                  741
#define IDS_TM_DB_LOCK_NONE             742
#define IDS_TM_DB_LOCKEDTBL             743
#define IDS_TM_DB_LOCKEDTBL_NONE        744
#define IDS_TM_DB_LOCKEDOTHER           745
#define IDS_TM_DB_LOCKEDOTHER_NONE      746
#define IDS_TM_DB_SERVER                747
#define IDS_TM_DB_SERVER_NONE           748
#define IDS_TM_DB_TRANSAC               749
#define IDS_TM_DB_TRANSAC_NONE          750
#define IDS_TM_DB_LOCKONDB              751
#define IDS_TM_DB_LOCKONDB_NONE         752
#define IDS_TM_DB_SESSION               753
#define IDS_TM_DB_SESSION_NONE          754
#define IDS_TM_ACTUSR                   755
#define IDS_TM_ACTUSR_NONE              756
#define IDS_TM_USRSESS                  757
#define IDS_TM_USRSESS_NONE             758
#define IDS_TM_ERR_ERR                  759
#define IDS_TM_ERR_TIMEOUT              760
#define IDS_TM_LOCK_LOCKLIST            761
#define IDS_TM_LOCK_LOCKLIST_NONE       762
#define IDS_TM_ERR_NOGRANT              763
#define IDS_TM_LOCK_SESSION             764
#define IDS_TM_LOCK_SESSION_NONE        765
#define IDS_TM_LOCK_SERVER              766
#define IDS_TM_LOCK_SERVER_NONE         767
#define IDS_TM_TRANSAC_LOCKLIST         768
#define IDS_TM_TRANSAC_LOCKLIST_NONE    769
#define IDS_TM_TRANSAC_LOCK             770
#define IDS_TM_TRANSAC_LOCK_NONE        771
#define IDS_TM_TRANSAC_RESOURCE         772
#define IDS_TM_TRANSAC_DB               773
#define IDS_TM_TRANSAC_DB_NONE          774
#define IDS_TM_TRANSAC_OTHER            775
#define IDS_TM_TRANSAC_OTHER_NONE       776
#define IDS_TM_TRANSAC_SESSION          777
#define IDS_TM_TRANSAC_SESSION_NONE     778
#define IDS_TM_TRANSAC_SERVER           779
#define IDS_TM_TRANSAC_SERVER_NONE      780
#define IDS_TM_BLOCKING_SESSION         781
#define IDS_TM_BLOCKING_SESSION_NONE    782
#define IDS_TM_ICE_ACTIVE_USER          783
#define IDS_TM_ICE_ACTIVE_USER_NONE     784
#define IDS_TM_ICE_HTTP_CONNECTION      785
#define IDS_TM_ICE_HTTP_CONNECTION_NONE 786
#define IDS_TM_ICE_DB_CONNECTION        787
#define IDS_TM_LOCKINFO                 788
#define IDS_TM_LOCKINFO_LOCKLIST        789
#define IDS_TM_LOCKINFO_LOCKLIST_NONE   790
#define IDS_TM_ICE_DB_CONNECTION_NONE   791
#define IDS_TM_RES_DBLOCK               792
#define IDS_TM_RES_DBLOCK_NONE          793
#define IDS_TM_RES_TBLLOCK              794
#define IDS_TM_RES_TBLLOCK_NONE         795
#define IDS_TM_RES_PGLOCK               796
#define IDS_TM_RES_PGLOCK_NONE          797
#define IDS_TM_RES_OTHLOCK              798
#define IDS_TM_RES_OTHLOCK_NONE         799
#define IDS_TM_SESS_TBL                 800
#define IDS_TM_SESS_TBL_NONE            801
#define IDS_TM_SESS_PAGE                802
#define IDS_TM_SESS_PAGE_NONE           803
#define IDS_TM_SESS_OTHER               804
#define IDS_TM_SESS_OTHER_NONE          805
#define IDS_TM_TBL                      806
#define IDS_TM_TBL_NONE                 807
#define IDS_TM_PAGE                     808
#define IDS_TM_PAGE_NONE                809
#define IDS_TM_OTHER                    810
#define IDS_TM_OTHER_NONE               811
#define IDS_TM_DB_LOCKEDPAGE            812
#define IDS_TM_DB_LOCKEDPAGE_NONE       813
#define IDS_TM_LOCKLIST_SESSION         814
#define IDS_TM_LOCKLIST_SESSION_NONE    815
#define IDS_TM_TRANSAC_TBL              816
#define IDS_TM_TRANSAC_TBL_NONE         817
#define IDS_TM_TRANSAC_PAGE             818
#define IDS_TM_TRANSAC_PAGE_NONE        819
#define IDS_TM_LOCKINFO_RESDB           820
#define IDS_TM_LOCKINFO_RESDB_NONE      821
#define IDS_TM_LOCKINFO_RESTBL          822
#define IDS_TM_LOCKINFO_RESTBL_NONE     823
#define IDS_TM_LOCKINFO_RESPG           824
#define IDS_TM_LOCKINFO_RESPG_NONE      825
#define IDS_TM_LOCKINFO_RESOTH          826
#define IDS_TM_LOCKINFO_RESOTH_NONE     827
#define IDS_TM_REPLIC_ALLDB             828
#define IDS_TM_REPLIC_ALLDB_NONE        829
#define IDS_TM_REPLIC_SERVER_NONE       830
#define IDS_TM_REPLIC_REPLIC            831
#define IDS_TM_REPLIC_NOTINSTALLED      832
#define IDS_TM_ICE_FILEINFO_ALL         833
#define IDS_TM_ICE_FILEINFO_ALL_NONE    834
#define IDS_TM_ICE_FILEINFO_USER        835
#define IDS_TM_ICE_FILEINFO_USER_NONE   836
#define IDS_TM_ICE_CONNECTED_USER       837
#define IDS_TM_ICE_CONNECTED_USER_NONE  838
#define IDS_TM_ICE_TRANSACTION          839
#define IDS_TM_ICE_TRANSACTION_NONE     840
#define IDS_TM_ICE_CURSOR               841
#define IDS_TM_ICE_CURSOR_NONE          842
#define IDS_TM_ICE_ALLTRANSACTION       843
#define IDS_TM_ICE_ALLTRANSACTION_NONE  844
#define IDS_TM_ICE_ALLCURSOR            845
#define IDS_TM_ICE_ALLCURSOR_NONE       846
#define IDS_SHUTDOWN_CONFIRM_SOFT       1001
#define IDS_SHUTDOWN_CONFIRM_HARD       1002
#define IDS_KILLSESSION_CONFIRM_CAPT    1003
#define IDS_SHUTDOWNSRV_TITLE           1004
#define IDS_KILLSESSION_CONFIRM_TXT     1005
#define IDS_DISKSPACE_FREE              1006
#define IDS_STATIC_AVAIL_OK             1007
#define IDS_STATIC_AVAIL_ABORT          1008
#define IDS_STATIC_AVAIL_LOGFULL        1009
#define IDS_SHUTDOWN_SOFT               1012
#define IDS_REPSERVER_TITLE             1013
#define IDS_REPSTATIC_TITLE             1014
#define IDS_BLOCKING_SESSION_CANNOT_SOLVE 1015
#define IDS_BLOCKING_SESSION_MULTIPLE_GRANTS 1016
#define IDS_IPM_FAST_CANNOTEXPAND       1017
#define IDS_E_DIRECT_ACCESS             1018
#define IDS_NOT_AVAILABLE               1019
#define IDS_MAX_NB_CONNECT              1020
#define IDS_E_READ_FILE                 1021
#define IDS_E_LOG_FILE_ERROR            1022
#define IDS_E_NB_SERVERS                1023
#define IDS_F_SERVICE_NOT_INSTALL       1024
#define IDS_E_REPINST_UTIL              1025
#define IDS_E_REPINST_INSTALL           1026
#define IDS_I_PASSWORD_REQUIRED         1027
#define IDS_I_INGRES_NOT_STARTED        1028
#define IDS_E_USER_PASSWORD             1029
#define IDS_E_INGRES_NOT_STARTED        1030
#define IDS_E_USER_PASSWORD_NB          1031
#define IDS_E_ISSUING_ERROR             1032
#define IDS_E_PING_FAILED               1033
#define IDS_E_CDDS_ASSIGNEMENT          1034
#define IDS_E_TAB_NOT_FOUND             1035
#define IDS_E_LOAD_DLG                  1036
#define IDS_E_CONSTRUCT_PROPERTY        1037
#define IDS_E_LOAD_RESOURCE             1038
#define IDS_E_REFRESH_LOCKING           1039
#define IDS_E_REFRESH_LOGGING           1040
#define IDS_E_ALL_SEQUENCES             1041
#define IDS_E_UPDATE_BRANCH             1042
#define IDS_STOP_SVR_REPLIC             1043
#define IDS_E_STRUCTURE                 1044
#define IDS_F_VNODE_NOT_FOUND           1045
#define IDS_E_STOP_REP_SVR              1046
#define IDS_A_CLOSE_SVR                 1047
#define IDS_E_TITLE_CLOSE_SVR           1048
#define IDS_TITLE_OPEN_SVR              1049
#define IDS_A_OPEN_SVR                  1050
#define IDS_E_CREATE_CHART              1051
#define IDS_E_CONNECT_SERVICE           1052
#define IDS_E_SERVICE_STATUS            1053
#define IDS_E_GET_SERVICE_NAME          1054
#define IDS_E_CHANGE_SERVICE_CONF       1055
#define IDS_F_REP_FLAG_DEFAULT          1056
#define IDS_F_REP_FLAG_INCONSISTENT     1057
#define IDS_F_REP_FLAG_VALUE            1058
#define IDS_F_REP_FLAG_UNKNOWN          1059
#define IDS_EVENT_ISSUED                1060
#define IDS_E_PAGE_DETAIL               1061
#define IDS_E_PLEASE_RETYPE_PASSWORD    1062
#define IDS_FIND_TREE_NOTFOUND          1063
#define IDS_F_DBA_OWNER                 1064
#define IDS_E_HANDLE_AVALAIBLE          1065
#define IDS_E_DB_OWNER                  1066
#define IDS_F_RESTORE_DEFAULT           1067
#define IDS_A_RESTORE_ALL               1068
#define IDS_A_STARTUP_SETTING           1069
#define IDS_E_EVENT_LAUNCH              1070
#define IDS_E_IMAGE_INDEX               1071
#define IDS_E_STRUCTURE_COMPLETED       1072
#define IDS_E_SUB_BRANCHES              1073
#define IDS_I_SVR_FLAG_INTEGER          1074
#define IDS_I_SVR_FLAG_BOOLEAN          1075
#define IDS_I_SVR_FLAG_STRING           1076
#define IDS_I_SVR_FLAG_SECONDS          1077
#define IDS_I_SVR_FLAG_SVR_NUM          1078
#define IDS_I_SVR_FLAG_LOC_DB           1079
#define IDS_I_SVR_FLAG_LOC_DBOWNER      1080
#define IDS_I_SVR_FLAG_SEND_NOTI        1081
#define IDS_I_SVR_FLAG_SEND_MON         1082
#define IDS_I_SVR_FLAG_PRINT_LEV        1083
#define IDS_I_SVR_FLAG_LOG_LEVEL        1084
#define IDS_I_SVR_FLAG_TIME_OUT         1085
#define IDS_I_SVR_FLAG_CONN_TIMEOUT     1086
#define IDS_I_SVR_FLAG_MAX_ERR          1087
#define IDS_I_SVR_FLAG_EVT_TIME         1088
#define IDS_I_SVR_FLAG_ERR_MAIL         1089
#define IDS_I_SVR_FLAG_NO_ERR_MAIL      1090
#define IDS_I_SVR_FLAG_NO_SKIP_RULE     1091
#define IDS_I_SVR_FLAG_SKIP_RULE        1092
#define IDS_I_SVR_FLAG_OPEN_RETRY       1093
#define IDS_I_SVR_FLAG_REPL_CYCLES      1094
#define IDS_I_SVR_FLAG_ABS_MEM          1095
#define IDS_I_SVR_FLAG_NB_RECORDS       1096
#define IDS_I_SVR_FLAG_QUEUE_BREAK      1097
#define IDS_I_SVR_FLAG_UNQUIET_SVR      1098
#define IDS_I_SVR_FLAG_QUIET_SVR        1099
#define IDS_I_SVR_FLAG_SINGLE_PASS      1100
#define IDS_I_SVR_FLAG_TWO_PHASE        1101
#define IDS_E_START_REPLIC_SVR          1102
#define IDS_E_VIEW_REPLIC_LOG           1103
#define IDS_E_VIEW_FIRST_REPLIC_LOG     1104
#define IDS_F_RESERVED                  1105
#define IDS_F_IN_USED                   1106
#define IDS_F_AVAILABLE                 1107
#define IDS_E_LOCAL_HOST_NAME           1108
#define IDS_F_NO_VALUE                  1109
#define IDS_I_RESERVED                  1110
#define IDS_I_IN_USE                    1111
#define IDS_I_AVAILABLE                 1112
#define IDS_TOTAL                       1113
#define IDS_COMPUTABLE_STATE            1114
#define IDS_CURRENT                     1115
#define IDS_MAX                         1116
#define IDS_E_INSTALLATION_NOT_FOUND    1117
#define IDS_E_ERROR_RMCMD               1118
#define IDS_I_LOCALNODE                 1119
#define IDS_BLOCKS                      1120
#define IDS_LOGFILE_DIAGRAM             1121
#define IDS_INUSE                       1122
#define IDS_RESERVED                    1123
#define IDS_AVAILABLE                   1124
#define IDS_MSG_NOINFORMATION_SELECTED  1125
#define IDS_MSG_ALLPARAMS_SET_2_DEFAULT 1126
#define IDS_I_EV_STOP_SVR               1200
#define IDS_I_EV_START_REPLIC           1201
#define IDS_I_EV_ACTIVE_ALL             1202
#define IDS_I_EV_CONNECT_TIME_OUT       1203
#define IDS_I_EV_CTO_30                 1204
#define IDS_I_EV_CTO_1                  1205
#define IDS_I_EV_CTO_ASK                1206
#define IDS_TEXT_EV_NB_SECONDS          1207
#define IDS_TITLE_EV_CTO                1208
#define IDS_I_EV_SHD_SVR_100_ERRORS     1209
#define IDS_I_EV_SHD_SVR_200_ERRORS     1210
#define IDS_I_EV_SHD_SVR_50_ERRORS      1211
#define IDS_I_EV_SHD_SVR_N_ERRORS       1212
#define IDS_TEXT_SHD_SVR                1213
#define IDS_TITLE_SHD_SVR               1214
#define IDS_I_EV_TIMEOUT                1215
#define IDS_I_EV_TIMEOUT_30             1216
#define IDS_I_EV_TIMEOUT_1              1217
#define IDS_I_EV_TIMEOUT_N              1218
#define IDS_TITLE_EV_PRN                1219
#define IDS_I_EV_NO_LOG_INF             1220
#define IDS_I_EV_LOG_ERROR_INF          1221
#define IDS_I_EV_LOG_ERR_IMP            1222
#define IDS_I_EV_LOG_ERR_WARNING        1223
#define IDS_I_EV_SEND_MAIL              1224
#define IDS_I_EV_SEND_DB_EV             1225
#define IDS_I_EV_NO_MAIL                1226
#define IDS_I_EV_NO_DB_EVENT            1227
#define IDS_I_EV_UNQUIET_REPL           1228
#define IDS_I_EV_PRINT_SESS             1229
#define IDS_I_EV_ENABLE_RULE            1230
#define IDS_I_EV_CHECK_CLOSED           1231
#define IDS_I_EV_CHECK_CLOSED50         1232
#define IDS_I_EV_CHECK_CLOSEDN          1233
#define IDS_TEXT_EV_REPL_CYCLES         1234
#define IDS_TITLE_EV_CLOSED_DB          1235
#define IDS_I_EV_NO_PRINT_LOG           1236
#define IDS_I_EV_PRINT_STANDARD         1237
#define IDS_I_EV_PRINT_ERR_INF          1238
#define IDS_I_EV_PRINT_WARNING          1239
#define IDC_REPLICQUESTION              1239
#define IDS_I_QUIET_CDDS                1240
#define IDC_QUESTION                    1240
#define IDS_I_UNQUIET_CDDS              1241
#define IDS_I_QUIET_DB                  1242
#define IDS_I_UNQUIET_DB                1243
#define IDS_I_QUIET_SVR                 1244
#define IDS_I_SKIP_INDEX                1245
#define IDS_I_PRINT_SESS_NUM            1246
#define IDS_I_CONN_TIMEOUT120           1247
#define IDS_I_CONN_TIMEOUT5             1248
#define IDS_I_CONN_TIMEOUT60            1249
#define IDS_I_CONN_TIMEOUTN             1250
#define IDS_TITLE_CONN_TIMEOUT          1251
#define IDS_I_TWO_PHASE_COMMIT_OFF      1252
#define IDS_I_XTWO_PHASE_COMMIT_ON      1253
#define IDS_PLEASE_ENLARGEPANE          1254
#define IDS_FAIL_TO_LOAD_DLL            1255
#define IDS_ANIMATE_TITLE_QUERYOBJECT   1256
#define IDS_ANIMATE_TITLE_QUERYOBJECT_DETAIL 1257
#define IDS_E_GET_SESSION               1260
#define IDS_F_OPEN_REPORT               1261
#define IDS_F_OPENING_SESSION           1262
#define IDS_ERR_CLOSE_TEMP_FILE         1263
#define IDS_F_COLUMN_INFO               1264
#define IDS_ERR_BLANK_TABLE_NAME        1265
#define IDS_F_TBL_NUMBER                1266
#define IDS_F_INVALID_OBJECT            1267
#define IDS_ERR_OPENING_CURSOR          1268
#define IDS_F_FETCHING_DATA             1269
#define IDS_ERR_SESSION_NUMBER          1270
#define IDS_ERR_IMMEDIATE_EXECUTION     1271
#define IDS_F_EXECUT_IMMEDIAT           1272
#define IDS_ERR_COUNT_CONNECTIONS       1273
#define IDS_ERR_MAX_CONNECTIONS         1274
#define IDS_ERR_FETCHING_TARGET_DB      1275
#define IDS_F_GETTING_COLUMNS           1276
#define IDS_F_REGISTRED_COL             1277
#define IDS_F_FLOAT_EXEC_IMMEDIATE      1278
#define IDS_ERR_CHAR_EXECUTE_IMMEDIATE  1279
#define IDS_ERR_TBL_NUMBER              1280
#define IDS_F_NO_COLUMN_REGISTRATION    1281
#define IDS_ERR_INCONSISTENT_COUNT      1282
#define IDS_ERR_RELEASE_SESSION         1283
#define IDS_E_SELECT_FAILED             1284
#define IDS_ERR_SELECT_FAILED           1285
#define IDS_ERR_UPDATE_DD_DISTRIB_QUEUE 1286
#define IDS_ERR_GENERATE_SHADOW         1287
#define IDS_F_SHADOW_TBL                1288
#define IDS_F_RELATIONSHIP              1289
#define IDS_ERR_SQLERR                  1290
#define IDS_F_MAX_CONN_SEND_EVENT       1291
#define IDS_F_DBA_OWNER_EVENT           1292
#define IDS_E_SEND_EXECUTE_IMMEDIAT     1293
#define IDS_NO_INFORMATION_FOUND        1294
#define IDS_ERR_ACTIVATE_SESSION        1295
#define IDS_ERR_READ_TEMPORARY_FILE     1296
#define IDS_E_UNEXPECTED_ROW            1297
#define IDS_E_GET_DB_NAME               1298
#define IDS_I_INGRES_REPLIC             1299
#define IDS_I_DISTRIB_CONFIG            1300
#define IDS_I_LOC_DB                    1301
#define IDS_E_DD_PATH_TBL               1302
#define IDS_E_PROPAGATION_PATH          1303
#define IDS_E_OPEN_LOCAL_CURSOR         1304
#define IDS_E_FETCHING_DB               1305
#define IDS_E_CLOSE_LOC_CURSOR          1306
#define IDS_E_LOCAL_ROLLBACK            1307
#define IDS_E_LOCAL_COMMIT              1308
#define IDS_I_REPORT_DB                 1309
#define IDS_E_MAX_CONNECTION            1310
#define IDS_E_PROHIBITS                 1311
#define IDS_I_NO_PROBLEM                1312
#define IDS_E_CONNECTING                1313
#define IDS_F_DBA_NAME                  1314
#define IDS_E_REPLIC_OBJECT_IN_DB       1315
#define IDS_E_INFO_MISSING              1316
#define IDS_E_UNBOUNDED_DTA             1317
#define IDS_E_REPLIC_OBJECT_EXIST       1318
#define IDS_E_OPEN_CURSOR               1319
#define IDS_E_FETCHING                  1320
#define IDS_E_CHECKING_DD_DB            1321
#define IDS_E_DD_DATABASES_ERROR        1322
#define IDS_E_RECORD_DB                 1323
#define IDS_F_DB_NAME                   1324
#define IDS_E_CLOSE_CURSOR_DD_DB        1325
#define IDS_E_OPEN_CUR_DD_REG           1326
#define IDS_E_DBNO_AND_VNODE            1327
#define IDS_E_DBNO_AND_DBMS             1328
#define IDS_E_FETCH_DD_REG              1329
#define IDS_E_CHECK_DD_REG              1330
#define IDS_E_DD_REG_TBL_ERROR          1331
#define IDS_E_RECORD_NO_NOT_FOUND       1332
#define IDS_E_SUPPORT_TBL_NOT_CREATE    1333
#define IDS_E_COLUMN_REGISTRED          1334
#define IDS_E_TBL_NAME_ERROR            1335
#define IDS_E_TBL_OWNER_ERROR           1336
#define IDS_E_DD_REGIST_CLOSE_CURSOR    1337
#define IDS_E_DD_REGIST_COL_OPEN_CURSOR 1338
#define IDS_E_DD_REGIST_COL_FETCH_CURSOR 1339
#define IDS_E_DD_REGIST_COL_CHECKING    1340
#define IDS_E_DD_REGIST_COL_ERROR       1341
#define IDS_E_RECORD_TABLE              1342
#define IDS_E_COLUMN_SEQUENCE           1343
#define IDS_E_REGIST_COL_CLOSE_CURSOR   1344
#define IDS_E_KEY_SEQUENCE_ERROR        1345
#define IDS_E_CDDS_OPEN_CURSOR          1346
#define IDS_E_CDDS_FETCH_CURSOR         1347
#define IDS_E_CDDS_CHECKING             1348
#define IDS_E_CDDS_ERROR                1349
#define IDS_E_CDDS_CHECK_ERROR          1350
#define IDS_E_CDDS_NO_FOUND             1351
#define IDS_E_CDDS_ERRORMODE            1352
#define IDS_E_CHECK_DB_CDDS_OPEN_CURSOR 1353
#define IDS_E_CDDS_FETCHING_CURSOR      1354
#define IDS_E_CDDS_CHECKING_DB_NO       1355
#define IDS_E_CDDS_DB_NO                1356
#define IDS_E_CDDS_TARGET_TYPE          1357
#define IDS_E_CDDS_CLOSE_CURSOR         1358
#define IDS_E_PATH_OPEN_CURSOR          1359
#define IDS_E_PATH_FETCHING_CURSOR      1360
#define IDS_E_DD_PATH_ERROR             1361
#define IDS_E_RECORD_CDDS_NO            1362
#define IDS_E_CDDS_LOCAL_NO             1363
#define IDS_E_CLOSING_CURSOR            1364
#define IDS_E_SETTING_SESSION           1365
#define IDS_E_DD_CDDS_CLOSE_CURSOR      1366
#define IDS_E_DB_CDDS_OPEN_CURSOR       1367
#define IDS_E_DISTRIB_DD_PATH_TBL       1368
#define IDS_E_CHECK_INDEXES_OPEN_CURSOR 1369
#define IDS_E_FETCH_INDEX               1370
#define IDS_E_CHECK_UNIQUE_KEYS_DBMS_ERROR 1371
#define IDS_E_LOOKING_UP_COLUMNS        1372
#define IDS_E_ACTIV_SESSION             1373
#define IDS_E_TBL_INTEG_ERROR           1374
#define IDS_E_INVALID_DB                1375
#define IDS_E_TBL_INTEG_TARGET_TYPE     1376
#define IDS_E_DB_UNPROTREADONLY         1377
#define IDS_E_MAX_NUM_CONNECTION        1378
#define IDS_E_CDDS_NAME                 1379
#define IDS_E_CONNECT_DB                1380
#define IDS_E_TBL_INTEG_REPORT          1381
#define IDS_I_FOR_TBL                   1382
#define IDS_E_TBL_INTEG_NO_REPLIC_COL   1383
#define IDS_E_KEY_COL_FOUND             1384
#define IDS_E_TBL_INTEG_PROB_CONFIG     1385
#define IDS_E_DESCRIBE_STATEMENT        1386
#define IDS_E_TBL_INTEG_OPEN_CURSOR     1387
#define IDS_E_TBL_INTEG_EXEC_IMM        1388
#define IDS_ROW_ONLY_IN                 1389
#define IDS_E_CDDS_COLLISION            1390
#define IDS_TBL_INTEG_TBL_DEF           1391
#define IDS_I_REG_KEY_COLUMNS           1392
#define IDS_I_UNIQUE                    1393
#define IDS_TBL_INTEG_DB_TRANSAC        1394
#define IDS_TBL_INTEG_FETCH_INTEG       1395
#define IDS_TBL_INTEG_ROW_DIFFERENCES   1396
#define IDS_TBL_INTEG_SOURCE_DB         1397
#define IDS_TBL_INTEG_NO_DIFFERENCES    1398
#define IDS_I_AND_TBL                   1399
#define IDS_E_UPDATE_COLLISION          1400
#define IDS_E_ISSUING_ERROR2            1401
#define IDS_E_ISSUING_EVENT             1402
#define IDS_F_COLLISION_DBA_OWNER       1403
#define IDS_E_PING_FAILED2              1404
#define IDS_I_DONT_FORGET_REBUILD       1405
#define IDS_E_REPLIC_UPDATE_FAILED      1406
#define IDS_F_STOP_REPLIC_SVR           1407
#define IDS_E_RUN_SERVER_REPLIC         1408
#define IDS_E_READ_FILE2                1409
#define IDS_F_DB_OWNER                  1410
#define IDS_E_SAVE_FILE                 1411
#define IDS_FIND_NO_OCCURENCE           1412
#define IDS_FIND_NOTFOUND               1413
#define IDS_FAIL_2_QUERY_OBJECT         1414
#define IDS_FAIL_2_QUERY_OBJECTxNOGRANT 1415
#define IDS_E_NO_GRANT                  1416
#define IDS_E_NO_CDDS                   1417
#define IDS_MSG_IPM_UNAVAILABLE         1418
#define IDS_E_REFRESH_NETTRAFIC         1419
#define IDS_MONITOR_INFO                1420
#define IDM_IPMBAR_REFRESH              32768
#define IDM_IPMBAR_SHUTDOWN             32769
#define IDM_IPMBAR_REPLICSVR_CHANGERUNNODE 32770
#define IDM_IPMBAR_CLOSESVR             32771
#define IDM_IPMBAR_OPENSVR              32772
#define IDB_SHIELD                      32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        274
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         291
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
