//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by iipostinst.rc
//
#define IDS_TITLE                       1
#define IDS_AREYOUSURE                  2
#define IDS_DELETE20DATABASEFOLDER      4
#define IDS_DELETE20NETWORKINGFOLDER    5
#define IDS_DELETE20TOOLSFOLDER         6
#define IDS_READRNS                     8
#define IDS_DELETE20OPENROADFOLDER      12
#define IDS_DELETE12DATABASEFOLDER      13
#define IDS_DELETE12NETWORKINGFOLDER    14
#define IDS_DELETE12TOOLSFOLDER         15
#define IDS_DELETE12OPENROADFOLDER      16
#define IDS_REMOVE_FOLDERS              17
#define IDS_SUCCEEDED                   31
#define IDS_PROBLEMS                    32
#define IDS_DONE                        33
#define IDS_FAILED                      34
#define IDS_SETTINGCONF                 36
#define IDS_STARTINGSERVER              40
#define IDS_STOPPINGSERVER              42
#define IDS_SPACE                       45
#define IDS_DISK                        46
#define IDS_TYPE                        47
#define IDS_AVAILABLE                   48
#define IDS_SIZE                        49
#define IDS_FILESYSTEM                  50
#define IDS_LABEL                       51
#define IDS_GATEDESC                    56
#define IDS_FINISH                      58
#define IDS_AGREE                       59
#define IDS_INGRESOPENFOLDER            61
#define IDS_SETTINGENV                  64
#define IDS_NOTENOUGHSPACE              66
#define IDS_PERCENT                     67
#define IDS_SIZEFORMAT                  68
#define IDS_ZEROSIZE                    69
#define IDS_ALREADYRUNNING              70
#define IDS_SERVERRUNNING               71
#define IDS_SIZEFORMAT2                 72
#define IDS_NOTENOUGHSPACEFORLOGFILE    73
#define IDS_SETENVIRONMENTVARIABLES     74
#define IDS_REBOOT                      76
#define IDS_SEPARATOR                   85
#define IDS_DATEFORMAT                  86
#define IDS_SERVICE                     90
#define IDS_SERVICENAME                 91
#define IDS_UINSTKEY                    93
#define IDS_INGRES                      94
#define IDS_CANNOTWRITE                 101
#define IDS_CANNOTWRITEREGISTRY         102
#define IDB_INFO                        103
#define IDB_BITMAP_INFO                 103
#define IDS_CREATESYSDB                 108
#define IDS_CREATELOGFILE               110
#define IDS_LABELDOC                    113
#define IDS_LOADIMA                     114
#define IDS_LOADPERFMON                 115
#define IDR_MAINFRAME                   129
#define IDD_SPLASHSCREEN                131
#define IDS_REGSVR                      132
#define IDD_POSTINSTALLATION            142
#define IDR_CLOCK_AVI                   153
#define IDD_WAIT_DIALOG                 163
#define IDR_RT_MANIFEST1                170
#define IDD_DIALOG1                     171
#define IDD_SUMMARY                     171
#define IDD_DIALOG_INFO                 176
#define IDB_BITMAP_LAUNCHPAD            177
#define IDB_BITMAP_ERROR                178
#define IDC_IMAGE                       1000
#define IDC_ANIMATE1                    1006
#define IDC_OUTPUT                      1007
#define IDC_STATICPERCENT               1043
#define IDS_LABELDBMSSERVER             1053
#define IDS_LABELINGRESNET              1054
#define IDS_LABELINGRESSTAR             1055
#define IDS_LABELESQLC                  1056
#define IDS_LABELESQLCOBOL              1057
#define IDS_LABELINFORMIXGATEWAY        1059
#define IDS_LABELSQLSERVERGATEWAY       1060
#define IDS_LABELTOOLS                  1061
#define IDS_LABELVISION                 1062
#define IDS_LABELREPLICATOR             1063
#define IDS_LABELICE                    1064
#define IDS_LABELOPENROADDEV            1065
#define IDS_CREATING_ING_ABFDIR         1066
#define IDC_AVI                         1066
#define IDS_ABF_SETUP_COMPLETE          1067
#define IDC_TEXT                        1067
#define IDS_ABF_SETUP_FAILED            1068
#define IDS_ABF_SETUP                   1069
#define IDS_STAR_NEEDS_DBMS             1070
#define IDS_LABELOPENROADRUN            1071
#define IDS_LABELSYBASEGATEWAY          1072
#define IDS_LABELORACLEGATEWAY          1073
#define IDS_INST_LOC_MESSAGE            1736
#define IDS_UPGRADE_INSTALLATION        1738
#define IDS_INSTALL_ACROBAT             1739
#define IDS_ANSISQL92_MESSAGE           1740
#define IDS_CLUSTER_SIZE_TOO_LARGE      1741
#define IDC_MSG                         1746
#define IDC_LAUNCH_PAD                  1747
#define IDC_BUTTON_INFO                 1748
#define IDC_SUMMARY_TITLE2              1749
#define IDC_SUMMARY_TITLE1              1750
#define IDC_STATIC_PATH                 1751
#define IDC_STATIC_ID                   1752
#define IDC_STATIC_BLOCK                1753
#define IDC_IMAGE1                      1754
#define IDC_STATIC_GROUPBOX             1755
#define IDC_STATIC_LOCTITLE             1756
#define IDC_STATIC_ID_TITLE             1757
#define IDC_STATIC_BLOCK2               1758
#define IDC_RICHEDIT21                  1759
#define IDC_RICHEDIT_SUMMARY            1759
#define IDC_BUTTON1                     1760
#define IDC_STATIC_SUCCESS              1761
#define IDC_STATIC_ERROR                1762
#define IDC_SUMMARY_TITLE_FAILED        1763
#define IDC_IMAGE2                      1764
#define IDC_MSG2                        1765
#define IDC_STATIC_UDBUPGRADED          1767
#define IDC_STATIC_UDBUPGRADED2         1768
#define IDS_LOADICE                     57345
#define IDS_CONFIGURINGICE              57346
#define IDS_CREATEICEDB                 57347
#define IDS_CREATEICEDBUSER             57348
#define IDS_USINGRESPONSEFILE           57349
#define IDS_UPDATELOGFILE               57355
#define IDS_UPDATESYSDB                 57356
#define IDS_USERFORMAT                  57357
#define IDS_SETTINGFILEASSOCIATIONS     57358
#define IDS_UPGRADEINSTALLATION         57359
#define IDS_UPGRADEDATABASESNOW         57360
#define IDS_ERRORUPGRADINGDATABASES     57361
#define IDS_UPGRADEDATABASES            57363
#define IDS_CANNOTFINDLOGFILE           57364
#define IDS_MOVINGLOGFILE               57365
#define IDS_READINGRESPONSEFILE         57372
#define IDS_CANCEL_WAITDLG              57375
#define IDS_MISSING_ACT_AS_OS_PRIVILEGE 57381
#define IDS_PROBLEMEXECUTINGINSTALLER   57383
#define IDS_USER_CONTINUED_WITHOUT_PRIVILEGE 57384
#define IDS_DISPLAYINGUSERENVIRONMENT   57387
#define IDS_LABELVDBA                   57388
#define IDS_LABELEMBEDDEDCOMPONENTS     57389
#define IDS_WRITINGREGISTRYENTRY_SZ     57391
#define IDS_REMOVINGINGRESODBCDRIVER    57392
#define IDS_SETTINGUPINGRESODBC         57393
#define IDS_WRITINGREGISTRYENTRY_DW     57394
#define IDS_REMOVINGINGRESODBCREADONLYDRIVER 57395
#define IDS_CANNOTFIND_ODBCCP32         57396
#define IDS_CANNOTFIND_SQLREMOVEDRIVER  57397
#define IDS_COMMANDLINE                 57399
#define IDS_REMOVINGOLDFILES            57400
#define IDS_PRESTARTUP                  57401
#define IDS_LEAVINGINGRESRUNNING        57402
#define IDS_LABELJDBC                   57403
#define IDS_CHECKPOINTINGDATABASES      57404
#define IDS_LABELODBC                   57405
#define IDS_REGISTERCONTROLS            57406
#define IDS_DELETEINGRESIIFOLDER        57407
#define IDS_LABELESQLFORTRAN            57408
#define IDS_ERRORSTARTINGBROWSER        57409
#define IDS_UPDATEICEDB                 57410
#define IDS_DELETEOLDDOCFOLDER          57411
#define IDS_SDKTITLE                    57412
#define IDS_CREATEOTHERDBUSERS          57413
#define IDS_CREATEOTHERDB               57414
#define IDS_UPDATEOTHERDB               57415
#define IDS_INSTALLPORTAL               57416
#define IDS_INSTALLFTREES               57417
#define IDS_INSTALLOPENROAD             57418
#define IDS_SDKSUCCEEDED                57419
#define IDS_STARTPORTAL                 57420
#define IDS_FINISHMSG                   57421
#define IDS_INSTALLAPACHE               57422
#define IDS_STARTAPACHE                 57423
#define IDS_ADDOSUER                    57424
#define IDS_APACHEINSTALLED             57425
#define IDS_OPENPORTAL                  57426
#define IDS_DOWNLOAD_NONENG_ADOBE       57427
#define IDS_APACHEINSTALLED2            57428
#define IDS_DATEFORMATS                 57429
#define IDS_DATEFORMATF                 57430
#define IDS_INSTALLJRE                  57431
#define IDS_INSTALL_ENG_ACROBAT         57432
#define IDS_LOADDEMODB                  57433
#define IDS_SUCCEEDED2                  57434
#define IDS_TITLE_DBA			57435
#define IDS_ADDING_VNODES	    	57436
#define IDS_BI_CONFIG			57437
#define IDS_CM_CONFIG			57438
#define IDS_TXN_CONFIG			57439
#define IDS_UPGRADEDEMODB		57440

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        179
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1769
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

